package cn.pawday.catalog;

import cn.pawday.audit.AuditWriter;
import cn.pawday.common.Api.Failure;
import cn.pawday.identity.*;
import cn.pawday.outbox.OutboxWriter;
import cn.pawday.pet.PetService;
import jakarta.servlet.http.HttpServletRequest;
import java.time.*;
import java.util.*;
import java.util.function.Supplier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;
import static cn.pawday.pet.PetService.*;

@Service
public class CatalogService {
 private final JdbcTemplate db;private final PetService commands;private final AuthService auth;private final AuditWriter audit;
 private final TransactionTemplate tx;private final OutboxWriter outbox;private final Clock clock;
 private final JsonMapper json=JsonMapper.builder().build();
 public CatalogService(JdbcTemplate db,PetService commands,AuthService auth,AuditWriter audit,TransactionTemplate tx,OutboxWriter outbox,Clock clock){this.db=db;this.commands=commands;this.auth=auth;this.audit=audit;this.tx=tx;this.outbox=outbox;this.clock=clock;}
 static void check(boolean v){if(!v)throw new Failure(400,"VALIDATION_ERROR");}
 static void fields(Map<?,?> b,String... keys){check(b.keySet().equals(Set.of(keys)));}
 void permission(Actor a,boolean write){String p=write?"catalog.standard.write":"catalog.standard.read";if(!a.permissions().contains(p)||write&&a.realm()!=Actor.Realm.ADMIN||!write&&a.realm()==Actor.Realm.CONSUMER)throw new Failure(403,"PERMISSION_DENIED");}
 void merchant(Actor a){if(a.realm()!=Actor.Realm.MERCHANT||a.merchantId()==null||!a.permissions().contains("catalog.request.write"))throw new Failure(403,"PERMISSION_DENIED");}
 Map<String,Object> write(Actor a,String action,String key,Object b,String proof,HttpServletRequest r,Supplier<Map<String,Object>> work){permission(a,true);return commands.command(a,action,key,b,()->{auth.consumeProof(a,"catalog.standard.write",proof);var result=work.get();audit.write(a,action,"CATALOG",result.get("id").toString(),Map.of(),Map.of("status",result.getOrDefault("status","CREATED")),r);return result;});}
 void serial(String key){db.queryForList("SELECT pg_advisory_xact_lock(hashtextextended(?,0))","catalog:"+key);}
 public Map<String,Object> create(Actor a,String kind,Map<String,Object>b,String proof,String key,HttpServletRequest r){return write(a,"catalog.create."+kind,key,b,proof,r,()->{
  UUID id=UUID.randomUUID();switch(kind){
   case "brands"->{fields(b,"name","source_ref");String name=text(b.get("name"),160),source=text(b.get("source_ref"),2000);serial("brand:"+name);if(db.queryForObject("SELECT count(*) FROM brands WHERE name=?",Integer.class,name)>0)throw new Failure(409,"ALREADY_EXISTS");db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,?)",id,name,source);}
   case "spus"->{fields(b,"brand_id","name","pet_category","category");UUID brand=uuid(b.get("brand_id"));String name=text(b.get("name"),160),category=text(b.get("pet_category"),16);check(Set.of("CAT","DOG","AQUATIC","BIRD","SMALL_PET").contains(category));String type=text(b.get("category"),80);if(db.queryForObject("SELECT count(*) FROM brands WHERE id=? AND status='ACTIVE'",Integer.class,brand)==0)throw new Failure(422,"BRAND_UNAVAILABLE");serial("spu:"+brand+":"+name);if(db.queryForObject("SELECT count(*) FROM spus WHERE brand_id=? AND name=?",Integer.class,brand,name)>0)throw new Failure(409,"ALREADY_EXISTS");db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,?,?,?)",id,brand,name,category,type);}
   case "skus"->{fields(b,"spu_id","sku_code","barcode","weight_g","package_unit");UUID spu=uuid(b.get("spu_id"));String code=text(b.get("sku_code"),80),barcode=b.get("barcode")==null?null:text(b.get("barcode"),80);long weight=number(b.get("weight_g"),1,100000000);String unit=text(b.get("package_unit"),40);if(db.queryForObject("SELECT count(*) FROM spus WHERE id=? AND status='ACTIVE'",Integer.class,spu)==0)throw new Failure(422,"SPU_UNAVAILABLE");serial("sku-uniqueness");if(db.queryForObject("SELECT count(*) FROM skus WHERE sku_code=? OR (? IS NOT NULL AND barcode=?)",Integer.class,code,barcode,barcode)>0)throw new Failure(409,"ALREADY_EXISTS");db.update("INSERT INTO skus(id,spu_id,sku_code,barcode,weight_g,package_unit) VALUES (?,?,?,?,?,?)",id,spu,code,barcode,weight,unit);}
   default->throw new Failure(404,"RESOURCE_NOT_FOUND");
  }return Map.of("id",id,"status","ACTIVE");
 });}
 public PetService.ResultPage list(Actor a,String kind,String cursor,int limit){permission(a,false);check(limit>0&&limit<=100);String table=switch(kind){case "brands","spus","skus"->kind;default->throw new Failure(404,"RESOURCE_NOT_FOUND");};UUID after=cursor==null?new UUID(0,0):uuid(cursor);var rows=db.queryForList("SELECT * FROM "+table+" WHERE id>? ORDER BY id LIMIT ?",after,limit+1);boolean more=rows.size()>limit;var data=rows.stream().limit(limit).toList();return new PetService.ResultPage(data,more?data.getLast().get("id").toString():null,more);}
 Map<String,Object> sku(UUID id){var rows=db.queryForList("SELECT * FROM skus WHERE id=? AND status='ACTIVE' FOR UPDATE",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");return rows.getFirst();}
 static long version(String raw){if(raw==null||!raw.matches("\"[0-9]{1,18}\""))throw new Failure(400,"VERSION_REQUIRED");return Long.parseLong(raw.substring(1,raw.length()-1));}
 void sameVersion(Map<String,Object> row,long expected){if(((Number)row.get("version")).longValue()!=expected)throw new Failure(409,"VERSION_CONFLICT");}
 Map<String,Object> standard(Map<String,Object> b,UUID skuId){
  fields(b,"ingredients","nutrients","allergen_ids","allergens_known","life_stage_ids","source_refs","source_updated_on");
  for(String f:List.of("ingredients","nutrients","allergen_ids","life_stage_ids","source_refs"))check(b.get(f) instanceof List<?>);
  var ingredients=(List<?>)b.get("ingredients");check(!ingredients.isEmpty()&&ingredients.size()<=200);ingredients.forEach(x->text(x,200));
  check(b.get("allergens_known") instanceof Boolean);var allergens=(List<?>)b.get("allergen_ids");check(allergens.size()<=100);check(Boolean.TRUE.equals(b.get("allergens_known"))||allergens.isEmpty());Set<UUID> seen=new HashSet<>();for(Object x:allergens){UUID id=uuid(x);check(seen.add(id));if(db.queryForObject("SELECT count(*) FROM allergens WHERE id=? AND status='ACTIVE'",Integer.class,id)==0)throw new Failure(422,"ALLERGEN_UNAVAILABLE");}
  var nutrients=(List<?>)b.get("nutrients");check(nutrients.size()<=100);Set<String> names=new HashSet<>();for(Object x:nutrients){check(x instanceof Map<?,?>);var n=(Map<?,?>)x;fields(n,"name","value_milli","unit","basis","qualifier");check(names.add(text(n.get("name"),80)));number(n.get("value_milli"),0,1000000000);check(Set.of("PERCENT","MG_PER_KG","G_PER_KG","KCAL_PER_KG").contains(text(n.get("unit"),20)));check(Set.of("AS_FED","DRY_MATTER").contains(text(n.get("basis"),20)));check(Set.of("MIN","MAX","EXACT").contains(text(n.get("qualifier"),10)));}
  var stages=(List<?>)b.get("life_stage_ids");check(stages.size()<=30);seen.clear();for(Object x:stages){UUID id=uuid(x);check(seen.add(id));if(db.queryForObject("SELECT count(*) FROM pet_life_stage_definitions d JOIN pet_life_stage_rule_versions v ON v.id=d.rule_version_id JOIN pet_species p ON p.id=v.species_id JOIN spus s ON s.pet_category=p.category JOIN skus k ON k.spu_id=s.id WHERE d.id=? AND k.id=? AND v.status='PUBLISHED'",Integer.class,id,skuId)==0)throw new Failure(422,"LIFE_STAGE_MISMATCH");}
  var sources=(List<?>)b.get("source_refs");check(!sources.isEmpty()&&sources.size()<=20);sources.forEach(x->text(x,2000));
  try{LocalDate d=LocalDate.parse(String.valueOf(b.get("source_updated_on")));check(d.getYear()>=1900&&!d.isAfter(LocalDate.now(clock.withZone(ZoneId.of("Asia/Shanghai")))));}catch(Failure f){throw f;}catch(Exception e){throw new Failure(400,"VALIDATION_ERROR");}
  return b;
 }
 Map<String,Object> insertVersion(Actor a,UUID skuId,Map<String,Object>b){standard(b,skuId);long n=db.queryForObject("SELECT COALESCE(max(version_no),0)+1 FROM sku_standard_versions WHERE sku_id=?",Long.class,skuId);UUID id=UUID.randomUUID();db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by) VALUES (?,?,?,?::jsonb,?::jsonb,?,?::jsonb,?::jsonb,?::date,?)",id,skuId,n,json.writeValueAsString(b.get("ingredients")),json.writeValueAsString(b.get("nutrients")),b.get("allergens_known"),json.writeValueAsString(b.get("life_stage_ids")),json.writeValueAsString(b.get("source_refs")),b.get("source_updated_on"),a.principalId());for(Object x:(List<?>)b.get("allergen_ids"))db.update("INSERT INTO sku_allergens VALUES (?,?)",id,uuid(x));return Map.of("id",id,"sku_id",skuId,"version_no",n,"status","DRAFT");}
 public Map<String,Object> draft(Actor a,UUID skuId,Map<String,Object>b,String match,String proof,String key,HttpServletRequest r){long expected=version(match);return write(a,"catalog.draft:"+skuId,key,Map.of("body",b,"version",expected),proof,r,()->{var row=sku(skuId);sameVersion(row,expected);var result=new LinkedHashMap<>(insertVersion(a,skuId,b));db.update("UPDATE skus SET version=version+1 WHERE id=?",skuId);result.put("sku_version",expected+1);return result;});}
 Map<String,Object> publishVersion(UUID id,UUID skuId,HttpServletRequest r){var rows=db.queryForList("SELECT * FROM sku_standard_versions WHERE id=? AND sku_id=? AND status='DRAFT' FOR UPDATE",id,skuId);if(rows.isEmpty())throw new Failure(409,"STANDARD_NOT_DRAFT");var draft=rows.getFirst();Map<String,Object> b=new LinkedHashMap<>();for(String f:List.of("ingredients","nutrients","life_stage_ids","source_refs"))b.put(f,json.readValue(draft.get(f).toString(),List.class));b.put("allergen_ids",db.queryForList("SELECT allergen_id FROM sku_allergens WHERE standard_version_id=?",UUID.class,id).stream().map(UUID::toString).toList());b.put("allergens_known",draft.get("allergens_known"));b.put("source_updated_on",draft.get("source_updated_on").toString());standard(b,skuId);
  db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=? AND status='PUBLISHED'",skuId);db.update("UPDATE sku_standard_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",id);db.update("UPDATE skus SET version=version+1 WHERE id=?",skuId);outbox.append("CATALOG_SKU",skuId.toString(),"CatalogStandardPublished",1,Map.of("sku_id",skuId.toString(),"standard_version_id",id.toString()),r==null?null:(String)r.getAttribute("correlation_id"));return Map.of("id",id,"sku_id",skuId,"status","PUBLISHED","sku_version",db.queryForObject("SELECT version FROM skus WHERE id=?",Long.class,skuId));
 }
 public Map<String,Object> publish(Actor a,UUID id,String match,String proof,String key,HttpServletRequest r){long expected=version(match);return write(a,"catalog.publish:"+id,key,Map.of("version",expected),proof,r,()->{var rows=db.queryForList("SELECT sku_id FROM sku_standard_versions WHERE id=?",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");UUID sku=(UUID)rows.getFirst().get("sku_id");sameVersion(sku(sku),expected);return publishVersion(id,sku,r);});}
 public Map<String,Object> getSku(Actor a,UUID id){permission(a,false);return tx.execute(s->{var row=sku(id);row.put("standard_versions",db.queryForList("SELECT id FROM sku_standard_versions WHERE sku_id=? AND (? OR status='PUBLISHED') ORDER BY version_no",id,a.realm()==Actor.Realm.ADMIN).stream().map(x->viewVersion((UUID)x.get("id"))).toList());return row;});}
 Map<String,Object> viewVersion(UUID id){var row=db.queryForMap("SELECT * FROM sku_standard_versions WHERE id=?",id);for(String f:List.of("ingredients","nutrients","life_stage_ids","source_refs"))row.put(f,json.readValue(row.get(f).toString(),List.class));row.put("source_updated_on",row.get("source_updated_on").toString());row.put("allergen_ids",db.queryForList("SELECT allergen_id FROM sku_allergens WHERE standard_version_id=? ORDER BY allergen_id",UUID.class,id));return row;}
 public Map<String,Object> correction(Actor a,Map<String,Object>b,String key,HttpServletRequest r){merchant(a);fields(b,"sku_id","base_sku_version","reason","standard");UUID skuId=uuid(b.get("sku_id"));long expected=number(b.get("base_sku_version"),0,Long.MAX_VALUE);check(b.get("standard") instanceof Map<?,?>);return commands.command(a,"catalog.request",key,b,()->{sameVersion(sku(skuId),expected);var proposed=standard((Map<String,Object>)b.get("standard"),skuId);UUID id=UUID.randomUUID();db.update("INSERT INTO catalog_change_requests(id,merchant_id,submitted_by,sku_id,base_sku_version,proposal,reason) VALUES (?,?,?,?,?,?::jsonb,?)",id,a.merchantId(),a.principalId(),skuId,expected,json.writeValueAsString(proposed),text(b.get("reason"),2000));audit.write(a,"catalog.request","CATALOG_REQUEST",id.toString(),Map.of(),Map.of("sku_id",skuId),r);return Map.of("id",id,"status","PENDING","version",0);});}
 public Map<String,Object> requestView(Actor a,UUID id){var rows=db.queryForList("SELECT * FROM catalog_change_requests WHERE id=?",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");var row=rows.getFirst();if(a.realm()==Actor.Realm.MERCHANT){merchant(a);if(!a.merchantId().equals(row.get("merchant_id")))throw new Failure(404,"RESOURCE_NOT_FOUND");}else permission(a,false);row.put("proposal",json.readValue(row.get("proposal").toString(),Map.class));row.put("reviews",db.queryForList("SELECT * FROM catalog_review_records WHERE request_id=?",id));return row;}
 public PetService.ResultPage requests(Actor a,String cursor,int limit){if(a.realm()==Actor.Realm.MERCHANT)merchant(a);else permission(a,false);check(limit>0&&limit<=100);UUID after=cursor==null?new UUID(0,0):uuid(cursor);var rows=a.realm()==Actor.Realm.MERCHANT?db.queryForList("SELECT id FROM catalog_change_requests WHERE merchant_id=? AND id>? ORDER BY id LIMIT ?",a.merchantId(),after,limit+1):db.queryForList("SELECT id FROM catalog_change_requests WHERE id>? ORDER BY id LIMIT ?",after,limit+1);boolean more=rows.size()>limit;var data=rows.stream().limit(limit).map(x->requestView(a,(UUID)x.get("id"))).toList();return new PetService.ResultPage(data,more?data.getLast().get("id").toString():null,more);}
 public Map<String,Object> review(Actor a,UUID id,boolean approve,Map<String,Object>b,String match,String proof,String key,HttpServletRequest r){fields(b,"reason");String reason=text(b.get("reason"),2000);long expected=version(match);return write(a,"catalog.review:"+id,key,Map.of("approve",approve,"reason",reason,"version",expected),proof,r,()->{var rows=db.queryForList("SELECT * FROM catalog_change_requests WHERE id=? FOR UPDATE",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");var row=rows.getFirst();sameVersion(row,expected);if(!"PENDING".equals(row.get("status")))throw new Failure(409,"REQUEST_ALREADY_REVIEWED");UUID skuId=(UUID)row.get("sku_id"),result=null;if(approve){sameVersion(sku(skuId),((Number)row.get("base_sku_version")).longValue());result=(UUID)insertVersion(a,skuId,json.readValue(row.get("proposal").toString(),Map.class)).get("id");publishVersion(result,skuId,r);}String status=approve?"APPROVED":"REJECTED";db.update("UPDATE catalog_change_requests SET status=?,version=version+1,result_version_id=? WHERE id=?",status,result,id);db.update("INSERT INTO catalog_review_records(id,request_id,reviewer_id,decision,reason) VALUES (?,?,?,?,?)",UUID.randomUUID(),id,a.principalId(),status,reason);return Map.of("id",id,"status",status,"version",expected+1);});}
 public Map<String,Object> preview(Actor a,Map<String,Object>b,String key,HttpServletRequest r){permission(a,true);fields(b,"format","content_base64");String format=text(b.get("format"),8);var input=CatalogImportParser.parse(format,text(b.get("content_base64"),2800000));return commands.command(a,"catalog.import.preview",key,b,()->{UUID id=UUID.randomUUID();db.update("INSERT INTO catalog_import_batches(id,created_by,format,status) VALUES (?,?,?,'PREVIEW')",id,a.principalId(),format);Set<String> seen=new HashSet<>();int n=0;for(var item:input){List<String> errors=new ArrayList<>();Long base=null;try{fields(item,"sku_code","standard");String code=text(item.get("sku_code"),80);if(!seen.add(code))errors.add("DUPLICATE_ROW");var rows=db.queryForList("SELECT id,version FROM skus WHERE sku_code=? AND status='ACTIVE'",code);if(rows.isEmpty())errors.add("SKU_NOT_FOUND");else{base=((Number)rows.getFirst().get("version")).longValue();check(item.get("standard") instanceof Map<?,?>);standard((Map<String,Object>)item.get("standard"),(UUID)rows.getFirst().get("id"));}}catch(Failure f){errors.add(f.code);}db.update("INSERT INTO catalog_import_rows(batch_id,row_no,payload,error_codes,base_sku_version) VALUES (?,?,?::jsonb,?::jsonb,?)",id,++n,json.writeValueAsString(item),json.writeValueAsString(errors),base);}audit.write(a,"catalog.import.preview","CATALOG_IMPORT",id.toString(),Map.of(),Map.of("row_count",n),r);return batch(a,id);});}
 public Map<String,Object> batch(Actor a,UUID id){permission(a,false);var rows=db.queryForList("SELECT * FROM catalog_import_batches WHERE id=?",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");var row=rows.getFirst();row.put("rows",db.queryForList("SELECT * FROM catalog_import_rows WHERE batch_id=? ORDER BY row_no",id).stream().map(x->{x.put("payload",json.readValue(x.get("payload").toString(),Map.class));x.put("error_codes",json.readValue(x.get("error_codes").toString(),List.class));return x;}).toList());return row;}
 public Map<String,Object> finishBatch(Actor a,UUID id,boolean confirm,String match,String proof,String key,HttpServletRequest r){long expected=version(match);return write(a,"catalog.import.finish:"+id,key,Map.of("confirm",confirm,"version",expected),proof,r,()->{var rows=db.queryForList("SELECT * FROM catalog_import_batches WHERE id=? FOR UPDATE",id);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");var row=rows.getFirst();sameVersion(row,expected);if(!"PREVIEW".equals(row.get("status")))throw new Failure(409,"IMPORT_ALREADY_FINISHED");if(confirm){if(db.queryForObject("SELECT count(*) FROM catalog_import_rows WHERE batch_id=? AND error_codes<>'[]'::jsonb",Integer.class,id)>0)throw new Failure(422,"IMPORT_HAS_ERRORS");var items=db.queryForList("SELECT * FROM catalog_import_rows WHERE batch_id=? ORDER BY payload->>'sku_code'",id);for(var item:items){var payload=json.readValue(item.get("payload").toString(),Map.class);UUID skuId=db.queryForObject("SELECT id FROM skus WHERE sku_code=?",UUID.class,payload.get("sku_code"));sameVersion(sku(skuId),((Number)item.get("base_sku_version")).longValue());UUID v=(UUID)insertVersion(a,skuId,(Map<String,Object>)payload.get("standard")).get("id");publishVersion(v,skuId,r);db.update("UPDATE catalog_import_rows SET result_version_id=? WHERE batch_id=? AND row_no=?",v,id,item.get("row_no"));}}String status=confirm?"CONFIRMED":"CANCELLED";db.update("UPDATE catalog_import_batches SET status=?,version=version+1 WHERE id=?",status,id);return Map.of("id",id,"status",status,"version",expected+1);});}
}
