<script setup lang="ts">
import {ref,watch} from 'vue';
import {unwrap,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
const props=defineProps<{session:StaffSession;realm:'merchant'|'admin';suborderId:string;itemNames?:Record<string,string>}>();
const emit=defineEmits<{changed:[]}>();
type Cancellation=components['schemas']['Cancellation'];type Fulfillment=components['schemas']['Fulfillment'];
const rows=ref<Cancellation[]>([]),fulfillment=ref<Fulfillment>(),busy=ref(false),error=ref(''),notice=ref(''),quantities=ref<Record<string,number>>({});let generation=0,key='',fingerprint='';
function money(fen:number){return `¥${(fen/100).toFixed(2)}`;}
function state(value:string){return ({REQUESTED:'待受理',ACCEPTED:'已受理',REFUND_PENDING:'退款处理中',COMPLETED:'已完成',REJECTED:'已驳回'} as Record<string,string>)[value]??'状态未知';}
function refundState(c:Cancellation){if(!c.refund)return c.refund_amount_fen>0?'退款待登记':'无退款';return ({CREATED:'退款待发起',PROCESSING:'退款处理中',SUCCEEDED:`退款成功 ${c.refund.refund_no}`,FAILED_RETRYABLE:'退款重试中',FAILED_FINAL:'退款待人工处理',CANCELLED:'退款已作废'} as Record<string,string>)[c.refund.status]??'退款状态未知';}
async function load(){if(busy.value)return;const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';try{const base=props.realm==='merchant'?'/merchant/suborders/{id}/cancellations':'/admin/suborders/{id}/cancellations';const value=unwrap(await props.session.client.api.GET(base,{params:{path:{id:props.suborderId}}})).data;const fulfil=props.realm==='merchant'&&props.session.can('order.cancel.handle')?unwrap(await props.session.client.api.GET('/merchant/suborders/{id}/fulfillment',{params:{path:{id:props.suborderId}}})).data:undefined;if(epoch===generation&&identity===props.session.state.principal?.session_id){rows.value=value;fulfillment.value=fulfil;if(fulfil)quantities.value=Object.fromEntries(fulfil.items.map(i=>[i.order_item_id,0]));}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
async function cancel(){const f=fulfillment.value;if(!f||busy.value)return;const body={reason_code:'MERCHANT_OUT_OF_STOCK' as const,items:f.items.filter(i=>(quantities.value[i.order_item_id]??0)>0).map(i=>({order_item_id:i.order_item_id,quantity:quantities.value[i.order_item_id]!}))};const next=JSON.stringify([f.suborder_id,f.version,body]);if(next!==fingerprint){fingerprint=next;key=crypto.randomUUID();}const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';notice.value='';try{const value=unwrap(await props.session.client.api.POST('/merchant/suborders/{id}/cancellations',{params:{path:{id:f.suborder_id},header:{'Idempotency-Key':key}},body})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id){rows.value=[...rows.value,value];quantities.value=Object.fromEntries(f.items.map(i=>[i.order_item_id,0]));key='';notice.value=value.refund?`取消成立，退款 ${money(value.refund_amount_fen)} 原路退回`:'取消成立';emit('changed');}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
watch(()=>[props.suborderId,props.session.state.principal?.session_id],()=>{generation++;rows.value=[];fulfillment.value=undefined;quantities.value={};error.value='';notice.value='';key='';fingerprint='';busy.value=false;if(props.session.state.principal?.session_id)load();},{immediate:true});
</script>
<template>
<section>
<h3>付款后取消</h3><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p><button :disabled="busy" @click="load">刷新取消记录</button>
<p v-if="!busy&&!rows.length">暂无取消记录</p>
<article v-for="c in rows" :key="c.id"><p>{{ state(c.status) }} · {{ c.actor_type==='MERCHANT'?'商家缺货取消':c.actor_type==='CONSUMER'?'消费者取消':'系统取消' }} · 退款 {{ money(c.refund_amount_fen) }} · {{ refundState(c) }}</p><p v-for="i in c.items" :key="i.id">{{ itemNames?.[i.order_item_id]??'商品' }} × {{ i.quantity }}<template v-if="i.shipping_refund_fen>0"> · 含运费 {{ money(i.shipping_refund_fen) }}</template></p></article>
<form v-if="realm==='merchant'&&session.can('order.cancel.handle')&&fulfillment&&fulfillment.items.some(i=>i.quantity-i.cancelled_qty-i.shipped_qty>0)" @submit.prevent="cancel"><p>缺货或未发货部分可取消，数量按冻结单位占额，退款原路返回。</p><label v-for="i in fulfillment.items.filter(i=>i.quantity-i.cancelled_qty-i.shipped_qty>0)" :key="i.order_item_id">取消数量 {{ itemNames?.[i.order_item_id]??'商品' }}（可取消 {{ i.quantity-i.cancelled_qty-i.shipped_qty }}）<input v-model.number="quantities[i.order_item_id]" type="number" min="0" :max="i.quantity-i.cancelled_qty-i.shipped_qty" required /></label><button :disabled="busy||!Object.values(quantities).some(q=>q>0)">确认取消并退款</button></form>
</section>
</template>
