<script setup lang="ts">
import {onMounted,ref} from 'vue';
import {unwrap,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
const props=defineProps<{session:StaffSession;realm:'admin'|'merchant'}>();
type S=components['schemas'];
const brands=ref<S['CatalogBrand'][]>([]),spus=ref<S['CatalogSpu'][]>([]),skus=ref<S['CatalogSku'][]>([]),requests=ref<S['CatalogRequest'][]>([]);
const detail=ref<S['CatalogSkuDetail']>(),batch=ref<S['CatalogImport']>();
const error=ref(''),notice=ref(''),busy=ref(false),password=ref(''),totp=ref(''),reason=ref('');
const name=ref(''),brandId=ref(''),spuId=ref(''),petCategory=ref<S['CatalogSpuInput']['pet_category']>('CAT'),category=ref(''),skuCode=ref(''),barcode=ref(''),weight=ref(1),packageUnit=ref('袋');
const source=ref(''),updated=ref(''),ingredients=ref(''),known=ref(false),allergenIds=ref<string[]>([]),lifeStages=ref<string[]>([]);
const allergens=ref<S['Allergen'][]>([]),species=ref<S['Species'][]>([]);
const nutrients=ref<S['CatalogNutrient'][]>([]);
let turn=0,selectionTurn=0,pending:{fingerprint:string;key:string}|undefined;
async function collect<T>(read:(cursor?:string)=>Promise<{data:T[];page:S['Page']}>){const rows:T[]=[];let cursor:string|undefined;const seen=new Set<string>();for(let i=0;i<1000;i++){const page=await read(cursor);rows.push(...page.data);if(!page.page.has_more)return rows;const next=page.page.next_cursor;if(!next||seen.has(next))throw new Error('INVALID_PAGINATION');seen.add(next);cursor=next;}throw new Error('PAGINATION_LIMIT');}
async function load(){const generation=++turn,sessionId=props.session.state.principal?.session_id;try{
 const values=await Promise.all([
  collect<S['CatalogSku']>(async cursor=>unwrap(await (props.realm==='admin'?props.session.client.api.GET('/admin/skus',{params:{query:{cursor}}}):props.session.client.api.GET('/merchant/catalog/search',{params:{query:{cursor}}})))),
  collect<S['CatalogRequest']>(async cursor=>unwrap(await (props.realm==='admin'?props.session.client.api.GET('/admin/catalog-reviews',{params:{query:{cursor}}}):props.session.client.api.GET('/merchant/catalog-requests',{params:{query:{cursor}}})))),
  props.session.client.api.GET('/public/allergens'),props.session.client.api.GET('/public/pet-taxonomy'),
 ]);
 if(generation!==turn||sessionId!==props.session.state.principal?.session_id)return;
 skus.value=values[0];requests.value=values[1];allergens.value=unwrap(values[2]).data;species.value=unwrap(values[3]).data;
 if(props.realm==='admin'){const [b,p]=await Promise.all([collect<S['CatalogBrand']>(async cursor=>unwrap(await props.session.client.api.GET('/admin/brands',{params:{query:{cursor}}}))),collect<S['CatalogSpu']>(async cursor=>unwrap(await props.session.client.api.GET('/admin/spus',{params:{query:{cursor}}})))]);if(generation===turn&&sessionId===props.session.state.principal?.session_id){brands.value=b;spus.value=p;}}
 }catch(e){if(generation===turn)error.value=explainError(e);}}
async function selectSku(id:string){const selection=++selectionTurn,sessionId=props.session.state.principal?.session_id;try{const result=unwrap(await (props.realm==='admin'?props.session.client.api.GET('/admin/skus/{id}',{params:{path:{id}}}):props.session.client.api.GET('/merchant/catalog/skus/{id}',{params:{path:{id}}}))).data;if(selection!==selectionTurn||sessionId!==props.session.state.principal?.session_id)return;detail.value=result;const latest=result.standard_versions.find(x=>x.status==='PUBLISHED');ingredients.value=latest?.ingredients.join('\n')??'';source.value=latest?.source_refs.join('\n')??'';updated.value=latest?.source_updated_on??'';known.value=latest?.allergens_known??false;allergenIds.value=latest?.allergen_ids??[];lifeStages.value=latest?.life_stage_ids??[];nutrients.value=latest?.nutrients.map(x=>({...x}))??[];}catch(e){if(selection===selectionTurn&&sessionId===props.session.state.principal?.session_id)error.value=explainError(e);}}
function standard():S['CatalogStandardInput']{return structuredClone({ingredients:ingredients.value.split('\n').map(x=>x.trim()).filter(Boolean),source_refs:source.value.split('\n').map(x=>x.trim()).filter(Boolean),source_updated_on:updated.value,allergens_known:known.value,allergen_ids:known.value?[...allergenIds.value]:[],life_stage_ids:[...lifeStages.value],nutrients:nutrients.value.map(x=>({...x}))});}
type Headers={'Idempotency-Key':string;'X-Reverify-Token'?:string;'If-Match'?:string};
async function command(fingerprint:string,action:(h:Headers)=>Promise<unknown>,version?:number,sensitive=true){if(busy.value)return;busy.value=true;error.value='';notice.value='';const sessionId=props.session.state.principal?.session_id;if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,key:crypto.randomUUID()};try{const h:Headers={'Idempotency-Key':pending.key};if(version!==undefined)h['If-Match']=`"${version}"`;if(sensitive){const proof=await props.session.client.reverify({action:'catalog.standard.write',password:password.value,totp_code:totp.value});h['X-Reverify-Token']=proof.reverify_token;}await action(h);if(sessionId===props.session.state.principal?.session_id){pending=undefined;notice.value='已保存，操作已记录。';await load();if(detail.value)await selectSku(detail.value.id);}}catch(e){if(sessionId===props.session.state.principal?.session_id)error.value=explainError(e);}finally{busy.value=false;password.value='';totp.value='';}}
async function create(kind:'brands'|'spus'|'skus'){
 const b=kind==='brands'?{name:name.value,source_ref:source.value}:kind==='spus'?{brand_id:brandId.value,name:name.value,pet_category:petCategory.value,category:category.value}:{spu_id:spuId.value,sku_code:skuCode.value,barcode:barcode.value||null,weight_g:weight.value,package_unit:packageUnit.value};
 await command(JSON.stringify([kind,b]),async h=>{
  if(kind==='brands')unwrap(await props.session.client.api.POST('/admin/brands',{params:{header:{...h,'X-Reverify-Token':h['X-Reverify-Token']!}},body:b as S['CatalogBrandInput']}));
  else if(kind==='spus')unwrap(await props.session.client.api.POST('/admin/spus',{params:{header:{...h,'X-Reverify-Token':h['X-Reverify-Token']!}},body:b as S['CatalogSpuInput']}));
  else unwrap(await props.session.client.api.POST('/admin/skus',{params:{header:{...h,'X-Reverify-Token':h['X-Reverify-Token']!}},body:b as S['CatalogSkuInput']}));
 });}
async function saveStandard(){const d=detail.value;if(!d)return;const body=standard();await command(JSON.stringify(['draft',d.id,d.version,body]),async h=>unwrap(await props.session.client.api.POST('/admin/skus/{id}/standard-versions',{params:{path:{id:d.id},header:{...h,'If-Match':h['If-Match']!,'X-Reverify-Token':h['X-Reverify-Token']!}},body})),d.version);}
async function publish(id:string){const d=detail.value;if(!d)return;await command(JSON.stringify(['publish',id,d.version]),async h=>unwrap(await props.session.client.api.POST('/admin/sku-standard-versions/{id}/publish',{params:{path:{id},header:{...h,'If-Match':h['If-Match']!,'X-Reverify-Token':h['X-Reverify-Token']!}}})),d.version);}
async function correction(){const d=detail.value;if(!d)return;const body={sku_id:d.id,base_sku_version:d.version,reason:reason.value,standard:standard()};await command(JSON.stringify(['correction',body]),async h=>unwrap(await props.session.client.api.POST('/merchant/catalog-requests',{params:{header:h},body})),undefined,false);}
async function review(row:S['CatalogRequest'],approve:boolean){const body={reason:reason.value},path=approve?'/admin/catalog-reviews/{id}/approve':'/admin/catalog-reviews/{id}/reject';await command(JSON.stringify(['review',row.id,row.version,approve,body]),async h=>unwrap(await props.session.client.api.POST(path,{params:{path:{id:row.id},header:{...h,'If-Match':h['If-Match']!,'X-Reverify-Token':h['X-Reverify-Token']!}},body})),row.version);}
async function preview(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>2000000){error.value='文件超过 2 MB。';return;}const bytes=new Uint8Array(await file.arrayBuffer());let raw='';bytes.forEach(x=>raw+=String.fromCharCode(x));const body:S['CatalogImportInput']={format:file.name.toLowerCase().endsWith('.xlsx')?'XLSX':'CSV',content_base64:btoa(raw)};await command(JSON.stringify(['preview',body]),async h=>{batch.value=unwrap(await props.session.client.api.POST('/admin/catalog-imports',{params:{header:h},body})).data;},undefined,false);}
async function finish(confirm:boolean){const b=batch.value;if(!b)return;const path=confirm?'/admin/catalog-imports/{id}/confirm':'/admin/catalog-imports/{id}/cancel';await command(JSON.stringify(['import',b.id,b.version,confirm]),async h=>{unwrap(await props.session.client.api.POST(path,{params:{path:{id:b.id},header:{...h,'If-Match':h['If-Match']!,'X-Reverify-Token':h['X-Reverify-Token']!}}}));batch.value=unwrap(await props.session.client.api.GET('/admin/catalog-imports/{id}',{params:{path:{id:b.id}}})).data;},b.version);}
onMounted(load);
</script>
<template>
 <div :inert="busy" :aria-busy="busy">
<div class="page-heading"><div><p class="eyebrow">STANDARD CATALOG</p><h1>{{ realm==='admin'?'标准商品与审核':'平台标准商品' }}</h1><p class="muted">配料、营养与来源按版本保留。商家可提交纠错申请，由平台审核。</p></div><button class="secondary" :disabled="busy" @click="load">刷新</button></div>
 <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="notice" class="notice" role="status">{{ notice }}</p>
 <div class="cards"><article v-for="item in skus" :key="item.id"><h2>{{ item.sku_code }}</h2><p>{{ item.weight_g }} 克 · {{ item.package_unit }}</p><button class="secondary" :disabled="busy" @click="selectSku(item.id)">查看标准资料</button></article></div><p v-if="!skus.length">尚无标准商品。</p>
 <section v-if="realm==='admin'&&session.can('catalog.standard.write')" class="confirm-card"><h2>操作验证</h2><label>再次输入密码<input v-model="password" type="password" autocomplete="current-password" :disabled="busy" /></label><label>新的动态验证码<input v-model="totp" inputmode="numeric" maxlength="6" autocomplete="one-time-code" :disabled="busy" /></label></section>
 <details v-if="realm==='admin'&&session.can('catalog.standard.write')" class="confirm-card">
<summary>新建品牌、商品与规格</summary>
 <form @submit.prevent="create('brands')"><h2>品牌</h2><label>名称<input v-model="name" required maxlength="160" /></label><label>来源依据<textarea v-model="source" required /></label><button :disabled="busy||!password||!totp">创建品牌</button></form>
 <form @submit.prevent="create('spus')"><h2>标准商品</h2><label>品牌<select v-model="brandId" required><option value="" disabled>请选择</option><option v-for="b in brands" :key="b.id" :value="b.id">{{ b.name }}</option></select></label><label>商品名称<input v-model="name" required /></label><label>宠物类别<select v-model="petCategory"><option>CAT</option><option>DOG</option><option>AQUATIC</option><option>BIRD</option><option>SMALL_PET</option></select></label><label>商品类目<input v-model="category" required maxlength="80" /></label><button :disabled="busy||!password||!totp">创建商品</button></form>
 <form @submit.prevent="create('skus')"><h2>标准规格</h2><label>所属商品<select v-model="spuId" required><option value="" disabled>请选择</option><option v-for="p in spus" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>规格标识<input v-model="skuCode" required maxlength="80" /></label><label>条码<input v-model="barcode" maxlength="80" /></label><label>净重（克）<input v-model.number="weight" type="number" min="1" max="100000000" required /></label><label>包装单位<input v-model="packageUnit" required maxlength="40" /></label><button :disabled="busy||!password||!totp">创建规格</button></form>
</details>
 <section v-if="detail" class="confirm-card">
<h2>{{ detail.sku_code }} 的标准资料</h2><article v-for="v in detail.standard_versions" :key="v.id"><h3>版本 {{ v.version_no }} · {{ v.status }}</h3><p>配料：{{ v.ingredients.join('、') }}</p><p>过敏原：{{ v.allergens_known?(v.allergen_ids.map(id=>allergens.find(a=>a.id===id)?.name??id).join('、')||'来源明确无标注过敏原'):'信息不足' }}</p><ul><li v-for="n in v.nutrients" :key="n.name">{{ n.name }} · {{ n.value_milli/1000 }} {{ n.unit }} · {{ n.qualifier }} / {{ n.basis }}</li></ul><p>来源更新日期：{{ v.source_updated_on }}</p><ul><li v-for="s in v.source_refs" :key="s">{{ s }}</li></ul><button v-if="v.status==='DRAFT'&&session.can('catalog.standard.write')" :disabled="busy||!password||!totp" @click="publish(v.id)">发布此版本</button></article>
 <form v-if="realm==='admin'?session.can('catalog.standard.write'):session.can('catalog.request.write')" @submit.prevent="realm==='admin'?saveStandard():correction()">
<h3>{{ realm==='admin'?'创建新的资料草稿':'提交标准资料纠错' }}</h3><label>配料（每行一项，保留原始顺序）<textarea v-model="ingredients" required /></label><label>来源依据（每行一条）<textarea v-model="source" required /></label><label>来源更新日期<input v-model="updated" type="date" required /></label><label><input v-model="known" type="checkbox" />来源足以确认过敏原信息</label><label v-if="known">标注的过敏原<select v-model="allergenIds" multiple><option v-for="a in allergens" :key="a.id" :value="a.id">{{ a.name }}</option></select></label><label>来源明确的适用阶段<select v-model="lifeStages" multiple><optgroup v-for="p in species" :key="p.id" :label="p.name"><option v-for="stage in p.life_stages.filter(x=>!x.is_unknown)" :key="stage.id" :value="stage.id">{{ stage.display_name }}</option></optgroup></select></label>
 <fieldset v-for="(n,i) in nutrients" :key="i"><legend>营养成分 {{ i+1 }}</legend><label>名称<input v-model="n.name" required /></label><label>标示数值<input :value="n.value_milli/1000" type="number" step="0.001" min="0" required @input="n.value_milli=Math.round(Number(($event.target as HTMLInputElement).value)*1000)" /></label><label>单位<select v-model="n.unit"><option>PERCENT</option><option>MG_PER_KG</option><option>G_PER_KG</option><option>KCAL_PER_KG</option></select></label><label>基准<select v-model="n.basis"><option>AS_FED</option><option>DRY_MATTER</option></select></label><label>界限<select v-model="n.qualifier"><option>MIN</option><option>MAX</option><option>EXACT</option></select></label><button type="button" class="secondary" @click="nutrients.splice(i,1)">移除</button></fieldset><button type="button" class="secondary" @click="nutrients.push({name:'',value_milli:0,unit:'PERCENT',basis:'AS_FED',qualifier:'MIN'})">添加营养项</button><label v-if="realm==='merchant'">纠错原因<textarea v-model="reason" required /></label><p>留空营养和适用阶段表示来源未提供；不会推断或补造资料。</p><button :disabled="busy||(realm==='admin'&&(!password||!totp))">{{ realm==='admin'?'保存新草稿':'提交审核' }}</button>
</form>
</section>
 <section class="confirm-card"><h2>{{ realm==='admin'?'纠错审核':'我的申请' }}</h2><label v-if="realm==='admin'&&session.can('catalog.standard.write')">审核理由<textarea v-model="reason" /></label><article v-for="row in requests" :key="row.id"><h3>{{ row.status }} · {{ row.sku_id }}</h3><p>{{ row.reason }}</p><details><summary>查看提交资料与审核记录</summary><p>配料：{{ row.proposal.ingredients.join('、') }}</p><ul><li v-for="s in row.proposal.source_refs" :key="s">{{ s }}</li></ul><p>来源更新：{{ row.proposal.source_updated_on }}；过敏原信息：{{ row.proposal.allergens_known?'已确认':'信息不足' }}</p><p>过敏原：{{ row.proposal.allergen_ids.map(id=>allergens.find(a=>a.id===id)?.name??id).join('、')||'—' }}</p><p>适用阶段：{{ row.proposal.life_stage_ids.map(id=>species.flatMap(p=>p.life_stages).find(s=>s.id===id)?.display_name??id).join('、')||'信息不足' }}</p><p v-for="n in row.proposal.nutrients" :key="n.name">{{ n.name }}：{{ n.value_milli/1000 }} {{ n.unit }} · {{ n.basis }} / {{ n.qualifier }}</p><p v-for="r in row.reviews" :key="r.id">{{ r.decision }}：{{ r.reason }}</p></details><template v-if="realm==='admin'&&row.status==='PENDING'&&session.can('catalog.standard.write')"><button :disabled="busy||!password||!totp||!reason" @click="review(row,true)">批准并发布新版本</button><button class="secondary" :disabled="busy||!password||!totp||!reason" @click="review(row,false)">驳回</button></template></article><p v-if="!requests.length">暂无申请。</p></section>
 <section v-if="realm==='admin'&&session.can('catalog.standard.write')" class="confirm-card"><h2>批量导入预览</h2><p>上传单工作表 CSV / XLSX；列为 sku_code、standard_json，每批最多 200 行、2 MB。标准资料填写方式见导入模板说明。预览通过后须再次确认发布。</p><input type="file" accept=".csv,.xlsx" :disabled="busy" @change="preview" /><template v-if="batch"><p>批次 {{ batch.id }} · {{ batch.status }}</p><table><thead><tr><th>行号</th><th>待导入资料</th><th>校验结果</th></tr></thead><tbody><tr v-for="row in batch.rows" :key="row.row_no"><td>{{ row.row_no }}</td><td><details><summary>{{ row.payload.sku_code }}</summary><pre>{{ JSON.stringify(row.payload.standard,null,2) }}</pre></details></td><td>{{ row.error_codes.join('、')||'通过' }}</td></tr></tbody></table><template v-if="batch.status==='PREVIEW'"><button :disabled="busy||!password||!totp||batch.rows.some(r=>r.error_codes.length>0)" @click="finish(true)">确认全部发布</button><button class="secondary" :disabled="busy||!password||!totp" @click="finish(false)">取消此批次</button></template></template></section>
 </div>
</template>
<style scoped>textarea{width:100%;min-height:90px;padding:12px;border:1px solid #dbe3dc;border-radius:10px;font:inherit}fieldset{border:1px solid #dbe3dc;border-radius:10px;padding:16px;margin:16px 0}form,article{margin:20px 0}pre{white-space:pre-wrap}</style>
