<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';
import {unwrap,mutationHeaders,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
import PublicationMedia from './PublicationMedia.vue';
const props=defineProps<{session:StaffSession}>();
type Article=components['schemas']['ArticleDetail'];type Input=components['schemas']['ArticleInput'];
const rows=ref<Article[]>([]),selected=ref<Article|null>(null),title=ref(''),bodyText=ref(''),category=ref<Input['category']>('FOOD_KNOWLEDGE'),sources=ref(''),skus=ref(''),sponsored=ref(false),assets=ref<string[]>([]),busy=ref(false),error=ref(''),notice=ref(''),reason=ref(''),password=ref(''),totp=ref(''),cursor=ref<string|null>(null);
let generation=0;const keys=new Map<string,string>();
function key(payload:string){let value=keys.get(payload);if(!value){value=crypto.randomUUID();keys.set(payload,value);}return value;}
function fence(){const gen=generation,id=props.session.state.principal?.session_id;return ()=>gen===generation&&id===props.session.state.principal?.session_id;}
function newDraft(){selected.value=null;title.value='';bodyText.value='';category.value='FOOD_KNOWLEDGE';sources.value='';skus.value='';sponsored.value=false;assets.value=[];reason.value='';password.value='';totp.value='';}
function fill(a:Article){selected.value=a;title.value=a.title;bodyText.value=a.body;category.value=a.category;sources.value=a.source_refs.join('\n');skus.value=a.sku_ids.join('\n');sponsored.value=a.sponsored;assets.value=a.media.map(m=>m.asset_id);reason.value='';password.value='';totp.value='';}
async function load(more=false){if(busy.value)return;const current=fence();busy.value=true;error.value='';try{const result=unwrap(await props.session.client.api.GET('/admin/content',{params:{query:{limit:20,...(more&&cursor.value?{cursor:cursor.value}:{})}}}));if(current()){rows.value=more?[...rows.value,...result.data]:result.data;cursor.value=result.page.next_cursor??null;}}catch(e){if(current())error.value=explainError(e);}finally{if(current())busy.value=false;}}
async function select(id:string){const current=fence();try{const a=unwrap(await props.session.client.api.GET('/admin/content/{id}',{params:{path:{id}}})).data;if(current())fill(a);}catch(e){if(current())error.value=explainError(e);}}
async function upload(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file||busy.value)return;const current=fence();busy.value=true;error.value='';try{if(assets.value.length>=6)throw new Error('limit');const a=await props.session.client.uploadMedia('ARTICLE',file);if(current()){assets.value.push(a.asset_id);notice.value='图片已上传，保存稿件后建立引用';}}catch(e){if(current())error.value=explainError(e);}finally{if(current())busy.value=false;}}
function draft():Input{return {title:title.value,body:bodyText.value,category:category.value,source_refs:sources.value.split('\n').map(s=>s.trim()).filter(Boolean),sku_ids:skus.value.split(/[\s,，]+/).filter(Boolean),sponsored:sponsored.value,asset_ids:assets.value};}
async function save(){if(busy.value)return;const current=fence(),b=draft(),a=selected.value;busy.value=true;error.value='';try{const result=a?unwrap(await props.session.client.api.PATCH('/admin/content/{id}',{params:{path:{id:a.id},header:mutationHeaders(key(`edit:${a.id}:${a.version}:${JSON.stringify(b)}`),undefined,a.version)},body:b})):unwrap(await props.session.client.api.POST('/admin/content',{params:{header:mutationHeaders(key(`create:${JSON.stringify(b)}`))},body:b}));if(current()){fill(result.data);notice.value='稿件已保存，需提交审核后发布';}}catch(e){if(current())error.value=explainError(e);}finally{if(current())busy.value=false;}}
async function submit(){if(busy.value||!selected.value)return;const a=selected.value,current=fence();busy.value=true;error.value='';try{const value=unwrap(await props.session.client.api.POST('/admin/content/{id}/submit',{params:{path:{id:a.id},header:mutationHeaders(key(`submit:${a.id}:${a.version}`),undefined,a.version)},body:{}})).data;if(current()){fill(value);notice.value='已提交保存的稿件';}}catch(e){if(current())error.value=explainError(e);}finally{if(current())busy.value=false;}}
async function moderate(decision:'PUBLISH'|'REJECT'|'HIDE'){if(busy.value||!selected.value||!reason.value.trim())return;const a=selected.value,current=fence(),b={decision,reason:reason.value};busy.value=true;error.value='';try{const proof=await props.session.client.reverify({action:'content.moderate',password:password.value,totp_code:totp.value});if(!current())return;const result=unwrap(await props.session.client.api.POST('/admin/content/{id}/moderation',{params:{path:{id:a.id},header:mutationHeaders(key(`moderate:${a.id}:${a.version}:${JSON.stringify(b)}`),proof.reverify_token,a.version)},body:b})).data;if(current()){fill(result);notice.value='内容审核结果已保存';}}catch(e){if(current())error.value=explainError(e);}finally{if(current()){password.value='';totp.value='';busy.value=false;}}}
watch(()=>props.session.state.principal?.session_id,()=>{generation++;rows.value=[];newDraft();keys.clear();cursor.value=null;busy.value=false;error.value='';notice.value='';if(props.session.state.principal)void load();});onMounted(load);
</script>
<template>
<section>
<div class="page-heading"><div><p class="eyebrow">PAWDAY KNOWLEDGE</p><h1>知识内容</h1><p>食品、品牌与养宠知识；公开内容保留来源与推广标识。</p></div><button :disabled="busy" @click="load()">刷新文章</button></div><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
<div class="cards"><article v-for="a in rows" :key="a.id"><h2>{{ a.title }}</h2><p>{{ a.draft_status }} · {{ a.visibility }} · v{{ a.version }}</p><button class="secondary" @click="select(a.id)">读取文章</button></article></div><button v-if="cursor" :disabled="busy" @click="load(true)">更多文章</button><button v-if="session.can('content.write')" :disabled="busy" class="secondary" @click="newDraft()">新建稿件</button>
<form v-if="session.can('content.write')" class="confirm-card" @submit.prevent="save"><h2>{{ selected?'修订稿件':'新文章' }}</h2><label>文章标题<input v-model="title" maxlength="160" required :disabled="busy" /></label><label>内容分类<select v-model="category" :disabled="busy"><option value="FOOD_KNOWLEDGE">食品知识</option><option value="BRAND_KNOWLEDGE">品牌知识</option><option value="PET_CARE">养宠知识</option></select></label><label>正文<textarea v-model="bodyText" maxlength="20000" required :disabled="busy" rows="8" /></label><label>信息来源（每行一条）<textarea v-model="sources" required :disabled="busy" /></label><label>关联商品 SKU（每行一个）<textarea v-model="skus" :disabled="busy" /></label><label><input v-model="sponsored" type="checkbox" :disabled="busy" />含商业推广</label><label>上传图片<input type="file" accept="image/png,image/jpeg" :disabled="busy||assets.length>=6" @change="upload" /></label><ul><li v-for="id in assets" :key="id">{{ id }} <button type="button" class="secondary" :disabled="busy" @click="assets=assets.filter(x=>x!==id)">移出稿件</button></li></ul><button :disabled="busy">保存新稿件版本</button><button v-if="selected&&['DRAFT','REJECTED'].includes(selected.draft_status)" type="button" :disabled="busy" @click="submit">提交已保存稿件审核</button></form>
<article v-if="selected" class="confirm-card"><h2>稿件预览</h2><p v-if="selected.sponsored" class="notice">商业推广</p><h3>{{ selected.title }}</h3><p style="white-space:pre-wrap">{{ selected.body }}</p><PublicationMedia v-for="m in selected.media" :key="m.asset_id" :client="session.client" :media="m" /><p>来源：{{ selected.source_refs.join('；') }}</p><ul><li v-for="(m,i) in selected.moderation" :key="i">{{ m.decision }} · {{ m.reason }} · {{ m.created_at }}</li></ul></article>
<form v-if="selected&&session.can('content.moderate')" class="confirm-card" @submit.prevent="moderate('PUBLISH')"><h2>审核保存的稿件</h2><p>{{ selected.draft_status }} · v{{ selected.version }}</p><label>审核原因<textarea v-model="reason" maxlength="1000" required /></label><label>再次输入密码<input v-model="password" type="password" required autocomplete="current-password" /></label><label>新的动态验证码<input v-model="totp" maxlength="6" pattern="[0-9]{6}" required /></label><button v-if="selected.draft_status==='SUBMITTED'" :disabled="busy">验证并发布文章</button><button v-if="selected.draft_status==='SUBMITTED'" type="button" :disabled="busy||!reason||!password||!totp" @click="moderate('REJECT')">验证并驳回文章</button><button v-if="selected.visibility==='PUBLIC'" type="button" :disabled="busy||!reason||!password||!totp" @click="moderate('HIDE')">验证并下架文章</button></form>
</section>
</template>
