<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';
import {unwrap,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
const props=defineProps<{session:StaffSession}>();
type Policy=components['schemas']['CommissionPolicy'];
type BufferPolicy=components['schemas']['SettlementPolicy'];
type Entry=components['schemas']['LedgerEntry'];
const policies=ref<Policy[]>([]),bufferPolicies=ref<BufferPolicy[]>([]),entries=ref<Entry[]>([]),ledgerMerchant=ref(''),entryType=ref(''),busy=ref(false),error=ref(''),notice=ref('');
const name=ref(''),rate=ref(500),priority=ref(0),scopeMerchant=ref(''),category=ref(''),effectiveFrom=ref('2026-01-01T00:00:00Z'),bufferDays=ref(7),adjustDirection=ref<'CREDIT'|'DEBIT'>('DEBIT'),adjustAmount=ref(0),adjustReason=ref(''),password=ref(''),totp=ref('');let generation=0;const keys=new Map<string,string>();
function keyFor(payload:string){const existing=keys.get(payload);if(existing)return existing;const created=crypto.randomUUID();keys.set(payload,created);return created;}
function money(fen:number){return `¥${(fen/100).toFixed(2)}`;}
function entryLabel(value:string){return ({SALE_CREDIT:'销售入账',COMMISSION_DEBIT:'佣金扣减',REFUND_DEBIT:'退款冲销',COMMISSION_REVERSAL:'佣金返还',SHIPPING_ADJUSTMENT:'运费调整',SETTLEMENT_DEBIT:'结算出账',SETTLEMENT_ADJUSTMENT:'结算调整',MANUAL_ADJUSTMENT:'人工调整'} as Record<string,string>)[value]??value;}
async function load(){const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';
 try{const policyRows=unwrap(await props.session.client.api.GET('/admin/commission-policies')).data;const bufferRows=unwrap(await props.session.client.api.GET('/admin/settlement-policies')).data;
  if(epoch===generation&&identity===props.session.state.principal?.session_id){policies.value=policyRows;bufferPolicies.value=bufferRows;}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
async function loadLedger(){const id=ledgerMerchant.value.trim();if(!id)return;const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';
 try{const query:{limit:number;entry_type?:'SALE_CREDIT'|'COMMISSION_DEBIT'|'REFUND_DEBIT'|'COMMISSION_REVERSAL'|'SHIPPING_ADJUSTMENT'|'SETTLEMENT_DEBIT'|'SETTLEMENT_ADJUSTMENT'|'MANUAL_ADJUSTMENT'}={limit:30};if(entryType.value)query.entry_type=entryType.value as never;
  const rows=unwrap(await props.session.client.api.GET('/admin/merchants/{id}/ledger',{params:{path:{id},query}})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id)entries.value=rows;}catch(e){if(epoch===generation){error.value=explainError(e);entries.value=[];}}finally{if(epoch===generation)busy.value=false;}}
async function withReverify(action:'settlement.policy.manage'|'ledger.adjust',work:(proof:string)=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';
 try{const proof=await props.session.client.reverify({action,password:password.value,totp_code:totp.value});await work(proof.reverify_token);password.value='';totp.value='';}catch(e){error.value=explainError(e);}finally{busy.value=false;}}
async function publishPolicy(){const body={name:name.value,merchant_id:scopeMerchant.value||null,category:category.value||null,rate_basis_points:rate.value,priority:priority.value,effective_from:effectiveFrom.value};
 await withReverify('settlement.policy.manage',async proof=>{await unwrap(await props.session.client.api.POST('/admin/commission-policies',{params:{header:{'X-Reverify-Token':proof}},body}));notice.value='佣金策略已发布，立即对后续支付生效，历史快照不变。';await load();});}
async function publishBuffer(){const body={buffer_days:bufferDays.value};
 await withReverify('settlement.policy.manage',async proof=>{await unwrap(await props.session.client.api.POST('/admin/settlement-policies',{params:{header:{'X-Reverify-Token':proof}},body}));notice.value='结算缓冲政策已发布，仅影响之后进入缓冲的子订单。';await load();});}
async function adjust(){const id=ledgerMerchant.value.trim();const body={direction:adjustDirection.value,amount_fen:adjustAmount.value,reason:adjustReason.value};
 await withReverify('ledger.adjust',async proof=>{await unwrap(await props.session.client.api.POST('/admin/merchants/{id}/ledger-adjustments',{params:{path:{id},header:{'Idempotency-Key':keyFor(`adjust:${id}:${JSON.stringify(body)}`),'X-Reverify-Token':proof}},body}));notice.value='人工调整已入账并记录审计。';await loadLedger();});}
watch(()=>props.session.state.principal?.session_id,()=>{generation++;policies.value=[];bufferPolicies.value=[];entries.value=[];ledgerMerchant.value='';password.value='';totp.value='';keys.clear();busy.value=false;error.value='';notice.value='';});onMounted(load);
</script>
<template>
<section>
<h3>佣金策略</h3><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
<table v-if="policies.length"><thead><tr><th>名称</th><th>费率</th><th>优先级</th><th>适用范围</th><th>生效时间</th></tr></thead><tbody><tr v-for="p in policies" :key="p.id"><td>{{ p.name }} · v{{ p.policy_version }}</td><td>{{ (p.rate_basis_points/100).toFixed(2) }}%</td><td>{{ p.priority }}</td><td>{{ p.merchant_id?`商家 ${p.merchant_id}`:p.category?`品类 ${p.category}`:'平台默认' }}</td><td>{{ p.effective_from }}</td></tr></tbody></table>
<form class="confirm-card" @submit.prevent="publishPolicy"><h4>发布佣金策略</h4><label>名称<input v-model="name" maxlength="160" :disabled="busy" required /></label><label>费率（基点，100=1%）<input v-model.number="rate" type="number" min="0" max="10000" step="1" :disabled="busy" required /></label><label>优先级<input v-model.number="priority" type="number" step="1" :disabled="busy" required /></label><label>商家编号（留空为平台/品类策略）<input v-model="scopeMerchant" minlength="0" maxlength="36" :disabled="busy" /></label><label>品类（留空为全部品类）<input v-model="category" maxlength="80" :disabled="busy" /></label><label>生效时间（ISO 时间）<input v-model="effectiveFrom" :disabled="busy" required /></label><label>再次输入密码<input v-model="password" type="password" autocomplete="current-password" :disabled="busy" required /></label><label>新的动态验证码<input v-model="totp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" :disabled="busy" required /></label><button :disabled="busy" type="submit">验证并发布佣金策略</button></form>
<h3>结算缓冲政策</h3>
<table v-if="bufferPolicies.length"><thead><tr><th>版本</th><th>缓冲天数</th><th>发布时间</th></tr></thead><tbody><tr v-for="p in bufferPolicies" :key="p.id"><td>v{{ p.policy_version }}</td><td>{{ p.buffer_days }} 天</td><td>{{ p.created_at }}</td></tr></tbody></table>
<form class="confirm-card" @submit.prevent="publishBuffer"><h4>调整售后缓冲天数</h4><label>缓冲天数<input v-model.number="bufferDays" type="number" min="0" max="90" step="1" :disabled="busy" required /></label><label>再次输入密码<input v-model="password" type="password" autocomplete="current-password" :disabled="busy" required /></label><label>新的动态验证码<input v-model="totp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" :disabled="busy" required /></label><button :disabled="busy" type="submit">验证并发布缓冲政策</button></form>
<h3>商家账本</h3><label>商家编号<input v-model="ledgerMerchant" minlength="36" maxlength="36" :disabled="busy" /></label><label>类型筛选<select v-model="entryType" @change="loadLedger()"><option value="">全部</option><option value="SALE_CREDIT">销售入账</option><option value="COMMISSION_DEBIT">佣金扣减</option><option value="REFUND_DEBIT">退款冲销</option><option value="COMMISSION_REVERSAL">佣金返还</option><option value="SHIPPING_ADJUSTMENT">运费调整</option><option value="SETTLEMENT_DEBIT">结算出账</option><option value="SETTLEMENT_ADJUSTMENT">结算调整</option><option value="MANUAL_ADJUSTMENT">人工调整</option></select></label><button class="secondary" :disabled="busy" @click="loadLedger()">读取账本</button>
<table v-if="entries.length"><thead><tr><th>类型</th><th>方向</th><th>金额</th><th>来源</th><th>时间</th></tr></thead><tbody><tr v-for="e in entries" :key="e.id"><td>{{ entryLabel(e.entry_type) }}<template v-if="!e.affects_balance">（凭证）</template></td><td>{{ e.direction==='CREDIT'?'入账':'扣减' }}</td><td>{{ money(e.amount_fen) }}</td><td>{{ e.source_event }}</td><td>{{ e.created_at }}</td></tr></tbody></table><p v-else-if="!busy">暂无账本条目</p>
<form class="confirm-card" @submit.prevent="adjust"><h4>人工账本调整</h4><label>方向<select v-model="adjustDirection"><option value="DEBIT">扣减商家</option><option value="CREDIT">补入商家</option></select></label><label>金额（分）<input v-model.number="adjustAmount" type="number" min="1" step="1" :disabled="busy" required /></label><label>调整原因<input v-model="adjustReason" maxlength="500" :disabled="busy" required /></label><label>再次输入密码<input v-model="password" type="password" autocomplete="current-password" :disabled="busy" required /></label><label>新的动态验证码<input v-model="totp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" :disabled="busy" required /></label><button :disabled="busy" type="submit">验证并入账调整</button></form>
</section>
</template>
