<script setup lang="ts">
import {ref,watch} from 'vue';
import {unwrap,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
const props=defineProps<{session:StaffSession;realm:'merchant'|'admin';suborderId:string;itemNames?:Record<string,string>}>();
const emit=defineEmits<{changed:[]}>();
const detail=ref<components['schemas']['Fulfillment']>(),tracking=ref<components['schemas']['Tracking']>(),busy=ref(false),error=ref(''),notice=ref(''),carrier=ref('SF'),number=ref(''),quantities=ref<Record<string,number>>({});let generation=0,key='',fingerprint='';
async function load(){if(busy.value)return;const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';try{const value=unwrap(await props.session.client.api.GET(props.realm==='merchant'?'/merchant/suborders/{id}/fulfillment':'/admin/suborders/{id}/fulfillment',{params:{path:{id:props.suborderId}}})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id){detail.value=value;quantities.value=Object.fromEntries(value.items.map(i=>[i.order_item_id,i.quantity-i.cancelled_qty-i.shipped_qty]));}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
async function ship(){const d=detail.value;if(!d||busy.value)return;const body={carrier_code:carrier.value,tracking_no:number.value,items:d.items.filter(i=>(quantities.value[i.order_item_id]??0)>0).map(i=>({order_item_id:i.order_item_id,quantity:quantities.value[i.order_item_id]!}))};const next=JSON.stringify([d.suborder_id,d.version,body]);if(next!==fingerprint){fingerprint=next;key=crypto.randomUUID();}const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';notice.value='';try{const value=unwrap(await props.session.client.api.POST('/merchant/suborders/{id}/shipments',{params:{path:{id:d.suborder_id},header:{'If-Match':`"${d.version}"`,'Idempotency-Key':key}},body})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id){detail.value=value;quantities.value=Object.fromEntries(value.items.map(i=>[i.order_item_id,i.quantity-i.cancelled_qty-i.shipped_qty]));number.value='';key='';notice.value='包裹已登记发货';emit('changed');}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
async function query(id:string){if(busy.value)return;const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';try{const value=unwrap(await props.session.client.api.GET(props.realm==='merchant'?'/merchant/shipments/{id}/tracking':'/admin/shipments/{id}/tracking',{params:{path:{id}}})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id)tracking.value=value;}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
watch(()=>[props.suborderId,props.session.state.principal?.session_id],()=>{generation++;detail.value=undefined;tracking.value=undefined;number.value='';quantities.value={};error.value='';notice.value='';key='';fingerprint='';busy.value=false;if(props.session.state.principal?.session_id)load();},{immediate:true});
</script>
<template>
<section>
<h3>包裹与收货</h3><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p><button :disabled="busy" @click="load">刷新履约</button>
<template v-if="detail">
<p v-for="i in detail.items" :key="i.order_item_id">{{ itemNames?.[i.order_item_id]??'商品' }} · 已发 {{ i.shipped_qty }}/{{ i.quantity-i.cancelled_qty }} · 已收 {{ i.received_qty }}</p>
<p v-if="detail.delivery_address">收件人 {{ detail.delivery_address.recipient }} · {{ detail.delivery_address.phone }} · 配送地区 {{ detail.delivery_address.province_code }} {{ detail.delivery_address.city_code }} {{ detail.delivery_address.district_code }} · {{ detail.delivery_address.detail }}</p>
<article v-for="h in detail.shipments" :key="h.id"><p>{{ h.carrier_code }} · {{ h.tracking_no }} · {{ h.confirmed_at?'用户已确认收货':'等待用户确认收货' }}</p><button :disabled="busy" @click="query(h.id)">查询此包裹物流</button></article>
<form v-if="realm==='merchant'&&session.can('order.ship')&&detail.items.some(i=>i.quantity-i.cancelled_qty-i.shipped_qty>0)&&!['PENDING_PAYMENT','CANCELLED'].includes(detail.fulfillment_status)" @submit.prevent="ship"><label>物流公司编码<input v-model="carrier" required pattern="[A-Z0-9_]{2,24}" /></label><label>运单号<input v-model="number" required pattern="[A-Za-z0-9-]{6,80}" maxlength="80" /></label><label v-for="i in detail.items" :key="i.order_item_id">本次发货数量 {{ itemNames?.[i.order_item_id]??'商品' }}<input v-model.number="quantities[i.order_item_id]" type="number" min="0" :max="i.quantity-i.cancelled_qty-i.shipped_qty" required /></label><button :disabled="busy||!Object.values(quantities).some(q=>q>0)">确认登记发货</button></form>
</template>
<p v-if="tracking">{{ tracking.status==='UNKNOWN'?'暂无可靠物流轨迹':tracking.status }} · {{ tracking.stale?'信息待更新，可稍后重试':'轨迹已更新' }}。物流签收与用户收货分别记录。</p>
</section>
</template>
