<script setup lang="ts">
import {ref,onMounted,watch} from 'vue';
import {unwrap,type components} from '../../api-client/src';
import {StaffSession,explainError} from './auth';
const props=defineProps<{session:StaffSession}>();
const current=ref<components['schemas']['OrderPolicy']>(),code=ref(''),seconds=ref(900),password=ref(''),totp=ref(''),busy=ref(false),error=ref(''),notice=ref('');let generation=0;const keys=new Map<string,string>();
async function read(){const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';try{const value=unwrap(await props.session.client.api.GET('/admin/order-policies')).data;if(epoch===generation&&identity===props.session.state.principal?.session_id)current.value=value;}catch(e){if(epoch===generation)error.value=explainError(e);}finally{if(epoch===generation)busy.value=false;}}
async function publish(){if(busy.value)return;const epoch=++generation,identity=props.session.state.principal?.session_id;busy.value=true;error.value='';notice.value='';try{const body={version_code:code.value,reservation_ttl_seconds:seconds.value},payload=JSON.stringify(body),key=keys.get(payload)??crypto.randomUUID();keys.set(payload,key);const proof=await props.session.client.reverify({action:'order.policy.manage',password:password.value,totp_code:totp.value});if(epoch!==generation||identity!==props.session.state.principal?.session_id)return;const value=unwrap(await props.session.client.api.POST('/admin/order-policies',{params:{header:{'Idempotency-Key':key,'X-Reverify-Token':proof.reverify_token}},body})).data;if(epoch===generation&&identity===props.session.state.principal?.session_id){current.value=value;notice.value='新付款期限规则已发布，已有订单期限保持原值';}}catch(e){if(epoch===generation)error.value=explainError(e);}finally{password.value='';totp.value='';if(epoch===generation)busy.value=false;}}
watch(()=>props.session.state.principal?.session_id,()=>{generation++;current.value=undefined;code.value='';password.value='';totp.value='';keys.clear();busy.value=false;error.value='';notice.value='';});onMounted(read);
</script>
<template>
 <h1>付款期限规则</h1><p class="muted">发布新版本仅影响之后创建的订单，已有库存及优惠券预占期限保持原值。</p><p v-if="current">当前版本 {{ current.version_code }} · 付款期限 {{ current.reservation_ttl_seconds }} 秒</p><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
 <form class="confirm-card" @submit.prevent="publish"><label>新版本编码<input v-model="code" pattern="[A-Z0-9_]{3,80}" :disabled="busy" required /></label><label>付款期限（秒）<input v-model.number="seconds" type="number" min="60" max="3600" step="1" :disabled="busy" required /></label><label>再次输入密码<input v-model="password" type="password" autocomplete="current-password" :disabled="busy" required /></label><label>新的动态验证码<input v-model="totp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" :disabled="busy" required /></label><button :disabled="busy" type="submit">验证并发布付款期限规则</button></form>
</template>
