package cn.pawday;

import cn.pawday.identity.*;
import cn.pawday.outbox.*;
import cn.pawday.search.*;
import cn.pawday.audit.AuditWriter;
import com.rabbitmq.client.*;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.awaitility.Awaitility.await;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.amqp.rabbit.core.RabbitAdmin;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** Actual PostgreSQL, RabbitMQ and OpenSearch. Network fault injection does not simulate a service. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(BusinessSearchIT.Fixtures.class)
class BusinessSearchIT {
    static final EmbeddedPostgres PG;static final TcpAvailabilityProxy PROXY,RABBIT_PROXY;
    static final String ENDPOINT=Objects.requireNonNull(System.getenv("PAWDAY_IT_OPENSEARCH_URL"),"Real isolated OpenSearch endpoint is mandatory");
    static final String HOST=env("PAWDAY_IT_RABBIT_HOST","127.0.0.1"),USER=env("PAWDAY_IT_RABBIT_USER","pawday_it"),PASSWORD=env("PAWDAY_IT_RABBIT_PASSWORD","TEST_ONLY_m22_broker");
    static final int RABBIT_PORT=Integer.parseInt(env("PAWDAY_IT_RABBIT_PORT","5672"));
    static String env(String name,String fallback){return System.getenv().getOrDefault(name,fallback);}
    static {try{URI endpoint=URI.create(ENDPOINT);if(!Set.of("127.0.0.1","localhost").contains(endpoint.getHost()))throw new IllegalArgumentException("Only isolated loopback search acceptance endpoint allowed");PG=EmbeddedPostgres.builder().setPort(0).start();PROXY=new TcpAvailabilityProxy(endpoint.getHost(),endpoint.getPort());RABBIT_PROXY=new TcpAvailabilityProxy(HOST,RABBIT_PORT);}catch(Exception e){throw new ExceptionInInitializerError(e);}}
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){
        r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
        r.add("spring.rabbitmq.host",()->HOST);r.add("spring.rabbitmq.port",()->RABBIT_PROXY.port());r.add("spring.rabbitmq.username",()->USER);r.add("spring.rabbitmq.password",()->PASSWORD);r.add("management.health.redis.enabled",()->false);
        r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.consumers-enabled",()->false);r.add("pawday.search.workers-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);
        r.add("pawday.search.url",()->"http://127.0.0.1:"+PROXY.port());r.add("pawday.search.timeout-ms",()->800);r.add("pawday.search.retry-max-attempts",()->3);r.add("pawday.search.retry-base-ms",()->50);r.add("pawday.search.lease-ms",()->5000);
        r.add("pawday.outbox.max-attempts",()->3);r.add("pawday.outbox.retry-base-ms",()->50);r.add("pawday.outbox.retry-max-ms",()->200);r.add("management.endpoint.health.show-details",()->"always");
    }
    static class TestClock extends Clock{volatile Instant value=Instant.now();public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return value;}}
    @TestConfiguration static class Fixtures{@Bean @Primary TestClock searchClock(){return new TestClock();}}
    @Autowired BusinessSearchProjection projection;@Autowired BusinessFactConsumer facts;@Autowired BusinessFactRabbitListener factListener;@Autowired JdbcTemplate db;@Autowired TransactionTemplate tx;@Autowired CatalogSearchSource source;@Autowired OpenSearchClient os;@Autowired IndexBootstrap bootstrap;@Autowired AliasManager aliases;@Autowired SearchSyncWorker sync;@Autowired SearchRebuildWorker rebuild;@Autowired SearchInboxConsumer inbox;@Autowired SearchRabbitListener listener;@Autowired OutboxPublisher publisher;@Autowired RabbitAdmin rabbitAdmin;@Autowired Crypto crypto;@Autowired TestClock clock;@Autowired PasswordEncoder passwords;
    @LocalServerPort int port;
    Connection connection;Channel channel;UUID adminId,readerId;String adminToken,readerToken;static String passwordHash;static final String STAFF_PASSWORD="TEST_ONLY_M23_admin_password";static final byte[] MFA="12345678901234567890".getBytes(StandardCharsets.US_ASCII);
    final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
    static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
    @BeforeEach void setup() throws Exception {
        RABBIT_PROXY.recover();PROXY.recover();assertEquals("pawday-m23-it",os.health().get("cluster_name"),"Search gate may only modify the explicitly isolated acceptance cluster");os.request("DELETE","/pawday-product-v1-*",null,404);
        db.execute("ALTER TABLE audit_event DISABLE TRIGGER audit_event_no_truncate");db.execute("ALTER TABLE inventory_adjustments DISABLE TRIGGER inventory_adjustment_no_truncate");
        try{db.execute("TRUNCATE search_admin_command,search_sync_task,search_rebuild_job,search_index_version,catalog_search_source,outbox_replay_command,processed_event,sms_delivery,outbox_event,identity_command,reverify_grant,auth_refresh_token,auth_session,otp_challenge,auth_rate_bucket,principal_store_scope,principal_role,identity_principal,merchant_store,merchant,app_user,role_permission,role,audit_event CASCADE");}finally{db.execute("ALTER TABLE audit_event ENABLE TRIGGER audit_event_no_truncate");db.execute("ALTER TABLE inventory_adjustments ENABLE TRIGGER inventory_adjustment_no_truncate");}
        db.update("INSERT INTO order_policy_versions(id,version_code,reservation_ttl_seconds) VALUES ('40000000-0000-0000-0000-000000000001','ORDER_V1_1',900) ON CONFLICT DO NOTHING");bootstrap.initialize();clock.value=Instant.now();
        var factory=new ConnectionFactory();factory.setHost(HOST);factory.setPort(RABBIT_PORT);factory.setUsername(USER);factory.setPassword(PASSWORD);connection=factory.newConnection();channel=connection.createChannel();rabbitAdmin.initialize();channel.queuePurge(RabbitTopology.CATALOG_STANDARD_QUEUE);channel.queuePurge(RabbitTopology.OFFER_FACT_QUEUE);channel.queuePurge(RabbitTopology.SEARCH_QUEUE);channel.queuePurge(RabbitTopology.DLQ);channel.queuePurge(RabbitTopology.QUEUE);channel.queuePurge("pawday.order.facts");
        if(passwordHash==null)passwordHash=passwords.encode(STAFF_PASSWORD);adminId=principal("m23-admin",List.of("search.read","search.manage","outbox.replay"));readerId=principal("m23-reader",List.of("search.read"));adminToken=session(adminId);readerToken=session(readerId);
    }
    UUID principal(String name,List<String> permissions){UUID id=UUID.randomUUID(),role=UUID.randomUUID();db.update("INSERT INTO identity_principal(id,realm,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,'ADMIN',?,?,?)",id,name,passwordHash,crypto.encrypt(MFA));db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,'ADMIN',?,?)",role,name,name);for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,'ADMIN')",id,role);return id;}
    String session(UUID principal){UUID id=UUID.randomUUID();String token=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'SEARCH-TEST',?,?,?)",id,principal,crypto.hash(token),Timestamp.from(clock.instant().plusSeconds(3600)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));return token;}
    record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}}
    Response call(String method,String path,Object body,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(15));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(body==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var data=json.readTree(response.body());var safe=json.readTree(response.body());if(safe.has("data")&&safe.get("data").has("reverify_token"))((tools.jackson.databind.node.ObjectNode)safe.get("data")).put("reverify_token","A".repeat(43));SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",safe));return new Response(response.statusCode(),data);}catch(Exception e){throw new AssertionError(path,e);}}
    Response call(String method,String path,Object body,String token){return call(method,path,body,token,Map.of());}
    String proof(String action){clock.value=clock.value.plusSeconds(60);var result=call("POST","/admin/auth/reverify",Map.of("action",action,"password",STAFF_PASSWORD,"totp_code",crypto.totp(MFA,clock.instant().getEpochSecond()/30)),adminToken);assertEquals(200,result.status(),result.body().toString());return result.data().get("reverify_token").asString();}
    Response command(String kind,String reason,String proof,String key){return call("POST","/admin/operations/search/"+kind,Map.of("reason_code",reason),adminToken,Map.of("X-Reverify-Token",proof,"Idempotency-Key",key));}
    CatalogSearchSource.Product product(UUID sku,long price){return new CatalogSearchSource.Product(UUID.nameUUIDFromBytes("TEST SPU".getBytes()),sku,"TEST Brand","CAT","ADULT","DRY",List.of("CHICKEN"),price,true,2,Instant.parse("2026-10-03T00:00:00Z"));}
    CatalogSearchSource.Change change(UUID sku,long price,String type){return source.change(product(sku,price),false,type,UUID.randomUUID().toString());}
    GetResponse next(String queue) throws Exception {final GetResponse[] value={null};await().atMost(Duration.ofSeconds(5)).until(()->{value[0]=channel.basicGet(queue,false);return value[0]!=null;});return value[0];}
    void receive() throws Exception {var value=next(RabbitTopology.SEARCH_QUEUE);var p=new org.springframework.amqp.core.MessageProperties();p.setMessageId(value.getProps().getMessageId());p.setDeliveryTag(value.getEnvelope().getDeliveryTag());listener.receive(new org.springframework.amqp.core.Message(value.getBody(),p),channel);}
    void pump() throws Exception {for(int i=0;i<40&&publisher.publishOne();i++){}while(channel.queueDeclarePassive(RabbitTopology.SEARCH_QUEUE).getMessageCount()>0)receive();while(sync.runOne()){} }
    Map<String,Object> doc(UUID sku){os.refresh(aliases.current());return os.documents(aliases.current()).get(sku);}
    void syncChange(UUID sku,long price) throws Exception {change(sku,price,"CatalogPublished");pump();assertNotNull(doc(sku));}
    @AfterEach void close() throws Exception {RABBIT_PROXY.recover();PROXY.recover();if(channel!=null&&channel.isOpen())channel.close();if(connection!=null&&connection.isOpen())connection.close();}
    @AfterAll static void finish() throws Exception {Files.writeString(Path.of("target/m34-search-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));RABBIT_PROXY.close();PROXY.close();PG.close();}


 UUID sku,spu,standard,merchant,offer;
 void catalogFixture(){sku=UUID.randomUUID();spu=UUID.randomUUID();standard=UUID.randomUUID();merchant=UUID.randomUUID();offer=UUID.randomUUID();UUID brand=UUID.randomUUID();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST source')",brand,"TEST real "+sku);db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST food','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",sku,spu,"TEST "+sku);db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST ingredient\"]','[]',false,'[]','[\"TEST source\"]','2026-10-01',?,clock_timestamp())",standard,sku,adminId);db.update("INSERT INTO merchant VALUES (?,'TEST real merchant','ACTIVE')",merchant);db.update("INSERT INTO offers(id,merchant_id,sku_id,sale_price_fen,fulfillment_sla,sale_status) VALUES (?,?,?,1400,'TEST 48h','ACTIVE')",offer,merchant,sku);db.update("INSERT INTO inventory_balances(offer_id,on_hand_qty) VALUES (?,7)",offer);}
 EventEnvelope fact(String type){UUID id=UUID.randomUUID();Map<String,Object> payload=type.equals("CatalogStandardPublished")?Map.of("sku_id",sku.toString(),"standard_version_id",standard.toString()):Map.of("offer_id",offer.toString(),"sku_id",sku.toString(),"version",0);return new EventEnvelope(id,type,1,type.equals("CatalogStandardPublished")?"CATALOG_SKU":"OFFER",type.equals("CatalogStandardPublished")?sku.toString():offer.toString(),null,1,0,payload);}
 void send(EventEnvelope e)throws Exception{channel.confirmSelect();channel.basicPublish(RabbitTopology.EXCHANGE,e.event_type(),new AMQP.BasicProperties.Builder().messageId(e.event_id().toString()).deliveryMode(2).build(),json.writeValueAsBytes(e));channel.waitForConfirmsOrDie(3000);}
 void receiveFact(String queue)throws Exception{var value=next(queue);var p=new org.springframework.amqp.core.MessageProperties();p.setMessageId(value.getProps().getMessageId());p.setDeliveryTag(value.getEnvelope().getDeliveryTag());factListener.receive(new org.springframework.amqp.core.Message(value.getBody(),p),channel);}
 @Test void realFactsThroughRabbitProjectLatestPricesAndInventory()throws Exception{catalogFixture();var e=fact("CatalogStandardPublished");send(e);receiveFact(RabbitTopology.CATALOG_STANDARD_QUEUE);pump();assertEquals(1400,((Number)doc(sku).get("price_min_fen")).intValue());assertEquals(true,doc(sku).get("in_stock"));assertEquals(1,((Number)doc(sku).get("merchant_count")).intValue());assertEquals(200,call("GET","/public/products?pet_category=CAT",null,null).status());UUID consumer=UUID.randomUUID(),user=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",user);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",consumer,user);assertEquals(200,call("GET","/consumer/products?pet_category=CAT",null,session(consumer)).status());}
 @Test void duplicateDeliveryAndCommitBeforeAckCrashStaySingle()throws Exception{catalogFixture();var e=fact("OfferStateChanged");send(e);var m=next(RabbitTopology.OFFER_FACT_QUEUE);facts.process(json.readValue(m.getBody(),EventEnvelope.class));channel.close();channel=connection.createChannel();receiveFact(RabbitTopology.OFFER_FACT_QUEUE);send(e);receiveFact(RabbitTopology.OFFER_FACT_QUEUE);pump();assertEquals(1,db.queryForObject("SELECT count(*) FROM processed_event WHERE consumer=? AND event_id=?",Integer.class,BusinessFactConsumer.CONSUMER,e.event_id()));assertEquals(1,db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Integer.class,sku));}
 @Test void searchOutageDoesNotRollbackFactsAndRecoveryCompensates()throws Exception{catalogFixture();PROXY.unavailable();send(fact("OfferStateChanged"));receiveFact(RabbitTopology.OFFER_FACT_QUEUE);assertEquals(1400,db.queryForObject("SELECT sale_price_fen FROM offers WHERE id=?",Integer.class,offer));assertEquals(1,db.queryForObject("SELECT count(*) FROM catalog_search_source WHERE sku_id=?",Integer.class,sku));for(int i=0;i<10&&publisher.publishOne();i++){}while(channel.queueDeclarePassive(RabbitTopology.SEARCH_QUEUE).getMessageCount()>0)receive();assertTrue(sync.runOne());assertEquals(503,call("GET","/public/products",null,null).status());PROXY.recover();Thread.sleep(100);while(sync.runOne()){}assertEquals(1400,((Number)doc(sku).get("price_min_fen")).intValue());}
 @Test void staleSearchCannotExposeFrozenOffer()throws Exception{catalogFixture();facts.process(fact("OfferStateChanged"));pump();assertNotNull(doc(sku));assertEquals(1,call("GET","/public/products",null,null).data().size());db.update("UPDATE offers SET sale_status='FROZEN' WHERE id=?",offer);assertEquals(0,call("GET","/public/products",null,null).data().size());assertEquals(0,call("GET","/public/skus/"+sku+"/offers",null,null).data().size());facts.process(fact("OfferStateChanged"));pump();assertTrue((Boolean)doc(sku).get("deleted"));}
 @Test void outOfOrderFactsDeriveCurrentStateAndSweepIsIdempotent()throws Exception{catalogFixture();var old=fact("OfferStateChanged");db.update("UPDATE offers SET sale_price_fen=1700,version=1 WHERE id=?",offer);facts.process(old);pump();assertEquals(1700,((Number)doc(sku).get("price_min_fen")).intValue());projection.refresh(sku,"CatalogPublished",null);assertEquals(1,db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Integer.class,sku));db.update("UPDATE inventory_balances SET on_hand_qty=0,version=1 WHERE offer_id=?",offer);projection.refresh(sku,"InventoryAvailabilityChanged",null);pump();assertEquals(false,doc(sku).get("in_stock"));}
 @Test void poisonFactRetriesToDeadAndDlq()throws Exception{catalogFixture();var e=fact("OfferStateChanged");var bad=new EventEnvelope(e.event_id(),e.event_type(),99,e.aggregate_type(),e.aggregate_id(),null,1,0,e.payload());facts.process(bad);facts.process(new EventEnvelope(e.event_id(),e.event_type(),99,e.aggregate_type(),e.aggregate_id(),null,2,0,e.payload()));facts.process(new EventEnvelope(e.event_id(),e.event_type(),99,e.aggregate_type(),e.aggregate_id(),null,3,0,e.payload()));assertEquals("DEAD",db.queryForObject("SELECT status FROM processed_event WHERE consumer=? AND event_id=?",String.class,BusinessFactConsumer.CONSUMER,e.event_id()));for(int i=0;i<10&&publisher.publishOne();i++){}assertNotNull(next(RabbitTopology.DLQ));}

 @Test void realBusinessProjectionRebuildPreservesOldUntilValidated()throws Exception{catalogFixture();projection.refresh(sku,"CatalogPublished",null);pump();String old=aliases.current();assertEquals(202,command("rebuild","BUSINESS_REBUILD",proof("search.rebuild"),"m34-business-rebuild-key").status());pump();PROXY.unavailable();assertTrue(rebuild.runOne());RABBIT_PROXY.recover();PROXY.recover();assertEquals(old,aliases.current());assertEquals(1400,((Number)doc(sku).get("price_min_fen")).intValue());await().atMost(Duration.ofSeconds(8)).until(()->{rebuild.runOne();return db.queryForObject("SELECT status FROM search_rebuild_job",String.class).equals("COMPLETED");});assertNotEquals(old,aliases.current());assertEquals(1400,((Number)doc(sku).get("price_min_fen")).intValue());}
 @Test void controlledReplayRepairsFailedBusinessConsumer()throws Exception{catalogFixture();var e=fact("OfferStateChanged");tx.executeWithoutResult(s->db.update("INSERT INTO outbox_event(id,root_event_id,aggregate_type,aggregate_id,event_type,event_version,payload,status) VALUES (?,?,'OFFER',?,'OfferStateChanged',1,?::jsonb,'PUBLISHED')",e.event_id(),e.event_id(),offer.toString(),json.writeValueAsString(e.payload())));
  db.execute("CREATE FUNCTION test_projection_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'TEST only failure'; END $$");db.execute("CREATE TRIGGER test_projection_failure BEFORE INSERT ON catalog_search_source FOR EACH ROW EXECUTE FUNCTION test_projection_failure()");try{for(int a=1;a<=3;a++)facts.process(new EventEnvelope(e.event_id(),e.event_type(),1,e.aggregate_type(),e.aggregate_id(),null,a,0,e.payload()));}finally{db.execute("DROP TRIGGER test_projection_failure ON catalog_search_source");db.execute("DROP FUNCTION test_projection_failure()");}
  assertEquals("DEAD",db.queryForObject("SELECT status FROM processed_event WHERE consumer=? AND event_id=?",String.class,BusinessFactConsumer.CONSUMER,e.event_id()));String path="/admin/operations/outbox/"+e.event_id()+"/replay";assertEquals(403,call("POST",path,Map.of("expected_generation",0,"reason_code","TEST_REPAIR"),readerToken,Map.of("Idempotency-Key","m34-replay-denied-key")).status());String proof=proof("outbox.replay");assertEquals(200,call("POST",path,Map.of("expected_generation",0,"reason_code","TEST_REPAIR"),adminToken,Map.of("Idempotency-Key","m34-replay-command-key","X-Reverify-Token",proof)).status());facts.process(new EventEnvelope(e.event_id(),e.event_type(),1,e.aggregate_type(),e.aggregate_id(),null,1,1,e.payload()));pump();assertEquals(1400,((Number)doc(sku).get("price_min_fen")).intValue());assertEquals("PROCESSED",db.queryForObject("SELECT status FROM processed_event WHERE consumer=? AND event_id=?",String.class,BusinessFactConsumer.CONSUMER,e.event_id()));
 }

 @Test void multipleStoresDoNotInflateMerchantCountAndMinimumUsesLiveOffers()throws Exception{catalogFixture();UUID store=UUID.randomUUID(),sameOffer=UUID.randomUUID(),otherMerchant=UUID.randomUUID(),otherOffer=UUID.randomUUID();db.update("INSERT INTO merchant_store VALUES (?,?,'TEST extra store')",store,merchant);db.update("INSERT INTO merchant VALUES (?,'TEST second merchant','ACTIVE')",otherMerchant);db.update("INSERT INTO offers(id,merchant_id,store_id,sku_id,sale_price_fen,fulfillment_sla,sale_status) VALUES (?,?,?,?,1200,'TEST extra store','ACTIVE')",sameOffer,merchant,store,sku);db.update("INSERT INTO offers(id,merchant_id,sku_id,sale_price_fen,fulfillment_sla,sale_status) VALUES (?,?,?,900,'TEST other merchant','ACTIVE')",otherOffer,otherMerchant,sku);db.update("INSERT INTO inventory_balances(offer_id,on_hand_qty) VALUES (?,1),(?,2)",sameOffer,otherOffer);projection.refresh(sku,"OfferChanged",null);pump();assertEquals(900,((Number)doc(sku).get("price_min_fen")).intValue());assertEquals(2,((Number)doc(sku).get("merchant_count")).intValue());db.update("UPDATE merchant SET status='SUSPENDED' WHERE id=?",otherMerchant);new BusinessProjectionReconciler(db,projection,true).sweep();pump();assertEquals(1200,((Number)doc(sku).get("price_min_fen")).intValue());assertEquals(1,((Number)doc(sku).get("merchant_count")).intValue());}
 @Test void retiredCatalogIsImmediatelyHiddenAndSweepCreatesStableTombstone()throws Exception{catalogFixture();projection.refresh(sku,"CatalogPublished",null);pump();assertNotNull(doc(sku));db.update("UPDATE skus SET status='RETIRED' WHERE id=?",sku);assertEquals(0,call("GET","/public/products",null,null).data().size());assertEquals(404,call("GET","/public/skus/"+sku,null,null).status());new BusinessProjectionReconciler(db,projection,true).sweep();pump();assertEquals(true,doc(sku).get("deleted"));int version=db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Integer.class,sku);new BusinessProjectionReconciler(db,projection,true).sweep();assertEquals(version,db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Integer.class,sku));}

 @Autowired cn.pawday.ordering.OrderService orders;
 @Autowired cn.pawday.checkout.CheckoutService checkout;
 @Test void orderCommitsDuringRealBrokerPartitionAndRecoversSearch()throws Exception{
  catalogFixture();var initial=fact("CatalogStandardPublished");send(initial);receiveFact(RabbitTopology.CATALOG_STANDARD_QUEUE);pump();assertEquals(true,doc(sku).get("in_stock"));
  UUID user=UUID.randomUUID(),principal=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",user);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",principal,user);String token=session(principal);UUID session=db.queryForObject("SELECT id FROM auth_session WHERE access_token_hash=?",UUID.class,crypto.hash(token));Actor actor=new Actor(principal,Actor.Realm.CONSUMER,user,null,session,Set.of(),Set.of());
  db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,?)",UUID.randomUUID(),merchant,adminId);
  var address=checkout.saveAddress(actor,null,Map.of("recipient","TEST ONLY","phone","13800000000","province_code","310000","detail","TEST ONLY"),null,UUID.randomUUID().toString());
  var item=checkout.add(actor,Map.of("offer_id",offer.toString(),"quantity",7),UUID.randomUUID().toString());var quote=checkout.quote(actor,Map.of("cart_item_ids",List.of(item.get("id").toString()),"address_id",address.get("id").toString()),UUID.randomUUID().toString());
  RABBIT_PROXY.unavailable();var order=orders.create(actor,Map.of("quote_id",quote.get("quote_id").toString()),UUID.randomUUID().toString(),null);UUID id=UUID.fromString(order.get("id").toString());assertEquals(7,db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,offer));
  assertTrue(publisher.publishOne());assertTrue(db.queryForObject("SELECT count(*) FROM outbox_event WHERE status IN ('PENDING','FAILED_RETRYABLE')",Integer.class)>0);
  var row=db.queryForMap("SELECT * FROM outbox_event WHERE event_type='InventoryReservationChanged' AND aggregate_id=?",offer.toString());var payload=json.readValue(row.get("payload").toString(),Map.class);var stock=new EventEnvelope((UUID)row.get("id"),"InventoryReservationChanged",1,"OFFER",offer.toString(),null,1,0,payload);
  RABBIT_PROXY.recover();await().atMost(Duration.ofSeconds(20)).until(()->{publisher.publishOne();return db.queryForObject("SELECT count(*) FROM outbox_event WHERE status<>'PUBLISHED'",Integer.class)==0;});
  receiveFact(RabbitTopology.OFFER_FACT_QUEUE);pump();assertEquals(false,doc(sku).get("in_stock"));long version=db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Long.class,sku);
  send(stock);receiveFact(RabbitTopology.OFFER_FACT_QUEUE);pump();assertEquals(version,db.queryForObject("SELECT revision FROM catalog_search_source WHERE sku_id=?",Long.class,sku));
  PROXY.unavailable();var cancelled=orders.cancel(actor,id,Map.of("reason_code","CONSUMER_CANCELLED"),"\"0\"",UUID.randomUUID().toString(),null);assertEquals("CANCELLED",cancelled.get("status"));assertEquals(0,db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,offer));for(int i=0;i<10&&publisher.publishOne();i++){}receiveFact(RabbitTopology.OFFER_FACT_QUEUE);while(channel.queueDeclarePassive(RabbitTopology.SEARCH_QUEUE).getMessageCount()>0)receive();sync.runOne();
  PROXY.recover();clock.value=clock.value.plusSeconds(60);await().atMost(Duration.ofSeconds(15)).until(()->{sync.runOne();return Boolean.TRUE.equals(doc(sku).get("in_stock"));});assertEquals("PUBLISHED",db.queryForObject("SELECT status FROM outbox_event WHERE event_type='OrderCreated' AND aggregate_id=?",String.class,id.toString()));
 }
}