package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
class CatalogIntegrationTests {
 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader;UUID adminPrincipal,adminSession;String sku,code;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}
 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID(),m=realm.equals("MERCHANT")?UUID.randomUUID():null;if(m!=null)db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",m,key());db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Catalog test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'CATALOG-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("catalog.standard.write")){adminSession=session;adminPrincipal=p;}return t;}
 @BeforeEach void setup(){admin=identity("ADMIN",List.of("catalog.standard.read","catalog.standard.write"));reader=identity("ADMIN",List.of("catalog.standard.read"));merchant=identity("MERCHANT",List.of("catalog.standard.read","catalog.request.write"));foreign=identity("MERCHANT",List.of("catalog.standard.read","catalog.request.write"));String brand=write("/admin/brands",Map.of("name",key(),"source_ref","TEST-ONLY source"),null).id();String spu=write("/admin/spus",Map.of("brand_id",brand,"name",key(),"pet_category","CAT","category","DRY_FOOD"),null).id();code=key();sku=write("/admin/skus",Map.of("spu_id",spu,"sku_code",code,"barcode",key(),"weight_g",1000,"package_unit","BAG"),null).id();}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'catalog.standard.write',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Response write(String path,Object b,String version){Map<String,String> h=new HashMap<>(Map.of("Idempotency-Key",key(),"X-Reverify-Token",proof()));if(version!=null)h.put("If-Match","\""+version+"\"");return req("POST",path,b,admin,h);}
 Map<String,Object> standard(){return new LinkedHashMap<>(Map.of("ingredients",List.of("TEST-ONLY ingredient"),"nutrients",List.of(Map.of("name","protein","value_milli",26000,"unit","PERCENT","basis","AS_FED","qualifier","MIN")),"allergens_known",false,"allergen_ids",List.of(),"life_stage_ids",List.of(),"source_refs",List.of("TEST-ONLY label fixture, not real product"),"source_updated_on","2026-10-01"));}
 Response draft(){var r=write("/admin/skus/"+sku+"/standard-versions",standard(),"0");assertEquals(201,r.status(),r.body().toString());return r;}
 Response correction(){var r=req("POST","/merchant/catalog-requests",Map.of("sku_id",sku,"base_sku_version",0,"reason","TEST-ONLY correction","standard",standard()),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r;}
 Response preview(List<String> codes){String s="sku_code,standard_json\r\n";String value=json.writeValueAsString(standard()).replace("\"","\"\"");for(String c:codes)s+=c+",\""+value+"\"\r\n";return req("POST","/admin/catalog-imports",Map.of("format","CSV","content_base64",Base64.getEncoder().encodeToString(s.getBytes(StandardCharsets.UTF_8))),admin,Map.of("Idempotency-Key",key()));}
 @AfterAll static void close()throws Exception{Files.writeString(Path.of("target/m32-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
 @Test void realmAndRbacBlockDirectMerchantStandardMutation(){assertEquals(403,req("POST","/admin/brands",Map.of("name",key()),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(403,req("POST","/admin/brands",Map.of("name",key()),reader,Map.of("Idempotency-Key",key())).status());assertEquals(401,read("/admin/skus",null).status());assertEquals(403,read("/merchant/catalog/search",admin).status());}
 @Test void merchantOnlySeesPublishedVersions(){draft();assertEquals(0,read("/merchant/catalog/skus/"+sku,merchant).data().get("standard_versions").size());assertEquals(1,read("/admin/skus/"+sku,admin).data().get("standard_versions").size());}
 @Test void publicationRetainsImmutableSourcesAndWritesOutbox(){String id=draft().id();assertEquals(200,write("/admin/sku-standard-versions/"+id+"/publish",null,"1").status());assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE sku_standard_versions SET ingredients='[]' WHERE id=?",UUID.fromString(id)));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM sku_standard_versions WHERE id=?",UUID.fromString(id)));assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE event_type='CatalogStandardPublished' AND aggregate_id=?",Integer.class,sku));assertEquals(1,read("/merchant/catalog/skus/"+sku,merchant).data().get("standard_versions").size());}
 @Test void replacementRetiresOldVersionWithoutChangingIngredients(){String old=draft().id();write("/admin/sku-standard-versions/"+old+"/publish",null,"1");var b=standard();b.put("ingredients",List.of("TEST-ONLY replacement"));String next=write("/admin/skus/"+sku+"/standard-versions",b,"2").id();assertEquals(200,write("/admin/sku-standard-versions/"+next+"/publish",null,"3").status());assertEquals("RETIRED",db.queryForObject("SELECT status FROM sku_standard_versions WHERE id=?",String.class,UUID.fromString(old)));assertTrue(db.queryForObject("SELECT ingredients::text FROM sku_standard_versions WHERE id=?",String.class,UUID.fromString(old)).contains("TEST-ONLY ingredient"));}
 @Test void sourceAndNutrientValidationRejectsFabricatedOrMalformedFacts(){for(String f:List.of("source_refs","ingredients")){var b=standard();b.put(f,List.of());assertEquals(400,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());}var b=standard();b.put("source_updated_on","2099-01-01");assertEquals(400,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());b=standard();b.put("nutrients",List.of(Map.of("name","p","value_milli",2.5,"unit","PERCENT","basis","AS_FED","qualifier","MIN")));assertEquals(400,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());}
 @Test void correctionIsScopedAndCannotChangeStandardUntilApproval(){String id=correction().id();assertEquals(404,read("/merchant/catalog-requests/"+id,foreign).status());assertEquals(200,read("/merchant/catalog-requests/"+id,merchant).status());assertEquals(0,db.queryForObject("SELECT count(*) FROM sku_standard_versions WHERE sku_id=?",Integer.class,UUID.fromString(sku)));assertEquals(200,write("/admin/catalog-reviews/"+id+"/approve",Map.of("reason","TEST-ONLY accepted"),"0").status());assertEquals("APPROVED",read("/merchant/catalog-requests/"+id,merchant).data().get("status").asString());}
 @Test void rejectionDoesNotPublishAndCannotBeReapproved(){String id=correction().id();assertEquals(200,write("/admin/catalog-reviews/"+id+"/reject",Map.of("reason","TEST-ONLY insufficient evidence"),"0").status());assertEquals(409,write("/admin/catalog-reviews/"+id+"/approve",Map.of("reason","retry"),"1").status());assertEquals(0,db.queryForObject("SELECT count(*) FROM sku_standard_versions WHERE sku_id=?",Integer.class,UUID.fromString(sku)));}
 @Test void staleCorrectionCannotOverwriteNewerStandard(){String id=correction().id();draft();assertEquals(409,write("/admin/catalog-reviews/"+id+"/approve",Map.of("reason","TEST-ONLY"),"0").status());assertEquals("PENDING",read("/admin/catalog-reviews/"+id,admin).data().get("status").asString());}
 @Test void simultaneousReviewHasOneWinner()throws Exception{String id=correction().id();try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->write("/admin/catalog-reviews/"+id+"/approve",Map.of("reason","TEST-ONLY"),"0"));var b=pool.submit(()->write("/admin/catalog-reviews/"+id+"/reject",Map.of("reason","TEST-ONLY"),"0"));var status=List.of(a.get().status(),b.get().status());assertTrue(status.contains(200)&&status.contains(409));}assertEquals(1,db.queryForObject("SELECT count(*) FROM catalog_review_records WHERE request_id=?",Integer.class,UUID.fromString(id)));}
 @Test void idempotentPublishDoesNotRepublishOrAddEvents(){String id=draft().id(),k=key(),p=proof();var h=Map.of("Idempotency-Key",k,"X-Reverify-Token",p,"If-Match","\"1\"");assertEquals(200,req("POST","/admin/sku-standard-versions/"+id+"/publish",null,admin,h).status());assertEquals(200,req("POST","/admin/sku-standard-versions/"+id+"/publish",null,admin,h).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE aggregate_id=?",Integer.class,sku));}
 @Test void previewDoesNotModifyFactsAndConfirmPublishesAtomically(){var r=preview(List.of(code));assertEquals(201,r.status(),r.body().toString());assertEquals(0,db.queryForObject("SELECT count(*) FROM sku_standard_versions WHERE sku_id=?",Integer.class,UUID.fromString(sku)));assertEquals(200,write("/admin/catalog-imports/"+r.id()+"/confirm",null,"0").status());assertEquals("CONFIRMED",read("/admin/catalog-imports/"+r.id(),admin).data().get("status").asString());}
 @Test void duplicateAndUnknownRowsBlockConfirm(){var r=preview(List.of(code,code,"unknown"));assertEquals(201,r.status());assertEquals(422,write("/admin/catalog-imports/"+r.id()+"/confirm",null,"0").status());assertEquals(0,db.queryForObject("SELECT count(*) FROM sku_standard_versions WHERE sku_id=?",Integer.class,UUID.fromString(sku)));assertEquals(200,write("/admin/catalog-imports/"+r.id()+"/cancel",null,"0").status());assertEquals(409,write("/admin/catalog-imports/"+r.id()+"/confirm",null,"1").status());}
 @Test void stalePreviewCannotSilentlyOverwriteFacts(){String id=preview(List.of(code)).id();draft();assertEquals(409,write("/admin/catalog-imports/"+id+"/confirm",null,"0").status());assertEquals("PREVIEW",read("/admin/catalog-imports/"+id,admin).data().get("status").asString());}
 @Test void proofWrongActionAndReuseAreRejected(){String p=proof();db.update("UPDATE reverify_grant SET action='pet.taxonomy.write' WHERE token_hash=?",crypto.hash(p));assertEquals(403,req("POST","/admin/skus/"+sku+"/standard-versions",standard(),admin,Map.of("Idempotency-Key",key(),"If-Match","\"0\"","X-Reverify-Token",p)).status());assertEquals(400,write("/admin/skus/"+sku+"/standard-versions",standard(),null).status());}
 @Test void auditFailureRollsBackPublicationAndOutbox(){String id=draft().id();db.execute("CREATE FUNCTION fail_catalog_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action LIKE 'catalog.publish:%' THEN RAISE EXCEPTION 'TEST_ONLY'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_catalog_audit BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION fail_catalog_audit()");try{assertEquals(503,write("/admin/sku-standard-versions/"+id+"/publish",null,"1").status());assertEquals("DRAFT",db.queryForObject("SELECT status FROM sku_standard_versions WHERE id=?",String.class,UUID.fromString(id)));assertEquals(0,db.queryForObject("SELECT count(*) FROM outbox_event WHERE aggregate_id=?",Integer.class,sku));}finally{db.execute("DROP TRIGGER test_catalog_audit ON audit_event");db.execute("DROP FUNCTION fail_catalog_audit()");}}
 @Test void listsHaveBoundedPaginationAndInvalidQueryRejected(){var r=read("/admin/skus?limit=1",admin);assertEquals(1,r.data().size());assertEquals(400,read("/admin/skus?limit=0",admin).status());assertEquals(400,read("/admin/skus?limit=no",admin).status());assertEquals(200,read("/merchant/catalog/search",merchant).status());assertEquals(200,read("/merchant/catalog-requests",merchant).status());}
 @Test void xlsxInlineTemplateAcceptedAndFormulaRejected()throws Exception{String escaped=json.writeValueAsString(standard()).replace("&","&amp;").replace("<","&lt;");String xml="<worksheet><sheetData><row><c r='A1' t='inlineStr'><is><t>sku_code</t></is></c><c r='B1' t='inlineStr'><is><t>standard_json</t></is></c></row><row><c r='A2' t='inlineStr'><is><t>"+code+"</t></is></c><c r='B2' t='inlineStr'><is><t>"+escaped+"</t></is></c></row></sheetData></worksheet>";String content=zip(xml);assertEquals(201,req("POST","/admin/catalog-imports",Map.of("format","XLSX","content_base64",content),admin,Map.of("Idempotency-Key",key())).status());assertThrows(cn.pawday.common.Api.Failure.class,()->CatalogImportParser.parse("XLSX",zip(xml.replace("<is><t>"+code,"<f>1+1</f><is><t>"+code))));}
 String zip(String xml){try{var bytes=new ByteArrayOutputStream();try(var z=new ZipOutputStream(bytes)){z.putNextEntry(new ZipEntry("xl/worksheets/sheet1.xml"));z.write(xml.getBytes(StandardCharsets.UTF_8));z.closeEntry();}return Base64.getEncoder().encodeToString(bytes.toByteArray());}catch(Exception e){throw new AssertionError(e);}}
 @Test void oversizedAndMalformedFilesRejected(){assertThrows(cn.pawday.common.Api.Failure.class,()->CatalogImportParser.parse("CSV",Base64.getEncoder().encodeToString(new byte[2000001])));assertThrows(cn.pawday.common.Api.Failure.class,()->CatalogImportParser.parse("CSV","broken"));assertThrows(cn.pawday.common.Api.Failure.class,()->CatalogImportParser.parse("XLSX",zip("<!DOCTYPE root [<!ENTITY x SYSTEM 'file:///etc/passwd'>]><worksheet>&x;</worksheet>")));}
 @Test void staleSecondRowRollsBackFirstRowAndCanBeCancelled(){
  var current=db.queryForMap("SELECT spu_id FROM skus WHERE id=?",UUID.fromString(sku));String secondCode=code+"z";
  String second=write("/admin/skus",new LinkedHashMap<>(Map.of("spu_id",current.get("spu_id").toString(),"sku_code",secondCode,"barcode",key(),"weight_g",1000,"package_unit","BAG")),null).id();
  String batch=preview(List.of(code,secondCode)).id();db.update("UPDATE skus SET version=version+1 WHERE id=?",UUID.fromString(second));
  assertEquals(409,write("/admin/catalog-imports/"+batch+"/confirm",null,"0").status());
  assertEquals(0,db.queryForObject("SELECT count(*) FROM sku_standard_versions WHERE sku_id IN (?,?)",Integer.class,UUID.fromString(sku),UUID.fromString(second)));
  assertEquals(0L,db.queryForObject("SELECT version FROM skus WHERE id=?",Long.class,UUID.fromString(sku)));
  assertEquals(0,db.queryForObject("SELECT count(*) FROM outbox_event WHERE aggregate_id=?",Integer.class,sku));
  assertEquals(200,write("/admin/catalog-imports/"+batch+"/cancel",null,"0").status());
 }
 @Test void eventFailureRollsBackPublicationAndRestoresProofForRetry(){
  String id=draft().id(),p=proof(),k=key();var h=Map.of("Idempotency-Key",k,"If-Match","\"1\"","X-Reverify-Token",p);
  db.execute("CREATE FUNCTION fail_catalog_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='CatalogStandardPublished' THEN RAISE EXCEPTION 'TEST_ONLY'; END IF; RETURN NEW; END $$");
  db.execute("CREATE TRIGGER test_catalog_outbox BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION fail_catalog_outbox()");
  try{assertEquals(503,req("POST","/admin/sku-standard-versions/"+id+"/publish",null,admin,h).status());assertEquals("DRAFT",db.queryForObject("SELECT status FROM sku_standard_versions WHERE id=?",String.class,UUID.fromString(id)));assertEquals(0,db.queryForObject("SELECT count(*) FROM identity_command WHERE idempotency_key=?",Integer.class,k));}
  finally{db.execute("DROP TRIGGER test_catalog_outbox ON outbox_event");db.execute("DROP FUNCTION fail_catalog_outbox()");}
  assertEquals(200,req("POST","/admin/sku-standard-versions/"+id+"/publish",null,admin,h).status());
 }
 @Test void publishedAllergenCannotBeChangedOrMoved(){
  UUID allergen=UUID.randomUUID();db.update("INSERT INTO allergens(id,name) VALUES (?,?)",allergen,key());var b=standard();b.put("allergens_known",true);b.put("allergen_ids",List.of(allergen.toString()));String id=write("/admin/skus/"+sku+"/standard-versions",b,"0").id();write("/admin/sku-standard-versions/"+id+"/publish",null,"1");
  String next=write("/admin/skus/"+sku+"/standard-versions",b,"2").id();
  assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM sku_allergens WHERE standard_version_id=?",UUID.fromString(id)));
  assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE sku_allergens SET standard_version_id=? WHERE standard_version_id=?",UUID.fromString(next),UUID.fromString(id)));
 }
 @Test void everyCatalogueReadRouteIsMapped(){assertEquals(200,read("/admin/brands",admin).status());assertEquals(200,read("/admin/spus",admin).status());assertEquals(200,read("/admin/catalog-reviews",admin).status());assertEquals(200,read("/admin/skus/"+sku,admin).status());}
 @Test void unknownAllergyAndWrongSpeciesStageAreRejected(){
  var b=standard();b.put("allergen_ids",List.of(key()));assertEquals(400,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());
  b=standard();b.put("allergens_known",true);b.put("allergen_ids",List.of(key()));assertEquals(422,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());
  String stage=db.queryForObject("SELECT d.id FROM pet_life_stage_definitions d JOIN pet_life_stage_rule_versions v ON v.id=d.rule_version_id JOIN pet_species p ON p.id=v.species_id WHERE p.category='DOG' LIMIT 1",UUID.class).toString();
  b=standard();b.put("life_stage_ids",List.of(stage));assertEquals(422,write("/admin/skus/"+sku+"/standard-versions",b,"0").status());
 }
 @Test void skuWithoutBarcodeCanBeCreatedAndCodeStillUnique(){
  String spu=db.queryForObject("SELECT spu_id FROM skus WHERE id=?",UUID.class,UUID.fromString(sku)).toString();
  var b=new LinkedHashMap<String,Object>(Map.of("spu_id",spu,"sku_code",key(),"weight_g",1000,"package_unit","BAG"));b.put("barcode",null);
  assertEquals(201,write("/admin/skus",b,null).status());assertEquals(409,write("/admin/skus",b,null).status());
  b.put("sku_code",key());assertEquals(201,write("/admin/skus",b,null).status());
 }
}
