package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@org.springframework.context.annotation.Import(CheckoutIntegrationTests.TimeConfiguration.class)
class CheckoutIntegrationTests {
 static final java.util.concurrent.atomic.AtomicLong OFFSET=new java.util.concurrent.atomic.AtomicLong();
 @org.springframework.boot.test.context.TestConfiguration static class TimeConfiguration {
  @org.springframework.context.annotation.Bean @org.springframework.context.annotation.Primary Clock checkoutTestClock(){return new Clock(){public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}public Instant instant(){return Instant.now().plusSeconds(OFFSET.get());}};}
 }
 @AfterEach void resetClock(){OFFSET.set(0);}

 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader,colleague;UUID adminPrincipal,adminSession,merchantId,store,otherStore,principal;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Offer test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'OFFER-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("offer.admin.manage")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT")){principal=p;db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);}return t;
 }
 @BeforeEach void setup(){OFFSET.set(0);merchantId=UUID.randomUUID();store=UUID.randomUUID();otherStore=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope'),(?,?,'TEST hidden')",store,merchantId,otherStore,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.read","offer.admin.manage"));reader=identity("ADMIN",null,List.of("offer.admin.read"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","offer.default-scope"));colleague=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust"));UUID m=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST foreign','ACTIVE')",m);UUID saved=store;store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST foreign store')",store,m);foreign=identity("MERCHANT",m,List.of("offer.read","offer.write","inventory.adjust"));store=saved;
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> createBody(UUID scope){var b=new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",1000,"member_price_fen",900,"fulfillment_sla","TEST-ONLY 48h"));b.put("store_id",scope==null?null:scope.toString());return b;}
 String create(){var r=req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r.id();}
 Response patch(String offer,Map<String,Object>b,int version){return req("PATCH","/merchant/offers/"+offer,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+version+"\""));}
 Response adjust(String offer,int delta,int version,String k,String who){return req("POST","/merchant/offers/"+offer+"/inventory-adjustments",Map.of("delta_qty",delta,"reason_code","COUNT_CORRECTION","expected_version",version),who,Map.of("Idempotency-Key",k));}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'offer.admin.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response state(String offer,String action,int version,String who,String p,String k){var h=new HashMap<String,String>(Map.of("Idempotency-Key",k,"If-Match","\""+version+"\""));if(p!=null)h.put("X-Reverify-Token",p);return req("POST","/"+(who.equals(admin)||who.equals(reader)?"admin":"merchant")+"/offers/"+offer+"/"+action,Map.of("reason","TEST-ONLY lifecycle"),who,h);}
 long balance(String offer){return db.queryForObject("SELECT on_hand_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(offer));}
 @AfterAll static void close()throws Exception{Files.writeString(Path.of("target/m41-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}

 String consumer(){return identity("CONSUMER",null,List.of());}
 UUID user(String token){return db.queryForObject("SELECT p.user_id FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",UUID.class,crypto.hash(token));}
 UUID pet(String token,String category){UUID id=UUID.randomUUID();UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category=? AND parent_id IS NULL",UUID.class,category);db.update("INSERT INTO pets(id,owner_user_id,name,species_id,sex,neutered_status,birth_date) VALUES (?,?,'TEST pet',?,'UNKNOWN','UNKNOWN','2025-01-01')",id,user(token),species);return id;}
 Response fit(String token,UUID pet){return read("/consumer/skus/"+sku+"/fit?pet_id="+pet,token);}
 UUID allergen(){UUID a=UUID.randomUUID();db.update("INSERT INTO allergens(id,name) VALUES (?,?)",a,key());return a;}
 void assessed(UUID pet,UUID a,String status){db.update("INSERT INTO pet_allergens VALUES (?,?,?,'OWNER_OBSERVATION',NULL)",pet,a,status);}
 UUID publish(boolean known,UUID allergy,UUID stage){UUID v=UUID.randomUUID();db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=? AND status='PUBLISHED'",UUID.fromString(sku));db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by) VALUES (?,?,2,'[\"TEST-only ingredient\"]','[{\"name\":\"TEST protein\",\"value_milli\":10000,\"unit\":\"PERCENT\",\"basis\":\"AS_FED\",\"qualifier\":\"MIN\"}]',?,?::jsonb,'[\"TEST-only source\"]','2026-10-01',?)",v,UUID.fromString(sku),known,stage==null?"[]":json.writeValueAsString(List.of(stage)),adminPrincipal);if(allergy!=null)db.update("INSERT INTO sku_allergens VALUES (?,?)",v,allergy);db.update("UPDATE sku_standard_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return v;}
 UUID adultRule(){UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category='CAT' AND parent_id IS NULL",UUID.class);db.update("UPDATE pet_life_stage_rule_versions SET status='RETIRED' WHERE species_id=? AND status='PUBLISHED'",species);UUID v=UUID.randomUUID(),d=UUID.randomUUID();db.update("INSERT INTO pet_life_stage_rule_versions VALUES (?,?,(SELECT coalesce(max(version_no),0)+1 FROM pet_life_stage_rule_versions WHERE species_id='10000000-0000-4000-8000-000000000001'),'DRAFT','[\"TEST rule source\"]',NULL)",v,species);db.update("INSERT INTO pet_life_stage_definitions VALUES (?,?,'ADULT','TEST adult',0,NULL,'MONTH',false)",d,v);db.update("UPDATE pet_life_stage_rule_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return d;}

 String ready(){String o=create();assertEquals(201,adjust(o,20,0,key(),merchant).status());assertEquals(200,state(o,"activate",0,merchant,null,key()).status());return o;}
 Map<String,Object> addressBody(){return Map.of("recipient","TEST recipient","phone","13800000000","province_code","310000","city_code","310100","district_code","310101","detail","TEST-only address");}
 String addressFor(String u){var r=req("POST","/consumer/addresses",addressBody(),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 String addFor(String u,String o){var r=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 void shipping(){db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,NULL,?)",UUID.randomUUID(),merchantId,adminPrincipal);}
 Response quoteFor(String u,String i,String a,List<String>coupons,boolean member,String key){return req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i),"address_id",a,"coupon_ids",coupons,"use_membership",member),u,Map.of("Idempotency-Key",key));}
 String coupon(String u,String scope,long amount,long threshold){UUID c=UUID.randomUUID(),def=UUID.randomUUID();db.update("INSERT INTO coupon_definitions(id,version,status,parameters) VALUES (?,1,'PUBLISHED','{}')",def);db.update("INSERT INTO user_coupons(id,user_id,definition_id,definition_version,scope,merchant_id,amount_fen,threshold_fen,status,expires_at,version,rule_version) VALUES (?,?,?,1,?, ?,?,?, 'AVAILABLE',?,0,'TEST-ONLY-1')",c,user(u),def,scope,scope.equals("MERCHANT")?merchantId:null,amount,threshold,Timestamp.from(clock.instant().plusSeconds(600)));return c.toString();}
 @Test void cartIdentityOwnershipVersionAndIdempotency(){String u=consumer(),v=consumer(),o=ready(),k=key();var b=Map.of("offer_id",o,"quantity",2);var first=req("POST","/consumer/cart/items",b,u,Map.of("Idempotency-Key",k));assertEquals(200,first.status());assertEquals(first.data(),req("POST","/consumer/cart/items",b,u,Map.of("Idempotency-Key",k)).data());assertEquals(409,req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",3),u,Map.of("Idempotency-Key",k)).status());assertEquals(401,read("/consumer/cart",null).status());assertEquals(403,read("/consumer/cart",merchant).status());assertEquals(403,read("/consumer/cart",admin).status());assertEquals(404,req("PATCH","/consumer/cart/items/"+first.id(),Map.of("quantity",1),v,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());assertEquals(428,req("PATCH","/consumer/cart/items/"+first.id(),Map.of("quantity",1),u,Map.of("Idempotency-Key",key())).status());assertEquals(200,req("PATCH","/consumer/cart/items/"+first.id(),Map.of("quantity",1),u,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());assertEquals(409,req("PATCH","/consumer/cart/items/"+first.id(),Map.of("quantity",1),u,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());assertEquals(200,req("DELETE","/consumer/cart/items/"+first.id(),null,u,Map.of("Idempotency-Key",key(),"If-Match","\"1\"")).status());}
 @Test void invalidOffersPetsAndAtomicGuestMerge(){String u=consumer(),other=consumer(),o=ready();assertEquals(404,req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",1,"pet_id",pet(other,"CAT").toString()),u,Map.of("Idempotency-Key",key())).status());assertEquals(409,req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",21),u,Map.of("Idempotency-Key",key())).status());var merge=Map.of("items",List.of(Map.of("offer_id",o,"quantity",2),Map.of("offer_id",UUID.randomUUID().toString(),"quantity",1)));assertEquals(404,req("POST","/consumer/cart/merge-guest-intent",merge,u,Map.of("Idempotency-Key",key())).status());assertEquals(0,read("/consumer/cart",u).data().get("items").size());var ok=Map.of("items",List.of(Map.of("offer_id",o,"quantity",2)));String k=key();assertEquals(200,req("POST","/consumer/cart/merge-guest-intent",ok,u,Map.of("Idempotency-Key",k)).status());assertEquals(200,req("POST","/consumer/cart/merge-guest-intent",ok,u,Map.of("Idempotency-Key",k)).status());assertEquals(2,read("/consumer/cart",u).data().get("items").get(0).get("quantity").asInt());}
 @Test void persistentQuoteDoesNotReserveAndCannotBeRewritten(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();String k=key();var q=quoteFor(u,i,a,List.of(),false,k);assertEquals(200,q.status(),q.body().toString());assertEquals(2500,q.data().get("payable_amount_fen").asInt());assertEquals(0,db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(o)));assertEquals(1,db.queryForObject("SELECT count(*) FROM pricing_quote_items WHERE quote_id=?",Integer.class,UUID.fromString(q.data().get("quote_id").asString())));assertEquals(q.data(),quoteFor(u,i,a,List.of(),false,k).data());String id=q.data().get("quote_id").asString();assertEquals(200,read("/consumer/checkout/quotes/"+id,u).status());assertEquals(404,read("/consumer/checkout/quotes/"+id,consumer()).status());assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE pricing_quotes SET payable_amount_fen=payable_amount_fen+1 WHERE id=?",UUID.fromString(id)));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE pricing_quote_items SET quantity=quantity+1 WHERE quote_id=?",UUID.fromString(id)));}
 @Test void addressScopeValidationAndInvalidation(){String u=consumer(),v=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();assertEquals(404,quoteFor(v,i,a,List.of(),false,key()).status());var q=quoteFor(u,i,a,List.of(),false,key());assertEquals(200,q.status(),q.body().toString());assertEquals(200,req("PATCH","/consumer/addresses/"+a,addressBody(),u,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());assertEquals(200,read("/consumer/addresses",u).status());assertEquals(404,req("DELETE","/consumer/addresses/"+a,null,v,Map.of("Idempotency-Key",key(),"If-Match","\"1\"")).status());assertEquals(200,req("DELETE","/consumer/addresses/"+a,null,u,Map.of("Idempotency-Key",key(),"If-Match","\"1\"")).status());}
 @Test void shippingMustBeConfiguredAndCoverAddress(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);var q=quoteFor(u,i,a,List.of(),false,key());assertEquals(422,q.status());assertEquals("SHIPPING_RULE_REQUIRED",q.body().get("error").get("code").asString());shipping();var b=new HashMap<>(addressBody());b.put("province_code","110000");assertEquals(200,req("PATCH","/consumer/addresses/"+a,b,u,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());assertEquals("ADDRESS_OUTSIDE_DELIVERY_AREA",quoteFor(u,i,a,List.of(),false,key()).body().get("error").get("code").asString());}
 @Test void shippingPublishingRequiresRbacProofAndAudit(){String path="/admin/merchants/"+merchantId+"/shipping-rules";var b=Map.of("province_codes",List.of("310000"),"base_fen",300,"per_kg_fen",100);assertEquals(403,req("POST",path,b,reader,Map.of("Idempotency-Key",key())).status());admin=identity("ADMIN",null,List.of("offer.admin.manage","pricing.shipping.manage"));assertEquals(403,req("POST",path,b,admin,Map.of("Idempotency-Key",key())).status());String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'pricing.shipping.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));String k=key();assertEquals(200,req("POST",path,b,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",p)).status());assertEquals(200,req("POST",path,b,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",p)).status());assertEquals(200,read(path,admin).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='pricing.shipping.publish' AND object_id=?",Integer.class,merchantId.toString()));}
 @Test void couponSlotsEligibilityAllocationsAndMinimumPayable(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();String c1=coupon(u,"MERCHANT",300,2000),c2=coupon(u,"PLATFORM",9999,0),c3=coupon(u,"SHIPPING",9999,0);var q=quoteFor(u,i,a,List.of(c3,c2,c1),false,key());assertEquals(200,q.status(),q.body().toString());assertEquals(1,q.data().get("payable_amount_fen").asInt());assertEquals(2499,q.data().get("discount_amount_fen").asInt());assertEquals(3,read("/consumer/checkout/benefits",u).data().get("coupons").size());assertFalse(read("/consumer/checkout/benefits",u).data().get("membership_eligible").asBoolean());assertEquals("AVAILABLE",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c1)));assertEquals(422,quoteFor(u,i,a,List.of(c1,coupon(u,"MERCHANT",1,0)),false,key()).status());assertEquals(422,quoteFor(u,i,a,List.of(coupon(consumer(),"PLATFORM",1,0)),false,key()).status());assertEquals(422,quoteFor(u,i,a,List.of(coupon(u,"PLATFORM",1,9999)),false,key()).status());}
 @Test void membershipQualificationAndSnapshot(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();assertEquals(422,quoteFor(u,i,a,List.of(),true,key()).status());UUID plan=UUID.randomUUID();db.update("INSERT INTO membership_plan_versions(id,version_code,parameters) VALUES (?,?,'{}')",plan,key());db.update("INSERT INTO membership_subscriptions VALUES (?,?,?,?,'ACTIVE',0)",user(u),plan,Timestamp.from(clock.instant().minusSeconds(60)),Timestamp.from(clock.instant().plusSeconds(600)));var q=quoteFor(u,i,a,List.of(),true,key());assertEquals(200,q.status(),q.body().toString());assertEquals(2300,q.data().get("payable_amount_fen").asInt());assertEquals("ACTIVE",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());db.update("UPDATE membership_subscriptions SET version=version+1 WHERE user_id=?",user(u));assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());}
 @Test void offerChangeInvalidatesWithoutRepricing(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();var q=quoteFor(u,i,a,List.of(),false,key());assertEquals(200,q.status(),q.body().toString());assertEquals(200,patch(o,Map.of("sale_price_fen",1100),1).status());var read=read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u);assertEquals("INVALIDATED",read.data().get("status").asString());assertEquals(2500,read.data().get("payable_amount_fen").asInt());assertEquals(2700,quoteFor(u,i,a,List.of(),false,key()).data().get("payable_amount_fen").asInt());}
 @Test void quoteSnapshotHasNoInventoryOrCouponReservations(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();String c=coupon(u,"PLATFORM",200,0);long before=balance(o);var q=quoteFor(u,i,a,List.of(c),false,key());assertEquals(200,q.status(),q.body().toString());assertEquals(before,balance(o));assertEquals(1,db.queryForObject("SELECT count(*) FROM pricing_quote_discount_allocations WHERE quote_id=?",Integer.class,UUID.fromString(q.data().get("quote_id").asString())));db.update("UPDATE user_coupons SET status='VOID',version=version+1 WHERE id=?",UUID.fromString(c));assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());}

 @Test void expirationWorkerPersistsExpiredAndKeepsSnapshot(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();var q=quoteFor(u,i,a,List.of(),false,key());assertEquals(200,q.status());String id=q.data().get("quote_id").asString();db.update("UPDATE auth_session SET expires_at=refresh_expires_at WHERE access_token_hash=?",crypto.hash(u));OFFSET.set(1000);new cn.pawday.checkout.QuoteExpiryWorker(db,clock,true).expire();var current=read("/consumer/checkout/quotes/"+id,u);assertEquals(200,current.status(),current.body().toString());assertEquals("EXPIRED",current.data().get("status").asString());assertEquals(2500,current.data().get("payable_amount_fen").asInt());assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE pricing_quotes SET status='ACTIVE',version=version+1 WHERE id=?",UUID.fromString(id)));}
 @Test void concurrentCartCommandsAndSameQuoteReplayProduceOneResult()throws Exception{String u=consumer(),o=ready();String k=key();var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);var futures=new ArrayList<Future<Response>>();for(int x=0;x<2;x++)futures.add(pool.submit(()->{start.await();return req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2),u,Map.of("Idempotency-Key",k));}));start.countDown();var r1=futures.get(0).get(20,TimeUnit.SECONDS);var r2=futures.get(1).get(20,TimeUnit.SECONDS);assertEquals(200,r1.status());assertEquals(r1.data(),r2.data());assertEquals(2,read("/consumer/cart",u).data().get("items").get(0).get("quantity").asInt());String a=addressFor(u);shipping();String qkey=key();var f1=pool.submit(()->quoteFor(u,r1.id(),a,List.of(),false,qkey));var f2=pool.submit(()->quoteFor(u,r1.id(),a,List.of(),false,qkey));var q1=f1.get(20,TimeUnit.SECONDS);var q2=f2.get(20,TimeUnit.SECONDS);assertEquals(200,q1.status(),q1.body().toString());assertEquals(q1.data(),q2.data());assertEquals(1,db.queryForObject("SELECT count(*) FROM pricing_quotes WHERE user_id=?",Integer.class,user(u)));}finally{pool.shutdownNow();}}
 @Test void twoMerchantsGetOneShippingGroupEachAndStableAllocations(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();UUID m=UUID.randomUUID(),other=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,'TEST second merchant','ACTIVE')",m);db.update("INSERT INTO offers(id,merchant_id,sku_id,sale_price_fen,fulfillment_sla,sale_status) VALUES (?,?,?,1000,'TEST-only','ACTIVE')",other,m,UUID.fromString(sku));db.update("INSERT INTO inventory_balances(offer_id,on_hand_qty) VALUES (?,20)",other);db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,created_by) VALUES (?,?,1,'[\"310000\"]',400,0,?)",UUID.randomUUID(),m,adminPrincipal);String j=addFor(u,other.toString()),c=coupon(u,"PLATFORM",333,0);var body=Map.of("cart_item_ids",List.of(j,i),"address_id",a,"coupon_ids",List.of(c));var q=req("POST","/consumer/checkout/quotes",body,u,Map.of("Idempotency-Key",key()));assertEquals(200,q.status(),q.body().toString());assertEquals(2,q.data().get("merchant_groups").size());assertEquals(4567,q.data().get("payable_amount_fen").asInt());var q2=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,j),"address_id",a,"coupon_ids",List.of(c)),u,Map.of("Idempotency-Key",key()));assertEquals(200,q2.status());assertEquals(q.data().get("items"),q2.data().get("items"));assertEquals(333,q.data().get("items").get(0).get("discount_amount_fen").asInt()+q.data().get("items").get(1).get("discount_amount_fen").asInt());}
 @Test void newShippingVersionAndInsufficientStockInvalidateOldQuotes(){String u=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();var q=quoteFor(u,i,a,List.of(),false,key());assertEquals(200,q.status());db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,created_by) VALUES (?,?,2,'[\"310000\"]',600,0,?)",UUID.randomUUID(),merchantId,adminPrincipal);assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());var fresh=quoteFor(u,i,a,List.of(),false,key());assertEquals(200,fresh.status());assertEquals(2600,fresh.data().get("payable_amount_fen").asInt());assertEquals(201,adjust(o,-19,1,key(),merchant).status());assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+fresh.data().get("quote_id").asString(),u).data().get("status").asString());}
 @Test void stoppedCouponDefinitionAndDeletedPetInvalidateFrozenQuote(){String u=consumer(),o=ready(),a=addressFor(u);UUID pet=pet(u,"CAT");var added=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",1,"pet_id",pet.toString()),u,Map.of("Idempotency-Key",key()));assertEquals(200,added.status());shipping();String c=coupon(u,"PLATFORM",10,0);var q=quoteFor(u,added.id(),a,List.of(c),false,key());assertEquals(200,q.status());db.update("UPDATE coupon_definitions SET status='STOPPED' WHERE id=(SELECT definition_id FROM user_coupons WHERE id=?)",UUID.fromString(c));assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+q.data().get("quote_id").asString(),u).data().get("status").asString());var fresh=quoteFor(u,added.id(),a,List.of(),false,key());assertEquals(200,fresh.status());db.update("UPDATE pets SET status='DELETED',version=version+1 WHERE id=?",pet);assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+fresh.data().get("quote_id").asString(),u).data().get("status").asString());}
 @Test void membershipAndCouponsNeverBelongToClientClaim(){String u=consumer(),other=consumer(),o=ready(),i=addFor(u,o),a=addressFor(u);shipping();String c=coupon(other,"PLATFORM",100,0);assertEquals(422,quoteFor(u,i,a,List.of(c),false,key()).status());assertEquals(0,read("/consumer/checkout/benefits",u).data().get("coupons").size());assertEquals(400,req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,i),"address_id",a),u,Map.of("Idempotency-Key",key())).status());assertEquals(400,req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i),"address_id",a,"payable_amount_fen",1),u,Map.of("Idempotency-Key",key())).status());}
}
