package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@org.springframework.context.annotation.Import(FulfillmentIntegrationTests.TimeConfiguration.class)
class FulfillmentIntegrationTests {
 static final java.util.concurrent.atomic.AtomicLong OFFSET=new java.util.concurrent.atomic.AtomicLong();
 @org.springframework.boot.test.context.TestConfiguration static class TimeConfiguration {
  @org.springframework.context.annotation.Bean @org.springframework.context.annotation.Primary Clock checkoutTestClock(){return new Clock(){public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}public Instant instant(){return Instant.now().plusSeconds(OFFSET.get());}};}
 }
 @AfterEach void resetClock(){OFFSET.set(0);}

 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);r.add("pawday.payment.simulation-enabled",()->true);r.add("pawday.payment.recovery-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader,colleague;UUID adminPrincipal,adminSession,merchantId,store,otherStore,principal;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Offer test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'OFFER-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("offer.admin.manage")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT")){principal=p;db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);}return t;
 }
 @BeforeEach void setup(){OFFSET.set(0);merchantId=UUID.randomUUID();store=UUID.randomUUID();otherStore=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope'),(?,?,'TEST hidden')",store,merchantId,otherStore,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.read","offer.admin.manage","order.admin.read","order.policy.manage","payment.read","payment.requery"));reader=identity("ADMIN",null,List.of("offer.admin.read"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","offer.default-scope","order.read","order.ship","order.default-scope"));colleague=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust"));UUID m=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST foreign','ACTIVE')",m);UUID saved=store;store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST foreign store')",store,m);foreign=identity("MERCHANT",m,List.of("offer.read","offer.write","inventory.adjust","order.read","order.ship"));store=saved;
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> createBody(UUID scope){var b=new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",1000,"member_price_fen",900,"fulfillment_sla","TEST-ONLY 48h"));b.put("store_id",scope==null?null:scope.toString());return b;}
 String create(){var r=req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r.id();}
 Response patch(String offer,Map<String,Object>b,int version){return req("PATCH","/merchant/offers/"+offer,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+version+"\""));}
 Response adjust(String offer,int delta,int version,String k,String who){return req("POST","/merchant/offers/"+offer+"/inventory-adjustments",Map.of("delta_qty",delta,"reason_code","COUNT_CORRECTION","expected_version",version),who,Map.of("Idempotency-Key",k));}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'offer.admin.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response state(String offer,String action,int version,String who,String p,String k){var h=new HashMap<String,String>(Map.of("Idempotency-Key",k,"If-Match","\""+version+"\""));if(p!=null)h.put("X-Reverify-Token",p);return req("POST","/"+(who.equals(admin)||who.equals(reader)?"admin":"merchant")+"/offers/"+offer+"/"+action,Map.of("reason","TEST-ONLY lifecycle"),who,h);}
 long balance(String offer){return db.queryForObject("SELECT on_hand_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(offer));}

 String consumer(){return identity("CONSUMER",null,List.of());}
 UUID user(String token){return db.queryForObject("SELECT p.user_id FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",UUID.class,crypto.hash(token));}
 UUID pet(String token,String category){UUID id=UUID.randomUUID();UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category=? AND parent_id IS NULL",UUID.class,category);db.update("INSERT INTO pets(id,owner_user_id,name,species_id,sex,neutered_status,birth_date) VALUES (?,?,'TEST pet',?,'UNKNOWN','UNKNOWN','2025-01-01')",id,user(token),species);return id;}
 Response fit(String token,UUID pet){return read("/consumer/skus/"+sku+"/fit?pet_id="+pet,token);}
 UUID allergen(){UUID a=UUID.randomUUID();db.update("INSERT INTO allergens(id,name) VALUES (?,?)",a,key());return a;}
 void assessed(UUID pet,UUID a,String status){db.update("INSERT INTO pet_allergens VALUES (?,?,?,'OWNER_OBSERVATION',NULL)",pet,a,status);}
 UUID publish(boolean known,UUID allergy,UUID stage){UUID v=UUID.randomUUID();db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=? AND status='PUBLISHED'",UUID.fromString(sku));db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by) VALUES (?,?,2,'[\"TEST-only ingredient\"]','[{\"name\":\"TEST protein\",\"value_milli\":10000,\"unit\":\"PERCENT\",\"basis\":\"AS_FED\",\"qualifier\":\"MIN\"}]',?,?::jsonb,'[\"TEST-only source\"]','2026-10-01',?)",v,UUID.fromString(sku),known,stage==null?"[]":json.writeValueAsString(List.of(stage)),adminPrincipal);if(allergy!=null)db.update("INSERT INTO sku_allergens VALUES (?,?)",v,allergy);db.update("UPDATE sku_standard_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return v;}
 UUID adultRule(){UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category='CAT' AND parent_id IS NULL",UUID.class);db.update("UPDATE pet_life_stage_rule_versions SET status='RETIRED' WHERE species_id=? AND status='PUBLISHED'",species);UUID v=UUID.randomUUID(),d=UUID.randomUUID();db.update("INSERT INTO pet_life_stage_rule_versions VALUES (?,?,(SELECT coalesce(max(version_no),0)+1 FROM pet_life_stage_rule_versions WHERE species_id='10000000-0000-4000-8000-000000000001'),'DRAFT','[\"TEST rule source\"]',NULL)",v,species);db.update("INSERT INTO pet_life_stage_definitions VALUES (?,?,'ADULT','TEST adult',0,NULL,'MONTH',false)",d,v);db.update("UPDATE pet_life_stage_rule_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return d;}

 String ready(){String o=create();assertEquals(201,adjust(o,20,0,key(),merchant).status());assertEquals(200,state(o,"activate",0,merchant,null,key()).status());return o;}
 Map<String,Object> addressBody(){return Map.of("recipient","TEST recipient","phone","13800000000","province_code","310000","city_code","310100","district_code","310101","detail","TEST-only address");}
 String addressFor(String u){var r=req("POST","/consumer/addresses",addressBody(),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 String addFor(String u,String o){var r=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 void shipping(){db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,NULL,?)",UUID.randomUUID(),merchantId,adminPrincipal);}
 Response quoteFor(String u,String i,String a,List<String>coupons,boolean member,String key){return req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i),"address_id",a,"coupon_ids",coupons,"use_membership",member),u,Map.of("Idempotency-Key",key));}
 String coupon(String u,String scope,long amount,long threshold){UUID c=UUID.randomUUID(),def=UUID.randomUUID();db.update("INSERT INTO coupon_definitions(id,version,status,parameters) VALUES (?,1,'PUBLISHED','{}')",def);db.update("INSERT INTO user_coupons(id,user_id,definition_id,definition_version,scope,merchant_id,amount_fen,threshold_fen,status,expires_at,version,rule_version) VALUES (?,?,?,1,?, ?,?,?, 'AVAILABLE',?,0,'TEST-ONLY-1')",c,user(u),def,scope,scope.equals("MERCHANT")?merchantId:null,amount,threshold,Timestamp.from(clock.instant().plusSeconds(600)));return c.toString();}

 @Autowired cn.pawday.ordering.OrderService orders;
 String q(String u,String o,List<String>coupons){String i=addFor(u,o),a=addressFor(u);var q=quoteFor(u,i,a,coupons,false,key());assertEquals(200,q.status(),q.body().toString());return q.data().get("quote_id").asString();}
 Response order(String u,String q,String k){return req("POST","/consumer/orders",Map.of("quote_id",q),u,Map.of("Idempotency-Key",k));}
 Response cancel(String u,String id,long v,String k){return req("POST","/consumer/orders/"+id+"/cancel",Map.of("reason_code","CONSUMER_CANCELLED"),u,Map.of("Idempotency-Key",k,"If-Match","\""+v+"\""));}
 long reserved(String o){return db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(o));}

 @Autowired cn.pawday.payment.PaymentService payments;@Autowired cn.pawday.payment.SimulatedPaymentGateway gateway;@Autowired org.springframework.transaction.support.TransactionTemplate tx;
 Response payment(String u,String p){return read("/consumer/payments/"+p,u);}
 Response attempt(String u,String p,String channel,String k){return req("POST","/consumer/payments/"+p+"/attempts",Map.of("channel",channel,"client_platform","ANDROID"),u,Map.of("Idempotency-Key",k));}
 Response query(String u,String p){return req("POST","/consumer/payments/"+p+"/requery",null,u,Map.of());}
 Response outcome(String u,String p,String a,String state){return req("POST","/consumer/payments/"+p+"/simulation",Map.of("attempt_id",a,"outcome",state),u,Map.of());}
 Response closeAttempt(String u,String p){return req("POST","/consumer/payments/"+p+"/close-attempt",null,u,Map.of());}
 String aid(Response r){return r.data().get("attempts").get(r.data().get("attempts").size()-1).get("id").asString();}
 String pid(Response o){return o.data().get("payment").get("id").asString();}
 record Fixture(String u,String offer,Response order,String payment){}
 Fixture fixture(){String u=consumer(),o=ready();shipping();var order=order(u,q(u,o,List.of()),key());assertEquals(200,order.status(),order.body().toString());return new Fixture(u,o,order,pid(order));}
 void providerSuccess(String a,long amount,String currency){db.update("UPDATE simulated_payment_transactions SET status='SUCCEEDED',amount_fen=?,currency=?,transaction_id=coalesce(transaction_id,?) WHERE attempt_no=(SELECT attempt_no FROM payment_attempts WHERE id=?)",amount,currency,"SIM-"+a,UUID.fromString(a));}

 Fixture paid(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));assertEquals(200,outcome(f.u(),f.payment(),a,"SUCCEEDED").status());return f;}
 String sub(Fixture f){return f.order().data().get("suborders").get(0).get("id").asString();}
 String item(Fixture f){return f.order().data().get("suborders").get(0).get("items").get(0).get("id").asString();}
 Response fulfillment(Fixture f,String who,String realm){return read("/"+realm+"/suborders/"+sub(f)+"/fulfillment",who);}
 Map<String,Object> shipBody(Fixture f,int qty,String tracking){return Map.of("carrier_code","SF","tracking_no",tracking,"items",List.of(Map.of("order_item_id",item(f),"quantity",qty)));}
 Response ship(Fixture f,int qty,long v,String who,String k){return req("POST","/merchant/suborders/"+sub(f)+"/shipments",shipBody(f,qty,"TEST"+k.replace("-","")),who,Map.of("If-Match","\""+v+"\"","Idempotency-Key",k));}
 String shipment(Response r){assertEquals(200,r.status(),r.body().toString());return r.data().get("shipments").get(r.data().get("shipments").size()-1).get("id").asString();}
 Response receive(Fixture f,String shipment,long v,String who,String k){return req("POST","/consumer/suborders/"+sub(f)+"/confirm-receipt",Map.of("shipment_ids",List.of(shipment)),who,Map.of("If-Match","\""+v+"\"","Idempotency-Key",k));}
 @Test void twoParcelsAndExplicitReceiptsConserveQuantity(){var f=paid();String first=shipment(ship(f,1,1,merchant,key()));assertEquals("PARTIALLY_SHIPPED",fulfillment(f,f.u(),"consumer").data().get("fulfillment_status").asString());assertEquals("PARTIALLY_SHIPPED",read("/consumer/orders/"+f.order().id(),f.u()).data().get("status").asString());assertEquals("PARTIALLY_COMPLETED",receive(f,first,2,f.u(),key()).data().get("fulfillment_status").asString());String second=shipment(ship(f,1,3,merchant,key()));var completed=receive(f,second,4,f.u(),key());assertEquals(200,completed.status(),completed.body().toString());assertEquals("COMPLETED",completed.data().get("fulfillment_status").asString());assertEquals("COMPLETED",read("/consumer/orders/"+f.order().id(),f.u()).data().get("status").asString());assertEquals(18,balance(f.offer()));assertEquals(1,db.queryForObject("SELECT count(*) FROM inventory_sale_events WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}
 @Test void allShippedWaitsForConsumerNotCarrier(){var f=paid();String h=shipment(ship(f,2,1,merchant,key()));assertEquals("AWAITING_RECEIPT",read("/consumer/orders/"+f.order().id(),f.u()).data().get("status").asString());var t=read("/consumer/shipments/"+h+"/tracking",f.u());assertEquals(200,t.status());assertEquals("UNKNOWN",t.data().get("status").asString());assertTrue(t.data().get("stale").asBoolean());assertEquals(0,t.data().get("events").size());assertEquals("SHIPPED_WAITING_RECEIPT",fulfillment(f,f.u(),"consumer").data().get("fulfillment_status").asString());}
 @Test void shipmentSameKeyReturnsSameEvidence(){var f=paid();String k=key(),h=shipment(ship(f,1,1,merchant,k));assertEquals(h,shipment(ship(f,1,1,merchant,k)));assertEquals(409,ship(f,2,1,merchant,k).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM shipments WHERE suborder_id=?",Integer.class,UUID.fromString(sub(f))));}
 @Test void receiptSameKeyCannotRepeatBusinessFact(){var f=paid();String h=shipment(ship(f,2,1,merchant,key())),k=key();assertEquals(200,receive(f,h,2,f.u(),k).status());assertEquals(200,receive(f,h,2,f.u(),k).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE event_type='SuborderReceiptConfirmed' AND aggregate_id=?",Integer.class,sub(f)));assertEquals(409,receive(f,h,3,f.u(),key()).status());}
 @Test void staleVersionRejectsWithoutSideEffects(){var f=paid();assertEquals(409,ship(f,1,0,merchant,key()).status());assertEquals(0,db.queryForObject("SELECT count(*) FROM shipments WHERE suborder_id=?",Integer.class,UUID.fromString(sub(f))));}
 @Test void overShipmentRejected(){var f=paid();assertEquals(409,ship(f,3,1,merchant,key()).status());shipment(ship(f,1,1,merchant,key()));assertEquals(409,ship(f,2,2,merchant,key()).status());}
 @Test void unpaidAndCancelledCannotShip(){var f=fixture();assertEquals(409,ship(f,1,0,merchant,key()).status());assertEquals(200,cancel(f.u(),f.order().id(),0,key()).status());assertEquals(409,ship(f,1,1,merchant,key()).status());}
 @Test void noPermissionAndWrongMerchantDenied(){var f=paid();assertEquals(403,ship(f,1,1,colleague,key()).status());String other=foreign;assertEquals(404,ship(f,1,1,other,key()).status());assertEquals(404,fulfillment(f,foreign,"merchant").status());}
 @Test void sameMerchantMissingStoreCannotShipOrRead(){var f=paid();String who=identity("MERCHANT",merchantId,List.of("order.read","order.ship"));UUID p=db.queryForObject("SELECT principal_id FROM auth_session WHERE access_token_hash=?",UUID.class,crypto.hash(who));db.update("DELETE FROM principal_store_scope WHERE principal_id=?",p);assertEquals(404,ship(f,1,1,who,key()).status());assertEquals(404,fulfillment(f,who,"merchant").status());}
 @Test void crossConsumerAndRealmNeverLeak(){var f=paid();String h=shipment(ship(f,2,1,merchant,key())),other=consumer();assertEquals(404,fulfillment(f,other,"consumer").status());assertEquals(404,receive(f,h,2,other,key()).status());assertEquals(404,read("/consumer/shipments/"+h+"/tracking",other).status());assertEquals(403,read("/admin/suborders/"+sub(f)+"/fulfillment",f.u()).status());}
 @Test void recipientOnlyForPaidScopedDispatcher(){var f=fixture();assertTrue(fulfillment(f,merchant,"merchant").data().get("delivery_address").isNull());String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));outcome(f.u(),f.payment(),a,"SUCCEEDED");assertEquals("TEST recipient",fulfillment(f,merchant,"merchant").data().get("delivery_address").get("recipient").asString());String who=identity("MERCHANT",merchantId,List.of("order.read"));assertTrue(fulfillment(f,who,"merchant").data().get("delivery_address").isNull());assertTrue(fulfillment(f,admin,"admin").data().get("delivery_address").isNull());}
 @Test void concurrentWorkersCannotOvershipOrDeadlock()throws Exception{var f=paid();var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);Callable<Response> work=()->{start.await();return ship(f,2,1,merchant,key());};var x=pool.submit(work);var y=pool.submit(work);start.countDown();var statuses=List.of(x.get(20,TimeUnit.SECONDS).status(),y.get(20,TimeUnit.SECONDS).status());assertTrue(statuses.contains(200),statuses.toString());assertTrue(statuses.contains(409),statuses.toString());assertEquals(2L,db.queryForObject("SELECT sum(quantity) FROM shipment_items WHERE suborder_id=?",Long.class,UUID.fromString(sub(f))));}finally{pool.shutdownNow();}}
 @Test void auditFailureRollsBackShipmentAndOutbox(){var f=paid();db.execute("CREATE FUNCTION fail_m44_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='order.ship' THEN RAISE EXCEPTION 'TEST fault';END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER fail_m44_audit BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION fail_m44_audit()");try{assertEquals(503,ship(f,1,1,merchant,key()).status());assertEquals(0,db.queryForObject("SELECT count(*) FROM shipments WHERE suborder_id=?",Integer.class,UUID.fromString(sub(f))));assertEquals(0,db.queryForObject("SELECT count(*) FROM outbox_event WHERE event_type='ShipmentCreated' AND aggregate_id=?",Integer.class,sub(f)));}finally{db.execute("DROP TRIGGER fail_m44_audit ON audit_event");db.execute("DROP FUNCTION fail_m44_audit()");}}
 @Test void malformedAndMissingPreconditionRejected(){var f=paid();assertEquals(428,req("POST","/merchant/suborders/"+sub(f)+"/shipments",shipBody(f,1,key()),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(400,ship(f,0,1,merchant,key()).status());assertEquals(400,req("POST","/consumer/suborders/"+sub(f)+"/confirm-receipt",Map.of("shipment_ids",List.of()),f.u(),Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());}
 @Test void immutableFactsCannotBeEditedOrDeleted(){var f=paid();String h=shipment(ship(f,2,1,merchant,key()));assertThrows(Exception.class,()->db.update("UPDATE shipments SET tracking_no='TAMPERED' WHERE id=?",UUID.fromString(h)));assertThrows(Exception.class,()->db.update("DELETE FROM shipment_items WHERE shipment_id=?",UUID.fromString(h)));assertThrows(Exception.class,()->db.update("UPDATE suborders SET fulfillment_status='COMPLETED',version=version+1 WHERE id=?",UUID.fromString(sub(f))));}

 @Test void foreignOrderItemAndParcelRejected(){var f=paid();String u=consumer();var ord=order(u,q(u,f.offer(),List.of()),key());var other=new Fixture(u,f.offer(),ord,pid(ord));String a=aid(attempt(u,other.payment(),"WECHAT",key()));outcome(u,other.payment(),a,"SUCCEEDED");ship(other,1,1,merchant,key());var invalid=req("POST","/merchant/suborders/"+sub(f)+"/shipments",shipBody(other,1,"TEST"+key().replace("-","")),merchant,Map.of("Idempotency-Key",key(),"If-Match","\"1\""));assertEquals(404,invalid.status());String h=shipment(ship(f,2,1,merchant,key()));assertEquals(404,receive(other,h,2,other.u(),key()).status());}
 @Test void wholeSuborderMixedStoreScopeMustBeGranted(){String first=ready(),u=consumer();shipping();String i=addFor(u,first);UUID scopedPrincipal=db.queryForObject("SELECT principal_id FROM auth_session WHERE access_token_hash=?",UUID.class,crypto.hash(merchant));db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",scopedPrincipal,merchantId,otherStore);UUID saved=store;store=otherStore;String second=ready();store=saved;db.update("DELETE FROM principal_store_scope WHERE principal_id=? AND store_id=?",scopedPrincipal,otherStore);String j=addFor(u,second);var quote=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,j),"address_id",addressFor(u)),u,Map.of("Idempotency-Key",key()));assertEquals(200,quote.status(),quote.body().toString());var order=order(u,quote.data().get("quote_id").asString(),key());var f=new Fixture(u,first,order,pid(order));String a=aid(attempt(u,f.payment(),"WECHAT",key()));outcome(u,f.payment(),a,"SUCCEEDED");assertEquals(404,fulfillment(f,merchant,"merchant").status());assertEquals(404,ship(f,1,1,merchant,key()).status());UUID p=db.queryForObject("SELECT principal_id FROM auth_session WHERE access_token_hash=?",UUID.class,crypto.hash(merchant));db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,merchantId,otherStore);assertEquals(200,fulfillment(f,merchant,"merchant").status());}
 @Test void parentAggregatesAcrossMerchantsAndReceiptStaysLocal(){String first=ready(),u=consumer();shipping();String i=addFor(u,first);UUID savedMerchant=merchantId,savedStore=store;String savedToken=merchant;merchantId=UUID.randomUUID();store=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST second','ACTIVE')",merchantId);db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST second')",store,merchantId);merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","order.read","order.ship"));String second=ready(),secondToken=merchant;shipping();String j=addFor(u,second);merchantId=savedMerchant;store=savedStore;merchant=savedToken;var quote=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,j),"address_id",addressFor(u)),u,Map.of("Idempotency-Key",key()));assertEquals(200,quote.status());var ord=order(u,quote.data().get("quote_id").asString(),key());String payment=pid(ord),attempt=aid(attempt(u,payment,"WECHAT",key()));outcome(u,payment,attempt,"SUCCEEDED");String sub1=db.queryForObject("SELECT id FROM suborders WHERE order_id=? AND merchant_id=?",UUID.class,UUID.fromString(ord.id()),merchantId).toString(),sub2=db.queryForObject("SELECT id FROM suborders WHERE order_id=? AND merchant_id<>?",UUID.class,UUID.fromString(ord.id()),merchantId).toString();String item1=db.queryForObject("SELECT id FROM order_items WHERE suborder_id=?",UUID.class,UUID.fromString(sub1)).toString(),item2=db.queryForObject("SELECT id FROM order_items WHERE suborder_id=?",UUID.class,UUID.fromString(sub2)).toString();var shipped=req("POST","/merchant/suborders/"+sub1+"/shipments",Map.of("carrier_code","SF","tracking_no","TEST"+key().replace("-",""),"items",List.of(Map.of("order_item_id",item1,"quantity",2))),merchant,Map.of("If-Match","\"1\"","Idempotency-Key",key()));String parcel=shipment(shipped);assertEquals("PARTIALLY_SHIPPED",read("/consumer/orders/"+ord.id(),u).data().get("status").asString());assertEquals(200,req("POST","/consumer/suborders/"+sub1+"/confirm-receipt",Map.of("shipment_ids",List.of(parcel)),u,Map.of("If-Match","\"2\"","Idempotency-Key",key())).status());assertEquals("PARTIALLY_COMPLETED",read("/consumer/orders/"+ord.id(),u).data().get("status").asString());assertEquals("PAID_WAITING_FULFILLMENT",read("/consumer/suborders/"+sub2+"/fulfillment",u).data().get("fulfillment_status").asString());assertEquals(404,read("/merchant/suborders/"+sub1+"/fulfillment",secondToken).status());assertEquals(200,req("POST","/merchant/suborders/"+sub2+"/shipments",Map.of("carrier_code","SF","tracking_no","TEST"+key().replace("-",""),"items",List.of(Map.of("order_item_id",item2,"quantity",2))),secondToken,Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());}
 @AfterAll static void finish()throws Exception{Files.writeString(Path.of("target/m44-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
}

