package cn.pawday;
import cn.pawday.identity.*;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
class NearbyIntegrationTests {
 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);r.add("pawday.payment.recovery-enabled",()->false);r.add("pawday.refund.recovery-enabled",()->false);r.add("pawday.settlement.worker-enabled",()->false);r.add("pawday.membership.worker-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new java.util.concurrent.CopyOnWriteArrayList<>();
 String admin,merchant;UUID adminSession,store,merchantId;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}}
 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID principal=UUID.randomUUID(),role=UUID.randomUUID();
  if(realm.equals("CONSUMER")){UUID user=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",user);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",principal,user);}
  else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",principal,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Nearby test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",principal,role,realm);
  UUID session=UUID.randomUUID();String token=crypto.token();Instant now=Instant.now();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'M54-IT',?,?,?)",session,principal,crypto.hash(token),Timestamp.from(now.plusSeconds(86400)),Timestamp.from(now.plusSeconds(86400)),Timestamp.from(now));if(realm.equals("ADMIN"))adminSession=session;if(realm.equals("MERCHANT"))db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",principal,m,store);return token;
 }
 @BeforeEach void setup(){merchantId=UUID.randomUUID();store=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST Nearby & Store')",store,merchantId);admin=identity("ADMIN",null,List.of("nearby.read","nearby.moderate"));merchant=identity("MERCHANT",merchantId,List.of("store.read","store.nearby.write"));}
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var result=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(result.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",result.statusCode(),"response",body));return new Response(result.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> input(){return new LinkedHashMap<>(Map.of("city","TEST-CITY-"+store,"category","PET_STORE","address","TEST street","phone","13800000000","business_hours","09:00–18:00","longitude",121.5,"latitude",31.2,"coordinate_system","WGS84","services",List.of("SUPPLIES","PET_FRIENDLY")));}
 Response save(Map<String,Object>b,long version,String key){return req("PUT","/merchant/stores/"+store+"/nearby-profile",b,merchant,Map.of("If-Match","\""+version+"\"","Idempotency-Key",key));}
 String proof(){String p=crypto.token();Instant now=Instant.now();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,?,?,?)",crypto.hash(p),adminSession,"nearby.moderate",Timestamp.from(now.plusSeconds(300)),Timestamp.from(now));return p;}
 Map<String,Object> decision(String status){return Map.of("publication_status",status,"claim_status","VERIFIED","pawday_certified",true,"reason","TEST reviewed ownership and source evidence");}
 Response moderate(String status,long version){return req("POST","/admin/nearby/stores/"+store+"/moderation",decision(status),admin,Map.of("If-Match","\""+version+"\"","Idempotency-Key",key(),"X-Reverify-Token",proof()));}
 void published(){assertEquals(200,save(input(),0,key()).status());assertEquals(200,moderate("PUBLISHED",1).status());}
 String nearby(){return "/public/nearby/places?city=TEST-CITY-"+store;}
 Response nav(String token){return req("POST",token==null?"/public/nearby/navigation-intents":"/consumer/nearby/navigation-intents",Map.of("place_id",store.toString(),"mode","DESTINATION"),token,Map.of());}
 @Test void publishedFactsAreGuestVisibleAndFullContractCovered(){published();assertEquals(200,read("/merchant/stores/"+store+"/nearby-profile",merchant).status());assertEquals(200,read("/admin/nearby/stores",admin).status());assertEquals(200,read("/admin/nearby/stores/"+store,admin).status());var detail=read("/public/nearby/places/"+store,null);assertEquals(200,detail.status());assertFalse(detail.data().has("merchant_id"));var result=read(nearby(),null);assertEquals(1,result.data().size());assertTrue(result.data().get(0).get("distance_m").isNull());assertEquals(200,nav(null).status());assertEquals(200,nav(identity("CONSUMER",null,List.of())).status());}
 @Test void draftAndHiddenCannotLeakDetailOrNavigate(){assertEquals(200,save(input(),0,key()).status());assertEquals(0,read(nearby(),null).data().size());assertEquals(404,nav(null).status());assertEquals(404,read("/public/nearby/places/"+store,null).status());moderate("HIDDEN",1);assertEquals(0,read(nearby(),null).data().size());}
 @Test void editRevokesPublicationClaimAndCertification(){published();var update=save(input(),2,key());assertEquals(200,update.status());assertEquals("DRAFT",update.data().get("publication_status").asString());assertEquals("UNREVIEWED",update.data().get("claim_status").asString());assertFalse(update.data().get("pawday_certified").asBoolean());assertEquals(404,nav(null).status());}
 @Test void foreignStoreAndRevokedScopeCannotWrite(){String other=identity("MERCHANT",merchantId,List.of("store.read","store.nearby.write"));db.update("DELETE FROM principal_store_scope WHERE principal_id=(SELECT principal_id FROM auth_session WHERE access_token_hash=?)",crypto.hash(other));assertEquals(404,req("PUT","/merchant/stores/"+store+"/nearby-profile",input(),other,Map.of("If-Match","\"0\"","Idempotency-Key",key())).status());assertEquals(404,read("/merchant/stores/"+store+"/nearby-profile",other).status());}
 @Test void missingPermissionsAndWrongRealmAreDenied(){String reader=identity("MERCHANT",merchantId,List.of("store.read"));assertEquals(403,req("PUT","/merchant/stores/"+store+"/nearby-profile",input(),reader,Map.of()).status());assertEquals(403,read("/admin/nearby/stores",merchant).status());assertEquals(401,read("/admin/nearby/stores",null).status());}
 @Test void moderatorNeedsProofAndCannotCertifyRejectedClaim(){save(input(),0,key());assertEquals(403,req("POST","/admin/nearby/stores/"+store+"/moderation",decision("PUBLISHED"),admin,Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());var b=new LinkedHashMap<>(decision("PUBLISHED"));b.put("claim_status","REJECTED");assertEquals(400,req("POST","/admin/nearby/stores/"+store+"/moderation",b,admin,Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());}
 @Test void sameKeyIsIdempotentAndChangedPayloadConflicts(){String k=key();assertEquals(200,save(input(),0,k).status());assertEquals(200,save(input(),0,k).status());var b=input();b.put("address","changed");assertEquals(409,save(b,0,k).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE aggregate_id=? AND event_type='NearbyStoreChanged'",Integer.class,store.toString()));}
 @Test void staleVersionDoesNotOverwriteFacts(){save(input(),0,key());var b=input();b.put("city","wrong");assertEquals(409,save(b,0,key()).status());assertEquals("TEST-CITY-"+store,read("/merchant/stores/"+store+"/nearby-profile",merchant).data().get("city").asString());}
 @Test void concurrentEditsSerializeAndOneWins()throws Exception{save(input(),0,key());try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var a=pool.submit(()->save(input(),1,key()).status());var b=pool.submit(()->save(input(),1,key()).status());assertEquals(Set.of(200,409),Set.of(a.get(),b.get()));}}
 @Test void invalidCoordinatesTaxonomyAndMedicalServicesRejected(){for(var entry:List.of(Map.entry("longitude",181),Map.entry("latitude",Double.NaN),Map.entry("coordinate_system","GCJ02"),Map.entry("services",List.of("EMERGENCY")),Map.entry("category","TREATMENT_RANK"))){var b=input();b.put(entry.getKey(),entry.getValue());assertEquals(400,save(b,0,key()).status(),entry.toString());}}
 @Test void distanceRadiusAndCategoryAreEnforced(){published();var near=read("/public/nearby/places?longitude=121.5&latitude=31.2&coordinate_system=WGS84&radius_m=100",null);assertTrue(near.data().size()>=1);assertEquals(0,read(nearby()+"&category=VET",null).data().size());assertEquals(0,read(nearby()+"&longitude=120&latitude=30&coordinate_system=WGS84&radius_m=100",null).data().size());}
 @Test void invalidQueryCannotFallBackSilently(){for(String query:List.of("","?longitude=121.5","?longitude=121.5&latitude=31.2","?longitude=121.5&latitude=31.2&coordinate_system=GCJ02","?city=test&radius_m=0","?city=test&offset=-1","?city=test&category=BAD"))assertEquals(400,read("/public/nearby/places"+query,null).status());}
 @Test void suspendedMerchantIsNotPublic(){published();db.update("UPDATE merchant SET status='SUSPENDED' WHERE id=?",merchantId);assertEquals(0,read(nearby(),null).data().size());assertEquals(404,nav(null).status());assertEquals(401,save(input(),2,key()).status());}
 @Test void navigationEncodesDestinationAndRejectsArbitraryUrl(){published();var result=nav(null);URI uri=URI.create(result.data().get("launch_url").asString());assertEquals("https",uri.getScheme());assertEquals("uri.amap.com",uri.getHost());assertEquals("/marker",uri.getPath());assertTrue(uri.getQuery().contains("coordinate=wgs84"));assertTrue(java.net.URLDecoder.decode(uri.getRawQuery(),java.nio.charset.StandardCharsets.UTF_8).contains("TEST Nearby & Store"));assertFalse(uri.getQuery().contains("from="));assertEquals(400,req("POST","/public/nearby/navigation-intents",Map.of("place_id",store.toString(),"mode","DESTINATION","url","https://evil.test"),null,Map.of()).status());}
 @Test void outboxFailureRollsBackProfile(){db.execute("CREATE FUNCTION test_nearby_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='NearbyStoreChanged' THEN RAISE EXCEPTION 'TEST failure'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_nearby_failure BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION test_nearby_failure()");try{assertEquals(503,save(input(),0,key()).status());}finally{db.execute("DROP TRIGGER test_nearby_failure ON outbox_event");db.execute("DROP FUNCTION test_nearby_failure()");}assertEquals(0,db.queryForObject("SELECT count(*) FROM nearby_store_profile WHERE store_id=?",Integer.class,store));}
 @Test void auditFailureRollsBackModerationAndRestoresProof(){save(input(),0,key());String proof=proof();var h=Map.of("If-Match","\"1\"","Idempotency-Key",key(),"X-Reverify-Token",proof);db.execute("CREATE FUNCTION test_nearby_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='nearby.moderate' THEN RAISE EXCEPTION 'TEST failure'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_nearby_audit_failure BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION test_nearby_audit_failure()");try{assertEquals(503,req("POST","/admin/nearby/stores/"+store+"/moderation",decision("PUBLISHED"),admin,h).status());}finally{db.execute("DROP TRIGGER test_nearby_audit_failure ON audit_event");db.execute("DROP FUNCTION test_nearby_audit_failure()");}assertNull(db.queryForObject("SELECT used_at FROM reverify_grant WHERE token_hash=?",Timestamp.class,crypto.hash(proof)));assertEquals(0,db.queryForObject("SELECT count(*) FROM nearby_moderation_history WHERE store_id=?",Integer.class,store));assertEquals(200,req("POST","/admin/nearby/stores/"+store+"/moderation",decision("PUBLISHED"),admin,h).status());assertEquals(403,req("POST","/admin/nearby/stores/"+store+"/moderation",decision("HIDDEN"),admin,Map.of("If-Match","\"2\"","Idempotency-Key",key(),"X-Reverify-Token",proof)).status());}
 @Test void moderationHistoryCannotBeOverwritten(){published();assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM nearby_moderation_history WHERE store_id=?",store));}
 @Test void navigationProviderDisabledFailsExplicitly(){var provider=new cn.pawday.nearby.AmapNavigationProvider(false);var e=assertThrows(cn.pawday.common.Api.Failure.class,()->provider.intent(Map.of(),"DESTINATION"));assertNotNull(e);}
 @Test void equalDistancesUseStableIdsAndPaginationDoesNotDuplicate(){String city="TEST-TIE-"+key();var ids=new ArrayList<String>();for(int n=0;n<3;n++){if(n>0){store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST tie store')",store,merchantId);db.update("INSERT INTO principal_store_scope(principal_id,merchant_id,store_id) SELECT principal_id,?,? FROM auth_session WHERE access_token_hash=?",merchantId,store,crypto.hash(merchant));}var b=input();b.put("city",city);assertEquals(200,save(b,0,key()).status());assertEquals(200,moderate("PUBLISHED",1).status());ids.add(store.toString());}Collections.sort(ids);String query="/public/nearby/places?city="+city+"&longitude=121.5&latitude=31.2&coordinate_system=WGS84&limit=2";var page=read(query,null);assertEquals(ids.get(0),page.data().get(0).get("id").asString());assertEquals(ids.get(1),page.data().get(1).get("id").asString());assertEquals("2",page.body().get("page").get("next_cursor").asString());var next=read(query+"&offset=2",null);assertEquals(ids.get(2),next.data().get(0).get("id").asString());assertFalse(next.body().get("page").get("has_more").asBoolean());}
 @AfterAll static void evidence()throws Exception{Files.createDirectories(Path.of("target"));Files.writeString(Path.of("target/m54-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
}
