package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
class OfferIntegrationTests {
 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader,colleague;UUID adminPrincipal,adminSession,merchantId,store,otherStore,principal;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Offer test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'OFFER-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("offer.admin.manage")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT")){principal=p;db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);}return t;
 }
 @BeforeEach void setup(){merchantId=UUID.randomUUID();store=UUID.randomUUID();otherStore=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope'),(?,?,'TEST hidden')",store,merchantId,otherStore,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.read","offer.admin.manage"));reader=identity("ADMIN",null,List.of("offer.admin.read"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","offer.default-scope"));colleague=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust"));UUID m=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST foreign','ACTIVE')",m);UUID saved=store;store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST foreign store')",store,m);foreign=identity("MERCHANT",m,List.of("offer.read","offer.write","inventory.adjust"));store=saved;
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> createBody(UUID scope){var b=new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",1000,"member_price_fen",900,"fulfillment_sla","TEST-ONLY 48h"));b.put("store_id",scope==null?null:scope.toString());return b;}
 String create(){var r=req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r.id();}
 Response patch(String offer,Map<String,Object>b,int version){return req("PATCH","/merchant/offers/"+offer,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+version+"\""));}
 Response adjust(String offer,int delta,int version,String k,String who){return req("POST","/merchant/offers/"+offer+"/inventory-adjustments",Map.of("delta_qty",delta,"reason_code","COUNT_CORRECTION","expected_version",version),who,Map.of("Idempotency-Key",k));}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'offer.admin.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response state(String offer,String action,int version,String who,String p,String k){var h=new HashMap<String,String>(Map.of("Idempotency-Key",k,"If-Match","\""+version+"\""));if(p!=null)h.put("X-Reverify-Token",p);return req("POST","/"+(who.equals(admin)||who.equals(reader)?"admin":"merchant")+"/offers/"+offer+"/"+action,Map.of("reason","TEST-ONLY lifecycle"),who,h);}
 long balance(String offer){return db.queryForObject("SELECT on_hand_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(offer));}
 @AfterAll static void close()throws Exception{Files.writeString(Path.of("target/m33-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
 @Test void createsDraftAtZeroWithScopedActor(){String offer=create();var data=read("/merchant/offers/"+offer,merchant).data();assertEquals("DRAFT",data.get("sale_status").asString());assertEquals(0,balance(offer));assertEquals(0,data.get("inventory").get("available_qty").asLong());assertEquals(merchantId.toString(),data.get("merchant_id").asString());}
 @Test void foreignAndSameMerchantHiddenStoreAreDenied(){String offer=create();assertEquals(404,read("/merchant/offers/"+offer,foreign).status());assertEquals(404,req("POST","/merchant/offers",createBody(otherStore),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(404,read("/merchant/offers?store_id="+otherStore,merchant).status());assertEquals(404,adjust(offer,1,0,key(),foreign).status());}
 @Test void revokedScopeDeniesReadsWritesAndCachedReplay(){String offer=create(),k=key();assertEquals(201,adjust(offer,2,0,k,colleague).status());UUID p=db.queryForObject("SELECT principal_id FROM auth_session WHERE access_token_hash=?",UUID.class,crypto.hash(colleague));db.update("DELETE FROM principal_store_scope WHERE principal_id=?",p);assertEquals(404,adjust(offer,2,0,k,colleague).status());assertEquals(0,read("/merchant/offers",colleague).data().size());}
 @Test void nullScopeUniqueAndExplicitPermissionRequired(){var r=req("POST","/merchant/offers",createBody(null),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());assertEquals(409,req("POST","/merchant/offers",createBody(null),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(404,read("/merchant/offers/"+r.id(),colleague).status());assertEquals(404,req("POST","/merchant/offers",createBody(null),colleague,Map.of("Idempotency-Key",key())).status());}
 @Test void sameSkuCanHaveDifferentScopedOffers(){create();assertEquals(201,req("POST","/merchant/offers",createBody(null),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(2,read("/merchant/offers",merchant).data().size());assertEquals(1,read("/merchant/offers?store_id="+store,merchant).data().size());}
 @Test void concurrentCreateOnlyOneSucceeds()throws Exception{var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key())).status());var b=pool.submit(()->req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(List.of(201,409),java.util.stream.Stream.of(a.get(),b.get()).sorted().toList());}finally{pool.shutdownNow();}}
 @Test void dbEnforcesNullUniquenessAndStoreOwnership(){String offer=create();UUID o=UUID.fromString(offer);assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("INSERT INTO offers SELECT ?,merchant_id,store_id,sku_id,sale_price_fen,member_price_fen,fulfillment_sla,sale_status,version,created_at,updated_at FROM offers WHERE id=?",UUID.randomUUID(),o));UUID f=db.queryForObject("SELECT merchant_id FROM identity_principal WHERE id=(SELECT principal_id FROM auth_session WHERE access_token_hash=?)",UUID.class,crypto.hash(foreign));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE offers SET merchant_id=? WHERE id=?",f,o));}
 @Test void patchRejectsInventoryStatusAndIdentityFields(){String offer=create();for(String field:List.of("on_hand_qty","reserved_qty","target_on_hand_qty","status","sale_status","operator","merchant_id","sku_id","store_id","ingredients"))assertEquals(400,patch(offer,Map.of(field,1),0).status());assertEquals(0,balance(offer));}
 @Test void pricesAndVersionsDoNotSilentlyChange(){String offer=create();assertEquals(400,patch(offer,Map.of("sale_price_fen",800),0).status());assertEquals(200,patch(offer,Map.of("sale_price_fen",1200),0).status());assertEquals(409,patch(offer,Map.of("sale_price_fen",1300),0).status());assertEquals(400,patch(offer,Map.of("sale_price_fen",1.5),1).status());var b=new HashMap<String,Object>();b.put("member_price_fen",null);assertEquals(200,patch(offer,b,1).status());}
 @Test void lifecycleAndPlatformFreezeCannotBeBypassed(){String offer=create();assertEquals(200,state(offer,"activate",0,merchant,null,key()).status());assertEquals(200,state(offer,"freeze",1,admin,proof(),key()).status());assertEquals(409,state(offer,"activate",2,merchant,null,key()).status());assertEquals(409,patch(offer,Map.of("sale_price_fen",1100),2).status());assertEquals(200,state(offer,"unfreeze",2,admin,proof(),key()).status());assertEquals("PAUSED",read("/admin/offers/"+offer,admin).data().get("sale_status").asString());assertEquals(200,state(offer,"activate",3,merchant,null,key()).status());assertEquals(200,state(offer,"pause",4,merchant,null,key()).status());}
 @Test void delistRetainsHistoryAndAllowsNewOffer(){String offer=create();assertEquals(200,state(offer,"delist",0,admin,proof(),key()).status());assertEquals(409,adjust(offer,1,0,key(),merchant).status());assertNotEquals(offer,create());assertEquals("DELISTED",read("/admin/offers/"+offer,admin).data().get("sale_status").asString());}
 @Test void unpublishedStandardOrSuspendedMerchantCannotSell(){db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=?",UUID.fromString(sku));assertEquals(422,req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key())).status());}
 @Test void suspendedMerchantCannotAdjustOrActivate(){String offer=create();db.update("UPDATE merchant SET status='SUSPENDED' WHERE id=?",merchantId);assertEquals(401,adjust(offer,1,0,key(),merchant).status());assertEquals(401,state(offer,"activate",0,merchant,null,key()).status());}
 @Test void concurrentAdjustmentOnlyOneVersionWins()throws Exception{String offer=create();var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->adjust(offer,3,0,key(),merchant).status());var b=pool.submit(()->adjust(offer,3,0,key(),merchant).status());assertEquals(List.of(201,409),java.util.stream.Stream.of(a.get(),b.get()).sorted().toList());assertEquals(3,balance(offer));}finally{pool.shutdownNow();}}
 @Test void replayAcrossEmployeesSameMerchantDoesNotDuplicateStock(){String offer=create(),k=key();var first=adjust(offer,3,0,k,merchant);assertEquals(201,first.status());var second=adjust(offer,3,0,k,colleague);assertEquals(first.data(),second.data());assertEquals(409,adjust(offer,4,0,k,colleague).status());assertEquals(3,balance(offer));assertEquals(1,db.queryForObject("SELECT count(*) FROM inventory_adjustments WHERE offer_id=?",Integer.class,UUID.fromString(offer)));}
 @Test void adjustmentsCannotInvadeReservations(){String offer=create();adjust(offer,10,0,key(),merchant);db.update("UPDATE inventory_balances SET reserved_qty=8 WHERE offer_id=?",UUID.fromString(offer));assertEquals(409,adjust(offer,-3,1,key(),merchant).status());assertEquals(201,adjust(offer,-2,1,key(),merchant).status());assertEquals(8,balance(offer));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE inventory_balances SET reserved_qty=9 WHERE offer_id=?",UUID.fromString(offer)));}
 @Test void invalidAdjustmentsRejected(){String offer=create();assertEquals(400,adjust(offer,0,0,key(),merchant).status());assertEquals(409,adjust(offer,-1,0,key(),merchant).status());var b=new HashMap<String,Object>(Map.of("delta_qty",1,"expected_version",0,"reason_code","UNKNOWN"));assertEquals(400,req("POST","/merchant/offers/"+offer+"/inventory-adjustments",b,merchant,Map.of("Idempotency-Key",key())).status());b.put("reason_code","RESTOCK");b.put("operator",key());assertEquals(400,req("POST","/merchant/offers/"+offer+"/inventory-adjustments",b,merchant,Map.of("Idempotency-Key",key())).status());}
 @Test void ledgerImmutableAndReasonCodeAudited(){String offer=create();String adjustment=adjust(offer,2,0,key(),merchant).data().get("adjustment_id").asString();assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE inventory_adjustments SET reason_code='DAMAGE' WHERE id=?",UUID.fromString(adjustment)));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM inventory_adjustments WHERE id=?",UUID.fromString(adjustment)));assertTrue(db.queryForObject("SELECT after_json::text FROM audit_event WHERE object_id=?",String.class,adjustment).contains("COUNT_CORRECTION"));assertEquals(200,read("/merchant/offers/"+offer+"/inventory-adjustments",merchant).status());assertEquals(200,read("/admin/offers/"+offer+"/inventory-adjustments",admin).status());}
 @Test void adminCommandsRequireCorrectOneUseProof(){String offer=create();assertEquals(403,state(offer,"freeze",0,admin,null,key()).status());String p=proof(),k=key();assertEquals(200,state(offer,"freeze",0,admin,p,k).status());assertEquals(200,state(offer,"freeze",0,admin,p,k).status());assertEquals(403,state(offer,"unfreeze",1,admin,p,key()).status());assertEquals(403,state(offer,"unfreeze",1,reader,proof(),key()).status());}
 @Test void realmAndReadOnlyRbacRejectWrites(){String offer=create();assertEquals(401,read("/merchant/offers",null).status());assertEquals(403,read("/admin/offers",merchant).status());assertEquals(403,read("/merchant/offers",admin).status());String t=identity("MERCHANT",merchantId,List.of("offer.read"));assertEquals(403,adjust(offer,1,0,key(),t).status());assertEquals(403,read("/merchant/offers",identity("CONSUMER",null,List.of("offer.read"))).status());}
 @Test void batchIsAtomicAndHasNoStockBypass(){String first=create();var second=req("POST","/merchant/offers",createBody(null),merchant,Map.of("Idempotency-Key",key())).id();var items=List.of(Map.of("offer_id",first,"expected_version",0,"changes",Map.of("sale_price_fen",1100)),Map.of("offer_id",second,"expected_version",1,"changes",Map.of("sale_price_fen",1200)));assertEquals(409,req("POST","/merchant/offers/batch",Map.of("items",items),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(1000,read("/merchant/offers/"+first,merchant).data().get("sale_price_fen").asLong());var good=List.of(items.getFirst(),Map.of("offer_id",second,"expected_version",0,"changes",Map.of("sale_price_fen",1200)));assertEquals(200,req("POST","/merchant/offers/batch",Map.of("items",good),merchant,Map.of("Idempotency-Key",key())).status());assertEquals(0,balance(first));}
 @Test void paginationAndUnknownOfferAreExplicit(){create();assertEquals(200,read("/admin/offers?limit=1",admin).status());assertEquals(400,read("/merchant/offers?limit=0",merchant).status());assertEquals(404,read("/merchant/offers/"+key(),merchant).status());}
 @Test void outboxFailureRollsBackAdjustmentAndCanRetry(){String offer=create(),k=key();db.execute("CREATE FUNCTION fail_offer_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='InventoryAdjusted' THEN RAISE EXCEPTION 'TEST_ONLY'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_offer_event BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION fail_offer_event()");try{assertEquals(503,adjust(offer,5,0,k,merchant).status());assertEquals(0,balance(offer));assertEquals(0,db.queryForObject("SELECT count(*) FROM inventory_adjustments WHERE offer_id=?",Integer.class,UUID.fromString(offer)));}finally{db.execute("DROP TRIGGER test_offer_event ON outbox_event");db.execute("DROP FUNCTION fail_offer_event()");}assertEquals(201,adjust(offer,5,0,k,merchant).status());}
 @Test void auditFailureRollsBackFreezeAndRestoresProof(){String offer=create(),k=key(),p=proof();db.execute("CREATE FUNCTION fail_offer_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='offer.freeze' THEN RAISE EXCEPTION 'TEST_ONLY'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_offer_audit BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION fail_offer_audit()");try{assertEquals(503,state(offer,"freeze",0,admin,p,k).status());assertEquals("DRAFT",read("/admin/offers/"+offer,admin).data().get("sale_status").asString());}finally{db.execute("DROP TRIGGER test_offer_audit ON audit_event");db.execute("DROP FUNCTION fail_offer_audit()");}assertEquals(200,state(offer,"freeze",0,admin,p,k).status());}
}
