package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@org.springframework.context.annotation.Import(OrderIntegrationTests.TimeConfiguration.class)
class OrderIntegrationTests {
 static final java.util.concurrent.atomic.AtomicLong OFFSET=new java.util.concurrent.atomic.AtomicLong();
 @org.springframework.boot.test.context.TestConfiguration static class TimeConfiguration {
  @org.springframework.context.annotation.Bean @org.springframework.context.annotation.Primary Clock checkoutTestClock(){return new Clock(){public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}public Instant instant(){return Instant.now().plusSeconds(OFFSET.get());}};}
 }
 @AfterEach void resetClock(){OFFSET.set(0);}

 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader,colleague;UUID adminPrincipal,adminSession,merchantId,store,otherStore,principal;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Offer test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'OFFER-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("offer.admin.manage")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT")){principal=p;db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);}return t;
 }
 @BeforeEach void setup(){OFFSET.set(0);merchantId=UUID.randomUUID();store=UUID.randomUUID();otherStore=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope'),(?,?,'TEST hidden')",store,merchantId,otherStore,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.read","offer.admin.manage","order.admin.read","order.policy.manage"));reader=identity("ADMIN",null,List.of("offer.admin.read"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","offer.default-scope","order.read","order.default-scope"));colleague=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust"));UUID m=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST foreign','ACTIVE')",m);UUID saved=store;store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST foreign store')",store,m);foreign=identity("MERCHANT",m,List.of("offer.read","offer.write","inventory.adjust"));store=saved;
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> createBody(UUID scope){var b=new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",1000,"member_price_fen",900,"fulfillment_sla","TEST-ONLY 48h"));b.put("store_id",scope==null?null:scope.toString());return b;}
 String create(){var r=req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r.id();}
 Response patch(String offer,Map<String,Object>b,int version){return req("PATCH","/merchant/offers/"+offer,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+version+"\""));}
 Response adjust(String offer,int delta,int version,String k,String who){return req("POST","/merchant/offers/"+offer+"/inventory-adjustments",Map.of("delta_qty",delta,"reason_code","COUNT_CORRECTION","expected_version",version),who,Map.of("Idempotency-Key",k));}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'offer.admin.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response state(String offer,String action,int version,String who,String p,String k){var h=new HashMap<String,String>(Map.of("Idempotency-Key",k,"If-Match","\""+version+"\""));if(p!=null)h.put("X-Reverify-Token",p);return req("POST","/"+(who.equals(admin)||who.equals(reader)?"admin":"merchant")+"/offers/"+offer+"/"+action,Map.of("reason","TEST-ONLY lifecycle"),who,h);}
 long balance(String offer){return db.queryForObject("SELECT on_hand_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(offer));}
 @AfterAll static void close()throws Exception{Files.writeString(Path.of("target/m42-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}

 String consumer(){return identity("CONSUMER",null,List.of());}
 UUID user(String token){return db.queryForObject("SELECT p.user_id FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",UUID.class,crypto.hash(token));}
 UUID pet(String token,String category){UUID id=UUID.randomUUID();UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category=? AND parent_id IS NULL",UUID.class,category);db.update("INSERT INTO pets(id,owner_user_id,name,species_id,sex,neutered_status,birth_date) VALUES (?,?,'TEST pet',?,'UNKNOWN','UNKNOWN','2025-01-01')",id,user(token),species);return id;}
 Response fit(String token,UUID pet){return read("/consumer/skus/"+sku+"/fit?pet_id="+pet,token);}
 UUID allergen(){UUID a=UUID.randomUUID();db.update("INSERT INTO allergens(id,name) VALUES (?,?)",a,key());return a;}
 void assessed(UUID pet,UUID a,String status){db.update("INSERT INTO pet_allergens VALUES (?,?,?,'OWNER_OBSERVATION',NULL)",pet,a,status);}
 UUID publish(boolean known,UUID allergy,UUID stage){UUID v=UUID.randomUUID();db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=? AND status='PUBLISHED'",UUID.fromString(sku));db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by) VALUES (?,?,2,'[\"TEST-only ingredient\"]','[{\"name\":\"TEST protein\",\"value_milli\":10000,\"unit\":\"PERCENT\",\"basis\":\"AS_FED\",\"qualifier\":\"MIN\"}]',?,?::jsonb,'[\"TEST-only source\"]','2026-10-01',?)",v,UUID.fromString(sku),known,stage==null?"[]":json.writeValueAsString(List.of(stage)),adminPrincipal);if(allergy!=null)db.update("INSERT INTO sku_allergens VALUES (?,?)",v,allergy);db.update("UPDATE sku_standard_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return v;}
 UUID adultRule(){UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category='CAT' AND parent_id IS NULL",UUID.class);db.update("UPDATE pet_life_stage_rule_versions SET status='RETIRED' WHERE species_id=? AND status='PUBLISHED'",species);UUID v=UUID.randomUUID(),d=UUID.randomUUID();db.update("INSERT INTO pet_life_stage_rule_versions VALUES (?,?,(SELECT coalesce(max(version_no),0)+1 FROM pet_life_stage_rule_versions WHERE species_id='10000000-0000-4000-8000-000000000001'),'DRAFT','[\"TEST rule source\"]',NULL)",v,species);db.update("INSERT INTO pet_life_stage_definitions VALUES (?,?,'ADULT','TEST adult',0,NULL,'MONTH',false)",d,v);db.update("UPDATE pet_life_stage_rule_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return d;}

 String ready(){String o=create();assertEquals(201,adjust(o,20,0,key(),merchant).status());assertEquals(200,state(o,"activate",0,merchant,null,key()).status());return o;}
 Map<String,Object> addressBody(){return Map.of("recipient","TEST recipient","phone","13800000000","province_code","310000","city_code","310100","district_code","310101","detail","TEST-only address");}
 String addressFor(String u){var r=req("POST","/consumer/addresses",addressBody(),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 String addFor(String u,String o){var r=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 void shipping(){db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,NULL,?)",UUID.randomUUID(),merchantId,adminPrincipal);}
 Response quoteFor(String u,String i,String a,List<String>coupons,boolean member,String key){return req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i),"address_id",a,"coupon_ids",coupons,"use_membership",member),u,Map.of("Idempotency-Key",key));}
 String coupon(String u,String scope,long amount,long threshold){UUID c=UUID.randomUUID(),def=UUID.randomUUID();db.update("INSERT INTO coupon_definitions(id,version,status,parameters) VALUES (?,1,'PUBLISHED','{}')",def);db.update("INSERT INTO user_coupons(id,user_id,definition_id,definition_version,scope,merchant_id,amount_fen,threshold_fen,status,expires_at,version,rule_version) VALUES (?,?,?,1,?, ?,?,?, 'AVAILABLE',?,0,'TEST-ONLY-1')",c,user(u),def,scope,scope.equals("MERCHANT")?merchantId:null,amount,threshold,Timestamp.from(clock.instant().plusSeconds(600)));return c.toString();}

 @Autowired cn.pawday.ordering.OrderService orders;
 String q(String u,String o,List<String>coupons){String i=addFor(u,o),a=addressFor(u);var q=quoteFor(u,i,a,coupons,false,key());assertEquals(200,q.status(),q.body().toString());return q.data().get("quote_id").asString();}
 Response order(String u,String q,String k){return req("POST","/consumer/orders",Map.of("quote_id",q),u,Map.of("Idempotency-Key",k));}
 Response cancel(String u,String id,long v,String k){return req("POST","/consumer/orders/"+id+"/cancel",Map.of("reason_code","CONSUMER_CANCELLED"),u,Map.of("Idempotency-Key",k,"If-Match","\""+v+"\""));}
 long reserved(String o){return db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(o));}
 @Test void orderConsumesQuoteAndFreezesFactsAtomically(){String u=consumer(),o=ready();shipping();String quote=q(u,o,List.of());var result=order(u,quote,key());assertEquals(200,result.status(),result.body().toString());assertEquals(2500,result.data().get("payable_amount_fen").asInt());assertEquals(2,reserved(o));assertEquals(20,balance(o));assertEquals("PENDING",result.data().get("payment").get("status").asString());assertEquals(0,read("/consumer/cart",u).data().get("items").size());assertEquals("CONSUMED",read("/consumer/checkout/quotes/"+quote,u).data().get("status").asString());assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE aggregate_id=? AND event_type='OrderCreated'",Integer.class,result.id()));assertEquals(200,patch(o,Map.of("sale_price_fen",2000),1).status());assertEquals(result.data().get("pricing_snapshot"),read("/consumer/orders/"+result.id(),u).data().get("pricing_snapshot"));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE orders SET payable_amount_fen=payable_amount_fen+1 WHERE id=?",UUID.fromString(result.id())));}
 @Test void keyReplayAndQuoteSingleConsumption(){String u=consumer(),o=ready();shipping();String quote=q(u,o,List.of()),k=key();var first=order(u,quote,k);assertEquals(200,first.status(),first.body().toString());assertEquals(first.data(),order(u,quote,k).data());assertEquals("QUOTE_ALREADY_CONSUMED",order(u,quote,key()).body().get("error").get("code").asString());assertEquals(409,order(u,UUID.randomUUID().toString(),k).status());assertEquals(2,reserved(o));assertEquals(1,db.queryForObject("SELECT count(*) FROM orders WHERE user_id=?",Integer.class,user(u)));}
 @Test void realmsOwnershipAndNoAmountOverride(){String u=consumer(),o=ready();shipping();String quote=q(u,o,List.of());assertEquals(401,order(null,quote,key()).status());assertEquals(403,order(merchant,quote,key()).status());assertEquals(404,order(consumer(),quote,key()).status());assertEquals(400,req("POST","/consumer/orders",Map.of("quote_id",quote,"payable_amount_fen",1),u,Map.of("Idempotency-Key",key())).status());var first=order(u,quote,key());assertEquals(200,first.status(),first.body().toString());assertEquals(404,read("/consumer/orders/"+first.id(),consumer()).status());assertEquals(403,read("/admin/orders/"+first.id(),reader).status());assertEquals(200,read("/admin/orders/"+first.id(),admin).status());assertEquals(200,read("/consumer/orders",u).status());assertEquals(200,read("/admin/orders",admin).status());assertEquals(200,read("/merchant/suborders",merchant).status());String sub=first.data().get("suborders").get(0).get("id").asString();assertEquals(200,read("/merchant/suborders/"+sub,merchant).status());assertEquals(403,read("/merchant/suborders/"+sub,colleague).status());assertEquals(403,read("/merchant/suborders/"+sub,foreign).status());}
 @Test void cancellationReleasesOnceAndPreservesAmounts(){String u=consumer(),o=ready();shipping();String c=coupon(u,"PLATFORM",200,0),quote=q(u,o,List.of(c));var first=order(u,quote,key());assertEquals(200,first.status(),first.body().toString());assertEquals("RESERVED",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));String id=first.id(),k=key();assertEquals(428,req("POST","/consumer/orders/"+id+"/cancel",Map.of("reason_code","CONSUMER_CANCELLED"),u,Map.of("Idempotency-Key",key())).status());assertEquals(409,cancel(u,id,9,key()).status());assertEquals(404,cancel(consumer(),id,0,key()).status());var result=cancel(u,id,0,k);assertEquals(200,result.status(),result.body().toString());assertEquals(result.data(),cancel(u,id,0,k).data());assertEquals("CANCELLED",result.data().get("status").asString());assertEquals("CLOSED",result.data().get("payment").get("status").asString());assertEquals(2300,result.data().get("payable_amount_fen").asInt());assertEquals(0,reserved(o));assertEquals(20,balance(o));assertEquals("AVAILABLE",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));assertEquals(1,db.queryForObject("SELECT count(*) FROM order_cancellations WHERE order_id=?",Integer.class,UUID.fromString(id)));assertEquals(2,db.queryForObject("SELECT cancelled_qty FROM order_items WHERE suborder_id=?",Integer.class,UUID.fromString(result.data().get("suborders").get(0).get("id").asString())));assertEquals(409,cancel(u,id,1,key()).status());assertEquals(400,req("POST","/consumer/orders/"+id+"/cancel",Map.of("reason_code","CONSUMER_CANCELLED","items",List.of()),u,Map.of("Idempotency-Key",key(),"If-Match","\"1\"")).status());}
 @Test void returnedCouponRestoresOriginAndExpiredCouponExpires(){String u=consumer(),o=ready();shipping();String c=coupon(u,"PLATFORM",200,0);db.update("UPDATE user_coupons SET status='RETURNED',version=version+1 WHERE id=?",UUID.fromString(c));var first=order(u,q(u,o,List.of(c)),key());assertEquals(200,first.status(),first.body().toString());assertEquals(200,cancel(u,first.id(),0,key()).status());assertEquals("RETURNED",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));var next=order(u,q(u,o,List.of(c)),key());assertEquals(200,next.status(),next.body().toString());db.update("UPDATE auth_session SET expires_at=refresh_expires_at WHERE access_token_hash=?",crypto.hash(u));OFFSET.set(1000);assertTrue(orders.expireBatch()>=1);assertEquals(0,orders.expireBatch());var expired=read("/consumer/orders/"+next.id(),u);assertEquals(200,expired.status());assertEquals("PAYMENT_WINDOW_EXPIRED",expired.data().get("cancellation").get("reason_code").asString());assertEquals("EXPIRED",expired.data().get("reservations").get(0).get("status").asString());assertEquals("EXPIRED",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));assertEquals(0,reserved(o));}
 @Test void invalidQuoteOrInsufficientTotalStockCreatesNothing(){String u=consumer(),o=ready();shipping();String quote=q(u,o,List.of());assertEquals(201,adjust(o,-19,1,key(),merchant).status());assertEquals(409,order(u,quote,key()).status());assertEquals(0,reserved(o));assertEquals(0,db.queryForObject("SELECT count(*) FROM orders WHERE user_id=?",Integer.class,user(u)));assertEquals("ACTIVE",db.queryForObject("SELECT status FROM pricing_quotes WHERE id=?",String.class,UUID.fromString(quote)));assertEquals("INVALIDATED",read("/consumer/checkout/quotes/"+quote,u).data().get("status").asString());}
 @Test void concurrentLastStockNeverOversells()throws Exception{String u=consumer(),v=consumer(),o=ready();shipping();assertEquals(201,adjust(o,-18,1,key(),merchant).status());String q1=q(u,o,List.of()),q2=q(v,o,List.of());var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);var a=pool.submit(()->{start.await();return order(u,q1,key());});var b=pool.submit(()->{start.await();return order(v,q2,key());});start.countDown();var x=a.get(20,TimeUnit.SECONDS);var y=b.get(20,TimeUnit.SECONDS);assertEquals(Set.of(200,409),Set.of(x.status(),y.status()),x.body()+" / "+y.body());assertEquals(2,reserved(o));assertEquals(1,db.queryForObject("SELECT count(*) FROM orders WHERE user_id IN (?,?)",Integer.class,user(u),user(v)));}finally{pool.shutdownNow();}}
 @Test void sameQuoteDifferentKeysRaceCreatesOneOrder()throws Exception{String u=consumer(),o=ready();shipping();String quote=q(u,o,List.of());var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->order(u,quote,key()));var b=pool.submit(()->order(u,quote,key()));var x=a.get(20,TimeUnit.SECONDS);var y=b.get(20,TimeUnit.SECONDS);assertEquals(Set.of(200,409),Set.of(x.status(),y.status()));assertEquals(2,reserved(o));}finally{pool.shutdownNow();}}
 @Test void outboxFailureRollsBackEveryBusinessFact(){String u=consumer(),o=ready();shipping();String c=coupon(u,"PLATFORM",200,0),quote=q(u,o,List.of(c));db.execute("CREATE FUNCTION fail_order_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='OrderCreated' THEN RAISE EXCEPTION 'TEST rollback'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_fail_order_outbox BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION fail_order_outbox()");try{assertEquals(503,order(u,quote,key()).status());assertEquals(0,reserved(o));assertEquals("AVAILABLE",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));assertEquals("ACTIVE",db.queryForObject("SELECT status FROM pricing_quotes WHERE id=?",String.class,UUID.fromString(quote)));assertEquals(0,db.queryForObject("SELECT count(*) FROM orders WHERE user_id=?",Integer.class,user(u)));assertEquals(1,read("/consumer/cart",u).data().get("items").size());}finally{db.execute("DROP TRIGGER test_fail_order_outbox ON outbox_event");db.execute("DROP FUNCTION fail_order_outbox()");}assertEquals(200,order(u,quote,key()).status());}
 @Test void orderPolicyRequiresProofAndDoesNotChangeOldExpiry(){String u=consumer(),o=ready();shipping();var first=order(u,q(u,o,List.of()),key());assertEquals(200,first.status());String expiry=first.data().get("reservation_expires_at").asString();var body=Map.of("version_code","TEST_"+key().replace("-","").toUpperCase(),"reservation_ttl_seconds",60);assertEquals(200,read("/admin/order-policies",admin).status());assertEquals(403,req("POST","/admin/order-policies",body,admin,Map.of("Idempotency-Key",key())).status());String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'order.policy.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));String k=key();var policy=req("POST","/admin/order-policies",body,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",p));assertEquals(200,policy.status(),policy.body().toString());assertEquals(policy.data(),req("POST","/admin/order-policies",body,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",p)).data());assertEquals(expiry,read("/consumer/orders/"+first.id(),u).data().get("reservation_expires_at").asString());var second=order(u,q(u,o,List.of()),key());assertEquals(200,second.status());assertTrue(Instant.parse(second.data().get("reservation_expires_at").asString()).isBefore(Instant.parse(expiry)));}

 @Test void crossMerchantOrderHasTwoGroupsAndAtomicFailure(){String u=consumer(),o=ready();shipping();var b=createBody(null);b.put("store_id",db.queryForObject("SELECT ss.store_id FROM principal_store_scope ss JOIN auth_session s ON s.principal_id=ss.principal_id WHERE s.access_token_hash=?",UUID.class,crypto.hash(foreign)).toString());String f=req("POST","/merchant/offers",b,foreign,Map.of("Idempotency-Key",key())).id();assertEquals(201,adjust(f,20,0,key(),foreign).status());assertEquals(200,state(f,"activate",0,foreign,null,key()).status());UUID fm=db.queryForObject("SELECT merchant_id FROM offers WHERE id=?",UUID.class,UUID.fromString(f));db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,?)",UUID.randomUUID(),fm,adminPrincipal);String i=addFor(u,o),j=addFor(u,f),addr=addressFor(u);var input=Map.of("cart_item_ids",List.of(i,j),"address_id",addr);var q1=req("POST","/consumer/checkout/quotes",input,u,Map.of("Idempotency-Key",key()));assertEquals(200,q1.status(),q1.body().toString());assertEquals(201,adjust(f,-19,1,key(),foreign).status());var failed=order(u,q1.data().get("quote_id").asString(),key());assertEquals(409,failed.status());assertEquals(0,reserved(o));assertEquals(0,reserved(f));assertEquals(0,db.queryForObject("SELECT count(*) FROM orders WHERE user_id=?",Integer.class,user(u)));assertEquals(201,adjust(f,19,2,key(),foreign).status());var q2=req("POST","/consumer/checkout/quotes",input,u,Map.of("Idempotency-Key",key()));assertEquals(200,q2.status());var created=order(u,q2.data().get("quote_id").asString(),key());assertEquals(200,created.status(),created.body().toString());assertEquals(2,created.data().get("suborders").size());assertEquals(5000,created.data().get("payable_amount_fen").asInt());assertEquals(2,reserved(o));assertEquals(2,reserved(f));assertEquals(200,cancel(u,created.id(),0,key()).status());assertEquals(0,reserved(o));assertEquals(0,reserved(f));}
 @Test void sharedOfferAcrossPetsAggregatesReservationAndRejectsOversell(){String u=consumer(),o=ready();shipping();assertEquals(201,adjust(o,-17,1,key(),merchant).status());String i=addFor(u,o);var other=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2,"pet_id",pet(u,"CAT").toString()),u,Map.of("Idempotency-Key",key()));assertEquals(200,other.status());String a=addressFor(u);var q=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,other.id()),"address_id",a),u,Map.of("Idempotency-Key",key()));assertEquals(200,q.status(),q.body().toString());assertEquals(409,order(u,q.data().get("quote_id").asString(),key()).status());assertEquals(0,reserved(o));assertEquals(0,db.queryForObject("SELECT count(*) FROM orders WHERE user_id=?",Integer.class,user(u)));assertEquals(201,adjust(o,1,2,key(),merchant).status());var q2=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,other.id()),"address_id",a),u,Map.of("Idempotency-Key",key()));var created=order(u,q2.data().get("quote_id").asString(),key());assertEquals(200,created.status(),created.body().toString());assertEquals(1,created.data().get("reservations").size());assertEquals(4,reserved(o));assertEquals(2,created.data().get("suborders").get(0).get("items").size());}
 @Test void storeScopedEmployeeCannotReadMixedScopeChildOrForeignMerchant(){String u=consumer(),o=ready();shipping();String defaultOffer=req("POST","/merchant/offers",createBody(null),merchant,Map.of("Idempotency-Key",key())).id();assertEquals(201,adjust(defaultOffer,20,0,key(),merchant).status());assertEquals(200,state(defaultOffer,"activate",0,merchant,null,key()).status());String i=addFor(u,o),j=addFor(u,defaultOffer),a=addressFor(u);var q=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i,j),"address_id",a),u,Map.of("Idempotency-Key",key()));var created=order(u,q.data().get("quote_id").asString(),key());assertEquals(200,created.status());String sub=created.data().get("suborders").get(0).get("id").asString();String scoped=identity("MERCHANT",merchantId,List.of("order.read"));assertEquals(404,read("/merchant/suborders/"+sub,scoped).status());assertEquals(0,read("/merchant/suborders",scoped).data().size());assertEquals(200,read("/merchant/suborders/"+sub,merchant).status());UUID fm=db.queryForObject("SELECT p.merchant_id FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",UUID.class,crypto.hash(foreign));UUID originalStore=store;store=db.queryForObject("SELECT id FROM merchant_store WHERE merchant_id=? LIMIT 1",UUID.class,fm);String outsider=identity("MERCHANT",fm,List.of("order.read","order.default-scope"));store=originalStore;assertEquals(404,read("/merchant/suborders/"+sub,outsider).status());}
 @Test void parallelExpiryWorkersReleaseEachOrderOnce()throws Exception{String u=consumer(),o=ready();shipping();var one=order(u,q(u,o,List.of()),key());var two=order(u,q(u,o,List.of()),key());assertEquals(200,one.status());assertEquals(200,two.status());OFFSET.set(1000);var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->orders.expireBatch());var b=pool.submit(()->orders.expireBatch());a.get(20,TimeUnit.SECONDS);b.get(20,TimeUnit.SECONDS);assertEquals(0,reserved(o));assertEquals(2,db.queryForObject("SELECT count(*) FROM order_cancellations WHERE order_id IN (?,?)",Integer.class,UUID.fromString(one.id()),UUID.fromString(two.id())));assertEquals(2,db.queryForObject("SELECT count(*) FROM inventory_reservation_events WHERE order_id IN (?,?) AND operation='EXPIRE'",Integer.class,UUID.fromString(one.id()),UUID.fromString(two.id())));assertEquals(0,orders.expireBatch());}finally{pool.shutdownNow();}}
 @Test void reservationBlocksMerchantDamageAndPaginationIsExplicit(){String u=consumer(),o=ready();shipping();var first=order(u,q(u,o,List.of()),key());assertEquals(200,first.status());assertEquals(409,adjust(o,-19,2,key(),merchant).status());assertEquals(20,balance(o));var second=order(u,q(u,o,List.of()),key());assertEquals(200,second.status());var page=read("/consumer/orders?limit=1",u);assertEquals(200,page.status());assertTrue(page.body().get("page").get("has_more").asBoolean());String cursor=page.body().get("page").get("next_cursor").asString();var next=read("/consumer/orders?limit=1&cursor="+cursor,u);assertEquals(1,next.data().size());assertNotEquals(page.data().get(0).get("id").asString(),next.data().get(0).get("id").asString());assertFalse(next.body().get("page").get("has_more").asBoolean());}
}
