package cn.pawday;
import cn.pawday.identity.*;
import cn.pawday.catalog.CatalogImportParser;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@org.springframework.context.annotation.Import(PaymentIntegrationTests.TimeConfiguration.class)
class PaymentIntegrationTests {
 static final java.util.concurrent.atomic.AtomicLong OFFSET=new java.util.concurrent.atomic.AtomicLong();
 @org.springframework.boot.test.context.TestConfiguration static class TimeConfiguration {
  @org.springframework.context.annotation.Bean @org.springframework.context.annotation.Primary Clock checkoutTestClock(){return new Clock(){public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}public Instant instant(){return Instant.now().plusSeconds(OFFSET.get());}};}
 }
 @AfterEach void resetClock(){OFFSET.set(0);}

 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);r.add("pawday.payment.simulation-enabled",()->true);r.add("pawday.payment.recovery-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String admin,merchant,foreign,reader,colleague;UUID adminPrincipal,adminSession,merchantId,store,otherStore,principal;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Offer test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'OFFER-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")&&permissions.contains("offer.admin.manage")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT")){principal=p;db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);}return t;
 }
 @BeforeEach void setup(){OFFSET.set(0);merchantId=UUID.randomUUID();store=UUID.randomUUID();otherStore=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope'),(?,?,'TEST hidden')",store,merchantId,otherStore,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.read","offer.admin.manage","order.admin.read","order.policy.manage","payment.read","payment.requery"));reader=identity("ADMIN",null,List.of("offer.admin.read"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","offer.default-scope","order.read","order.default-scope"));colleague=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust"));UUID m=UUID.randomUUID();db.update("INSERT INTO merchant VALUES (?,'TEST foreign','ACTIVE')",m);UUID saved=store;store=UUID.randomUUID();db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST foreign store')",store,m);foreign=identity("MERCHANT",m,List.of("offer.read","offer.write","inventory.adjust"));store=saved;
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 Map<String,Object> createBody(UUID scope){var b=new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",1000,"member_price_fen",900,"fulfillment_sla","TEST-ONLY 48h"));b.put("store_id",scope==null?null:scope.toString());return b;}
 String create(){var r=req("POST","/merchant/offers",createBody(store),merchant,Map.of("Idempotency-Key",key()));assertEquals(201,r.status(),r.body().toString());return r.id();}
 Response patch(String offer,Map<String,Object>b,int version){return req("PATCH","/merchant/offers/"+offer,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+version+"\""));}
 Response adjust(String offer,int delta,int version,String k,String who){return req("POST","/merchant/offers/"+offer+"/inventory-adjustments",Map.of("delta_qty",delta,"reason_code","COUNT_CORRECTION","expected_version",version),who,Map.of("Idempotency-Key",k));}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'offer.admin.manage',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response state(String offer,String action,int version,String who,String p,String k){var h=new HashMap<String,String>(Map.of("Idempotency-Key",k,"If-Match","\""+version+"\""));if(p!=null)h.put("X-Reverify-Token",p);return req("POST","/"+(who.equals(admin)||who.equals(reader)?"admin":"merchant")+"/offers/"+offer+"/"+action,Map.of("reason","TEST-ONLY lifecycle"),who,h);}
 long balance(String offer){return db.queryForObject("SELECT on_hand_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(offer));}

 String consumer(){return identity("CONSUMER",null,List.of());}
 UUID user(String token){return db.queryForObject("SELECT p.user_id FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",UUID.class,crypto.hash(token));}
 UUID pet(String token,String category){UUID id=UUID.randomUUID();UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category=? AND parent_id IS NULL",UUID.class,category);db.update("INSERT INTO pets(id,owner_user_id,name,species_id,sex,neutered_status,birth_date) VALUES (?,?,'TEST pet',?,'UNKNOWN','UNKNOWN','2025-01-01')",id,user(token),species);return id;}
 Response fit(String token,UUID pet){return read("/consumer/skus/"+sku+"/fit?pet_id="+pet,token);}
 UUID allergen(){UUID a=UUID.randomUUID();db.update("INSERT INTO allergens(id,name) VALUES (?,?)",a,key());return a;}
 void assessed(UUID pet,UUID a,String status){db.update("INSERT INTO pet_allergens VALUES (?,?,?,'OWNER_OBSERVATION',NULL)",pet,a,status);}
 UUID publish(boolean known,UUID allergy,UUID stage){UUID v=UUID.randomUUID();db.update("UPDATE sku_standard_versions SET status='RETIRED' WHERE sku_id=? AND status='PUBLISHED'",UUID.fromString(sku));db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by) VALUES (?,?,2,'[\"TEST-only ingredient\"]','[{\"name\":\"TEST protein\",\"value_milli\":10000,\"unit\":\"PERCENT\",\"basis\":\"AS_FED\",\"qualifier\":\"MIN\"}]',?,?::jsonb,'[\"TEST-only source\"]','2026-10-01',?)",v,UUID.fromString(sku),known,stage==null?"[]":json.writeValueAsString(List.of(stage)),adminPrincipal);if(allergy!=null)db.update("INSERT INTO sku_allergens VALUES (?,?)",v,allergy);db.update("UPDATE sku_standard_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return v;}
 UUID adultRule(){UUID species=db.queryForObject("SELECT id FROM pet_species WHERE category='CAT' AND parent_id IS NULL",UUID.class);db.update("UPDATE pet_life_stage_rule_versions SET status='RETIRED' WHERE species_id=? AND status='PUBLISHED'",species);UUID v=UUID.randomUUID(),d=UUID.randomUUID();db.update("INSERT INTO pet_life_stage_rule_versions VALUES (?,?,(SELECT coalesce(max(version_no),0)+1 FROM pet_life_stage_rule_versions WHERE species_id='10000000-0000-4000-8000-000000000001'),'DRAFT','[\"TEST rule source\"]',NULL)",v,species);db.update("INSERT INTO pet_life_stage_definitions VALUES (?,?,'ADULT','TEST adult',0,NULL,'MONTH',false)",d,v);db.update("UPDATE pet_life_stage_rule_versions SET status='PUBLISHED',published_at=clock_timestamp() WHERE id=?",v);return d;}

 String ready(){String o=create();assertEquals(201,adjust(o,20,0,key(),merchant).status());assertEquals(200,state(o,"activate",0,merchant,null,key()).status());return o;}
 Map<String,Object> addressBody(){return Map.of("recipient","TEST recipient","phone","13800000000","province_code","310000","city_code","310100","district_code","310101","detail","TEST-only address");}
 String addressFor(String u){var r=req("POST","/consumer/addresses",addressBody(),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 String addFor(String u,String o){var r=req("POST","/consumer/cart/items",Map.of("offer_id",o,"quantity",2),u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r.id();}
 void shipping(){db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,1,'[\"310000\"]',300,100,NULL,?)",UUID.randomUUID(),merchantId,adminPrincipal);}
 Response quoteFor(String u,String i,String a,List<String>coupons,boolean member,String key){return req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",List.of(i),"address_id",a,"coupon_ids",coupons,"use_membership",member),u,Map.of("Idempotency-Key",key));}
 String coupon(String u,String scope,long amount,long threshold){UUID c=UUID.randomUUID(),def=UUID.randomUUID();db.update("INSERT INTO coupon_definitions(id,version,status,parameters) VALUES (?,1,'PUBLISHED','{}')",def);db.update("INSERT INTO user_coupons(id,user_id,definition_id,definition_version,scope,merchant_id,amount_fen,threshold_fen,status,expires_at,version,rule_version) VALUES (?,?,?,1,?, ?,?,?, 'AVAILABLE',?,0,'TEST-ONLY-1')",c,user(u),def,scope,scope.equals("MERCHANT")?merchantId:null,amount,threshold,Timestamp.from(clock.instant().plusSeconds(600)));return c.toString();}

 @Autowired cn.pawday.ordering.OrderService orders;
 String q(String u,String o,List<String>coupons){String i=addFor(u,o),a=addressFor(u);var q=quoteFor(u,i,a,coupons,false,key());assertEquals(200,q.status(),q.body().toString());return q.data().get("quote_id").asString();}
 Response order(String u,String q,String k){return req("POST","/consumer/orders",Map.of("quote_id",q),u,Map.of("Idempotency-Key",k));}
 Response cancel(String u,String id,long v,String k){return req("POST","/consumer/orders/"+id+"/cancel",Map.of("reason_code","CONSUMER_CANCELLED"),u,Map.of("Idempotency-Key",k,"If-Match","\""+v+"\""));}
 long reserved(String o){return db.queryForObject("SELECT reserved_qty FROM inventory_balances WHERE offer_id=?",Long.class,UUID.fromString(o));}

 @Autowired cn.pawday.payment.PaymentService payments;@Autowired cn.pawday.payment.SimulatedPaymentGateway gateway;@Autowired org.springframework.transaction.support.TransactionTemplate tx;
 Response payment(String u,String p){return read("/consumer/payments/"+p,u);}
 Response attempt(String u,String p,String channel,String k){return req("POST","/consumer/payments/"+p+"/attempts",Map.of("channel",channel,"client_platform","ANDROID"),u,Map.of("Idempotency-Key",k));}
 Response query(String u,String p){return req("POST","/consumer/payments/"+p+"/requery",null,u,Map.of());}
 Response outcome(String u,String p,String a,String state){return req("POST","/consumer/payments/"+p+"/simulation",Map.of("attempt_id",a,"outcome",state),u,Map.of());}
 Response closeAttempt(String u,String p){return req("POST","/consumer/payments/"+p+"/close-attempt",null,u,Map.of());}
 String aid(Response r){return r.data().get("attempts").get(r.data().get("attempts").size()-1).get("id").asString();}
 String pid(Response o){return o.data().get("payment").get("id").asString();}
 record Fixture(String u,String offer,Response order,String payment){}
 Fixture fixture(){String u=consumer(),o=ready();shipping();var order=order(u,q(u,o,List.of()),key());assertEquals(200,order.status(),order.body().toString());return new Fixture(u,o,order,pid(order));}
 void providerSuccess(String a,long amount,String currency){db.update("UPDATE simulated_payment_transactions SET status='SUCCEEDED',amount_fen=?,currency=?,transaction_id=coalesce(transaction_id,?) WHERE attempt_no=(SELECT attempt_no FROM payment_attempts WHERE id=?)",amount,currency,"SIM-"+a,UUID.fromString(a));}
 @Test void serverConfirmationConsumesExactlyOnce(){var f=fixture();String k=key();var created=attempt(f.u(),f.payment(),"WECHAT",k);assertEquals(200,created.status(),created.body().toString());assertEquals("PROCESSING",created.data().get("status").asString());String a=aid(created);assertEquals(a,aid(attempt(f.u(),f.payment(),"WECHAT",k)));var success=outcome(f.u(),f.payment(),a,"SUCCEEDED");assertEquals(200,success.status(),success.body().toString());assertEquals("SUCCEEDED",success.data().get("status").asString());assertEquals("WECHAT",success.data().get("final_channel").asString());assertEquals(a,success.data().get("successful_attempt_id").asString());assertEquals(18,balance(f.offer()));assertEquals(0,reserved(f.offer()));assertEquals("FULFILLING",read("/consumer/orders/"+f.order().id(),f.u()).data().get("status").asString());assertEquals("CONSUMED",db.queryForObject("SELECT status FROM inventory_reservations WHERE order_id=?",String.class,UUID.fromString(f.order().id())));for(int i=0;i<3;i++)assertEquals("SUCCEEDED",query(f.u(),f.payment()).data().get("status").asString());assertEquals(1,db.queryForObject("SELECT count(*) FROM inventory_sale_events WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));assertEquals(1,db.queryForObject("SELECT count(*) FROM payment_receipts WHERE attempt_id=?",Integer.class,UUID.fromString(a)));assertEquals(1,db.queryForObject("SELECT count(*) FROM outbox_event WHERE event_type='OrderPaid' AND aggregate_id=?",Integer.class,f.order().id()));assertEquals(409,attempt(f.u(),f.payment(),"ALIPAY",key()).status());assertEquals(409,cancel(f.u(),f.order().id(),1,key()).status());}
 @Test void successfulPaymentRedeemsReservedCoupon(){String u=consumer(),o=ready();shipping();String c=coupon(u,"PLATFORM",200,0);var ord=order(u,q(u,o,List.of(c)),key());String p=pid(ord),a=aid(attempt(u,p,"ALIPAY",key()));assertEquals(200,outcome(u,p,a,"SUCCEEDED").status());assertEquals("USED",db.queryForObject("SELECT status FROM user_coupons WHERE id=?",String.class,UUID.fromString(c)));assertEquals(1,db.queryForObject("SELECT count(*) FROM coupon_redemption_events WHERE coupon_id=?",Integer.class,UUID.fromString(c)));query(u,p);assertEquals(1,db.queryForObject("SELECT count(*) FROM coupon_redemption_events WHERE coupon_id=?",Integer.class,UUID.fromString(c)));}
 @Test void pendingCannotReleaseAndSafeCloseAllowsCancellation(){var f=fixture();attempt(f.u(),f.payment(),"WECHAT",key());assertEquals(409,cancel(f.u(),f.order().id(),0,key()).status());assertEquals(2,reserved(f.offer()));assertEquals("PENDING",closeAttempt(f.u(),f.payment()).data().get("status").asString());assertEquals(200,cancel(f.u(),f.order().id(),0,key()).status());assertEquals(0,reserved(f.offer()));assertEquals(20,balance(f.offer()));assertEquals("CLOSED",payment(f.u(),f.payment()).data().get("status").asString());}
 @Test void channelSwitchClosesOldBeforeOpeningNew(){var f=fixture();var first=attempt(f.u(),f.payment(),"WECHAT",key());String old=aid(first);var second=attempt(f.u(),f.payment(),"ALIPAY",key());assertEquals(200,second.status(),second.body().toString());assertNotEquals(old,aid(second));assertEquals("CANCELLED",second.data().get("attempts").get(0).get("status").asString());assertEquals(1,db.queryForObject("SELECT count(*) FROM simulated_payment_transactions WHERE status='PENDING' AND attempt_no IN (SELECT attempt_no FROM payment_attempts WHERE payment_id=?)",Integer.class,UUID.fromString(f.payment())));}
 @Test void uncertainResultBlocksSwitchAndExpirationUntilConfirmed(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));assertEquals("UNKNOWN",outcome(f.u(),f.payment(),a,"UNKNOWN").data().get("attempts").get(0).get("status").asString());assertEquals(409,attempt(f.u(),f.payment(),"ALIPAY",key()).status());assertEquals(409,closeAttempt(f.u(),f.payment()).status());OFFSET.set(901);payments.refresh(UUID.fromString(a),true);orders.expireBatch();assertEquals(2,reserved(f.offer()));assertEquals("PROCESSING",db.queryForObject("SELECT status FROM payments WHERE id=?",String.class,UUID.fromString(f.payment())));OFFSET.set(0);assertEquals("PENDING",outcome(f.u(),f.payment(),a,"FAILED").data().get("status").asString());OFFSET.set(901);orders.expireBatch();assertEquals(0,reserved(f.offer()));}
 @Test void failureKeepsReservationAndAllowsRetry(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));assertEquals("PENDING",outcome(f.u(),f.payment(),a,"FAILED").data().get("status").asString());assertEquals(2,reserved(f.offer()));assertEquals(200,attempt(f.u(),f.payment(),"ALIPAY",key()).status());}
 @Test void ownershipRealmAndAmountOverrideAreRejected(){var f=fixture();assertEquals(404,payment(consumer(),f.payment()).status());assertEquals(403,payment(merchant,f.payment()).status());assertEquals(403,read("/admin/payments/"+f.payment(),reader).status());assertEquals(200,read("/admin/payments/"+f.payment(),admin).status());assertEquals(400,req("POST","/consumer/payments/"+f.payment()+"/attempts",Map.of("channel","WECHAT","client_platform","ANDROID","amount_fen",1),f.u(),Map.of("Idempotency-Key",key())).status());assertEquals(400,attempt(f.u(),f.payment(),"OTHER",key()).status());assertEquals(400,attempt(f.u(),f.payment(),"WECHAT","short").status());assertEquals(0,db.queryForObject("SELECT count(*) FROM payment_attempts WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}
 @Test void sameKeyConcurrentRequestsDoNotCloseTheirOwnAttempt()throws Exception{var f=fixture();String k=key();var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->attempt(f.u(),f.payment(),"WECHAT",k));var b=pool.submit(()->attempt(f.u(),f.payment(),"WECHAT",k));var first=a.get(30,TimeUnit.SECONDS);var second=b.get(30,TimeUnit.SECONDS);assertEquals(200,first.status());assertEquals(200,second.status());assertEquals(aid(first),aid(second));assertEquals("CHANNEL_PENDING",payment(f.u(),f.payment()).data().get("attempts").get(0).get("status").asString());assertEquals(1,db.queryForObject("SELECT count(*) FROM payment_attempts WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}finally{pool.shutdownNow();}}
 @Test void differentPayloadSameKeyDoesNotCloseActiveAttempt(){var f=fixture();String k=key();attempt(f.u(),f.payment(),"WECHAT",k);assertEquals(409,attempt(f.u(),f.payment(),"ALIPAY",k).status());assertEquals("CHANNEL_PENDING",payment(f.u(),f.payment()).data().get("attempts").get(0).get("status").asString());}
 @org.junit.jupiter.params.ParameterizedTest @org.junit.jupiter.params.provider.ValueSource(strings={"CNY","USD"}) void amountAndCurrencyMismatchCreateOriginalRouteCompensation(String currency){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));providerSuccess(a,currency.equals("CNY")?2501:2500,currency);var result=query(f.u(),f.payment());assertEquals(200,result.status(),result.body().toString());assertEquals("PENDING",result.data().get("status").asString());assertEquals(currency.equals("CNY")?"AMOUNT_MISMATCH":"CURRENCY_MISMATCH",result.data().get("cases").get(0).get("reason_code").asString());assertEquals("REFUNDED",result.data().get("cases").get(0).get("status").asString());assertEquals(20,balance(f.offer()));assertEquals(2,reserved(f.offer()));assertEquals(1,db.queryForObject("SELECT count(*) FROM simulated_payment_refunds WHERE transaction_id IN (SELECT channel_transaction_id FROM payment_receipts WHERE attempt_id=?)",Integer.class,UUID.fromString(a)));}
 @Test void lateCollectionNeverRevivesClosedOrder(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));closeAttempt(f.u(),f.payment());cancel(f.u(),f.order().id(),0,key());providerSuccess(a,2500,"CNY");var result=query(f.u(),f.payment());assertEquals("CLOSED",result.data().get("status").asString());assertEquals("LATE_COLLECTION",result.data().get("cases").get(0).get("reason_code").asString());assertEquals("REFUNDED",result.data().get("cases").get(0).get("status").asString());assertEquals(20,balance(f.offer()));assertEquals(0,reserved(f.offer()));assertEquals("CANCELLED",read("/consumer/orders/"+f.order().id(),f.u()).data().get("status").asString());query(f.u(),f.payment());assertEquals(1,db.queryForObject("SELECT count(*) FROM payment_cases WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}
 @Test void duplicateCollectionDoesNotOverwriteWinningAttempt(){var f=fixture();String old=aid(attempt(f.u(),f.payment(),"WECHAT",key()));String winner=aid(attempt(f.u(),f.payment(),"ALIPAY",key()));outcome(f.u(),f.payment(),winner,"SUCCEEDED");providerSuccess(old,2500,"CNY");var result=query(f.u(),f.payment());assertEquals(winner,result.data().get("successful_attempt_id").asString());assertEquals("ALIPAY",result.data().get("final_channel").asString());assertEquals("DUPLICATE_COLLECTION",result.data().get("cases").get(0).get("reason_code").asString());assertEquals(18,balance(f.offer()));assertEquals(1,db.queryForObject("SELECT count(*) FROM inventory_sale_events WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}
 @Test void durableProviderSuccessRecoversAfterOutboxFailure(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));providerSuccess(a,2500,"CNY");db.execute("CREATE FUNCTION reject_m43_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='OrderPaid' AND NEW.aggregate_id='"+f.order().id()+"' THEN RAISE EXCEPTION 'TEST ONLY';END IF;RETURN NEW;END $$");db.execute("CREATE TRIGGER m43_fault BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION reject_m43_outbox()");try{assertEquals(503,query(f.u(),f.payment()).status());assertEquals(20,balance(f.offer()));assertEquals(2,reserved(f.offer()));assertEquals("PROCESSING",payment(f.u(),f.payment()).data().get("status").asString());}finally{db.execute("DROP TRIGGER m43_fault ON outbox_event");db.execute("DROP FUNCTION reject_m43_outbox()");}db.update("UPDATE payment_requery_schedule SET next_query_at=clock_timestamp() WHERE attempt_id=?",UUID.fromString(a));assertTrue(payments.recoverBatch()>0);assertEquals("SUCCEEDED",payment(f.u(),f.payment()).data().get("status").asString());assertEquals(18,balance(f.offer()));}
 @Test void providerIOCannotRunInsideBusinessTransaction(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));var request=new cn.pawday.payment.PaymentGateway.Request(UUID.fromString(a),"TEST ONLY","WECHAT",2500,"CNY");assertThrows(IllegalStateException.class,()->tx.execute(s->gateway.query(request)));}
 @Test void adminRequeryRequiresReverifyAndAudit(){var f=fixture();assertEquals(403,req("POST","/admin/payments/"+f.payment()+"/requery",null,reader,Map.of("Idempotency-Key",key())).status());assertEquals(403,req("POST","/admin/payments/"+f.payment()+"/requery",null,admin,Map.of("Idempotency-Key",key())).status());UUID grant=UUID.randomUUID();String proof=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?, ?,'payment.requery',?,?)",crypto.hash(proof),adminSession,Timestamp.from(clock.instant().plusSeconds(300)),Timestamp.from(clock.instant()));String k=key();var result=req("POST","/admin/payments/"+f.payment()+"/requery",null,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",proof));assertEquals(200,result.status(),result.body().toString());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='payment.requery' AND object_id=?",Integer.class,f.payment()));assertEquals(200,req("POST","/admin/payments/"+f.payment()+"/requery",null,admin,Map.of("Idempotency-Key",k,"X-Reverify-Token",proof)).status());}

 @Test void pendingAttemptIsScheduledPromptlyAndPaidExpiryCannotRelease(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));assertTrue(db.queryForObject("SELECT next_query_at<clock_timestamp()+interval '10 seconds' FROM payment_requery_schedule WHERE attempt_id=?",Boolean.class,UUID.fromString(a)));outcome(f.u(),f.payment(),a,"SUCCEEDED");OFFSET.set(1000);orders.expireBatch();assertEquals(18,balance(f.offer()));assertEquals(0,reserved(f.offer()));assertEquals("FULFILLING",db.queryForObject("SELECT status FROM orders WHERE id=?",String.class,UUID.fromString(f.order().id())));}
 @Test void concurrentQueriesConfirmOneSale(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));providerSuccess(a,2500,"CNY");var pool=java.util.concurrent.Executors.newFixedThreadPool(2);try{var x=pool.submit(()->query(f.u(),f.payment()));var y=pool.submit(()->query(f.u(),f.payment()));assertEquals(200,x.get().status());assertEquals(200,y.get().status());assertEquals(18,balance(f.offer()));assertEquals(1,db.queryForObject("SELECT count(*) FROM inventory_sale_events WHERE payment_id=?",Integer.class,UUID.fromString(f.payment())));}catch(Exception e){throw new AssertionError(e);}finally{pool.shutdownNow();}}
 @Test void compensationCommitCrashReusesOriginalRefund(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));closeAttempt(f.u(),f.payment());cancel(f.u(),f.order().id(),0,key());providerSuccess(a,2500,"CNY");db.execute("CREATE FUNCTION reject_m43_refund() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='PaymentCompensated' AND NEW.aggregate_id='"+f.payment()+"' THEN RAISE EXCEPTION 'TEST ONLY';END IF;RETURN NEW;END $$");db.execute("CREATE TRIGGER m43_refund_fault BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION reject_m43_refund()");try{assertEquals(503,query(f.u(),f.payment()).status());assertEquals("REFUND_PENDING",payment(f.u(),f.payment()).data().get("cases").get(0).get("status").asString());}finally{db.execute("DROP TRIGGER m43_refund_fault ON outbox_event");db.execute("DROP FUNCTION reject_m43_refund()");}assertEquals("REFUNDED",query(f.u(),f.payment()).data().get("cases").get(0).get("status").asString());assertEquals(1,db.queryForObject("SELECT count(*) FROM simulated_payment_refunds WHERE transaction_id IN (SELECT channel_transaction_id FROM payment_receipts WHERE attempt_id=?)",Integer.class,UUID.fromString(a)));}

 @Test void compensationRetriesStopAtEightAndAdminReverifyRestarts(){var f=fixture();String a=aid(attempt(f.u(),f.payment(),"WECHAT",key()));closeAttempt(f.u(),f.payment());cancel(f.u(),f.order().id(),0,key());providerSuccess(a,2500,"CNY");db.execute("CREATE FUNCTION reject_m43_provider_refund() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'TEST ONLY provider outage';END $$");db.execute("CREATE TRIGGER m43_provider_refund_fault BEFORE INSERT ON simulated_payment_refunds FOR EACH ROW EXECUTE FUNCTION reject_m43_provider_refund()");try{for(int i=0;i<8;i++){db.update("UPDATE payment_cases SET next_retry_at=clock_timestamp() WHERE payment_id=?",UUID.fromString(f.payment()));assertEquals(200,query(f.u(),f.payment()).status());}assertEquals("NEEDS_REVIEW",payment(f.u(),f.payment()).data().get("cases").get(0).get("status").asString());assertEquals(8,payment(f.u(),f.payment()).data().get("cases").get(0).get("attempt_count").asInt());query(f.u(),f.payment());assertEquals(8,payment(f.u(),f.payment()).data().get("cases").get(0).get("attempt_count").asInt());}finally{db.execute("DROP TRIGGER m43_provider_refund_fault ON simulated_payment_refunds");db.execute("DROP FUNCTION reject_m43_provider_refund()");}String proof=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'payment.requery',?,?)",crypto.hash(proof),adminSession,Timestamp.from(clock.instant().plusSeconds(300)),Timestamp.from(clock.instant()));var result=req("POST","/admin/payments/"+f.payment()+"/requery",null,admin,Map.of("Idempotency-Key",key(),"X-Reverify-Token",proof));assertEquals(200,result.status(),result.body().toString());assertEquals("REFUNDED",result.data().get("cases").get(0).get("status").asString());}

 @Test void missingReservedCouponRollsBackConfirmationAndCanRecover(){String o=ready(),u=consumer();shipping();String a=addressFor(u),i=addFor(u,o),c=coupon(u,"PLATFORM",100,1000);var q=quoteFor(u,i,a,List.of(c),false,key());var order=order(u,q.data().get("quote_id").asString(),key());String p=order.data().get("payment").get("id").asString(),attempt=aid(attempt(u,p,"WECHAT",key()));providerSuccess(attempt,2400,"CNY");db.update("UPDATE user_coupons SET status='AVAILABLE',reserved_order_id=NULL,reserved_from_status=NULL,reservation_expires_at=NULL,version=version+1 WHERE id=?",UUID.fromString(c));assertEquals(409,query(u,p).status());assertEquals(20,balance(o));assertEquals(2,reserved(o));assertEquals(0,db.queryForObject("SELECT count(*) FROM payment_receipts WHERE attempt_id=?",Integer.class,UUID.fromString(attempt)));db.update("UPDATE user_coupons SET status='RESERVED',reserved_order_id=?,reserved_from_status='AVAILABLE',version=version+1,reservation_expires_at=(SELECT expires_at FROM payments WHERE id=?) WHERE id=?",UUID.fromString(order.id()),UUID.fromString(p),UUID.fromString(c));assertEquals("SUCCEEDED",query(u,p).data().get("status").asString());assertEquals(18,balance(o));}
 @AfterAll static void finish()throws Exception{Files.writeString(Path.of("target/m43-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
}

