package cn.pawday;
import cn.pawday.identity.*;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(PetIntegrationTests.Fixtures.class)
class PetIntegrationTests {
 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);}
 @TestConfiguration static class Fixtures {@Bean @Primary Clock petClock(){return Clock.fixed(Instant.parse("2026-10-04T00:00:00Z"),ZoneId.of("Asia/Shanghai"));}}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired Clock clock;@LocalServerPort int port;
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
 String tokenA,tokenB,adminToken;UUID userA,adminPrincipal,adminSession;
 static final String CAT="10000000-0000-4000-8000-000000000001",SMALL="10000000-0000-4000-8000-000000000005";
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}
 String key(){return UUID.randomUUID().toString();}
 String consumer(){UUID user=UUID.randomUUID(),p=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",user);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,user);userA=user;return session(p);}
 String session(UUID p){UUID s=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'PET-IT',?,?,?)",s,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(900)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));adminSession=s;return t;}
 @BeforeEach void setup(){tokenB=consumer();tokenA=consumer();adminPrincipal=UUID.randomUUID();db.update("INSERT INTO identity_principal(id,realm,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,'ADMIN',?,?,?)",adminPrincipal,key(),"TEST-ONLY",crypto.encrypt("12345678901234567890".getBytes(java.nio.charset.StandardCharsets.UTF_8)));UUID role=UUID.randomUUID();db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,'ADMIN',?,'Pet test')",role,key());db.update("INSERT INTO role_permission(role_id,permission_id) SELECT ?,id FROM permission WHERE code IN ('pet.taxonomy.read','pet.taxonomy.write')",role);db.update("INSERT INTO principal_role(principal_id,role_id,realm) VALUES (?,?,'ADMIN')",adminPrincipal,role);adminToken=session(adminPrincipal);}
 String proof(){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,'pet.taxonomy.write',?,?)",crypto.hash(p),adminSession,Timestamp.from(clock.instant().plusSeconds(120)),Timestamp.from(clock.instant()));return p;}
 Response request(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response req(String method,String path,Object b,String token){return request(method,path,b,token,Map.of("Idempotency-Key",key()));}
 Map<String,Object> pet(){return new LinkedHashMap<>(Map.of("name","小爪","species_id",CAT,"sex","UNKNOWN","neutered_status","UNKNOWN","allergens",List.of(),"avoidance_notes",List.of()));}
 Response create(){var r=req("POST","/consumer/pets",pet(),tokenA);assertEquals(201,r.status(),r.body().toString());return r;}
 Response admin(String type,Map<String,Object> b){return request("POST","/admin/pet-taxonomy/"+type,b,adminToken,Map.of("Idempotency-Key",key(),"X-Reverify-Token",proof()));}
 Map<String,Object> stage(String code,Integer min,Integer max,boolean unknown,String unit){Map<String,Object>d=new LinkedHashMap<>();d.put("stage_code",code);d.put("display_name",code);d.put("min_age_value",min);d.put("max_age_value",max);d.put("age_unit",unit);d.put("is_unknown",unknown);return d;}
 Response publish(List<Map<String,Object>> stages,List<String> sources){return admin("life-stage-rules",Map.of("species_id",CAT,"source_refs",sources,"stages",stages));}
 @AfterAll static void close() throws Exception{Files.createDirectories(Path.of("target"));Files.writeString(Path.of("target/m31-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PG.close();}
 @Test void publicFiveCategoriesHaveUnknownStages(){var r=req("GET","/public/pet-taxonomy",null,null);assertEquals(200,r.status());assertTrue(r.data().size()>=5);for(String category:List.of("CAT","DOG","AQUATIC","BIRD","SMALL_PET"))assertTrue(r.data().valueStream().anyMatch(x->x.get("category").asString().equals(category)));}
 @Test void guestAndAdminCannotWriteConsumerPets(){assertEquals(401,req("POST","/consumer/pets",pet(),null).status());assertEquals(403,req("POST","/consumer/pets",pet(),adminToken).status());}
 @Test void createListAndUnknownAreRealDatabaseFacts(){var created=create();assertTrue(created.data().get("life_stage_unknown").asBoolean());assertEquals(userA,db.queryForObject("SELECT owner_user_id FROM pets WHERE id=?",UUID.class,UUID.fromString(created.id())));assertTrue(req("GET","/consumer/pets",null,tokenA).data().valueStream().anyMatch(x->x.get("id").asString().equals(created.id())));}
 @Test void foreignReadPatchDeleteAndWeightAreHidden(){String id=create().id();String path="/consumer/pets/"+id;assertEquals(404,req("GET",path,null,tokenB).status());assertEquals(404,request("PATCH",path,Map.of("name","偷改"),tokenB,Map.of("If-Match","\"0\"","Idempotency-Key",key())).status());assertEquals(404,request("DELETE",path,null,tokenB,Map.of("If-Match","\"0\"","Idempotency-Key",key())).status());assertEquals(404,req("GET",path+"/weight-records",null,tokenB).status());}
 @Test void createIdempotencyAndPayloadMismatch(){String k=key();var a=request("POST","/consumer/pets",pet(),tokenA,Map.of("Idempotency-Key",k));var b=request("POST","/consumer/pets",pet(),tokenA,Map.of("Idempotency-Key",k));assertEquals(a.id(),b.id());var changed=pet();changed.put("name","另一个");assertEquals(409,request("POST","/consumer/pets",changed,tokenA,Map.of("Idempotency-Key",k)).status());}
 @Test void concurrentUpdatesOnlyOneWins() throws Exception{String path="/consumer/pets/"+create().id();try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->request("PATCH",path,Map.of("name","甲"),tokenA,Map.of("If-Match","\"0\"","Idempotency-Key",key())));var b=pool.submit(()->request("PATCH",path,Map.of("name","乙"),tokenA,Map.of("If-Match","\"0\"","Idempotency-Key",key())));var codes=List.of(a.get().status(),b.get().status());assertTrue(codes.contains(200)&&codes.contains(409));}}
 @Test void missingVersionRejected(){assertEquals(400,req("PATCH","/consumer/pets/"+create().id(),Map.of("name","新"),tokenA).status());}
 @Test void forbiddenFieldsFutureBirthdayAndAmbiguousAgeRejected(){for(var pair:List.of(Map.entry("owner_user_id",(Object)key()),Map.entry("birth_date",(Object)"2027-01-01"),Map.entry("age_estimate_months",(Object)Integer.valueOf(-1)))){var p=pet();p.put(pair.getKey(),pair.getValue());assertEquals(400,req("POST","/consumer/pets",p,tokenA).status());}var p=pet();p.put("birth_date","2025-01-01");p.put("age_estimate_months",12);assertEquals(400,req("POST","/consumer/pets",p,tokenA).status());}
 @Test void breedMustBelongToSpecies(){var breed=admin("breeds",Map.of("species_id",SMALL,"name",key()));assertEquals(201,breed.status());var p=pet();p.put("breed_id",breed.id());assertEquals(422,req("POST","/consumer/pets",p,tokenA).status());}
 @Test void unknownAllergyRemainsUnknownAndDuplicateRejected(){var allergen=admin("allergens",Map.of("name",key()));assertEquals(201,allergen.status());var entry=Map.of("allergen_id",allergen.id(),"status","UNKNOWN","source","OWNER_OBSERVATION");var p=pet();p.put("allergens",List.of(entry));var created=req("POST","/consumer/pets",p,tokenA);assertEquals("UNKNOWN",created.data().get("allergens").get(0).get("status").asString());p.put("allergens",List.of(entry,entry));assertEquals(400,req("POST","/consumer/pets",p,tokenA).status());}
 @Test void deleteKeepsHistoryAndIsIdempotent(){String id=create().id();String k=key(),path="/consumer/pets/"+id;var headers=Map.of("If-Match","\"0\"","Idempotency-Key",k);assertEquals(200,request("DELETE",path,null,tokenA,headers).status());assertEquals(200,request("DELETE",path,null,tokenA,headers).status());assertEquals(404,req("GET",path,null,tokenA).status());assertEquals("DELETED",db.queryForObject("SELECT status FROM pets WHERE id=?",String.class,UUID.fromString(id)));}
 @Test void weightRetryAndBackdatedRecordDoNotOverwriteCurrent(){String id=create().id(),path="/consumer/pets/"+id+"/weight-records",k=key();var b=Map.of("weight_g",5000,"recorded_on","2026-10-04","source","OWNER_OBSERVATION");var headers=Map.of("If-Match","\"0\"","Idempotency-Key",k);var first=request("POST",path,b,tokenA,headers);assertEquals(201,first.status());assertEquals(first.id(),request("POST",path,b,tokenA,headers).id());assertEquals(201,request("POST",path,Map.of("weight_g",4000,"recorded_on","2026-10-01","source","OWNER_OBSERVATION"),tokenA,Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());assertEquals(5000L,db.queryForObject("SELECT current_weight_g FROM pets WHERE id=?",Long.class,UUID.fromString(id)));assertEquals(2,req("GET",path,null,tokenA).data().size());}
 @Test void taxonomyWriteRequiresPermissionAndFreshProof(){assertEquals(403,req("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),tokenA).status());assertEquals(403,req("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),adminToken).status());String p=proof();var headers=Map.of("X-Reverify-Token",p,"Idempotency-Key",key());assertEquals(201,request("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),adminToken,headers).status());assertEquals(403,request("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),adminToken,Map.of("X-Reverify-Token",p,"Idempotency-Key",key())).status());}
 @Test void dynamicSpeciesDoesNotInheritCatThresholds(){var r=admin("species",Map.of("name",key(),"parent_id",SMALL));assertEquals(201,r.status());var p=pet();p.put("species_id",r.id());p.put("birth_date","2025-01-01");assertTrue(req("POST","/consumer/pets",p,tokenA).data().get("life_stage_unknown").asBoolean());}
 @Test void sourcedCalendarStagesAreVersionedAndImmutable(){var rule=publish(List.of(stage("JUNIOR",0,12,false,"MONTH"),stage("ADULT",12,null,false,"MONTH"),stage("UNKNOWN",null,null,true,"MONTH")),List.of("TEST-ONLY boundary fixture; not production veterinary guidance"));assertEquals(201,rule.status(),rule.body().toString());var p=pet();p.put("birth_date","2025-10-04");var created=req("POST","/consumer/pets",p,tokenA);assertFalse(created.data().get("life_stage_unknown").asBoolean());assertEquals("ADULT",db.queryForObject("SELECT stage_code FROM pet_life_stage_definitions WHERE id=?",String.class,UUID.fromString(created.data().get("life_stage_id").asString())));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE pet_life_stage_definitions SET display_name='overwrite' WHERE rule_version_id=?",UUID.fromString(rule.id())));var next=publish(List.of(stage("UNKNOWN",null,null,true,"MONTH")),List.of());assertEquals(201,next.status());assertEquals("RETIRED",db.queryForObject("SELECT status FROM pet_life_stage_rule_versions WHERE id=?",String.class,UUID.fromString(rule.id())));}
 @Test void overlappingMixedUnitAndUnsourcedRulesRejected(){assertEquals(400,publish(List.of(stage("A",0,20,false,"MONTH"),stage("B",10,null,false,"MONTH"),stage("UNKNOWN",null,null,true,"MONTH")),List.of("TEST-ONLY")).status());assertEquals(400,publish(List.of(stage("A",0,20,false,"MONTH"),stage("B",20,null,false,"YEAR"),stage("UNKNOWN",null,null,true,"MONTH")),List.of("TEST-ONLY")).status());assertEquals(400,publish(List.of(stage("A",0,null,false,"MONTH"),stage("UNKNOWN",null,null,true,"MONTH")),List.of()).status());}
 @Test void taxonomyRetirementKeepsHistoricalPetReference(){var species=admin("species",Map.of("name",key(),"parent_id",SMALL));var p=pet();p.put("species_id",species.id());var created=req("POST","/consumer/pets",p,tokenA);assertEquals(200,request("POST","/admin/pet-taxonomy/species/"+species.id()+"/retire",null,adminToken,Map.of("Idempotency-Key",key(),"X-Reverify-Token",proof())).status());assertEquals(200,req("GET","/consumer/pets/"+created.id(),null,tokenA).status());assertEquals(422,req("POST","/consumer/pets",p,tokenA).status());}
 @Test void successfulMutationsHaveAuditWithoutPrivateProfile(){String id=create().id();var rows=db.queryForList("SELECT after_json::text FROM audit_event WHERE object_id=? AND action='pet.create'",id);assertEquals(1,rows.size());assertFalse(rows.getFirst().get("after_json").toString().contains("小爪"));}
 @Test void listsUseScopedPaginationWithoutDuplicates(){create();create();create();var first=req("GET","/consumer/pets?limit=2",null,tokenA);assertEquals(2,first.data().size());assertTrue(first.body().get("page").get("has_more").asBoolean());String cursor=first.body().get("page").get("next_cursor").asString();var next=req("GET","/consumer/pets?limit=2&cursor="+cursor,null,tokenA);assertEquals(1,next.data().size());assertFalse(next.body().get("page").get("has_more").asBoolean());assertEquals(0,req("GET","/consumer/pets?limit=2",null,tokenB).data().size());assertEquals(400,req("GET","/consumer/pets?limit=abc",null,tokenA).status());}
 @Test void birthdayUsesCalendarYearsAndEstimatesStayUnknown(){assertEquals(201,publish(List.of(stage("FIRST_YEAR",0,1,false,"YEAR"),stage("OLDER",1,null,false,"YEAR"),stage("UNKNOWN",null,null,true,"YEAR")),List.of("TEST-ONLY year boundary fixture")).status());var p=pet();p.put("birth_date","2025-10-05");var before=req("POST","/consumer/pets",p,tokenA);assertEquals("FIRST_YEAR",db.queryForObject("SELECT stage_code FROM pet_life_stage_definitions WHERE id=?",String.class,UUID.fromString(before.data().get("life_stage_id").asString())));p.put("birth_date","2025-10-04");var at=req("POST","/consumer/pets",p,tokenA);assertEquals("OLDER",db.queryForObject("SELECT stage_code FROM pet_life_stage_definitions WHERE id=?",String.class,UUID.fromString(at.data().get("life_stage_id").asString())));p.remove("birth_date");p.put("age_estimate_months",24);assertTrue(req("POST","/consumer/pets",p,tokenA).data().get("life_stage_unknown").asBoolean());}
 @Test void foreignWeightWriteIsHiddenAndStaleVersionRejected(){String path="/consumer/pets/"+create().id()+"/weight-records";var b=Map.of("weight_g",1000,"recorded_on","2026-10-04","source","OWNER_OBSERVATION");assertEquals(404,request("POST",path,b,tokenB,Map.of("If-Match","\"0\"","Idempotency-Key",key())).status());assertEquals(409,request("POST",path,b,tokenA,Map.of("If-Match","\"1\"","Idempotency-Key",key())).status());}
 @Test void auditFailureRollsBackPetAndIdempotencyCommand(){int before=db.queryForObject("SELECT count(*) FROM pets",Integer.class);String k=key();db.execute("CREATE FUNCTION fail_pet_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='pet.create' THEN RAISE EXCEPTION 'TEST_ONLY audit failure'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_pet_audit BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION fail_pet_audit()");try{assertEquals(503,request("POST","/consumer/pets",pet(),tokenA,Map.of("Idempotency-Key",k)).status());assertEquals(before,db.queryForObject("SELECT count(*) FROM pets",Integer.class));assertEquals(0,db.queryForObject("SELECT count(*) FROM identity_command WHERE idempotency_key=?",Integer.class,k));}finally{db.execute("DROP TRIGGER test_pet_audit ON audit_event");db.execute("DROP FUNCTION fail_pet_audit()");}assertEquals(201,request("POST","/consumer/pets",pet(),tokenA,Map.of("Idempotency-Key",k)).status());}
 @Test void wrongActionAndExpiredReverifyAreRejected(){String p=proof();db.update("UPDATE reverify_grant SET action='search.rebuild' WHERE token_hash=?",crypto.hash(p));assertEquals(403,request("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),adminToken,Map.of("Idempotency-Key",key(),"X-Reverify-Token",p)).status());String expired=proof();db.update("UPDATE reverify_grant SET expires_at=? WHERE token_hash=?",Timestamp.from(clock.instant().minusSeconds(1)),crypto.hash(expired));assertEquals(403,request("POST","/admin/pet-taxonomy/allergens",Map.of("name",key()),adminToken,Map.of("Idempotency-Key",key(),"X-Reverify-Token",expired)).status());}
 @Test void publishedStageCannotMoveToAnotherDraft(){var rule=publish(List.of(stage("UNKNOWN",null,null,true,"MONTH")),List.of());UUID draft=UUID.randomUUID();db.update("INSERT INTO pet_life_stage_rule_versions(id,species_id,version_no,status,source_refs) VALUES (?,?::uuid,999,'DRAFT','[]')",draft,CAT);assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE pet_life_stage_definitions SET rule_version_id=? WHERE rule_version_id=?",draft,UUID.fromString(rule.id())));}
}
