package cn.pawday;

import cn.pawday.identity.*;
import cn.pawday.outbox.*;
import cn.pawday.search.*;
import cn.pawday.audit.AuditWriter;
import com.rabbitmq.client.*;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.awaitility.Awaitility.await;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.amqp.rabbit.core.RabbitAdmin;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** Actual PostgreSQL, RabbitMQ and OpenSearch. Network fault injection does not simulate a service. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(SearchInfrastructureIT.Fixtures.class)
class SearchInfrastructureIT {
    static final EmbeddedPostgres PG;static final TcpAvailabilityProxy PROXY;
    static final String ENDPOINT=Objects.requireNonNull(System.getenv("PAWDAY_IT_OPENSEARCH_URL"),"Real isolated OpenSearch endpoint is mandatory");
    static final String HOST=env("PAWDAY_IT_RABBIT_HOST","127.0.0.1"),USER=env("PAWDAY_IT_RABBIT_USER","pawday_it"),PASSWORD=env("PAWDAY_IT_RABBIT_PASSWORD","TEST_ONLY_m22_broker");
    static final int RABBIT_PORT=Integer.parseInt(env("PAWDAY_IT_RABBIT_PORT","5672"));
    static String env(String name,String fallback){return System.getenv().getOrDefault(name,fallback);}
    static {try{URI endpoint=URI.create(ENDPOINT);if(!Set.of("127.0.0.1","localhost").contains(endpoint.getHost()))throw new IllegalArgumentException("Only isolated loopback search acceptance endpoint allowed");PG=EmbeddedPostgres.builder().setPort(0).start();PROXY=new TcpAvailabilityProxy(endpoint.getHost(),endpoint.getPort());}catch(Exception e){throw new ExceptionInInitializerError(e);}}
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){
        r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
        r.add("spring.rabbitmq.host",()->HOST);r.add("spring.rabbitmq.port",()->RABBIT_PORT);r.add("spring.rabbitmq.username",()->USER);r.add("spring.rabbitmq.password",()->PASSWORD);r.add("management.health.redis.enabled",()->false);
        r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.consumers-enabled",()->false);r.add("pawday.search.workers-enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);
        r.add("pawday.search.url",()->"http://127.0.0.1:"+PROXY.port());r.add("pawday.search.timeout-ms",()->800);r.add("pawday.search.retry-max-attempts",()->3);r.add("pawday.search.retry-base-ms",()->50);r.add("pawday.search.lease-ms",()->5000);
        r.add("pawday.outbox.max-attempts",()->3);r.add("pawday.outbox.retry-base-ms",()->50);r.add("pawday.outbox.retry-max-ms",()->200);r.add("management.endpoint.health.show-details",()->"always");
    }
    static class TestClock extends Clock{volatile Instant value=Instant.now();public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return value;}}
    @TestConfiguration static class Fixtures{@Bean @Primary TestClock searchClock(){return new TestClock();}}
    @Autowired JdbcTemplate db;@Autowired TransactionTemplate tx;@Autowired CatalogSearchSource source;@Autowired OpenSearchClient os;@Autowired IndexBootstrap bootstrap;@Autowired AliasManager aliases;@Autowired SearchSyncWorker sync;@Autowired SearchRebuildWorker rebuild;@Autowired SearchInboxConsumer inbox;@Autowired SearchRabbitListener listener;@Autowired OutboxPublisher publisher;@Autowired RabbitAdmin rabbitAdmin;@Autowired Crypto crypto;@Autowired TestClock clock;@Autowired PasswordEncoder passwords;
    @LocalServerPort int port;
    Connection connection;Channel channel;UUID adminId,readerId;String adminToken,readerToken;static String passwordHash;static final String STAFF_PASSWORD="TEST_ONLY_M23_admin_password";static final byte[] MFA="12345678901234567890".getBytes(StandardCharsets.US_ASCII);
    final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
    static final List<Map<String,Object>> SAMPLES=new CopyOnWriteArrayList<>();
    @BeforeEach void setup() throws Exception {
        PROXY.recover();assertEquals("pawday-m23-it",os.health().get("cluster_name"),"Search gate may only modify the explicitly isolated acceptance cluster");os.request("DELETE","/pawday-product-v1-*",null,404);
        db.execute("ALTER TABLE audit_event DISABLE TRIGGER audit_event_no_truncate");
        try{db.execute("TRUNCATE search_admin_command,search_sync_task,search_rebuild_job,search_index_version,catalog_search_source,outbox_replay_command,processed_event,sms_delivery,outbox_event,identity_command,reverify_grant,auth_refresh_token,auth_session,otp_challenge,auth_rate_bucket,principal_store_scope,principal_role,identity_principal,merchant_store,merchant,app_user,role_permission,role,audit_event CASCADE");}finally{db.execute("ALTER TABLE audit_event ENABLE TRIGGER audit_event_no_truncate");}
        bootstrap.initialize();clock.value=Instant.now();
        var factory=new ConnectionFactory();factory.setHost(HOST);factory.setPort(RABBIT_PORT);factory.setUsername(USER);factory.setPassword(PASSWORD);connection=factory.newConnection();channel=connection.createChannel();rabbitAdmin.initialize();channel.queuePurge(RabbitTopology.SEARCH_QUEUE);channel.queuePurge(RabbitTopology.DLQ);channel.queuePurge(RabbitTopology.QUEUE);
        if(passwordHash==null)passwordHash=passwords.encode(STAFF_PASSWORD);adminId=principal("m23-admin",List.of("search.read","search.manage","outbox.replay"));readerId=principal("m23-reader",List.of("search.read"));adminToken=session(adminId);readerToken=session(readerId);
    }
    UUID principal(String name,List<String> permissions){UUID id=UUID.randomUUID(),role=UUID.randomUUID();db.update("INSERT INTO identity_principal(id,realm,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,'ADMIN',?,?,?)",id,name,passwordHash,crypto.encrypt(MFA));db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,'ADMIN',?,?)",role,name,name);for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,'ADMIN')",id,role);return id;}
    String session(UUID principal){UUID id=UUID.randomUUID();String token=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'SEARCH-TEST',?,?,?)",id,principal,crypto.hash(token),Timestamp.from(clock.instant().plusSeconds(3600)),Timestamp.from(clock.instant().plusSeconds(2592000)),Timestamp.from(clock.instant()));return token;}
    record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}}
    Response call(String method,String path,Object body,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(15));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(body==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var data=json.readTree(response.body());var safe=json.readTree(response.body());if(safe.has("data")&&safe.get("data").has("reverify_token"))((tools.jackson.databind.node.ObjectNode)safe.get("data")).put("reverify_token","A".repeat(43));SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",safe));return new Response(response.statusCode(),data);}catch(Exception e){throw new AssertionError(path,e);}}
    Response call(String method,String path,Object body,String token){return call(method,path,body,token,Map.of());}
    String proof(String action){clock.value=clock.value.plusSeconds(60);var result=call("POST","/admin/auth/reverify",Map.of("action",action,"password",STAFF_PASSWORD,"totp_code",crypto.totp(MFA,clock.instant().getEpochSecond()/30)),adminToken);assertEquals(200,result.status(),result.body().toString());return result.data().get("reverify_token").asString();}
    Response command(String kind,String reason,String proof,String key){return call("POST","/admin/operations/search/"+kind,Map.of("reason_code",reason),adminToken,Map.of("X-Reverify-Token",proof,"Idempotency-Key",key));}
    CatalogSearchSource.Product product(UUID sku,long price){return new CatalogSearchSource.Product(UUID.nameUUIDFromBytes("TEST SPU".getBytes()),sku,"TEST Brand","CAT","ADULT","DRY",List.of("CHICKEN"),price,true,2,Instant.parse("2026-10-03T00:00:00Z"));}
    CatalogSearchSource.Change change(UUID sku,long price,String type){return source.change(product(sku,price),false,type,UUID.randomUUID().toString());}
    GetResponse next(String queue) throws Exception {final GetResponse[] value={null};await().atMost(Duration.ofSeconds(5)).until(()->{value[0]=channel.basicGet(queue,false);return value[0]!=null;});return value[0];}
    void receive() throws Exception {var value=next(RabbitTopology.SEARCH_QUEUE);var p=new org.springframework.amqp.core.MessageProperties();p.setMessageId(value.getProps().getMessageId());p.setDeliveryTag(value.getEnvelope().getDeliveryTag());listener.receive(new org.springframework.amqp.core.Message(value.getBody(),p),channel);}
    void pump() throws Exception {for(int i=0;i<40&&publisher.publishOne();i++){}while(channel.queueDeclarePassive(RabbitTopology.SEARCH_QUEUE).getMessageCount()>0)receive();while(sync.runOne()){} }
    Map<String,Object> doc(UUID sku){os.refresh(aliases.current());return os.documents(aliases.current()).get(sku);}
    void syncChange(UUID sku,long price) throws Exception {change(sku,price,"CatalogPublished");pump();assertNotNull(doc(sku));}
    @AfterEach void close() throws Exception {PROXY.recover();if(channel!=null&&channel.isOpen())channel.close();if(connection!=null&&connection.isOpen())connection.close();}
    @AfterAll static void finish() throws Exception {Files.writeString(Path.of("target/m23-search-contract-samples.json"),JsonMapper.builder().build().writeValueAsString(SAMPLES));PROXY.close();PG.close();}

    @Test void realMappingVersionAliasesAndHealthRepeatInitialization() throws Exception {assertEquals(IndexVersion.INITIAL,bootstrap.initialize());assertEquals(IndexVersion.INITIAL,bootstrap.initialize());assertEquals(1,db.queryForObject("SELECT count(*) FROM search_index_version WHERE status='ACTIVE'",Integer.class));IndexVersion.validate(os,IndexVersion.INITIAL);assertEquals(IndexVersion.INITIAL,aliases.target(IndexVersion.READ_ALIAS));assertEquals(IndexVersion.INITIAL,aliases.target(IndexVersion.WRITE_ALIAS));var result=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/actuator/health/search")).GET().build(),HttpResponse.BodyHandlers.ofString());assertEquals(200,result.statusCode(),result.body());}
    @Test void sourceAndOutboxRollbackTogether(){UUID sku=UUID.randomUUID();assertThrows(IllegalStateException.class,()->tx.executeWithoutResult(s->{change(sku,100,"CatalogPublished");throw new IllegalStateException("business rollback");}));assertEquals(0,db.queryForObject("SELECT count(*) FROM catalog_search_source",Integer.class));assertEquals(0,db.queryForObject("SELECT count(*) FROM outbox_event",Integer.class));}
    @Test void allThreeSourceEventsPublishAndDuplicateRealDeliveryProducesOneTask() throws Exception {UUID sku=UUID.randomUUID();var first=change(sku,100,"CatalogPublished");pump();change(sku,200,"OfferChanged");pump();change(sku,300,"InventoryAvailabilityChanged");pump();assertEquals(300,((Number)doc(sku).get("price_min_fen")).intValue());assertEquals(3,db.queryForObject("SELECT count(*) FROM processed_event WHERE consumer=?",Integer.class,SearchInboxConsumer.CONSUMER));assertEquals(1,db.queryForObject("SELECT count(*) FROM search_sync_task",Integer.class));var row=db.queryForMap("SELECT * FROM outbox_event WHERE id=?",first.event_id());var event=new EventEnvelope(first.event_id(),"CatalogPublished",1,"CATALOG_SKU",sku.toString(),null,1,0,Map.of("sku_id",sku.toString(),"revision",1));channel.confirmSelect();var props=new AMQP.BasicProperties.Builder().messageId(first.event_id().toString()).deliveryMode(2).build();for(int i=0;i<2;i++)channel.basicPublish(RabbitTopology.EXCHANGE,"CatalogPublished",props,json.writeValueAsBytes(event));channel.waitForConfirmsOrDie(3000);receive();receive();assertEquals(1,db.queryForObject("SELECT count(*) FROM search_sync_task",Integer.class));assertEquals(300,((Number)doc(sku).get("price_min_fen")).intValue());}
    @Test void commitBeforeAckCrashRedeliversAndSearchEffectStaysSingle() throws Exception {UUID sku=UUID.randomUUID();change(sku,100,"CatalogPublished");publisher.publishOne();var message=next(RabbitTopology.SEARCH_QUEUE);inbox.process(json.readValue(message.getBody(),EventEnvelope.class));channel.close();channel=connection.createChannel();receive();assertEquals(1,db.queryForObject("SELECT count(*) FROM processed_event WHERE consumer=?",Integer.class,SearchInboxConsumer.CONSUMER));assertTrue(sync.runOne());os.refresh(aliases.current());assertEquals(1,os.documents(aliases.current()).size());}
    @Test void newerRevisionAndTombstoneCannotBeOverwrittenByOldWorkers() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);change(sku,200,"OfferChanged");pump();os.put(aliases.current(),sku,1,product(sku,1).document(1,false));assertEquals(200,((Number)doc(sku).get("price_min_fen")).intValue());source.change(product(sku,200),true,"CatalogPublished",null);pump();os.put(aliases.current(),sku,1,product(sku,1).document(1,false));assertEquals(true,doc(sku).get("deleted"));var result=os.request("GET","/"+IndexVersion.READ_ALIAS+"/_count",null);assertEquals(0,((Number)result.get("count")).intValue());}
    @Test void searchDownDoesNotRollbackPgAndRecoversDurableTask() throws Exception {UUID sku=UUID.randomUUID();PROXY.unavailable();var event=change(sku,1200,"CatalogPublished");publisher.publishOne();receive();assertEquals(1200,((Number)json.readValue(db.queryForObject("SELECT document::text FROM catalog_search_source WHERE sku_id=?",String.class,sku),Map.class).get("price_min_fen")).intValue());assertEquals("PUBLISHED",db.queryForObject("SELECT status FROM outbox_event WHERE id=?",String.class,event.event_id()));assertTrue(sync.runOne());assertEquals("FAILED_RETRYABLE",db.queryForObject("SELECT status FROM search_sync_task",String.class));var down=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/actuator/health/search")).GET().build(),HttpResponse.BodyHandlers.ofString());assertEquals(503,down.statusCode());PROXY.recover();await().atMost(Duration.ofSeconds(5)).until(()->{sync.runOne();return db.queryForObject("SELECT status FROM search_sync_task",String.class).equals("APPLIED");});assertEquals(1200,((Number)doc(sku).get("price_min_fen")).intValue());}
    @Test void boundedSearchFailuresDeadLetterAndControlledOutboxReplay() throws Exception {UUID sku=UUID.randomUUID();var event=change(sku,100,"CatalogPublished");publisher.publishOne();receive();PROXY.unavailable();await().atMost(Duration.ofSeconds(6)).until(()->{sync.runOne();return db.queryForObject("SELECT status FROM search_sync_task",String.class).equals("DEAD");});assertEquals(3,db.queryForObject("SELECT attempt_count FROM search_sync_task",Integer.class));PROXY.recover();publisher.publishOne();var dead=next(RabbitTopology.DLQ);assertTrue(new String(dead.getBody()).contains("SEARCH_SYNC"));channel.basicAck(dead.getEnvelope().getDeliveryTag(),false);var receipt=call("POST","/admin/operations/outbox/"+event.event_id()+"/replay",Map.of("expected_generation",0,"reason_code","SEARCH_RECOVERED"),adminToken,Map.of("Idempotency-Key","search-outbox-replay-key","X-Reverify-Token",proof("outbox.replay")));assertEquals(200,receipt.status(),receipt.body().toString());pump();assertEquals(1,db.queryForObject("SELECT count(*) FROM processed_event WHERE consumer=? AND status='PROCESSED'",Integer.class,SearchInboxConsumer.CONSUMER));assertEquals(100,((Number)doc(sku).get("price_min_fen")).intValue());}
    @Test void fullRebuildNewIndexValidatesAndSwitchesBothAliases() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);String old=aliases.current();var receipt=command("rebuild","INDEX_REBUILD",proof("search.rebuild"),"full-rebuild-command-key");assertEquals(202,receipt.status(),receipt.body().toString());pump();assertTrue(rebuild.runOne());String active=aliases.current();assertNotEquals(old,active);assertEquals(active,aliases.target(IndexVersion.WRITE_ALIAS));assertEquals("COMPLETED",db.queryForObject("SELECT status FROM search_rebuild_job",String.class));assertEquals(1,db.queryForObject("SELECT validated_count FROM search_rebuild_job",Integer.class));assertEquals(100,((Number)doc(sku).get("price_min_fen")).intValue());assertFalse(os.documents(old).isEmpty());}
    @Test void rebuildFailureKeepsOldIndexAndCanRetryAfterRecovery() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);String old=aliases.current();command("rebuild","FAILURE_REBUILD",proof("search.rebuild"),"failed-rebuild-command-key");pump();PROXY.unavailable();assertTrue(rebuild.runOne());assertEquals("FAILED_RETRYABLE",db.queryForObject("SELECT status FROM search_rebuild_job",String.class));PROXY.recover();assertEquals(old,aliases.current());assertEquals(100,((Number)os.documents(old).get(sku).get("price_min_fen")).intValue());await().atMost(Duration.ofSeconds(8)).until(()->{rebuild.runOne();return db.queryForObject("SELECT status FROM search_rebuild_job",String.class).equals("COMPLETED");});assertNotEquals(old,aliases.current());}
    @Test void lostAliasResponseRecoveryFinalizesWithoutRebuildingOldIndex() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);command("rebuild","ALIAS_RECOVERY",proof("search.rebuild"),"alias-recovery-command-key");pump();var claim=rebuild.claim().orElseThrow();IndexVersion.ensure(os,claim.index());db.update("INSERT INTO search_index_version(index_name,schema_version,status) VALUES (?,1,'BUILDING')",claim.index());os.put(claim.index(),sku,1,product(sku,100).document(1,false));aliases.switchTo(claim.index());db.update("UPDATE search_rebuild_job SET lease_expires_at=clock_timestamp()-interval '1 second'");assertTrue(rebuild.runOne());assertEquals("COMPLETED",db.queryForObject("SELECT status FROM search_rebuild_job",String.class));assertEquals(claim.index(),db.queryForObject("SELECT index_name FROM search_index_version WHERE status='ACTIVE'",String.class));}
    @Test void reconciliationRepairsMissingDocumentAndExternalDrift() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);os.request("DELETE","/"+aliases.current()+"/_doc/"+sku,null);var receipt=command("reconcile","MISSING_DOCUMENT",proof("search.reconcile"),"reconcile-missing-command-key");assertEquals(202,receipt.status());assertEquals(1,receipt.data().get("affected_count").asInt());pump();assertTrue(rebuild.runOne());assertEquals(100,((Number)doc(sku).get("price_min_fen")).intValue());}
    @Test void reconciliationOrphanUsesNewIndexInsteadOfDeletingLiveIndex() throws Exception {UUID sku=UUID.randomUUID();syncChange(sku,100);String old=aliases.current();os.put(old,UUID.randomUUID(),1,product(UUID.randomUUID(),999).document(1,false));var receipt=command("reconcile","UNKNOWN_DOCUMENT",proof("search.reconcile"),"reconcile-orphan-command-key");assertEquals(202,receipt.status());assertEquals("RECONCILIATION_REBUILD",receipt.data().get("kind").asString());pump();assertTrue(rebuild.runOne());assertNotEquals(old,aliases.current());assertEquals(1,os.documents(aliases.current()).size());assertEquals(2,os.documents(old).size());}
    @Test void operationsRequireRealmPermissionActionProofAndAreIdempotent() throws Exception {assertEquals(401,call("GET","/admin/operations/search",null,null).status());assertEquals(200,call("GET","/admin/operations/search",null,readerToken).status());assertEquals(403,call("POST","/admin/operations/search/rebuild",Map.of("reason_code","REBUILD_TEST"),readerToken).status());assertEquals(403,call("POST","/admin/operations/search/rebuild",Map.of("reason_code","REBUILD_TEST"),adminToken,Map.of("Idempotency-Key","requires-new-proof-key")).status());String proof=proof("search.retry");assertEquals(403,command("rebuild","WRONG_ACTION",proof,"wrong-action-command-key").status());String correct=proof("search.rebuild");var a=command("rebuild","IDEMPOTENT_REBUILD",correct,"idem-rebuild-command-key");var b=command("rebuild","IDEMPOTENT_REBUILD",correct,"idem-rebuild-command-key");assertEquals(202,a.status());assertEquals(a.data(),b.data());assertEquals(409,command("rebuild","DIFFERENT_PAYLOAD",correct,"idem-rebuild-command-key").status());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='search.rebuild'",Integer.class));}
    @Test void administrativeAuditFailureRollsBackProofCommandAndEvent(){String proof=proof("search.rebuild");db.execute("CREATE FUNCTION fail_search_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='search.rebuild' THEN RAISE EXCEPTION 'TEST audit unavailable'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER fail_search_audit BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION fail_search_audit()");try{assertEquals(503,command("rebuild","AUDIT_ROLLBACK",proof,"audit-rebuild-command-key").status());assertEquals(0,db.queryForObject("SELECT count(*) FROM search_admin_command",Integer.class));assertEquals(0,db.queryForObject("SELECT count(*) FROM outbox_event",Integer.class));assertNull(db.queryForObject("SELECT used_at FROM reverify_grant WHERE token_hash=?",Timestamp.class,crypto.hash(proof)));}finally{db.execute("DROP TRIGGER fail_search_audit ON audit_event");db.execute("DROP FUNCTION fail_search_audit()");}assertEquals(202,command("rebuild","AUDIT_ROLLBACK",proof,"audit-rebuild-command-key").status());}
    @Test void automaticScheduledOutboxRabbitSearchChainUsesRealServices() throws Exception {
        try(var live=new org.springframework.boot.builder.SpringApplicationBuilder(PawdayApplication.class,Fixtures.class).run(
            "--server.port=0","--spring.datasource.url="+PG.getJdbcUrl("postgres","postgres"),"--spring.datasource.username=postgres","--spring.datasource.password=postgres",
            "--pawday.auth.secret-key=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","--spring.rabbitmq.host="+HOST,"--spring.rabbitmq.port="+RABBIT_PORT,"--spring.rabbitmq.username="+USER,"--spring.rabbitmq.password="+PASSWORD,
            "--pawday.search.url="+ENDPOINT,"--pawday.search.workers-enabled=true","--pawday.search.consumers-enabled=true","--pawday.search.poll-ms=50",
            "--pawday.outbox.workers-enabled=true","--pawday.outbox.consumer-enabled=false","--pawday.outbox.poll-ms=50","--pawday.storage.cleanup-enabled=false","--management.health.redis.enabled=false")) {
            UUID sku=UUID.randomUUID();var change=live.getBean(CatalogSearchSource.class).change(product(sku,5500),false,"CatalogPublished",UUID.randomUUID().toString());
            await().atMost(Duration.ofSeconds(15)).ignoreExceptions().until(()->db.queryForObject("SELECT count(*) FROM search_sync_task WHERE source_id=? AND status='APPLIED'",Integer.class,sku)==1);
            assertEquals("PUBLISHED",db.queryForObject("SELECT status FROM outbox_event WHERE id=?",String.class,change.event_id()));assertEquals(1,db.queryForObject("SELECT count(*) FROM processed_event WHERE consumer=? AND event_id=? AND status='PROCESSED'",Integer.class,SearchInboxConsumer.CONSUMER,change.event_id()));assertEquals(5500,((Number)doc(sku).get("price_min_fen")).intValue());
        }
    }
    @Test void concurrentSyncWorkersClaimDifferentRowsAndExpiredClaimIsFenced() throws Exception {
        UUID a=UUID.randomUUID(),b=UUID.randomUUID();change(a,100,"CatalogPublished");change(b,200,"CatalogPublished");while(publisher.publishOne()){}receive();receive();
        try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var one=pool.submit(()->sync.claim(null).orElseThrow());var two=pool.submit(()->sync.claim(null).orElseThrow());var first=one.get();var second=two.get();assertNotEquals(first.sourceId(),second.sourceId());
            db.update("UPDATE search_sync_task SET lease_expires_at=clock_timestamp()-interval '1 second' WHERE source_id=?",first.sourceId());assertFalse(sync.complete(first));os.put(second.index(),second.sourceId(),second.revision(),second.document());assertTrue(sync.complete(second));
        }
        await().atMost(Duration.ofSeconds(5)).until(()->{sync.runOne();return db.queryForObject("SELECT count(*) FROM search_sync_task WHERE status='APPLIED'",Integer.class)==2;});os.refresh(aliases.current());assertEquals(2,os.documents(aliases.current()).size());
    }
    @Test void failedItemRetryRequiresProofAndRestoresDeadTask() throws Exception {
        UUID sku=UUID.randomUUID();change(sku,700,"CatalogPublished");publisher.publishOne();receive();PROXY.unavailable();await().atMost(Duration.ofSeconds(6)).until(()->{sync.runOne();return db.queryForObject("SELECT status FROM search_sync_task",String.class).equals("DEAD");});PROXY.recover();
        var receipt=command("retry","FAILED_ITEM_RECOVERED",proof("search.retry"),"retry-failed-search-key");assertEquals(202,receipt.status());assertEquals(1,receipt.data().get("affected_count").asInt());assertTrue(sync.runOne());assertEquals(700,((Number)doc(sku).get("price_min_fen")).intValue());
    }
    @Test void rebuildingTargetReceivesChangesThatOccurAfterSnapshot() throws Exception {
        UUID sku=UUID.randomUUID();syncChange(sku,100);command("rebuild","CONCURRENT_CHANGE",proof("search.rebuild"),"concurrent-rebuild-key");pump();var job=rebuild.claim().orElseThrow();IndexVersion.ensure(os,job.index());db.update("INSERT INTO search_index_version(index_name,schema_version,status) VALUES (?,1,'BUILDING')",job.index());
        os.put(job.index(),sku,1,product(sku,100).document(1,false));change(sku,999,"OfferChanged");pump();assertEquals(2,db.queryForObject("SELECT count(*) FROM search_sync_task WHERE source_id=? AND completed_revision=2",Integer.class,sku));
        db.update("UPDATE search_rebuild_job SET lease_expires_at=clock_timestamp()-interval '1 second'");assertTrue(rebuild.runOne());assertEquals("COMPLETED",db.queryForObject("SELECT status FROM search_rebuild_job",String.class));assertEquals(999,((Number)doc(sku).get("price_min_fen")).intValue());
    }

    @Test void partiallyBuiltPoisonIndexCannotReplaceHealthyAliasesAndRetryCompletes() throws Exception {
        UUID sku=UUID.randomUUID();syncChange(sku,100);String old=aliases.current();command("rebuild","POISON_REBUILD",proof("search.rebuild"),"poison-partial-rebuild-key");pump();
        db.update("UPDATE catalog_search_source SET document=jsonb_set(document,'{price_min_fen}','\"not_money\"'::jsonb) WHERE sku_id=?",sku);
        assertTrue(rebuild.runOne());String target=db.queryForObject("SELECT target_index FROM search_rebuild_job",String.class);assertNotEquals(old,target);IndexVersion.validate(os,target);assertEquals(old,aliases.current());assertEquals(100,((Number)os.documents(old).get(sku).get("price_min_fen")).intValue());
        await().atMost(Duration.ofSeconds(8)).until(()->{rebuild.runOne();return db.queryForObject("SELECT status FROM search_rebuild_job",String.class).equals("DEAD");});assertEquals(old,aliases.current());assertEquals(old,aliases.target(IndexVersion.WRITE_ALIAS));
        db.update("UPDATE catalog_search_source SET document=jsonb_set(document,'{price_min_fen}','100'::jsonb) WHERE sku_id=?",sku);
        var retry=command("retry","POISON_REPAIRED",proof("search.retry"),"poison-repaired-retry-key");assertEquals(202,retry.status());await().atMost(Duration.ofSeconds(8)).until(()->{rebuild.runOne();return db.queryForObject("SELECT status FROM search_rebuild_job",String.class).equals("COMPLETED");});assertEquals(target,aliases.current());assertEquals(100,((Number)doc(sku).get("price_min_fen")).intValue());
    }

}
