package cn.pawday;
import cn.pawday.identity.*;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.URI;
import java.net.http.*;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
class SupportMessagesIntegrationTests {
 static final EmbeddedPostgres PG;
 static {try{PG=EmbeddedPostgres.builder().setPort(0).start();}catch(Exception e){throw new ExceptionInInitializerError(e);}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->PG.getJdbcUrl("postgres","postgres"));r.add("pawday.storage.local-root",()->System.getProperty("java.io.tmpdir")+"/pawday-m53-"+PG.getPort());r.add("spring.datasource.username",()->"postgres");r.add("spring.datasource.password",()->"postgres");r.add("pawday.auth.secret-key",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");r.add("management.health.redis.enabled",()->false);r.add("management.health.rabbit.enabled",()->false);r.add("pawday.outbox.workers-enabled",()->false);r.add("pawday.outbox.consumer-enabled",()->false);r.add("pawday.search.enabled",()->false);r.add("pawday.storage.cleanup-enabled",()->false);r.add("pawday.checkout.expiry-enabled",()->false);r.add("pawday.ordering.expiry-enabled",()->false);r.add("pawday.payment.simulation-enabled",()->true);r.add("pawday.payment.recovery-enabled",()->false);r.add("pawday.refund.recovery-enabled",()->false);r.add("pawday.settlement.worker-enabled",()->false);r.add("pawday.membership.worker-enabled",()->false);}
 @Autowired JdbcTemplate db;@Autowired Crypto crypto;@Autowired MutableClock clock;@LocalServerPort int port;
 @Autowired cn.pawday.membership.MembershipService memberships;
 static class MutableClock extends Clock {
  volatile Instant current=Instant.parse("2026-10-07T00:00:00Z");
  void advance(long seconds){current=current.plusSeconds(seconds);}
  @Override public ZoneId getZone(){return ZoneOffset.UTC;}
  @Override public Clock withZone(ZoneId zone){return this;}
  @Override public Instant instant(){return current;}
 }
 @org.springframework.boot.test.context.TestConfiguration static class FixtureBeans {
  @org.springframework.context.annotation.Bean @org.springframework.context.annotation.Primary MutableClock testClock(){return new MutableClock();}
 }
 final JsonMapper json=JsonMapper.builder().build();final HttpClient http=HttpClient.newHttpClient();
 static final List<Map<String,Object>> SAMPLES=new java.util.concurrent.CopyOnWriteArrayList<>();
 String admin,merchant;UUID adminSession,adminPrincipal,merchantId,store;String sku;
 record Response(int status,JsonNode body){JsonNode data(){return body.get("data");}String id(){return data().get("id").asString();}}

 boolean multi;
 String key(){return UUID.randomUUID().toString();}
 String identity(String realm,UUID m,List<String> permissions){UUID p=UUID.randomUUID(),role=UUID.randomUUID();if(realm.equals("CONSUMER")){UUID u=UUID.randomUUID();db.update("INSERT INTO app_user(id,status) VALUES (?,'ACTIVE')",u);db.update("INSERT INTO identity_principal(id,realm,user_id) VALUES (?,'CONSUMER',?)",p,u);}else db.update("INSERT INTO identity_principal(id,realm,merchant_id,login_name,password_hash,mfa_secret_ciphertext) VALUES (?,?,?,?,?,?)",p,realm,m,key(),"TEST-ONLY",realm.equals("ADMIN")?crypto.encrypt(new byte[20]):null);
  db.update("INSERT INTO role(id,scope_type,code,name) VALUES (?,?,?,'Membership test')",role,realm,key());for(String permission:permissions)db.update("INSERT INTO role_permission SELECT ?,id FROM permission WHERE code=?",role,permission);db.update("INSERT INTO principal_role VALUES (?,?,?)",p,role,realm);UUID session=UUID.randomUUID();String t=crypto.token();db.update("INSERT INTO auth_session(id,principal_id,access_token_hash,device_id,expires_at,refresh_expires_at,created_at) VALUES (?,?,?,'M51-IT',?,?,?)",session,p,crypto.hash(t),Timestamp.from(clock.instant().plusSeconds(86400*40)),Timestamp.from(clock.instant().plusSeconds(86400*40)),Timestamp.from(clock.instant()));if(realm.equals("ADMIN")){adminSession=session;adminPrincipal=p;}if(realm.equals("MERCHANT"))db.update("INSERT INTO principal_store_scope VALUES (?,?,?)",p,m,store);return t;
 }
 @BeforeEach void setup(){multi=false;merchantId=UUID.randomUUID();store=UUID.randomUUID();db.update("INSERT INTO merchant(id,name,status) VALUES (?,?,'ACTIVE')",merchantId,key());db.update("INSERT INTO merchant_store(id,merchant_id,name) VALUES (?,?,'TEST scope')",store,merchantId);
  admin=identity("ADMIN",null,List.of("offer.admin.manage","order.admin.read","payment.read","membership.plan.manage","points.policy.manage","points.reward.manage","points.adjust","points.read","review.read","review.moderate","review.policy.manage","content.read","content.write","content.moderate","aftersale.arbitrate","support.read","support.reply","support.assign","outbox.replay"));merchant=identity("MERCHANT",merchantId,List.of("offer.read","offer.write","inventory.adjust","order.read","order.default-scope","order.ship","aftersale.handle","review.merchant.read","support.read","support.reply","support.assign"));
  UUID brand=UUID.randomUUID(),spu=UUID.randomUUID(),k=UUID.randomUUID();sku=k.toString();db.update("INSERT INTO brands(id,name,source_ref) VALUES (?,?,'TEST-ONLY')",brand,key());db.update("INSERT INTO spus(id,brand_id,name,pet_category,category) VALUES (?,?,'TEST-ONLY','CAT','DRY_FOOD')",spu,brand);db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) VALUES (?,?,?,1000,'BAG')",k,spu,key());db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) VALUES (?,?,1,'PUBLISHED','[\"TEST-ONLY\"]','[]',false,'[]','[\"TEST-ONLY source\"]','2026-10-01',?,clock_timestamp())",UUID.randomUUID(),k,adminPrincipal);
 }
 Response req(String method,String path,Object payload,String token,Map<String,String> headers){try{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(20));if(token!=null)b.header("Authorization","Bearer "+token);headers.forEach(b::header);if(payload==null)b.method(method,HttpRequest.BodyPublishers.noBody());else b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload)));var response=http.send(b.build(),HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method",method.toLowerCase(),"path",path,"status",response.statusCode(),"response",body));return new Response(response.statusCode(),body);}catch(Exception e){throw new AssertionError(e);}}
 Response read(String path,String token){return req("GET",path,null,token,Map.of());}
 String consumer(){return identity("CONSUMER",null,List.of());}
 String proof(String action){String p=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) VALUES (?,?,?,?,?)",crypto.hash(p),adminSession,action,Timestamp.from(clock.instant().plusSeconds(300)),Timestamp.from(clock.instant()));return p;}
 @BeforeEach void reviewPolicyFixture(){int v=db.queryForObject("SELECT coalesce(max(policy_version),0)+1 FROM review_reward_policies",Integer.class);db.update("INSERT INTO review_reward_policies(id,policy_version,base_points,media_bonus_points,refund_strategy) VALUES (?,?,10,5,'PROPORTIONAL_GOODS')",UUID.randomUUID(),v);}
 String userIdOf(String token){return read("/consumer/me",token).data().get("user_id").asString();}

 record GoodsFixture(String payment,String subId,String itemId,long payable){}
 GoodsFixture paidGoods(String u,int qty){return paidGoods(u,qty,1000,List.of());}
 GoodsFixture paidGoods(String u,int qty,long price,List<String> coupons){return paidGoods(u,qty,price,coupons,()->{},200);}
 GoodsFixture paidGoods(String u,int qty,long price,List<String> coupons,Runnable beforeConfirm,int expectedStatus){
  var offer=req("POST","/merchant/offers",new LinkedHashMap<String,Object>(Map.of("sku_id",sku,"sale_price_fen",price,"member_price_fen",Math.min(price,900),"fulfillment_sla","TEST-ONLY 48h")){{put("store_id",store.toString());}},merchant,Map.of("Idempotency-Key",key()));assertEquals(201,offer.status(),offer.body().toString());
  assertEquals(201,req("POST","/merchant/offers/"+offer.id()+"/inventory-adjustments",Map.of("delta_qty",20,"reason_code","COUNT_CORRECTION","expected_version",0),merchant,Map.of("Idempotency-Key",key())).status());
  assertEquals(200,req("POST","/merchant/offers/"+offer.id()+"/activate",Map.of("reason","TEST-ONLY lifecycle"),merchant,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());
  int v=db.queryForObject("SELECT coalesce(max(version_no),0)+1 FROM shipping_rule_versions WHERE merchant_id=?",Integer.class,merchantId);
  db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,?,'[\"310000\"]',300,100,NULL,?)",UUID.randomUUID(),merchantId,v,adminPrincipal);
  var cart=req("POST","/consumer/cart/items",Map.of("offer_id",offer.id(),"quantity",qty),u,Map.of("Idempotency-Key",key()));
  var address=req("POST","/consumer/addresses",Map.of("recipient","TEST recipient","phone","13800000000","province_code","310000","city_code","310100","district_code","310101","detail","TEST-only address"),u,Map.of("Idempotency-Key",key()));
  var quote=req("POST","/consumer/checkout/quotes",Map.of("cart_item_ids",multi?List.of(cart.id(),secondCart(u,price,qty)):List.of(cart.id()),"address_id",address.id(),"coupon_ids",coupons,"use_membership",false),u,Map.of("Idempotency-Key",key()));assertEquals(200,quote.status(),quote.body().toString());
  var order=req("POST","/consumer/orders",Map.of("quote_id",quote.data().get("quote_id").asString()),u,Map.of("Idempotency-Key",key()));assertEquals(200,order.status(),order.body().toString());
  String payment=order.data().get("payment").get("id").asString();
  var attempt=req("POST","/consumer/payments/"+payment+"/attempts",Map.of("channel","WECHAT","client_platform","ANDROID"),u,Map.of("Idempotency-Key",key()));
  beforeConfirm.run();assertEquals(expectedStatus,req("POST","/consumer/payments/"+payment+"/simulation",Map.of("attempt_id",attempt.data().get("attempts").get(0).get("id").asString(),"outcome","SUCCEEDED"),u,Map.of()).status());
  return new GoodsFixture(payment,order.data().get("suborders").get(0).get("id").asString(),order.data().get("suborders").get(0).get("items").get(0).get("id").asString(),order.data().get("payable_amount_fen").asLong());
 }

 String secondCart(String u,long price,int qty){
  UUID second=UUID.randomUUID();db.update("INSERT INTO skus(id,spu_id,sku_code,weight_g,package_unit) SELECT ?,spu_id,?,weight_g,package_unit FROM skus WHERE id=?",second,key(),UUID.fromString(sku));
  db.update("INSERT INTO sku_standard_versions(id,sku_id,version_no,status,ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,published_at) SELECT ?,?,1,'PUBLISHED',ingredients,nutrients,allergens_known,life_stage_ids,source_refs,source_updated_on,created_by,clock_timestamp() FROM sku_standard_versions WHERE sku_id=? AND status='PUBLISHED'",UUID.randomUUID(),second,UUID.fromString(sku));
  var body=new LinkedHashMap<String,Object>(Map.of("sku_id",second.toString(),"sale_price_fen",price,"member_price_fen",Math.min(price,900),"fulfillment_sla","TEST-ONLY"));body.put("store_id",store.toString());
  var offer=req("POST","/merchant/offers",body,merchant,Map.of("Idempotency-Key",key()));assertEquals(201,offer.status(),offer.body().toString());
  assertEquals(201,req("POST","/merchant/offers/"+offer.id()+"/inventory-adjustments",Map.of("delta_qty",20,"reason_code","COUNT_CORRECTION","expected_version",0),merchant,Map.of("Idempotency-Key",key())).status());
  assertEquals(200,req("POST","/merchant/offers/"+offer.id()+"/activate",Map.of("reason","TEST-ONLY"),merchant,Map.of("Idempotency-Key",key(),"If-Match","\"0\"")).status());
  var cart=req("POST","/consumer/cart/items",Map.of("offer_id",offer.id(),"quantity",qty),u,Map.of("Idempotency-Key",key()));assertEquals(200,cart.status(),cart.body().toString());return cart.id();
 }
 void receiveAll(String u,GoodsFixture f){
  var items=db.queryForList("SELECT id,quantity FROM order_items WHERE suborder_id=? ORDER BY id",UUID.fromString(f.subId())).stream().map(row->Map.of("order_item_id",row.get("id").toString(),"quantity",row.get("quantity"))).toList();
  long v=read("/consumer/suborders/"+f.subId()+"/fulfillment",u).data().get("version").asLong();
  var shipped=req("POST","/merchant/suborders/"+f.subId()+"/shipments",Map.of("carrier_code","SF","tracking_no","TEST"+key().replace("-",""),"items",items),merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+v+"\""));assertEquals(200,shipped.status(),shipped.body().toString());
  var shipments=shipped.data().get("shipments");String ship=shipments.get(shipments.size()-1).get("id").asString();
  var received=req("POST","/consumer/suborders/"+f.subId()+"/confirm-receipt",Map.of("shipment_ids",List.of(ship)),u,Map.of("Idempotency-Key",key(),"If-Match","\""+shipped.data().get("version").asLong()+"\""));assertEquals(200,received.status(),received.body().toString());
 }
 Map<String,Object> reviewBody(List<String>assets,String pet,boolean share){var b=new LinkedHashMap<String,Object>();b.put("rating",4);b.put("service_rating",5);b.put("body","TEST-ONLY received goods review");b.put("asset_ids",assets);b.put("pet_id",pet);b.put("share_pet_label",share);return b;}
 Map<String,Object> articleBody(List<String>assets,List<String>skus){return Map.of("title","TEST-ONLY knowledge","category","FOOD_KNOWLEDGE","body","<script>plain text, no execution</script>","source_refs",List.of("TEST-ONLY source"),"sponsored",true,"asset_ids",assets,"sku_ids",skus);}
 Response submitReview(String u,String item,Map<String,Object>b){return req("POST","/consumer/order-items/"+item+"/reviews",b,u,Map.of("Idempotency-Key",key()));}
 Response approveReview(Response review){var r=req("POST","/admin/reviews/"+review.id()+"/moderation",Map.of("decision","APPROVE","reason","TEST-ONLY checked"),admin,Map.of("Idempotency-Key",key(),"If-Match","\""+review.data().get("version").asLong()+"\"","X-Reverify-Token",proof("review.moderate")));assertEquals(200,r.status(),r.body().toString());return r;}
 Response editReview(String u,Response review,Map<String,Object>b){return req("PATCH","/consumer/reviews/"+review.id(),b,u,Map.of("Idempotency-Key",key(),"If-Match","\""+review.data().get("version").asLong()+"\""));}
 Response createArticle(Map<String,Object>b){var r=req("POST","/admin/content",b,admin,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r;}
 Response submitArticle(Response article){var r=req("POST","/admin/content/"+article.id()+"/submit",Map.of(),admin,Map.of("Idempotency-Key",key(),"If-Match","\""+article.data().get("version").asLong()+"\""));assertEquals(200,r.status(),r.body().toString());return r;}
 Response moderateArticle(Response article,String decision){return req("POST","/admin/content/"+article.id()+"/moderation",Map.of("decision",decision,"reason","TEST-ONLY explicit decision"),admin,Map.of("Idempotency-Key",key(),"If-Match","\""+article.data().get("version").asLong()+"\"","X-Reverify-Token",proof("content.moderate")));}
 byte[] png(){try{var image=new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB);var out=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",out);return out.toByteArray();}catch(Exception e){throw new AssertionError(e);}}
 byte[] video(){try(var in=getClass().getResourceAsStream("/review-video.base64")){return Base64.getDecoder().decode(new String(in.readAllBytes(),java.nio.charset.StandardCharsets.US_ASCII).strip());}catch(Exception e){throw new AssertionError(e);}}
 String upload(String who,String scope,String mime,byte[] bytes){try{
  String hash=HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));
  var grant=req("POST","/media/upload-grants",Map.of("scope",scope,"mime",mime,"size_bytes",bytes.length,"sha256",hash),who,Map.of());assertEquals(201,grant.status(),grant.body().toString());String id=grant.data().get("asset_id").asString();
  var request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1/media/"+id+"/content")).header("Authorization","Bearer "+who).header("Content-Type",mime).header("X-Upload-Token",grant.data().get("upload_token").asString()).PUT(HttpRequest.BodyPublishers.ofByteArray(bytes)).build();
  var response=http.send(request,HttpResponse.BodyHandlers.ofString());var body=json.readTree(response.body());SAMPLES.add(Map.of("method","put","path","/media/"+id+"/content","status",response.statusCode(),"response",body));assertEquals(200,response.statusCode(),response.body());return id;
 }catch(Exception e){throw new AssertionError(e);}}
 static final List<Map<String,Object>> BINARY=new java.util.concurrent.CopyOnWriteArrayList<>();
 int binary(String path,String who,byte[] expected){try{var request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path));if(who!=null)request.header("Authorization","Bearer "+who);var r=http.send(request.GET().build(),HttpResponse.BodyHandlers.ofByteArray());if(r.statusCode()==200){assertArrayEquals(expected,r.body());assertEquals("nosniff",r.headers().firstValue("X-Content-Type-Options").orElseThrow());assertTrue(r.headers().firstValue("Cache-Control").orElseThrow().contains("no-store"));BINARY.add(Map.of("path",path,"status",r.statusCode(),"content_type",r.headers().firstValue("Content-Type").orElseThrow(),"bytes",r.body().length));}else{SAMPLES.add(Map.of("method","get","path",path,"status",r.statusCode(),"response",json.readTree(new String(r.body(),java.nio.charset.StandardCharsets.UTF_8))));}return r.statusCode();}catch(Exception e){throw new AssertionError(e);}}
 long reviewEarn(String u){return db.queryForObject("SELECT coalesce(sum(points),0) FROM points_ledger WHERE user_id=? AND entry_type IN ('REVIEW_EARN','MEDIA_REVIEW_BONUS','REVIEW_CLAWBACK')",Long.class,UUID.fromString(userIdOf(u)));}
 Response aftersale(String u,GoodsFixture f,int quantity){var a=req("POST","/consumer/suborders/"+f.subId()+"/aftersales",Map.of("type","REFUND_ONLY","reason_code","QUALITY_ISSUE","reason_text","TEST-ONLY", "items",List.of(Map.of("order_item_id",f.itemId(),"quantity",quantity)),"evidence",List.of()),u,Map.of("Idempotency-Key",key()));assertEquals(200,a.status(),a.body().toString());return a;}
 Response refund(String u,GoodsFixture f,int quantity){var a=aftersale(u,f,quantity);var r=req("POST","/merchant/aftersales/"+a.id()+"/decide",Map.of("action","APPROVE_REFUND","reason","TEST-ONLY"),merchant,Map.of("Idempotency-Key",key(),"If-Match","\""+a.data().get("version").asLong()+"\""));assertEquals(200,r.status(),r.body().toString());return r;}

 String match(Response r){return "\""+r.data().get("version").asLong()+"\"";}

 @Autowired cn.pawday.support.SupportInboxConsumer inbox;
 String principalOf(String token){return db.queryForObject("SELECT p.id::text FROM identity_principal p JOIN auth_session s ON s.principal_id=p.id WHERE s.access_token_hash=?",String.class,crypto.hash(token));}
 String proofFor(String token,String action){String proof=crypto.token();db.update("INSERT INTO reverify_grant(token_hash,session_id,action,expires_at,created_at) SELECT ?,id,?,?,? FROM auth_session WHERE access_token_hash=?",crypto.hash(proof),action,Timestamp.from(clock.instant().plusSeconds(300)),Timestamp.from(clock.instant()),crypto.hash(token));return proof;}
 Response conversation(String u,boolean platform){var body=new LinkedHashMap<String,Object>();body.put("kind",platform?"PLATFORM":"MERCHANT");body.put("store_id",platform?null:store.toString());var r=req("POST","/consumer/conversations",body,u,Map.of("Idempotency-Key",key()));assertEquals(200,r.status(),r.body().toString());return r;}
 Response assign(Response c,String who,String target){String realm=who.equals(merchant)?"merchant":"admin";var r=req("POST","/"+realm+"/conversations/"+c.id()+"/assignment",Map.of("principal_id",principalOf(target),"reason","TEST ONLY assignment"),who,Map.of("Idempotency-Key",key(),"If-Match",match(c),"X-Reverify-Token",proofFor(who,"support.assign")));assertEquals(200,r.status(),r.body().toString());return r;}
 Map<String,Object> body(String type,String text,List<String>assets,String target){var b=new LinkedHashMap<String,Object>();b.put("type",type);b.put("body",text);b.put("asset_ids",assets);b.put("target_id",target);return b;}
 Response send(String realm,String who,String c,Map<String,Object>body,String k){return req("POST","/"+realm+"/conversations/"+c+"/messages",body,who,Map.of("Idempotency-Key",k));}
 cn.pawday.outbox.EventEnvelope event(String mid,int attempt){var row=db.queryForMap("SELECT * FROM outbox_event WHERE event_type='SupportMessageCreated' AND payload->>'message_id'=?",mid);return new cn.pawday.outbox.EventEnvelope((UUID)row.get("id"),"SupportMessageCreated",1,"CONVERSATION",row.get("aggregate_id").toString(),null,attempt,((Number)row.get("generation")).intValue(),json.readValue(row.get("payload").toString(),Map.class));}
 @Test void createIsUniqueAcrossCommandKeysAndRealmBoundary(){String u=consumer();var c=conversation(u,true);assertEquals(c.id(),conversation(u,true).id());assertEquals(1,read("/consumer/conversations",u).data().size());assertEquals(404,read("/consumer/conversations/"+c.id(),consumer()).status());assertEquals(403,read("/consumer/conversations/"+c.id(),merchant).status());assertEquals(401,read("/consumer/conversations",null).status());}
 @Test void unassignedQueueExposesOnlyMetadataAndCurrentParticipantCanRead(){String u=consumer();var c=conversation(u,true);var sent=send("consumer",u,c.id(),body("TEXT","PRIVATE_TEXT",List.of(),null),key());assertEquals(200,sent.status());assertEquals(404,read("/admin/conversations/"+c.id()+"/messages",admin).status());var queue=read("/admin/conversations",admin);assertEquals(200,queue.status());assertFalse(queue.body().toString().contains("PRIVATE_TEXT"));assertFalse(queue.body().toString().contains(principalOf(u)));c=assign(read("/consumer/conversations/"+c.id(),u),admin,admin);assertEquals(200,read("/admin/conversations/"+c.id(),admin).status());assertEquals(200,read("/admin/conversations/"+c.id()+"/messages",admin).status());assertEquals(200,req("POST","/admin/conversations/"+c.id()+"/read",Map.of("through_sequence",1),admin,Map.of("Idempotency-Key",key())).status());}
 @Test void assignmentRequiresProofVersionScopeAndAuditsNoChatText(){String u=consumer();var c=conversation(u,false);String path="/merchant/conversations/"+c.id()+"/assignment";var b=Map.of("principal_id",principalOf(merchant),"reason","TEST ONLY");assertEquals(403,req("POST",path,b,merchant,Map.of("Idempotency-Key",key(),"If-Match",match(c))).status());c=assign(c,merchant,merchant);assertEquals(409,req("POST",path,b,merchant,Map.of("Idempotency-Key",key(),"If-Match","\"0\"","X-Reverify-Token",proofFor(merchant,"support.assign"))).status());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='support.assign' AND object_id=?",Integer.class,c.id()));assertEquals(200,read("/merchant/conversations?store_id="+store,merchant).status());assertEquals(404,read("/merchant/conversations?store_id="+UUID.randomUUID(),merchant).status());assertEquals(404,read("/admin/conversations/"+c.id(),admin).status());}
 @Test void reassignmentRevokesHistoryMediaAndRetryBeforeReturningSavedResult(){String u=consumer();var c=assign(conversation(u,true),admin,admin);String old=admin;String next=identity("ADMIN",null,List.of("support.read","support.reply","support.assign"));String asset=upload(old,"CHAT","image/png",png());String k=key();var sent=send("admin",old,c.id(),body("IMAGE",null,List.of(asset),null),k);assertEquals(200,sent.status());String path="/admin/conversations/"+c.id()+"/messages/"+sent.id()+"/media/"+asset;assertEquals(200,binary(path,old,png()));assign(read("/consumer/conversations/"+c.id(),u),next,next);assertEquals(404,read("/admin/conversations/"+c.id()+"/messages",old).status());assertEquals(404,binary(path,old,png()));assertEquals(404,send("admin",old,c.id(),body("IMAGE",null,List.of(asset),null),k).status());assertEquals(200,binary(path,next,png()));}
 @Test void orderedIdempotentMessagesAndReadHighWater(){String u=consumer();var c=assign(conversation(u,false),merchant,merchant);String k=key();var b=body("TEXT","<script>plain private text</script>",List.of(),null);var m=send("consumer",u,c.id(),b,k);assertEquals(200,m.status());assertEquals(m.id(),send("consumer",u,c.id(),b,k).id());assertEquals(409,send("consumer",u,c.id(),body("TEXT","changed",List.of(),null),k).status());var reply=send("merchant",merchant,c.id(),body("TEXT","TEST reply",List.of(),null),key());assertEquals(2,reply.data().get("sequence").asLong());
  for(String realm:List.of("consumer","merchant")){String who=realm.equals("consumer")?u:merchant;assertEquals(200,read("/"+realm+"/conversations/"+c.id(),who).status());assertEquals(200,read("/"+realm+"/conversations/"+c.id()+"/messages?after_sequence=0&limit=1",who).status());String path="/"+realm+"/conversations/"+c.id()+"/read";assertEquals(0,req("POST",path,Map.of("through_sequence",2),who,Map.of("Idempotency-Key",key())).data().get("unread_count").asLong());assertEquals(2,req("POST",path,Map.of("through_sequence",1),who,Map.of("Idempotency-Key",key())).data().get("read_sequence").asLong());assertEquals(400,req("POST",path,Map.of("through_sequence",3),who,Map.of("Idempotency-Key",key())).status());}
  assertFalse(db.queryForObject("SELECT payload::text FROM outbox_event WHERE payload->>'message_id'=?",String.class,m.id()).contains("private text"));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE conversation_messages SET body='overwrite' WHERE id=?",UUID.fromString(m.id())));
 }
 @Test void concurrentSendsCannotDuplicateSequence()throws Exception{String u=consumer();var c=conversation(u,true);var start=new java.util.concurrent.CountDownLatch(1);try(var pool=java.util.concurrent.Executors.newFixedThreadPool(6)){var jobs=new ArrayList<java.util.concurrent.Future<Response>>();for(int i=0;i<6;i++){int n=i;jobs.add(pool.submit(()->{start.await();return send("consumer",u,c.id(),body("TEXT","concurrent "+n,List.of(),null),key());}));}start.countDown();for(var job:jobs)assertEquals(200,job.get().status());}assertEquals(List.of(1L,2L,3L,4L,5L,6L),db.queryForList("SELECT sequence FROM conversation_messages WHERE conversation_id=? ORDER BY sequence",Long.class,UUID.fromString(c.id())));}
 @Test void closingBlocksNewSendAndReopenIsVersioned(){String u=consumer();var c=assign(conversation(u,true),admin,admin);for(String realm:List.of("consumer","admin")){String who=realm.equals("consumer")?u:admin;for(String state:List.of("CLOSED","OPEN")){c=read("/"+realm+"/conversations/"+c.id(),who);var changed=req("POST","/"+realm+"/conversations/"+c.id()+"/status",Map.of("status",state),who,Map.of("Idempotency-Key",key(),"If-Match",match(c)));assertEquals(200,changed.status());if(state.equals("CLOSED"))assertEquals(409,send(realm,who,c.id(),body("TEXT","closed",List.of(),null),key()).status());}}}
 @Test void merchantStatusAndReplyAreScoped(){String u=consumer();var c=assign(conversation(u,false),merchant,merchant);assertEquals(200,req("POST","/merchant/conversations/"+c.id()+"/status",Map.of("status","CLOSED"),merchant,Map.of("Idempotency-Key",key(),"If-Match",match(c))).status());db.update("DELETE FROM principal_store_scope WHERE principal_id=?",UUID.fromString(principalOf(merchant)));assertEquals(404,read("/merchant/conversations/"+c.id()+"/messages",merchant).status());}
 @Test void allThreePrivateImagesAndNoForeignScope(){String u=consumer();for(boolean platform:List.of(true,false)){var c=assign(conversation(u,platform),platform?admin:merchant,platform?admin:merchant);String staff=platform?admin:merchant,realm=platform?"admin":"merchant";String asset=upload(u,"CHAT","image/png",png());var m=send("consumer",u,c.id(),body("IMAGE",null,List.of(asset),null),key());assertEquals(200,m.status());for(String who:List.of("consumer",realm))assertEquals(200,binary("/"+who+"/conversations/"+c.id()+"/messages/"+m.id()+"/media/"+asset,who.equals("consumer")?u:staff,png()));assertEquals(409,req("DELETE","/media/"+asset,null,u,Map.of()).status());assertEquals(404,send(realm,staff,c.id(),body("IMAGE",null,List.of(asset),null),key()).status());assertEquals(404,binary("/consumer/conversations/"+c.id()+"/messages/"+m.id()+"/media/"+asset,consumer(),png()));}assertEquals(400,send("consumer",u,conversation(u,true).id(),body("TEXT",null,List.of(),null),key()).status());}
 @Test void productAndOrderCardsReauthorizeAtOpen(){String u=consumer();var f=paidGoods(u,1);for(boolean platform:List.of(true,false)){var c=assign(conversation(u,platform),platform?admin:merchant,platform?admin:merchant);String realm=platform?"admin":"merchant",who=platform?admin:merchant;for(String t:List.of("PRODUCT","ORDER")){var m=send("consumer",u,c.id(),body(t,null,List.of(),t.equals("PRODUCT")?sku:f.subId()),key());assertEquals(200,m.status(),m.body().toString());assertEquals(200,read("/consumer/conversations/"+c.id()+"/messages/"+m.id()+"/card",u).status());assertEquals(200,read("/"+realm+"/conversations/"+c.id()+"/messages/"+m.id()+"/card",who).status());if(t.equals("ORDER")){db.update("DELETE FROM role_permission rp USING principal_role pr,permission p WHERE rp.role_id=pr.role_id AND rp.permission_id=p.id AND pr.principal_id=? AND p.code=?",UUID.fromString(principalOf(who)),platform?"order.admin.read":"order.read");assertEquals(403,read("/"+realm+"/conversations/"+c.id()+"/messages/"+m.id()+"/card",who).status());}}}}
 @Test void notificationProjectionIsDeduplicatedAndPreferencesAreIndependent(){String u=consumer();var c=assign(conversation(u,true),admin,admin);assertEquals(7,read("/consumer/notification-preferences",u).data().size());assertEquals(200,req("PUT","/consumer/notification-preferences/SUPPORT",Map.of("enabled",false),u,Map.of("Idempotency-Key",key())).status());var m=send("admin",admin,c.id(),body("TEXT","reply",List.of(),null),key());var e=event(m.id(),1);inbox.process(e);inbox.process(e);var listed=read("/consumer/messages",u);assertEquals(1,listed.data().size());assertFalse(listed.data().get(0).get("notify_enabled").asBoolean());assertEquals(1,read("/consumer/messages/unread",u).data().get("unread_count").asLong());String id=listed.data().get(0).get("id").asString();assertEquals(404,req("POST","/consumer/messages/"+id+"/read",null,consumer(),Map.of("Idempotency-Key",key())).status());assertEquals(200,read("/consumer/messages/"+id+"/target",u).status());assertEquals(200,req("POST","/consumer/messages/"+id+"/read",null,u,Map.of("Idempotency-Key",key())).status());assertEquals(0,read("/consumer/messages/unread",u).data().get("unread_count").asLong());assertEquals(1,db.queryForObject("SELECT count(*) FROM notification_messages WHERE event_id=?",Integer.class,e.event_id()));}
 @Test void waitingReadRevokesSessionBeforeReturning()throws Exception{String u=consumer();var c=conversation(u,true);try(var pool=java.util.concurrent.Executors.newSingleThreadExecutor()){var started=new java.util.concurrent.CountDownLatch(1);var waiting=pool.submit(()->{started.countDown();return read("/consumer/conversations/"+c.id()+"/messages?wait_seconds=3",u);});started.await();Thread.sleep(500);db.update("UPDATE auth_session SET revoked_at=clock_timestamp() WHERE access_token_hash=?",crypto.hash(u));assertEquals(401,waiting.get().status());}}
 @Test void brokerUnavailableStillCommitsMessageAndOutbox(){String u=consumer();var c=conversation(u,true);var m=send("consumer",u,c.id(),body("TEXT","saved without broker",List.of(),null),key());assertEquals(200,m.status());assertEquals("PENDING",db.queryForObject("SELECT status FROM outbox_event WHERE payload->>'message_id'=?",String.class,m.id()));assertEquals(1,read("/consumer/conversations/"+c.id()+"/messages",u).data().size());}
 @Test void outboxFailureRollsBackMessageAndSequence(){String u=consumer();var c=conversation(u,true);db.execute("CREATE FUNCTION test_support_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='SupportMessageCreated' THEN RAISE EXCEPTION 'TEST failure'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_support_failure BEFORE INSERT ON outbox_event FOR EACH ROW EXECUTE FUNCTION test_support_failure()");try{assertEquals(503,send("consumer",u,c.id(),body("TEXT","rollback",List.of(),null),key()).status());}finally{db.execute("DROP TRIGGER test_support_failure ON outbox_event");db.execute("DROP FUNCTION test_support_failure()");}assertEquals(0,read("/consumer/conversations/"+c.id(),u).data().get("last_sequence").asLong());assertEquals(0,db.queryForObject("SELECT count(*) FROM conversation_messages WHERE conversation_id=?",Integer.class,UUID.fromString(c.id())));}
 @Test void outOfOrderDeliveryDoesNotClaimMissingMessageWasDelivered(){String u=consumer();var c=assign(conversation(u,true),admin,admin);var first=send("admin",admin,c.id(),body("TEXT","first",List.of(),null),key());var second=send("admin",admin,c.id(),body("TEXT","second",List.of(),null),key());inbox.process(event(second.id(),1));assertEquals(0,read("/consumer/conversations/"+c.id(),u).data().get("delivered_sequence").asLong());inbox.process(event(first.id(),1));assertEquals(2,read("/consumer/conversations/"+c.id(),u).data().get("delivered_sequence").asLong());assertEquals(0,read("/admin/conversations/"+c.id(),admin).data().get("unread_count").asLong());assertEquals(2,read("/consumer/conversations/"+c.id(),u).data().get("unread_count").asLong());}
 @Test void foreignOrderCardIsRejectedAndLiveProductRetirementIsVisible(){String u=consumer(),other=consumer();var f=paidGoods(other,1);var c=conversation(u,true);assertEquals(404,send("consumer",u,c.id(),body("ORDER",null,List.of(),f.subId()),key()).status());var m=send("consumer",u,c.id(),body("PRODUCT",null,List.of(),sku),key());assertEquals(200,m.status());db.update("UPDATE skus SET status='RETIRED' WHERE id=?",UUID.fromString(sku));var card=read("/consumer/conversations/"+c.id()+"/messages/"+m.id()+"/card",u);assertEquals(200,card.status());assertFalse(card.data().get("available").asBoolean());}
 @Test void failedAssignmentAuditDoesNotConsumeProofOrTransferParticipant(){String u=consumer();var c=conversation(u,true);String proof=proofFor(admin,"support.assign"),path="/admin/conversations/"+c.id()+"/assignment",k=key();var b=Map.of("principal_id",principalOf(admin),"reason","TEST auditable");var headers=Map.of("Idempotency-Key",k,"If-Match",match(c),"X-Reverify-Token",proof);db.execute("CREATE FUNCTION test_support_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='support.assign' THEN RAISE EXCEPTION 'TEST audit failure'; END IF; RETURN NEW; END $$");db.execute("CREATE TRIGGER test_support_audit_failure BEFORE INSERT ON audit_event FOR EACH ROW EXECUTE FUNCTION test_support_audit_failure()");try{assertEquals(503,req("POST",path,b,admin,headers).status());}finally{db.execute("DROP TRIGGER test_support_audit_failure ON audit_event");db.execute("DROP FUNCTION test_support_audit_failure()");}assertFalse(read("/consumer/conversations/"+c.id(),u).data().get("assigned").asBoolean());assertNull(db.queryForObject("SELECT used_at FROM reverify_grant WHERE token_hash=?",Timestamp.class,crypto.hash(proof)));assertEquals(200,req("POST",path,b,admin,headers).status());}
 @Test void notificationsUseTimeCursorWithoutDuplicateAndForeignReadIsDenied(){String u=consumer();var c=assign(conversation(u,true),admin,admin);for(int i=0;i<3;i++){var m=send("admin",admin,c.id(),body("TEXT","notice "+i,List.of(),null),key());inbox.process(event(m.id(),1));}var page=read("/consumer/messages?limit=1",u);assertTrue(page.body().get("page").get("has_more").asBoolean());String cursor=page.body().get("page").get("next_cursor").asString();var next=read("/consumer/messages?limit=2&cursor="+cursor,u);assertEquals(2,next.data().size());for(var row:next.data())assertNotEquals(page.data().get(0).get("id").asString(),row.get("id").asString());assertEquals(404,read("/consumer/messages/"+cursor+"/target",consumer()).status());}
 @AfterAll static void evidence()throws Exception{Files.createDirectories(Path.of("target"));JsonMapper j=JsonMapper.builder().build();Files.writeString(Path.of("target/m53-contract-samples.json"),j.writeValueAsString(SAMPLES));Files.writeString(Path.of("target/m53-binary-samples.json"),j.writeValueAsString(BINARY));PG.close();}
}
