import {it,expect} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import CancellationPanel from '../packages/web-shell/src/CancellationPanel.vue';
import AfterSalePanel from '../packages/web-shell/src/AfterSalePanel.vue';
import RefundsPanel from '../packages/web-shell/src/RefundsPanel.vue';
const id='00000000-0000-0000-0000-000000000001',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),expires_in:900,session_id:id,user_id:null};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(status===200?{data,meta}:{error:{code:'SERVICE_UNAVAILABLE',message:'RETRY',retryable:true,details:{}},meta}),{status,headers:{'Content-Type':'application/json'}});
const cancellation={id,order_id:id,suborder_id:id,actor_type:'MERCHANT',actor_id:id,reason_code:'MERCHANT_OUT_OF_STOCK',status:'COMPLETED',version:1,created_at:'2026-10-06T00:00:00Z',items:[{id,cancellation_id:id,order_item_id:id,quantity:1,item_payable_refund_fen:1000,shipping_refund_fen:0,allocation_snapshot:{},refund_id:id}],refund:{id,refund_no:'R1',payment_id:id,payment_attempt_id:id,cancellation_id:id,aftersale_id:null,amount_fen:1000,channel_refund_no:'SIMR-R1',status:'SUCCEEDED',attempt_count:1,next_retry_at:null,last_error_code:null,created_at:'2026-10-06T00:00:00Z',decided_at:'2026-10-06T00:00:01Z'},refund_amount_fen:1000};
const fulfillment={suborder_id:id,version:3,fulfillment_status:'PAID_WAITING_FULFILLMENT',items:[{order_item_id:id,quantity:3,cancelled_qty:0,shipped_qty:0,received_qty:0}],shipments:[],delivery_address:null};
const aftersale={id,suborder_id:id,order_id:id,user_id:id,merchant_id:id,type:'REFUND_ONLY',reason_code:'QUALITY_ISSUE',reason_text:'PRIVATE REASON',status:'PENDING_MERCHANT',return_carrier_code:null,return_tracking_no:null,version:0,created_at:'2026-10-06T00:00:00Z',items:[{id,aftersale_id:id,order_item_id:id,quantity:1,item_payable_refund_fen:1000,refund_id:null}],refund:null,refund_amount_fen:1000,evidence:[{id,actor_type:'CONSUMER',kind:'TEXT',content:'PRIVATE EVIDENCE',asset_id:null,created_at:'2026-10-06T00:00:00Z'}],decisions:[]};
function staff(network:typeof fetch,realm:'merchant'|'admin',permissions:string[]){const client=new PawdayClient(realm,'http://localhost/api/v1',network);client.setSession(tokens);const session=new StaffSession(client);session.state.principal={id,realm:realm.toUpperCase() as 'MERCHANT'|'ADMIN',merchant_id:realm==='merchant'?id:null,user_id:null,session_id:id,permissions};return session;}
it('merchant cancel retains idempotency key across uncertain retry',async()=>{const calls:Request[]=[];const network=async(input:RequestInfo|URL)=>{const r=input as Request;calls.push(r);if(r.method==='GET'&&r.url.includes('cancellations'))return json([]);if(r.method==='GET'&&r.url.includes('fulfillment'))return json(fulfillment);return json(null,503);};const wrapper=mount(CancellationPanel,{props:{session:staff(network,'merchant',['order.read','order.cancel.handle']),realm:'merchant',suborderId:id}});await flushPromises();const input=wrapper.find('form input');await input.setValue('2');await wrapper.find('form').trigger('submit');await flushPromises();await wrapper.find('form').trigger('submit');await flushPromises();const writes=calls.filter(r=>r.method==='POST');expect(writes).toHaveLength(2);expect(writes[0]!.headers.get('Idempotency-Key')).toBe(writes[1]!.headers.get('Idempotency-Key'));expect(await writes[0]!.json()).toEqual({reason_code:'MERCHANT_OUT_OF_STOCK',items:[{order_item_id:id,quantity:2}]});wrapper.unmount();});
it('merchant without cancel permission has no cancel form',async()=>{const network=async(input:RequestInfo|URL)=>{const r=input as Request;if(r.url.includes('cancellations'))return json([cancellation]);return json(fulfillment);};const wrapper=mount(CancellationPanel,{props:{session:staff(network,'merchant',['order.read']),realm:'merchant',suborderId:id}});await flushPromises();expect(wrapper.find('form').exists()).toBe(false);expect(wrapper.text()).toContain('退款成功');wrapper.unmount();});
it('merchant decide sends current version and retains key on retry',async()=>{const calls:Request[]=[];const network=async(input:RequestInfo|URL)=>{const r=input as Request;calls.push(r);if(r.method==='GET')return json([aftersale]);return json(null,503);};const wrapper=mount(AfterSalePanel,{props:{session:staff(network,'merchant',['order.read','aftersale.handle']),realm:'merchant',suborderId:id,itemNames:{[id]:'TEST ITEM'}}});await flushPromises();expect(wrapper.text()).toContain('PRIVATE EVIDENCE');await wrapper.find('form select').setValue('APPROVE_REFUND');await wrapper.find('form input').setValue('TEST decision');await wrapper.find('form').trigger('submit');await flushPromises();await wrapper.find('form').trigger('submit');await flushPromises();const writes=calls.filter(r=>r.method==='POST');expect(writes).toHaveLength(2);expect(writes[0]!.headers.get('Idempotency-Key')).toBe(writes[1]!.headers.get('Idempotency-Key'));expect(writes[0]!.headers.get('If-Match')).toBe('"0"');expect(await writes[0]!.json()).toEqual({action:'APPROVE_REFUND',reason:'TEST decision'});wrapper.unmount();});
it('admin arbitration reverifies before deciding',async()=>{const calls:Request[]=[];const escalated={...aftersale,status:'PLATFORM_ESCALATED',version:2};const network=async(input:RequestInfo|URL)=>{const r=input as Request;calls.push(r);if(r.method==='GET')return json([escalated]);if(r.url.includes('reverify'))return json({reverify_token:'PROOF',action:'aftersale.arbitrate',expires_at:'2026-10-06T01:00:00Z'});return json({...escalated,status:'COMPLETED'});};const wrapper=mount(AfterSalePanel,{props:{session:staff(network,'admin',['order.admin.read','aftersale.arbitrate']),realm:'admin',suborderId:id}});await flushPromises();const form=wrapper.find('form');await form.find('select').setValue('REFUND_APPROVED');const inputs=form.findAll('input');await inputs[0]!.setValue('TEST ruling');await inputs[1]!.setValue('pass');await inputs[2]!.setValue('123456');await form.trigger('submit');await flushPromises();const writes=calls.filter(r=>r.method==='POST');expect(writes).toHaveLength(2);expect(writes[0]!.url).toContain('/admin/auth/reverify');expect(writes[1]!.url).toContain('/admin/aftersales/');expect(writes[1]!.headers.get('X-Reverify-Token')).toBe('PROOF');expect(writes[1]!.headers.get('If-Match')).toBe('"2"');wrapper.unmount();});
it('admin refunds ledger renders and filters',async()=>{const refundRow={...cancellation.refund,order_id:id,currency:'CNY'};const network=async(input:RequestInfo|URL)=>{const r=input as Request;expect(r.url).toContain('/admin/refunds');return json([refundRow]);};const wrapper=mount(RefundsPanel,{props:{session:staff(network,'admin',['payment.read'])}});await flushPromises();expect(wrapper.text()).toContain('R1');expect(wrapper.text()).toContain('¥10.00');expect(wrapper.text()).toContain('退款成功');wrapper.unmount();});
