import {it,expect} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import AiPanel from '../packages/web-shell/src/AiPanel.vue';
const id='00000000-0000-4000-8000-000000000001',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),session_id:id,expires_in:900,user_id:null};
const release={active_prompt_id:id,staged_prompt_id:null,staged_percent:0,policy_id:id,version:7,provider_available:false,fit_rule_version:'pawday-fit-1'};
const policy={id,ordinary_daily_limit:3,member_daily_ceiling:200,retention_days:30,lease_seconds:60,enabled:true,created_at:'2026-10-09T00:00:00Z'};
const json=(data:unknown)=>new Response(JSON.stringify({data,page:{next_cursor:null,has_more:false},meta}),{headers:{'Content-Type':'application/json'}});
function session(network:typeof fetch,realm:'merchant'|'admin'='admin',permissions=['ai.read','ai.manage']){const client=new PawdayClient(realm,'http://localhost/api/v1',network);client.setSession(tokens);const s=new StaffSession(client);s.state.principal={id,session_id:id,realm:realm.toUpperCase() as 'ADMIN'|'MERCHANT',user_id:null,merchant_id:realm==='merchant'?id:null,permissions};return s;}
function get(request:Request){return json(request.url.endsWith('/release')?release:request.url.endsWith('/policies')?[policy]:[]);}
it('merchant AI help never requests consumer or admin data',async()=>{let calls=0;const w=mount(AiPanel,{props:{realm:'merchant',session:session(async()=>{calls++;return json({});},'merchant',[])}});await flushPromises();expect(calls).toBe(0);expect(w.text()).toContain('商家不能读取消费者 AI 会话');expect(w.find('input[type=password]').exists()).toBe(false);w.unmount();});
it('read-only administrator cannot mutate AI policy or prompts',async()=>{const w=mount(AiPanel,{props:{realm:'admin',session:session(async input=>get(input as Request),'admin',['ai.read'])}});await flushPromises();expect(w.text()).toContain('尚未配置供应商凭证');expect(w.find('form').exists()).toBe(false);expect(w.text()).toContain('确定性边界验证记录');w.unmount();});
it('policy command requires fresh proof, preserves immutable purchased-term semantics and clears secrets',async()=>{const calls:Request[]=[];const w=mount(AiPanel,{props:{realm:'admin',session:session(async input=>{const r=input as Request;calls.push(r);return r.url.includes('/auth/reverify')?json({reverify_token:'p'.repeat(43),expires_in:300}):r.method==='POST'?json(policy):get(r);})}});await flushPromises();await w.find('input[type=password]').setValue('TEST_PASSWORD');await w.find('input[inputmode=numeric]').setValue('123456');await w.find('form').trigger('submit');await flushPromises();const write=calls.find(r=>r.url.endsWith('/policies/versions'));expect(write?.headers.get('If-Match')).toBe('"7"');expect(write?.headers.get('X-Reverify-Token')).toBe('p'.repeat(43));expect(await write?.json()).toEqual({ordinary_daily_limit:3,member_daily_ceiling:200,retention_days:30,lease_seconds:60,enabled:true});expect((w.find('input[type=password]').element as HTMLInputElement).value).toBe('');expect(w.text()).toContain('不按天重置');w.unmount();});
it('late configuration cannot populate a logged-out session',async()=>{const pending:Array<(r:Response)=>void>=[];const s=session(async()=>new Promise<Response>(resolve=>pending.push(resolve)));const w=mount(AiPanel,{props:{realm:'admin',session:s}});await flushPromises();s.clear();await flushPromises();pending.slice(0,4).forEach((resolve,n)=>resolve(json(n===0?release:n===2?[policy]:[])));await flushPromises();expect(w.text()).not.toContain('配置版本 7');w.unmount();});
