import {it,expect} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import FulfillmentPanel from '../packages/web-shell/src/FulfillmentPanel.vue';
const id='00000000-0000-0000-0000-000000000001',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),expires_in:900,session_id:id,user_id:null};
const detail={suborder_id:id,version:1,fulfillment_status:'PAID_WAITING_FULFILLMENT',items:[{order_item_id:id,quantity:3,cancelled_qty:0,shipped_qty:0,received_qty:0}],shipments:[],delivery_address:{recipient:'PRIVATE RECIPIENT',phone:'13800000000',detail:'PRIVATE ADDRESS'}};
const json=(data:unknown)=>new Response(JSON.stringify({data,meta}),{headers:{'Content-Type':'application/json'}});
function staff(network:typeof fetch,permissions=['order.read','order.ship']){const client=new PawdayClient('merchant','http://localhost/api/v1',network);client.setSession(tokens);const session=new StaffSession(client);session.state.principal={id,realm:'MERCHANT',merchant_id:id,user_id:null,session_id:id,permissions};return session;}
it('logout discards a late private recipient response',async()=>{let resolve:((r:Response)=>void)|undefined;const session=staff(async()=>new Promise(r=>{resolve=r;}));const wrapper=mount(FulfillmentPanel,{props:{session,realm:'merchant',suborderId:id}});await flushPromises();session.clear();await flushPromises();resolve?.(json(detail));await flushPromises();expect(wrapper.text()).not.toContain('PRIVATE');expect(wrapper.find('form').exists()).toBe(false);wrapper.unmount();});
it('reader has no dispatch form',async()=>{const wrapper=mount(FulfillmentPanel,{props:{session:staff(async()=>json({...detail,delivery_address:null}),['order.read']),realm:'merchant',suborderId:id}});await flushPromises();expect(wrapper.find('form').exists()).toBe(false);expect(wrapper.text()).not.toContain('PRIVATE');wrapper.unmount();});
it('uncertain dispatch retry retains key and sends current version and partial quantity',async()=>{const calls:Request[]=[];const session=staff(async input=>{const r=input as Request;calls.push(r);if(r.method==='GET')return json(detail);return new Response(JSON.stringify({error:{code:'SERVICE_UNAVAILABLE',message:'RETRY',retryable:true,details:{}},meta}),{status:503,headers:{'Content-Type':'application/json'}});});const wrapper=mount(FulfillmentPanel,{props:{session,realm:'merchant',suborderId:id}});await flushPromises();const inputs=wrapper.findAll('input');await inputs[1]!.setValue('TEST0000001');await inputs[2]!.setValue('1');await wrapper.find('form').trigger('submit');await flushPromises();await wrapper.find('form').trigger('submit');await flushPromises();const writes=calls.filter(r=>r.method==='POST');expect(writes).toHaveLength(2);expect(writes[0]!.headers.get('Idempotency-Key')).toBe(writes[1]!.headers.get('Idempotency-Key'));expect(writes[0]!.headers.get('If-Match')).toBe('"1"');expect((await writes[0]!.json()).items).toEqual([{order_item_id:id,quantity:1}]);wrapper.unmount();});
