import {it,expect} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import NearbyPanel from '../packages/web-shell/src/NearbyPanel.vue';
const id='00000000-0000-4000-8000-000000000001',store='00000000-0000-4000-8000-000000000002',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),session_id:id,expires_in:900,user_id:null};
const profile={id:store,name:'TEST store',merchant_id:id,city:'上海',category:'PET_STORE',address:'TEST address',phone:'13800000000',business_hours:'9–18',longitude:121.5,latitude:31.2,coordinate_system:'WGS84',services:['SUPPLIES'],source:'MERCHANT_SUBMITTED',publication_status:'DRAFT',claim_status:'UNREVIEWED',pawday_certified:false,version:1,updated_at:'2026-10-08T00:00:00Z'};
const json=(data:unknown)=>new Response(JSON.stringify({data,page:{next_cursor:null,has_more:false},meta}),{headers:{'Content-Type':'application/json'}});
function session(network:typeof fetch,realm:'merchant'|'admin'='merchant',permissions=['store.read','store.nearby.write']){const client=new PawdayClient(realm,'http://localhost/api/v1',network);client.setSession(tokens);const s=new StaffSession(client);s.state.principal={id,session_id:id,realm:realm.toUpperCase() as 'ADMIN'|'MERCHANT',user_id:null,merchant_id:realm==='merchant'?id:null,permissions};s.state.storeId=store;return s;}
it('nearby editing cannot impersonate platform certification',async()=>{const w=mount(NearbyPanel,{props:{session:session(async()=>json(profile)),realm:'merchant'}});await flushPromises();expect(w.find('button[type=submit]').exists()).toBe(false);expect(w.text()).toContain('保存附近资料');expect(w.text()).not.toContain('验证并提交审核');expect(w.find('input[type=password]').exists()).toBe(false);w.unmount();});
it('read-only merchant does not see save command',async()=>{const w=mount(NearbyPanel,{props:{session:session(async()=>json(profile),'merchant',['store.read']),realm:'merchant'}});await flushPromises();expect(w.text()).not.toContain('保存附近资料');w.unmount();});
it('retry preserves key and expected version and excludes protected fields',async()=>{const calls:Request[]=[];const w=mount(NearbyPanel,{props:{session:session(async input=>{const r=input as Request;calls.push(r);return r.method==='PUT'?new Response(JSON.stringify({error:{code:'PERSISTENCE_UNAVAILABLE',message:'failed',retryable:true,details:{}},meta}),{status:503}):json(profile);}),realm:'merchant'}});await flushPromises();await w.find('form').trigger('submit');await flushPromises();await w.find('form').trigger('submit');await flushPromises();const writes=calls.filter(r=>r.method==='PUT');expect(writes).toHaveLength(2);expect(writes[0]!.headers.get('If-Match')).toBe('"1"');expect(writes[0]!.headers.get('Idempotency-Key')).toBe(writes[1]!.headers.get('Idempotency-Key'));const body=await writes[0]!.json();expect(body.coordinate_system).toBe('WGS84');expect(body).not.toHaveProperty('pawday_certified');expect(body).not.toHaveProperty('publication_status');w.unmount();});
it('late profile is fenced when staff switches stores',async()=>{let done!:(r:Response)=>void;const s=session(async input=>(input as Request).url.includes(store)?new Promise<Response>(r=>{done=r;}):json({...profile,id:'00000000-0000-4000-8000-000000000003',city:'北京'}));const w=mount(NearbyPanel,{props:{session:s,realm:'merchant'}});await flushPromises();s.state.storeId='00000000-0000-4000-8000-000000000003';await flushPromises();done(json(profile));await flushPromises();expect((w.find('input').element as HTMLInputElement).value).toBe('北京');w.unmount();});
it('platform moderation controls require RBAC and escape merchant facts',async()=>{const w=mount(NearbyPanel,{props:{session:session(async()=>json([{...profile,name:'<script>store</script>'}]),'admin',['nearby.read']),realm:'admin'}});await flushPromises();await w.find('article button').trigger('click');expect(w.text()).toContain('<script>store</script>');expect(w.find('script').exists()).toBe(false);expect(w.find('input[type=password]').exists()).toBe(false);w.unmount();});
