import {it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import ReviewPanel from '../packages/web-shell/src/ReviewPanel.vue';
import ContentPanel from '../packages/web-shell/src/ContentPanel.vue';
const id='00000000-0000-4000-8000-000000000001',store='00000000-0000-4000-8000-000000000002',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),session_id:id,expires_in:900,user_id:null};
const review={id,revision_id:id,spu_id:id,sku_id:id,rating:4,service_rating:5,body:'PRIVATE pending text',verified_purchase:true,version:0,created_at:'2026-10-08T00:00:00Z',media:[],pet_label:null,order_id:id,suborder_id:id,order_item_id:id,user_id:id,merchant_id:id,store_id:store,visibility:'HIDDEN',draft_status:'PENDING',share_pet_label:false,published_revision_id:null,pet_id:null,revision_no:1,moderation:[]};
const article={id,revision_id:id,title:'资料来源文章',category:'PET_CARE',body:'<script>never run this</script>',source_refs:['TEST ONLY source'],sponsored:true,version:0,media:[],published_at:null,sku_ids:[],visibility:'HIDDEN',draft_status:'DRAFT',published_revision_id:null,created_by:id,moderation:[]};
const json=(data:unknown)=>new Response(JSON.stringify({data,page:{next_cursor:null,has_more:false},meta}),{headers:{'Content-Type':'application/json'}});
function session(network:typeof fetch,realm:'admin'|'merchant'='admin',permissions=['review.read','review.moderate','content.read','content.write','content.moderate']){const client=new PawdayClient(realm,'http://localhost/api/v1',network);client.setSession(tokens);const s=new StaffSession(client);s.state.principal={id,session_id:id,realm:realm.toUpperCase() as 'ADMIN'|'MERCHANT',user_id:null,merchant_id:realm==='merchant'?id:null,permissions};s.state.storeId=store;return s;}
it('merchant reviews request the selected store and never expose moderation controls',async()=>{const calls:Request[]=[];const s=session(async input=>{calls.push(input as Request);return json([review]);},'merchant',['review.merchant.read']);const w=mount(ReviewPanel,{props:{session:s,realm:'merchant'}});await flushPromises();expect(new URL(calls[0]!.url).searchParams.get('store_id')).toBe(store);expect(w.find('form').exists()).toBe(false);w.unmount();});
it('reader can inspect review evidence but cannot moderate',async()=>{const w=mount(ReviewPanel,{props:{session:session(async r=>json(new URL((r as Request).url).pathname.endsWith('/reviews')?[review]:(r as Request).url.includes('policies')?[]:review),'admin',['review.read']),realm:'admin'}});await flushPromises();await w.findAll('button').find(b=>b.text().includes('审核详情'))!.trigger('click');await flushPromises();expect(w.text()).toContain('PRIVATE pending text');expect(w.find('input[type="password"]').exists()).toBe(false);w.unmount();});
it('failed reverify never posts review moderation and clears credentials',async()=>{const calls:Request[]=[];const w=mount(ReviewPanel,{props:{session:session(async input=>{const r=input as Request;calls.push(r);if(r.url.includes('/reverify'))return new Response(JSON.stringify({error:{code:'INVALID_CREDENTIALS',message:'INVALID_CREDENTIALS',retryable:false,details:{}},meta}),{status:401});return json(new URL(r.url).pathname.endsWith('/reviews')?[review]:r.url.includes('policies')?[]:review);}),realm:'admin'}});await flushPromises();await w.findAll('button').find(b=>b.text().includes('审核详情'))!.trigger('click');await flushPromises();const form=w.find('form');await form.find('textarea').setValue('TEST reason');const inputs=form.findAll('input');await inputs[0]!.setValue('TEST password');await inputs[1]!.setValue('123456');await form.trigger('submit');await flushPromises();expect(calls.some(r=>r.url.endsWith('/moderation'))).toBe(false);expect((inputs[0]!.element as HTMLInputElement).value).toBe('');w.unmount();});
it('article preview escapes HTML and keeps sources and sponsorship visible',async()=>{const w=mount(ContentPanel,{props:{session:session(async r=>json(new URL((r as Request).url).pathname.endsWith('/content')?[article]:article))}});await flushPromises();await w.findAll('button').find(b=>b.text()==='读取文章')!.trigger('click');await flushPromises();expect(w.text()).toContain('<script>never run this</script>');expect(w.find('script').exists()).toBe(false);expect(w.text()).toContain('商业推广');expect(w.text()).toContain('TEST ONLY source');w.unmount();});
it('late article detail cannot repopulate a logged out session',async()=>{let resolve!:(v:Response)=>void;const s=session(async r=>new URL((r as Request).url).pathname.endsWith('/content')?json([article]):new Promise<Response>(done=>{resolve=done;}));const w=mount(ContentPanel,{props:{session:s}});await flushPromises();await w.findAll('button').find(b=>b.text()==='读取文章')!.trigger('click');s.client.clearSession();s.clear();await flushPromises();resolve(json(article));await flushPromises();expect(w.text()).not.toContain('never run this');expect(w.find('input[type="password"]').exists()).toBe(false);w.unmount();});
it('binary media helper refuses arbitrary origins and cross realm paths',async()=>{const fetcher=vi.fn<typeof fetch>(async()=>new Response());const client=new PawdayClient('merchant','http://localhost/api/v1',fetcher);client.setSession(tokens);await expect(client.publicationMedia('https://example.com/file')).rejects.toMatchObject({code:'INVALID_API_DESTINATION'});await expect(client.publicationMedia(`/api/v1/admin/content/${id}/media/${id}`)).rejects.toMatchObject({code:'REALM_MISMATCH'});expect(fetcher).not.toHaveBeenCalled();});
