import {it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {createRouter,createMemoryHistory} from 'vue-router';
import {PawdayClient,type Tokens} from '../packages/api-client/src';
import {StaffSession} from '../packages/web-shell/src/auth';
import SupportPanel from '../packages/web-shell/src/SupportPanel.vue';
const id='00000000-0000-4000-8000-000000000001',store='00000000-0000-4000-8000-000000000002',meta={request_id:id,correlation_id:id};
const tokens:Tokens={access_token:'a'.repeat(43),refresh_token:'b'.repeat(43),session_id:id,expires_in:900,user_id:null};
const conversation={id,kind:'PLATFORM',store_id:null,status:'OPEN',last_sequence:1,delivered_sequence:1,version:1,created_at:'2026-10-08T00:00:00Z',updated_at:'2026-10-08T00:00:00Z',assigned:true,assigned_to_me:true,read_sequence:1,unread_count:0};
const message={id,conversation_id:id,sequence:1,sender_realm:'CONSUMER',type:'TEXT',body:'<script>private plain text</script>',target_id:null,created_at:'2026-10-08T00:00:00Z',outgoing:false,media:[]};
const json=(data:unknown)=>new Response(JSON.stringify({data,page:{next_cursor:null,has_more:false},meta}),{headers:{'Content-Type':'application/json'}});
function session(network:typeof fetch,realm:'admin'|'merchant'='admin',permissions=['support.read','support.reply','support.assign']){const client=new PawdayClient(realm,'http://localhost/api/v1',network);client.setSession(tokens);const s=new StaffSession(client);s.state.principal={id,session_id:id,realm:realm.toUpperCase() as 'ADMIN'|'MERCHANT',user_id:null,merchant_id:realm==='merchant'?id:null,permissions};s.state.storeId=store;return s;}
function mounted(s:StaffSession,realm:'admin'|'merchant'='admin'){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:{template:'<span />'}}]});return mount(SupportPanel,{props:{session:s,realm},global:{plugins:[router]}});}
it('merchant support queue always sends the selected store',async()=>{const calls:Request[]=[];const w=mounted(session(async input=>{calls.push(input as Request);return json([]);},'merchant'),'merchant');await flushPromises();expect(new URL(calls[0]!.url).searchParams.get('store_id')).toBe(store);w.unmount();});
it('unassigned support metadata cannot load private history',async()=>{const calls:Request[]=[];const w=mounted(session(async input=>{calls.push(input as Request);return json([{...conversation,assigned:false,assigned_to_me:false}]);}));await flushPromises();await w.find('.support-queue button').trigger('click');await flushPromises();expect(calls.some(r=>r.url.includes('/messages'))).toBe(false);expect(w.text()).toContain('仅向当前接待客服开放');w.unmount();});
it('private message text is escaped and reply controls require RBAC',async()=>{const w=mounted(session(async input=>json((input as Request).url.includes('/messages')?[message]:[conversation]),'admin',['support.read']));await flushPromises();await w.find('.support-queue button').trigger('click');await flushPromises();expect(w.text()).toContain('<script>private plain text</script>');expect(w.find('script').exists()).toBe(false);expect(w.find('.support-compose').exists()).toBe(false);expect(w.find('input[type=password]').exists()).toBe(false);w.unmount();});
it('failed sends keep the same key for user retry',async()=>{const calls:Request[]=[];const s=session(async input=>{const r=input as Request;calls.push(r);if(r.method==='POST'&&r.url.endsWith('/messages'))return new Response(JSON.stringify({error:{code:'RETRY_LATER',message:'RETRY_LATER',retryable:true,details:{}},meta}),{status:503});return json(r.url.includes('/messages')?[message]:[conversation]);});const w=mounted(s);await flushPromises();await w.find('.support-queue button').trigger('click');await flushPromises();await w.find('textarea').setValue('retry this private text');await w.find('.support-compose').trigger('submit');await flushPromises();await w.find('.support-compose').trigger('submit');await flushPromises();const sends=calls.filter(r=>r.method==='POST'&&r.url.endsWith('/messages'));expect(sends).toHaveLength(2);expect(sends[0]!.headers.get('Idempotency-Key')).toBe(sends[1]!.headers.get('Idempotency-Key'));expect((w.find('textarea').element as HTMLTextAreaElement).value).toBe('retry this private text');w.unmount();});
it('late support history is fenced after store switch',async()=>{let resolve!:(r:Response)=>void;const s=session(async input=>(input as Request).url.includes('/messages')?new Promise<Response>(done=>{resolve=done;}):json([conversation]));const w=mounted(s);await flushPromises();await w.find('.support-queue button').trigger('click');s.state.storeId='00000000-0000-4000-8000-000000000003';await flushPromises();resolve(json([message]));await flushPromises();expect(w.text()).not.toContain('private plain text');w.unmount();});
it('private chat media rejects cross realm and public paths before network',async()=>{const fetcher=vi.fn<typeof fetch>();const c=new PawdayClient('merchant','http://localhost/api/v1',fetcher);c.setSession(tokens);await expect(c.publicationMedia(`/api/v1/admin/conversations/${id}/messages/${id}/media/${id}`)).rejects.toMatchObject({code:'REALM_MISMATCH'});await expect(c.publicationMedia(`/api/v1/public/conversations/${id}/messages/${id}/media/${id}`)).rejects.toMatchObject({code:'INVALID_API_DESTINATION'});expect(fetcher).not.toHaveBeenCalled();});
