package cn.pawday.payment;

import cn.pawday.common.Api.Failure;
import cn.pawday.common.IdempotentCommandExecutor;
import cn.pawday.identity.*;
import cn.pawday.audit.AuditWriter;
import cn.pawday.outbox.OutboxWriter;
import jakarta.servlet.http.HttpServletRequest;
import java.sql.Timestamp;
import java.time.Clock;
import java.util.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

@Service public class PaymentService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final IdempotentCommandExecutor commands;
 private final ObjectProvider<PaymentGateway> gateways;private final OutboxWriter outbox;private final AuditWriter audit;private final AuthService auth;private final cn.pawday.settlement.SettlementService settlement;private final cn.pawday.membership.MembershipService membership;private final cn.pawday.points.PointsService points;private final RefundService refunds;private final Clock clock;
 public PaymentService(JdbcTemplate db,TransactionTemplate tx,IdempotentCommandExecutor commands,ObjectProvider<PaymentGateway> gateways,OutboxWriter outbox,AuditWriter audit,AuthService auth,cn.pawday.settlement.SettlementService settlement,cn.pawday.membership.MembershipService membership,cn.pawday.points.PointsService points,RefundService refunds,Clock clock){this.db=db;this.tx=tx;this.commands=commands;this.gateways=gateways;this.outbox=outbox;this.audit=audit;this.auth=auth;this.settlement=settlement;this.membership=membership;this.points=points;this.refunds=refunds;this.clock=clock;}
 private PaymentGateway gateway(){var g=gateways.getIfAvailable();if(g==null)throw new Failure(503,"PAYMENT_PROVIDER_UNAVAILABLE");return g;}
 private Map<String,Object> one(String q,Object...args){var rows=db.queryForList(q,args);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");return rows.getFirst();}
 private long n(Object v){return ((Number)v).longValue();}
 private Map<String,Object> view(Map<String,Object> r){var v=new LinkedHashMap<String,Object>();r.forEach((k,x)->v.put(k,x instanceof Timestamp t?t.toInstant().toString():x));return v;}
 private void consumer(Actor a){if(a.realm()!=Actor.Realm.CONSUMER)throw new Failure(403,"PERMISSION_DENIED");}
 private void permission(Actor a,String p){if(a.realm()!=Actor.Realm.ADMIN||!a.permissions().contains(p))throw new Failure(403,"PERMISSION_DENIED");}
 private Map<String,Object> owned(Actor a,UUID p){consumer(a);return one("SELECT p.* FROM payments p LEFT JOIN orders o ON o.id=p.order_id LEFT JOIN membership_orders mo ON mo.id=p.membership_order_id WHERE p.id=? AND coalesce(o.user_id,mo.user_id)=?",p,a.userId());}
 private Map<String,Object> lock(UUID p){var seed=one("SELECT order_id,membership_order_id FROM payments WHERE id=?",p);if(seed.get("order_id")!=null)one("SELECT id FROM orders WHERE id=? FOR UPDATE",seed.get("order_id"));else one("SELECT id FROM membership_orders WHERE id=? FOR UPDATE",seed.get("membership_order_id"));return one("SELECT * FROM payments WHERE id=? FOR UPDATE",p);}
 private PaymentGateway.Request request(UUID attempt){var x=one("SELECT a.*,p.amount_fen,p.currency FROM payment_attempts a JOIN payments p ON p.id=a.payment_id WHERE a.id=?",attempt);return new PaymentGateway.Request(attempt,x.get("attempt_no").toString(),x.get("channel").toString(),n(x.get("amount_fen")),x.get("currency").toString());}
 public Map<String,Object> get(Actor a,UUID p,boolean admin){if(admin)permission(a,"payment.read");else owned(a,p);return tx.execute(s->{var seed=one("SELECT order_id,membership_order_id FROM payments WHERE id=?",p);if(seed.get("order_id")!=null)one("SELECT id FROM orders WHERE id=? FOR SHARE",seed.get("order_id"));else one("SELECT id FROM membership_orders WHERE id=? FOR SHARE",seed.get("membership_order_id"));var result=view(one("SELECT * FROM payments WHERE id=?",p));var attempts=db.queryForList("SELECT * FROM payment_attempts WHERE payment_id=? ORDER BY created_at,id",p);result.put("attempts",attempts.stream().map(this::view).toList());result.put("final_channel",result.get("successful_attempt_id")==null?null:one("SELECT channel FROM payment_attempts WHERE id=?",result.get("successful_attempt_id")).get("channel"));result.put("simulation",gateways.getIfAvailable() instanceof SimulatedPaymentGateway);result.put("cases",db.queryForList("SELECT * FROM payment_cases WHERE payment_id=? ORDER BY created_at,id",p).stream().map(this::view).toList());return result;});}
 public Map<String,Object> attempt(Actor a,UUID p,Map<String,Object>b,String key,HttpServletRequest r){owned(a,p);gateway();if(!b.keySet().equals(Set.of("channel","client_platform"))||!Set.of("WECHAT","ALIPAY").contains(b.get("channel"))||!Set.of("IOS","ANDROID","WEB").contains(b.get("client_platform")))throw new Failure(400,"VALIDATION_ERROR");
  java.util.function.Supplier<Map<String,Object>> work=()->{var payment=lock(p);if(!payment.get("status").equals("PENDING"))throw new Failure(409,"PAYMENT_NOT_PAYABLE");if(!((Timestamp)payment.get("expires_at")).toInstant().isAfter(clock.instant()))throw new Failure(409,"PAYMENT_WINDOW_EXPIRED");
   if(db.queryForObject("SELECT count(*) FROM payment_attempts WHERE payment_id=? AND status IN ('CREATED','CHANNEL_PENDING','UNKNOWN')",Integer.class,p)>0)throw new Failure(409,"PAYMENT_CONFIRMATION_PENDING");UUID id=UUID.randomUUID();db.update("INSERT INTO payment_attempts(id,payment_id,attempt_no,channel,client_platform) VALUES (?,?,?,?,?)",id,p,"A"+id.toString().replace("-",""),b.get("channel"),b.get("client_platform"));db.update("INSERT INTO payment_requery_schedule(attempt_id) VALUES (?)",id);db.update("UPDATE payments SET status='PROCESSING',version=version+1 WHERE id=?",p);audit.write(a,"payment.attempt","PAYMENT",p.toString(),Map.of(),Map.of("attempt_id",id,"channel",b.get("channel")),r);outbox.append("PAYMENT",p.toString(),"PaymentAttemptCreated",1,Map.of("payment_id",p.toString(),"attempt_id",id.toString()),null);return Map.of("attempt_id",id.toString());};
  Map<String,Object> identity;try{identity=commands.command(a,"payment.attempt:"+p,key,b,work);}catch(Failure failure){if(!failure.code.equals("PAYMENT_NOT_PAYABLE"))throw failure;closeActive(p);identity=commands.command(a,"payment.attempt:"+p,key,b,work);}
  refresh(UUID.fromString(identity.get("attempt_id").toString()),false);return get(a,p,false);
 }
 public Map<String,Object> close(Actor a,UUID p){owned(a,p);closeActive(p);return get(a,p,false);}
 private void closeActive(UUID p){for(var x:db.queryForList("SELECT id FROM payment_attempts WHERE payment_id=? AND status IN ('CREATED','CHANNEL_PENDING','UNKNOWN')",p)){UUID id=(UUID)x.get("id");refresh(id,true);var state=one("SELECT status FROM payment_attempts WHERE id=?",id).get("status");if(Set.of("CREATED","CHANNEL_PENDING","UNKNOWN").contains(state))throw new Failure(409,"PAYMENT_CONFIRMATION_PENDING");}}
 public Map<String,Object> requery(Actor a,UUID p,boolean admin,String key,String proof,HttpServletRequest r){if(admin){permission(a,"payment.requery");commands.command(a,"payment.requery:"+p,key,Map.of("payment_id",p.toString()),()->{auth.consumeProof(a,"payment.requery",proof);lock(p);db.update("UPDATE refunds SET status='FAILED_RETRYABLE',attempt_count=0,next_retry_at=clock_timestamp(),last_error_code='MANUAL_RETRY_REQUESTED',lease_token=NULL,lease_until=NULL WHERE payment_id=? AND status='FAILED_FINAL'",p);db.update("UPDATE payment_cases SET status='REFUND_PENDING',attempt_count=0,next_retry_at=clock_timestamp(),last_error_code=NULL WHERE payment_id=? AND status='NEEDS_REVIEW'",p);audit.write(a,"payment.requery","PAYMENT",p.toString(),Map.of(),Map.of("requested",true),r);return Map.of("payment_id",p.toString());});}else owned(a,p);
  gateway();for(var x:db.queryForList("SELECT id FROM payment_attempts WHERE payment_id=? ORDER BY created_at,id",p))refresh((UUID)x.get("id"),false);compensate(p);refunds.dueForPayment(p);return get(a,p,admin);
 }
 public Map<String,Object> simulate(Actor a,UUID p,Map<String,Object>b){owned(a,p);if(!b.keySet().equals(Set.of("attempt_id","outcome"))||!(b.get("attempt_id") instanceof String id)||!(b.get("outcome") instanceof String state)||!Set.of("SUCCEEDED","FAILED","UNKNOWN").contains(state))throw new Failure(400,"VALIDATION_ERROR");UUID attempt;try{attempt=UUID.fromString(id);}catch(Exception e){throw new Failure(400,"VALIDATION_ERROR");}one("SELECT id FROM payment_attempts WHERE id=? AND payment_id=?",attempt,p);if(!(gateway() instanceof SimulatedPaymentGateway g))throw new Failure(404,"RESOURCE_NOT_FOUND");g.outcome(request(attempt),state);refresh(attempt,false);compensate(p);return get(a,p,false);}
 public void refresh(UUID id,boolean close){var req=request(id);PaymentGateway.Result result;try{result=close?gateway().close(req):gateway().query(req);if(!close&&result.status().equals("NOT_FOUND")&&one("SELECT status FROM payment_attempts WHERE id=?",id).get("status").equals("CREATED"))result=gateway().start(req);}catch(Exception e){result=new PaymentGateway.Result("UNKNOWN","UNAVAILABLE",null,0,req.currency());}apply(id,result);}
 private void state(UUID id,String state){db.update("UPDATE payment_attempts SET status=?,version=version+1 WHERE id=? AND status<>?",state,id,state);}
 private void apply(UUID id,PaymentGateway.Result result){tx.executeWithoutResult(s->{var seed=one("SELECT payment_id FROM payment_attempts WHERE id=?",id);UUID p=(UUID)seed.get("payment_id");var payment=lock(p);var attempt=one("SELECT * FROM payment_attempts WHERE id=? FOR UPDATE",id);String old=attempt.get("status").toString();db.update("UPDATE payment_requery_schedule SET failure_count=CASE WHEN ? THEN failure_count+1 ELSE 0 END,next_query_at=clock_timestamp()+(CASE WHEN ? THEN least(300,power(2,least(failure_count+1,6))*5) WHEN ? THEN 5 ELSE 1800 END*interval '1 second') WHERE attempt_id=?",result.status().equals("UNKNOWN"),result.status().equals("UNKNOWN"),Set.of("PENDING","NOT_FOUND").contains(result.status()),id);boolean active=Set.of("CREATED","CHANNEL_PENDING","UNKNOWN").contains(old);
  if(!result.status().equals("SUCCEEDED")){if(!active)return;String status=switch(result.status()){case "PENDING"->"CHANNEL_PENDING";case "FAILED"->"CHANNEL_FAILED";case "CLOSED"->"CANCELLED";default->"UNKNOWN";};state(id,status);if(Set.of("CHANNEL_FAILED","CANCELLED").contains(status)&&payment.get("status").equals("PROCESSING"))db.update("UPDATE payments SET status='PENDING',version=version+1 WHERE id=?",p);return;}
  if(result.transactionId()==null||result.transactionId().isBlank()||result.amountFen()<1||result.currency()==null)throw new Failure(409,"INVALID_PROVIDER_RECEIPT");
  var prior=db.queryForList("SELECT * FROM payment_receipts WHERE provider=? AND channel_transaction_id=?",result.provider(),result.transactionId());if(!prior.isEmpty()){var row=prior.getFirst();if(!row.get("attempt_id").equals(id)||n(row.get("amount_fen"))!=result.amountFen()||!row.get("currency").equals(result.currency()))throw new Failure(409,"RECEIPT_IDENTITY_CONFLICT");return;}
  UUID receipt=UUID.randomUUID();db.update("INSERT INTO payment_receipts(id,attempt_id,provider,channel_transaction_id,amount_fen,currency) VALUES (?,?,?,?,?,?)",receipt,id,result.provider(),result.transactionId(),result.amountFen(),result.currency());state(id,"CHANNEL_SUCCEEDED");UUID order=(UUID)payment.get("order_id");UUID membershipOrder=(UUID)payment.get("membership_order_id");
  String reason=payment.get("status").equals("SUCCEEDED")?"DUPLICATE_COLLECTION":payment.get("status").equals("CLOSED")||!active?"LATE_COLLECTION":n(payment.get("amount_fen"))!=result.amountFen()?"AMOUNT_MISMATCH":!payment.get("currency").equals(result.currency())?"CURRENCY_MISMATCH":null;
  if(reason!=null){UUID c=UUID.randomUUID();db.update("INSERT INTO payment_cases(id,payment_id,attempt_id,receipt_id,reason_code,refund_no) VALUES (?,?,?,?,?,?)",c,p,id,receipt,reason,"R"+c.toString().replace("-",""));if(payment.get("status").equals("PROCESSING")&&active)db.update("UPDATE payments SET status='PENDING',version=version+1 WHERE id=?",p);outbox.append("PAYMENT",p.toString(),"PaymentExceptionRecorded",1,Map.of("payment_id",p.toString(),"case_id",c.toString(),"reason_code",reason),null);audit.write(null,"payment.exception","PAYMENT",p.toString(),Map.of(),Map.of("case_id",c,"reason_code",reason),null);return;}
  if(membershipOrder!=null){db.update("UPDATE payments SET status='SUCCEEDED',successful_attempt_id=?,successful_receipt_id=?,paid_at=?,version=version+1 WHERE id=?",id,receipt,Timestamp.from(clock.instant()),p);membership.activate(membershipOrder,p);outbox.append("PAYMENT",p.toString(),"MembershipPaymentSucceeded",1,Map.of("payment_id",p.toString(),"membership_order_id",membershipOrder.toString(),"attempt_id",id.toString()),null);audit.write(null,"payment.confirm","PAYMENT",p.toString(),Map.of(),Map.of("receipt_id",receipt,"attempt_id",id,"amount_fen",result.amountFen(),"membership_order_id",membershipOrder),null);return;}
  for(var reservation:db.queryForList("SELECT * FROM inventory_reservations WHERE order_id=? ORDER BY offer_id FOR UPDATE",order)){UUID offer=(UUID)reservation.get("offer_id"),rid=(UUID)reservation.get("id");one("SELECT id FROM offers WHERE id=? FOR UPDATE",offer);var stock=one("SELECT * FROM inventory_balances WHERE offer_id=? FOR UPDATE",offer);long qty=n(reservation.get("quantity")),onHand=n(stock.get("on_hand_qty")),reserved=n(stock.get("reserved_qty")),version=n(stock.get("version"))+1;if(!reservation.get("status").equals("ACTIVE")||reserved<qty||onHand<qty)throw new Failure(409,"RESERVATION_STATE_CONFLICT");
   db.update("UPDATE inventory_balances SET on_hand_qty=?,reserved_qty=?,version=version+1,updated_at=clock_timestamp() WHERE offer_id=?",onHand-qty,reserved-qty,offer);db.update("UPDATE inventory_reservations SET status='CONSUMED',version=version+1 WHERE id=?",rid);db.update("INSERT INTO inventory_sale_events VALUES (?,?,?,?,?,?,?,?,?,?,clock_timestamp())",UUID.randomUUID(),rid,p,offer,qty,onHand,onHand-qty,reserved,reserved-qty,version);UUID event=UUID.randomUUID();db.update("INSERT INTO inventory_reservation_events(id,reservation_id,order_id,offer_id,operation,delta_reserved_qty,before_reserved_qty,resulting_reserved_qty,resulting_inventory_version) VALUES (?,?,?,?,'CONSUME',?,?,?,?)",event,rid,order,offer,-qty,reserved,reserved-qty,version);UUID sku=(UUID)one("SELECT sku_id FROM offers WHERE id=?",offer).get("sku_id");outbox.append("OFFER",offer.toString(),"InventoryReservationChanged",1,Map.of("offer_id",offer.toString(),"sku_id",sku.toString(),"reservation_event_id",event.toString(),"inventory_version",version),null);
  }
  for(var coupon:db.queryForList("SELECT c.* FROM user_coupons c JOIN order_coupon_snapshots s ON s.coupon_id=c.id WHERE s.order_id=? ORDER BY c.id FOR UPDATE OF c",order)){UUID cid=(UUID)coupon.get("id");if(!coupon.get("status").equals("RESERVED")||!order.equals(coupon.get("reserved_order_id")))throw new Failure(409,"COUPON_RESERVATION_CONFLICT");db.update("UPDATE user_coupons SET status='USED',reserved_order_id=NULL,reserved_from_status=NULL,reservation_expires_at=NULL,version=version+1 WHERE id=?",cid);db.update("INSERT INTO coupon_redemption_events VALUES (?,?,?,?,clock_timestamp())",UUID.randomUUID(),cid,order,p);}
  db.update("UPDATE payments SET status='SUCCEEDED',successful_attempt_id=?,successful_receipt_id=?,paid_at=?,version=version+1 WHERE id=?",id,receipt,Timestamp.from(clock.instant()),p);db.update("UPDATE suborders SET fulfillment_status='PAID_WAITING_FULFILLMENT',version=version+1 WHERE order_id=?",order);db.update("UPDATE orders SET status='FULFILLING',version=version+1 WHERE id=?",order);settlement.recordPaymentSuccess(order,p);points.recordGoodsPaymentSuccess(order,p,(UUID)one("SELECT user_id FROM orders WHERE id=?",order).get("user_id"));outbox.append("ORDER",order.toString(),"OrderPaid",1,Map.of("order_id",order.toString(),"payment_id",p.toString(),"attempt_id",id.toString()),null);audit.write(null,"payment.confirm","PAYMENT",p.toString(),Map.of(),Map.of("receipt_id",receipt,"attempt_id",id,"amount_fen",result.amountFen()),null);
 });}
 private void compensate(UUID p){for(var x:db.queryForList("SELECT c.*,r.provider,r.channel_transaction_id,r.amount_fen,r.currency FROM payment_cases c JOIN payment_receipts r ON r.id=c.receipt_id WHERE c.payment_id=? AND c.status='REFUND_PENDING' AND c.next_retry_at<=clock_timestamp()",p)){UUID id=(UUID)x.get("id");boolean done;try{done=gateway().refund(new PaymentGateway.RefundInstruction(x.get("refund_no").toString(),x.get("provider").toString(),x.get("channel_transaction_id").toString(),n(x.get("amount_fen")),x.get("currency").toString())).status().equals("SUCCEEDED");}catch(Exception e){done=false;}boolean success=done;tx.executeWithoutResult(s->{var rows=db.queryForList("SELECT * FROM payment_cases WHERE id=? AND status='REFUND_PENDING' FOR UPDATE",id);if(rows.isEmpty())return;int attemptCount=((Number)rows.getFirst().get("attempt_count")).intValue()+1;db.update("UPDATE payment_cases SET status=?,last_error_code=?,attempt_count=?,next_retry_at=clock_timestamp()+(?*interval '1 second') WHERE id=?",success?"REFUNDED":attemptCount>=8?"NEEDS_REVIEW":"REFUND_PENDING",success?null:"COMPENSATION_RETRYABLE",attemptCount,Math.min(300,5L*(1L<<Math.min(attemptCount,6))),id);if(success){outbox.append("PAYMENT",p.toString(),"PaymentCompensated",1,Map.of("payment_id",p.toString(),"case_id",id.toString()),null);audit.write(null,"payment.compensate","PAYMENT_CASE",id.toString(),Map.of(),Map.of("status","REFUNDED"),null);}});}}
 public int recoverBatch(){if(gateways.getIfAvailable()==null)return 0;var candidates=tx.execute(s->{var rows=db.queryForList("SELECT q.attempt_id FROM payment_requery_schedule q WHERE next_query_at<=clock_timestamp() ORDER BY next_query_at,attempt_id LIMIT 50 FOR UPDATE SKIP LOCKED");for(var row:rows)db.update("UPDATE payment_requery_schedule SET next_query_at=clock_timestamp()+interval '30 second' WHERE attempt_id=?",row.get("attempt_id"));return rows;});int count=0;for(var x:candidates){UUID id=(UUID)x.get("attempt_id");try{var payment=one("SELECT p.expires_at,a.status FROM payments p JOIN payment_attempts a ON a.payment_id=p.id WHERE a.id=?",id);boolean active=Set.of("CREATED","CHANNEL_PENDING","UNKNOWN").contains(payment.get("status"));boolean due=active&&!((Timestamp)payment.get("expires_at")).toInstant().isAfter(clock.instant());refresh(id,due);count++;}catch(Exception ignored){org.slf4j.LoggerFactory.getLogger(PaymentService.class).warn("Payment recovery retained for retry: {}",id);}}for(var x:db.queryForList("SELECT DISTINCT payment_id FROM payment_cases WHERE status='REFUND_PENDING' AND next_retry_at<=clock_timestamp() LIMIT 50"))compensate((UUID)x.get("payment_id"));return count;}
}

