package cn.pawday.content;

import cn.pawday.audit.AuditWriter;
import cn.pawday.catalog.ConsumerCatalogService;
import cn.pawday.common.Api.Failure;
import cn.pawday.common.IdempotentCommandExecutor;
import cn.pawday.identity.*;
import cn.pawday.outbox.OutboxWriter;
import cn.pawday.pet.PetService;
import cn.pawday.publishing.PublishingSupport;
import static cn.pawday.publishing.PublishingSupport.*;
import jakarta.servlet.http.HttpServletRequest;
import java.util.*;
import org.springframework.stereotype.Service;

@Service
public class ContentService {
 private final PublishingSupport p;private final IdempotentCommandExecutor commands;private final AuthService auth;
 private final AuditWriter audit;private final OutboxWriter outbox;private final ConsumerCatalogService catalog;private final PetService pets;
 public ContentService(PublishingSupport p,IdempotentCommandExecutor commands,AuthService auth,AuditWriter audit,OutboxWriter outbox,ConsumerCatalogService catalog,PetService pets){this.p=p;this.commands=commands;this.auth=auth;this.audit=audit;this.outbox=outbox;this.catalog=catalog;this.pets=pets;}
 private Map<String,Object> article(UUID id){return p.one("SELECT * FROM content_articles WHERE id=?",id);}
 private void validate(Map<String,Object>b){fields(b,"title","category","body","source_refs","sponsored","asset_ids","sku_ids");text(b.get("title"),160);text(b.get("body"),20000);String category=text(b.get("category"),24);if(!Set.of("FOOD_KNOWLEDGE","BRAND_KNOWLEDGE","PET_CARE").contains(category))throw new Failure(400,"VALIDATION_ERROR");bool(b.get("sponsored"));ids(b.get("asset_ids"),6);ids(b.get("sku_ids"),8);if(!(b.get("source_refs") instanceof List<?> refs)||refs.isEmpty()||refs.size()>10)throw new Failure(400,"VALIDATION_ERROR");refs.forEach(x->text(x,500));}
 private UUID revision(Actor a,UUID article,Map<String,Object>b){
  UUID id=UUID.randomUUID();int v=p.db.queryForObject("SELECT coalesce(max(revision_no),0)+1 FROM content_article_revisions WHERE article_id=?",Integer.class,article);
  var assets=ids(b.get("asset_ids"),6);var skuIds=ids(b.get("sku_ids"),8);skuIds.forEach(catalog::sku);
  p.db.update("INSERT INTO content_article_revisions(id,article_id,revision_no,title,category,body,source_refs,sponsored,asset_ids,sku_ids,created_by) VALUES (?,?,?,?,?,?,?::jsonb,?,?::jsonb,?::jsonb,?)",id,article,v,b.get("title"),b.get("category"),b.get("body"),p.json.writeValueAsString(b.get("source_refs")),b.get("sponsored"),p.json.writeValueAsString(assets),p.json.writeValueAsString(skuIds),a.principalId());p.bindMedia(a,"ARTICLE",id,assets);return id;
 }
 private void event(Actor a,String event,UUID id,HttpServletRequest r){var row=article(id);audit.write(a,"content."+event,"ARTICLE",id.toString(),Map.of(),Map.of("version",row.get("version"),"draft_status",row.get("draft_status"),"visibility",row.get("visibility")),r);outbox.append("ARTICLE",id.toString(),event,1,Map.of("article_id",id.toString(),"version",row.get("version")),r==null?null:(String)r.getAttribute("correlation_id"));}
 public Map<String,Object> create(Actor a,Map<String,Object>b,String key,HttpServletRequest r){permission(a,Actor.Realm.ADMIN,"content.write");permission(a,Actor.Realm.ADMIN,"content.read");validate(b);var result=commands.command(a,"content.create",key,b,()->{UUID id=UUID.randomUUID();p.db.update("INSERT INTO content_articles(id,created_by) VALUES (?,?)",id,a.principalId());UUID revision=revision(a,id,b);p.db.update("UPDATE content_articles SET current_revision_id=? WHERE id=?",revision,id);event(a,"ArticleCreated",id,r);return Map.of("id",id.toString());});return adminView(a,UUID.fromString(result.get("id").toString()));}
 public Map<String,Object> update(Actor a,UUID id,Map<String,Object>b,String match,String key,HttpServletRequest r){permission(a,Actor.Realm.ADMIN,"content.write");permission(a,Actor.Realm.ADMIN,"content.read");validate(b);article(id);long expected=version(match);var result=commands.command(a,"content.update:"+id,key,Map.of("body",b,"version",expected),()->{var row=p.one("SELECT * FROM content_articles WHERE id=? FOR UPDATE",id);sameVersion(row,expected);UUID revision=revision(a,id,b);p.db.update("UPDATE content_articles SET current_revision_id=?,draft_status='DRAFT',version=version+1,updated_at=now() WHERE id=?",revision,id);event(a,"ArticleUpdated",id,r);return Map.of("id",id.toString());});return adminView(a,UUID.fromString(result.get("id").toString()));}
 public Map<String,Object> submit(Actor a,UUID id,Map<String,Object>b,String match,String key,HttpServletRequest r){permission(a,Actor.Realm.ADMIN,"content.write");permission(a,Actor.Realm.ADMIN,"content.read");fields(b);article(id);long expected=version(match);var result=commands.command(a,"content.submit:"+id,key,Map.of("version",expected),()->{var row=p.one("SELECT * FROM content_articles WHERE id=? FOR UPDATE",id);sameVersion(row,expected);if(!Set.of("DRAFT","REJECTED").contains(row.get("draft_status")))throw new Failure(409,"ARTICLE_NOT_DRAFT");p.db.update("UPDATE content_articles SET draft_status='SUBMITTED',version=version+1,updated_at=now() WHERE id=?",id);event(a,"ArticleSubmitted",id,r);return Map.of("id",id.toString());});return adminView(a,UUID.fromString(result.get("id").toString()));}
 public Map<String,Object> moderate(Actor a,UUID id,Map<String,Object>b,String match,String key,String proof,HttpServletRequest r){permission(a,Actor.Realm.ADMIN,"content.moderate");permission(a,Actor.Realm.ADMIN,"content.read");fields(b,"decision","reason");String decision=text(b.get("decision"),12),reason=text(b.get("reason"),1000);if(!Set.of("PUBLISH","REJECT","HIDE").contains(decision))throw new Failure(400,"VALIDATION_ERROR");article(id);long expected=version(match);var result=commands.command(a,"content.moderate:"+id,key,Map.of("body",b,"version",expected),()->{
  var row=p.one("SELECT * FROM content_articles WHERE id=? FOR UPDATE",id);sameVersion(row,expected);auth.consumeProof(a,"content.moderate",proof);
  if(decision.equals("HIDE")){if(!row.get("visibility").equals("PUBLIC"))throw new Failure(409,"ARTICLE_NOT_PUBLIC");p.db.update("UPDATE content_articles SET visibility='HIDDEN',version=version+1,updated_at=now() WHERE id=?",id);}
  else{if(!row.get("draft_status").equals("SUBMITTED"))throw new Failure(409,"ARTICLE_NOT_SUBMITTED");if(decision.equals("PUBLISH")){
    // Recheck current authoritative standards at publication; do not advertise a retired SKU from an old draft.
    var rev=p.one("SELECT sku_ids FROM content_article_revisions WHERE id=?",row.get("current_revision_id"));p.storedIds(rev.get("sku_ids")).forEach(catalog::sku);
    p.db.update("UPDATE content_articles SET published_revision_id=current_revision_id,visibility='PUBLIC',draft_status='APPROVED',version=version+1,published_at=now(),updated_at=now() WHERE id=?",id);
   }else p.db.update("UPDATE content_articles SET draft_status='REJECTED',version=version+1,updated_at=now() WHERE id=?",id);}
  p.db.update("INSERT INTO content_moderation(id,article_id,revision_id,decision,reason,actor_id) VALUES (?,?,?,?,?,?)",UUID.randomUUID(),id,decision.equals("HIDE")?row.get("published_revision_id"):row.get("current_revision_id"),decision,reason,a.principalId());event(a,decision.equals("PUBLISH")?"ArticlePublished":decision.equals("REJECT")?"ArticleRejected":"ArticleHidden",id,r);return Map.of("id",id.toString());
 });return adminView(a,UUID.fromString(result.get("id").toString()));}
 private Map<String,Object> snapshot(Map<String,Object> row,UUID revision,String path){var rev=p.one("SELECT * FROM content_article_revisions WHERE id=? AND article_id=?",revision,row.get("id"));var result=new LinkedHashMap<String,Object>();for(String k:List.of("title","category","body","sponsored"))result.put(k,rev.get(k));result.put("id",row.get("id"));result.put("revision_id",revision);result.put("version",row.get("version"));result.put("source_refs",p.json.readValue(rev.get("source_refs").toString(),List.class));result.put("media",p.media(rev.get("asset_ids"),path));result.put("published_at",p.view(row).get("published_at"));result.put("sku_ids",p.storedIds(rev.get("sku_ids")));return result;}
 public Map<String,Object> adminView(Actor a,UUID id){permission(a,Actor.Realm.ADMIN,"content.read");var row=article(id);var result=snapshot(row,(UUID)row.get("current_revision_id"),"/api/v1/admin/content/"+id+"/media/");for(String k:List.of("visibility","draft_status","published_revision_id","created_by"))result.put(k,row.get(k));result.put("moderation",p.db.queryForList("SELECT decision,reason,created_at FROM content_moderation WHERE article_id=? ORDER BY created_at,id",id).stream().map(p::view).toList());return result;}
 public Map<String,Object> publicView(UUID id,Actor a,UUID pet){if(pet!=null){if(a==null||a.realm()!=Actor.Realm.CONSUMER)throw new Failure(403,"PERMISSION_DENIED");pets.get(a,pet);}var row=p.one("SELECT * FROM content_articles WHERE id=? AND visibility='PUBLIC' AND published_revision_id IS NOT NULL",id);var result=snapshot(row,(UUID)row.get("published_revision_id"),"/api/v1/public/content/"+id+"/media/");var skuIds=(List<UUID>)result.remove("sku_ids");result.put("products",skuIds.stream().map(sku->product(sku,a,pet)).toList());return result;}
 private Map<String,Object> product(UUID sku,Actor a,UUID pet){var result=new LinkedHashMap<String,Object>();result.put("sku_id",sku);result.put("available",false);result.put("in_stock",false);result.put("spu_id",null);result.put("name",null);result.put("fit",null);try{var standard=catalog.sku(sku);result.put("available",true);result.put("spu_id",standard.get("spu_id"));result.put("name",standard.get("name"));result.put("in_stock",catalog.offers(sku).stream().anyMatch(o->Boolean.TRUE.equals(o.get("in_stock"))));if(pet!=null)result.put("fit",catalog.fit(a,sku,pet));}catch(Failure f){if(f.status!=404)throw f;}return result;}
 public List<Map<String,Object>> publicList(String category,UUID after,int limit){limit(limit);if(category!=null&&!Set.of("FOOD_KNOWLEDGE","BRAND_KNOWLEDGE","PET_CARE").contains(category))throw new Failure(400,"VALIDATION_ERROR");String query="SELECT a.id FROM content_articles a JOIN content_article_revisions v ON v.id=a.published_revision_id WHERE a.visibility='PUBLIC' AND a.id>?";var args=new ArrayList<Object>();args.add(after);if(category!=null){query+=" AND v.category=?";args.add(category);}args.add(limit+1);return p.db.queryForList(query+" ORDER BY a.id LIMIT ?",args.toArray()).stream().map(row->publicView((UUID)row.get("id"),null,null)).toList();}
 public List<Map<String,Object>> adminList(Actor a,UUID after,int limit){permission(a,Actor.Realm.ADMIN,"content.read");limit(limit);return p.db.queryForList("SELECT id FROM content_articles WHERE id>? ORDER BY id LIMIT ?",after,limit+1).stream().map(row->adminView(a,(UUID)row.get("id"))).toList();}
 public PublishingSupport.Content content(Actor a,UUID id,UUID asset){Map<String,Object> row;if(a==null)row=p.one("SELECT * FROM content_articles WHERE id=? AND visibility='PUBLIC' AND published_revision_id IS NOT NULL",id);else{permission(a,Actor.Realm.ADMIN,"content.read");row=article(id);}return p.content(p.one("SELECT asset_ids FROM content_article_revisions WHERE id=?",row.get(a==null?"published_revision_id":"current_revision_id")).get("asset_ids"),asset);}
}
