package cn.pawday.ai;
import cn.pawday.common.*;
import cn.pawday.common.Api.Failure;
import cn.pawday.identity.*;
import cn.pawday.audit.AuditWriter;
import cn.pawday.pet.PetService;
import cn.pawday.publishing.PublishingSupport;
import static cn.pawday.publishing.PublishingSupport.*;
import static cn.pawday.ai.AiQuotaService.consumer;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.util.*;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;

@Service
public class AiService {
 private final PublishingSupport p;private final AiQuotaService quota;private final AiEvidenceService evidence;private final ExplanationProvider provider;
 private final Crypto crypto;private final IdempotentCommandExecutor commands;private final AuditWriter audit;private final PetService pets;
 public AiService(PublishingSupport p,AiQuotaService quota,AiEvidenceService evidence,ExplanationProvider provider,Crypto crypto,IdempotentCommandExecutor commands,AuditWriter audit,PetService pets){this.p=p;this.quota=quota;this.evidence=evidence;this.provider=provider;this.crypto=crypto;this.commands=commands;this.audit=audit;this.pets=pets;}
 public Map<String,Object> preferences(Actor a){consumer(a);return quota.tx.execute(s->{quota.lock(a.userId());return preferenceView(quota.preferences(a.userId()));});}
 private Map<String,Object> preferenceView(Map<String,Object> raw){return Map.of("personalization_enabled",raw.get("personalization_enabled"),"version",raw.get("version"),"data_usage","模型仅接收商品证据类型及规则结论，不接收账户、宠物姓名、电话、地址、档案备注或原始问题。会话加密保存，可主动清除。","provider_available",provider.available());}
 public Map<String,Object> preference(Actor a,Map<String,Object>b,String match,String key,HttpServletRequest r){consumer(a);fields(b,"personalization_enabled");boolean value=bool(b.get("personalization_enabled"));long expected=version(match);
  commands.command(a,"ai.preference",key,Map.of("body",b,"version",expected),()->{quota.lock(a.userId());var before=quota.preferences(a.userId());sameVersion(before,expected);p.db.update("UPDATE ai_preferences SET personalization_enabled=?,version=version+1 WHERE user_id=?",value,a.userId());
   for(var pending:p.db.queryForList("SELECT id FROM ai_quota_reservations WHERE user_id=? AND status='RESERVED' ORDER BY id",a.userId()))quota.transition((UUID)pending.get("id"),"RELEASED");audit.write(a,"ai.preference","USER",a.userId().toString(),Map.of("version",expected),Map.of("version",expected+1,"personalization_enabled",value),r);return Map.of("user_id",a.userId());});return preferences(a);
 }
 private Map<String,Object> conversation(UUID user,UUID id){return p.one("SELECT * FROM ai_conversations WHERE id=? AND user_id=? AND status='ACTIVE' AND expires_at>? FOR UPDATE",id,user,quota.now());}
 public Map<String,Object> create(Actor a,Map<String,Object>b,String key){consumer(a);fields(b,"current_pet_id");UUID pet=b.get("current_pet_id")==null?null:id(b.get("current_pet_id"));
  var result=commands.command(a,"ai.conversation.create",key,b,()->{quota.lock(a.userId());var prefs=quota.preferences(a.userId());if(pet!=null){if(!Boolean.TRUE.equals(prefs.get("personalization_enabled")))throw new Failure(409,"AI_PERSONALIZATION_DISABLED");pets.get(a,pet);}var policy=quota.policy();UUID c=UUID.randomUUID();p.db.update("INSERT INTO ai_conversations(id,user_id,pet_id,expires_at) VALUES (?,?,?,?)",c,a.userId(),pet,Timestamp.from(quota.clock.instant().plusSeconds(((Number)policy.get("retention_days")).longValue()*86400)));return Map.of("id",c);});return detail(a,UUID.fromString(result.get("id").toString()));
 }
 public List<Map<String,Object>> list(Actor a,UUID after,int limit){consumer(a);if(limit<1||limit>100)throw new Failure(400,"VALIDATION_ERROR");return quota.tx.execute(s->{quota.lock(a.userId());quota.clean(a.userId());return p.db.queryForList("SELECT id,pet_id,status,created_at,expires_at FROM ai_conversations WHERE user_id=? AND status='ACTIVE' AND id>? ORDER BY id LIMIT ?",a.userId(),after,limit+1).stream().map(p::view).toList();});}
 @SuppressWarnings("unchecked") private Map<String,Object> answer(UUID request){var row=p.one("SELECT * FROM ai_messages WHERE id=? AND result_ciphertext IS NOT NULL",request);return p.json.readValue(new String(crypto.decrypt(row.get("result_ciphertext").toString()),StandardCharsets.UTF_8),Map.class);}
 public Map<String,Object> detail(Actor a,UUID id){consumer(a);return quota.tx.execute(s->{quota.lock(a.userId());quota.clean(a.userId());var raw=conversation(a.userId(),id);var result=new LinkedHashMap<>(p.view(raw));result.remove("user_id");result.put("messages",p.db.queryForList("SELECT id FROM ai_messages WHERE conversation_id=? AND result_ciphertext IS NOT NULL ORDER BY created_at,id LIMIT 50",id).stream().map(x->answer((UUID)x.get("id"))).toList());return result;});}
 public Map<String,Object> clear(Actor a,UUID id,String key,HttpServletRequest r){consumer(a);return commands.command(a,"ai.conversation.clear:"+id,key,Map.of("id",id),()->{quota.lock(a.userId());quota.clear(a.userId(),id,"DELETED");audit.write(a,"ai.clear","AI_CONVERSATION",id.toString(),Map.of(),Map.of("status","DELETED"),r);return Map.of("id",id,"status","DELETED");});}
 record Started(UUID request,AiEvidenceService.Snapshot snapshot,String instruction,Map<String,Object> replay,Map<String,Object> policy,long preferenceVersion){}
 public Map<String,Object> send(Actor a,UUID conversation,Map<String,Object>b,String key){consumer(a);fields(b,"text","current_pet_id","selected_sku_ids");String question=text(b.get("text"),1000);UUID pet=b.get("current_pet_id")==null?null:id(b.get("current_pet_id"));List<UUID> selected=ids(b.get("selected_sku_ids"),3);
  if(key==null||key.length()<16||key.length()>128)throw new Failure(400,"IDEMPOTENCY_KEY_REQUIRED");String hash=crypto.otpHash(conversation.toString(),p.json.writeValueAsString(Arrays.asList(conversation,question,pet,selected)));
  Started started=quota.tx.execute(s->{quota.lock(a.userId());quota.active(a);quota.clean(a.userId());var prefs=quota.preferences(a.userId());var convo=conversation(a.userId(),conversation);if(pet!=null&&!Boolean.TRUE.equals(prefs.get("personalization_enabled")))throw new Failure(409,"AI_PERSONALIZATION_DISABLED");
   var prior=p.db.queryForList("SELECT q.*,r.status FROM ai_requests q JOIN ai_quota_reservations r ON r.id=q.id WHERE q.user_id=? AND q.idempotency_key=?",a.userId(),key);
   if(!prior.isEmpty()){var old=prior.getFirst();if(!hash.equals(old.get("payload_hash")))throw new Failure(409,"IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD");if(old.get("status").equals("CONSUMED"))return new Started((UUID)old.get("id"),null,null,answer((UUID)old.get("id")),null,0);throw new Failure(409,old.get("status").equals("RESERVED")?"AI_REQUEST_IN_PROGRESS":"AI_REQUEST_RELEASED_RETRY_NEW_KEY");}
   var policy=quota.policy();if(!Boolean.TRUE.equals(policy.get("enabled")))throw new Failure(503,"AI_DISABLED");var snapshot=evidence.snapshot(a,pet,selected,question);var release=p.one("SELECT * FROM ai_release FOR SHARE");UUID prompt=(UUID)release.get("active_prompt_id");if(release.get("staged_prompt_id")!=null&&Math.floorMod(a.userId().hashCode(),100)<((Number)release.get("staged_percent")).intValue())prompt=(UUID)release.get("staged_prompt_id");UUID request=UUID.randomUUID();
   p.db.update("INSERT INTO ai_requests(id,user_id,conversation_id,idempotency_key,payload_hash,preference_version,prompt_id,policy_id) VALUES (?,?,?,?,?,?,?,?)",request,a.userId(),conversation,key,hash,prefs.get("version"),prompt,policy.get("id"));quota.reserve(request,a.userId(),policy);return new Started(request,snapshot,p.one("SELECT instruction FROM ai_prompt_versions WHERE id=?",prompt).get("instruction").toString(),null,policy,number(prefs.get("version")));
  });
  if(started.replay!=null)return started.replay;
  try{
   // Network latency never holds a PostgreSQL transaction or business row lock.
   ExplanationProvider.Plan plan=provider.explain(started.instruction,started.snapshot.evidence());String rendered=evidence.render(started.snapshot,plan);
   return quota.tx.execute(s->{quota.lock(a.userId());quota.active(a);quota.clean(a.userId());var prefs=quota.preferences(a.userId());if(!Boolean.TRUE.equals(quota.policy().get("enabled")))throw new Failure(503,"AI_DISABLED");conversation(a.userId(),conversation);var reservation=p.one("SELECT * FROM ai_quota_reservations WHERE id=? FOR UPDATE",started.request);
    if(!reservation.get("status").equals("RESERVED")||!((Timestamp)reservation.get("lease_expires_at")).toInstant().isAfter(quota.clock.instant())||number(prefs.get("version"))!=started.preferenceVersion)throw new Failure(409,"AI_CONTEXT_VERSION_CONFLICT");
    quota.validateGrant(reservation);var current=evidence.snapshot(a,pet,started.snapshot.cards().stream().map(c->(UUID)c.get("sku_id")).toList(),question);if(!p.json.writeValueAsString(started.snapshot).equals(p.json.writeValueAsString(current)))throw new Failure(409,"AI_CONTEXT_VERSION_CONFLICT");
    UUID proposal=null;String value=AiEvidenceService.proposalValue(question);if(pet!=null&&value!=null&&!value.equals(started.snapshot.neutered())){proposal=UUID.randomUUID();p.db.update("INSERT INTO ai_profile_proposals(id,request_id,user_id,pet_id,pet_version,before_value,proposed_value,expires_at) VALUES (?,?,?,?,?,?,?,?)",proposal,started.request,a.userId(),pet,started.snapshot.petVersion(),started.snapshot.neutered(),value,Timestamp.from(quota.clock.instant().plusSeconds(3600)));}
    var request=p.one("SELECT prompt_id,policy_id FROM ai_requests WHERE id=?",started.request);var output=new LinkedHashMap<String,Object>();output.put("message_id",started.request);output.put("conversation_id",conversation);output.put("text",rendered);output.put("user_text",question);output.put("pet_context",pet==null?null:Map.of("pet_id",pet,"pet_version",started.snapshot.petVersion()));output.put("product_cards",started.snapshot.cards());output.put("prompt_id",request.get("prompt_id"));output.put("policy_id",request.get("policy_id"));output.put("fit_rule_version",cn.pawday.catalog.ConsumerCatalogService.FIT_RULE_VERSION);output.put("mode","DEEPSEEK_GROUNDED");output.put("proposal_id",proposal);output.put("created_at",quota.clock.instant().toString());
    quota.transition(started.request,"CONSUMED");output.put("quota",quota.quotaLocked(a.userId(),quota.policy()));
    p.db.update("INSERT INTO ai_messages(id,conversation_id,user_text_ciphertext,result_ciphertext) VALUES (?,?,?,?)",started.request,conversation,crypto.encrypt(question.getBytes(StandardCharsets.UTF_8)),crypto.encrypt(p.json.writeValueAsString(output).getBytes(StandardCharsets.UTF_8)));p.db.update("UPDATE ai_conversations SET pet_id=? WHERE id=?",pet,conversation);
    return output;
   });
  }catch(RuntimeException ex){try{quota.tx.executeWithoutResult(s->{quota.lock(a.userId());quota.transition(started.request,"RELEASED");});}catch(RuntimeException ignored){/* Durable lease recovery handles an unavailable database. */}throw ex;}
 }
 public Map<String,Object> proposal(Actor a,UUID id){consumer(a);return quota.tx.execute(s->{quota.lock(a.userId());quota.clean(a.userId());var row=p.one("SELECT * FROM ai_profile_proposals WHERE id=? AND user_id=?",id,a.userId());if(row.get("status").equals("PENDING")&&!((Timestamp)row.get("expires_at")).toInstant().isAfter(quota.clock.instant())){p.db.update("UPDATE ai_profile_proposals SET status='EXPIRED',pet_id=NULL,before_value=NULL,proposed_value=NULL,version=version+1 WHERE id=?",id);row=p.one("SELECT * FROM ai_profile_proposals WHERE id=?",id);}var out=p.view(row);out.remove("user_id");return out;});}
 public Map<String,Object> decide(Actor a,UUID id,boolean accept,String match,String key,HttpServletRequest r){consumer(a);long expected=version(match);commands.command(a,"ai.proposal.decide:"+id,key,Map.of("accept",accept,"version",expected),()->{quota.lock(a.userId());quota.clean(a.userId());var row=p.one("SELECT * FROM ai_profile_proposals WHERE id=? AND user_id=? FOR UPDATE",id,a.userId());if(!row.get("status").equals("PENDING")||!((Timestamp)row.get("expires_at")).toInstant().isAfter(quota.clock.instant()))throw new Failure(409,"AI_PROPOSAL_EXPIRED");
   var pet=pets.get(a,(UUID)row.get("pet_id"));if(number(pet.get("version"))!=expected||expected!=number(row.get("pet_version")))throw new Failure(409,"AI_CONTEXT_VERSION_CONFLICT");if(accept)pets.save(a,(UUID)row.get("pet_id"),expected,Map.of("neutered_status",row.get("proposed_value")),key,r);p.db.update("UPDATE ai_profile_proposals SET status=?,version=version+1 WHERE id=?",accept?"ACCEPTED":"REJECTED",id);audit.write(a,accept?"ai.proposal.accept":"ai.proposal.reject","AI_PROFILE_PROPOSAL",id.toString(),Map.of(),Map.of("status",accept?"ACCEPTED":"REJECTED"),r);return Map.of("id",id);});return proposal(a,id);}
}
