import {readdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createHmac} from 'node:crypto';
import {test,expect} from '@playwright/test';
test.skip(!process.env.PAWDAY_REAL_E2E,'Run in the mandatory real-infrastructure CI job');
test.use({actionTimeout:15000});
function totp(){
  const secret=process.env.PAWDAY_DEMO_ADMIN_TOTP_BASE64;
  if(!secret)throw new Error('Real admin TOTP fixture must be explicitly configured');
  const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));
  const hash=createHmac('sha1',Buffer.from(secret,'base64')).update(counter).digest();const offset=hash[19]!&15;
  return String((hash.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');
}
test('real merchant login, scope, refresh rotation and cross-realm rejection',async({page,request})=>{
  const password=process.env.PAWDAY_DEMO_MERCHANT_PASSWORD;if(!password)throw new Error('Real merchant fixture required');
  await page.goto('http://127.0.0.1:5173/stores');await page.getByLabel('账号',{exact:true}).fill('local-staff-a');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录工作台'}).click();
  await expect(page).toHaveURL('http://127.0.0.1:5173/stores');await expect(page.getByRole('heading',{name:'LOCAL DEMO Store a'})).toBeVisible();await expect(page.getByText('LOCAL DEMO Store b',{exact:true})).toHaveCount(0);
  const login=await request.post('http://127.0.0.1:8080/api/v1/merchant/auth/login',{data:{login_name:'local-staff-b',password,device_id:'ci-real-client'}});expect(login.ok()).toBe(true);const tokens=(await login.json()).data;
  const badRealm=await request.get('http://127.0.0.1:8080/api/v1/admin/me',{headers:{Authorization:`Bearer ${tokens.access_token}`}});expect(badRealm.status()).toBe(403);
  const refresh=await request.post('http://127.0.0.1:8080/api/v1/merchant/auth/refresh',{data:{refresh_token:tokens.refresh_token}});expect(refresh.ok()).toBe(true);const rotated=(await refresh.json()).data;expect(rotated.refresh_token).not.toBe(tokens.refresh_token);
  const me=await request.get('http://127.0.0.1:8080/api/v1/merchant/me',{headers:{Authorization:`Bearer ${rotated.access_token}`}});expect(me.ok()).toBe(true);expect((await me.json()).data.realm).toBe('MERCHANT');
  await page.getByRole('link',{name:'账号与设备'}).click();await expect(page.getByText('当前设备',{exact:true})).toBeVisible();await page.getByRole('button',{name:'注销其他设备',exact:true}).click();await page.getByLabel('再次输入密码').fill(password);await page.getByRole('button',{name:'验证并注销其他设备',exact:true}).click();await expect(page.getByRole('status')).toHaveText('其他设备的会话已注销。');
  await page.getByRole('button',{name:'退出登录'}).click();await expect(page).toHaveURL(/\/login$/);
});
test('real administrator TOTP, catalog publication, merchant correction and review',async({page,browser})=>{
  test.setTimeout(720000);
  const password=process.env.PAWDAY_DEMO_ADMIN_PASSWORD;if(!password)throw new Error('Real admin fixture required');
  await page.goto('http://127.0.0.1:5174/audit');await page.getByLabel('账号',{exact:true}).fill('local-admin');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByLabel('动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'登录工作台'}).click();
  await expect(page).toHaveURL('http://127.0.0.1:5174/audit');await expect(page.getByRole('table')).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByRole('link',{name:'账号与设备'}).click();await expect(page.getByText('当前设备',{exact:true})).toBeVisible();await page.getByRole('button',{name:'注销其他设备',exact:true}).click();
  // A login TOTP is single-use. Wait for the next real step before reverify.
  const currentStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(currentStep);
  await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());await page.getByRole('button',{name:'验证并注销其他设备',exact:true}).click();await expect(page.getByRole('status')).toHaveText('其他设备的会话已注销。');
  await page.getByRole('link',{name:'审计记录'}).click();await expect(page.getByRole('cell',{name:'auth.sessions.revoked-others',exact:true}).first()).toBeVisible();
  await page.getByRole('link',{name:'宠物分类',exact:true}).click();await expect(page.getByRole('heading',{name:'宠物分类与年龄规则'})).toBeVisible();
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'维护分类词典'})});await form.getByLabel('类型').selectOption('allergens');await form.getByLabel('名称',{exact:true}).fill(`CI REAL TEST allergen ${Date.now()}`);
  const taxonomyStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(taxonomyStep);
  await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());await form.getByRole('button',{name:'保存词典项'}).click();await expect(page.getByRole('status')).toHaveText('已保存，操作已记录。');
  await page.getByRole('link',{name:'审计记录'}).click();await expect(page.getByRole('cell',{name:'pet.taxonomy.create',exact:true}).first()).toBeVisible();
  await page.getByRole('link',{name:'标准商品',exact:true}).click();
  await expect(page.getByRole('heading',{name:'标准商品与审核'})).toBeVisible();
  const fresh=async()=>{const step=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(step);await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());};
  const saved=async()=>{await expect(page.getByRole('status')).toHaveText('已保存，操作已记录。');await expect(page.getByLabel('再次输入密码')).toHaveValue('');};
  const label=`CI REAL TEST ${Date.now()}`;
  await page.getByText('新建品牌、商品与规格',{exact:true}).click();
  const brandForm=page.locator('form').filter({has:page.getByRole('heading',{name:'品牌',exact:true})});
  await brandForm.getByLabel('名称',{exact:true}).fill(label);await brandForm.getByLabel('来源依据',{exact:true}).fill('TEST-ONLY generated browser fixture, not real merchandise');await fresh();await brandForm.getByRole('button',{name:'创建品牌'}).click();await saved();
  const spuForm=page.locator('form').filter({has:page.getByRole('heading',{name:'标准商品',exact:true})});
  await spuForm.getByRole('combobox',{name:'品牌',exact:true}).selectOption({label},{timeout:10000});await spuForm.getByLabel('商品名称').fill(label);await spuForm.getByLabel('商品类目').fill('DRY_FOOD');await fresh();await spuForm.getByRole('button',{name:'创建商品'}).click();await saved();
  const skuForm=page.locator('form').filter({has:page.getByRole('heading',{name:'标准规格',exact:true})});
  await skuForm.getByRole('combobox',{name:'所属商品',exact:true}).selectOption({label},{timeout:10000});await skuForm.getByLabel('规格标识').fill(label);await skuForm.getByLabel('净重（克）').fill('1000');await fresh();await skuForm.getByRole('button',{name:'创建规格'}).click();await saved();
  await page.locator('article').filter({has:page.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();
  const standardForm=page.locator('form').filter({has:page.getByRole('heading',{name:'创建新的资料草稿',exact:true})});
  await standardForm.getByLabel('配料（每行一项，保留原始顺序）').fill('TEST-ONLY ingredient');await standardForm.getByLabel('来源依据（每行一条）').fill('TEST-ONLY label fixture');await standardForm.getByLabel('来源更新日期').fill('2026-10-01');await fresh();await standardForm.getByRole('button',{name:'保存新草稿'}).click();await saved();
  await fresh();await page.getByRole('button',{name:'发布此版本'}).click();await saved();await expect(page.getByRole('heading',{name:'版本 1 · PUBLISHED'})).toBeVisible();
  const context=await browser.newContext(),merchantPage=await context.newPage();
  await merchantPage.goto('http://127.0.0.1:5173/catalog');await merchantPage.getByLabel('账号',{exact:true}).fill('local-staff-a');await merchantPage.getByLabel('密码',{exact:true}).fill(process.env.PAWDAY_DEMO_MERCHANT_PASSWORD!);await merchantPage.getByRole('button',{name:'登录工作台'}).click();await expect(merchantPage.getByRole('heading',{name:'平台标准商品'})).toBeVisible();
  await merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();await expect(merchantPage.getByRole('button',{name:'发布此版本'})).toHaveCount(0);
  await merchantPage.getByLabel('配料（每行一项，保留原始顺序）').fill('TEST-ONLY corrected ingredient');await merchantPage.getByLabel('纠错原因').fill('TEST-ONLY packaging correction');await merchantPage.getByRole('button',{name:'提交审核',exact:true}).click();await expect(merchantPage.getByRole('status')).toHaveText('已保存，操作已记录。');
  await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.getByText('TEST-ONLY packaging correction',{exact:true})).toBeVisible();await page.getByLabel('审核理由').fill('TEST-ONLY source reviewed');await fresh();await page.getByRole('button',{name:'批准并发布新版本'}).click();await saved();await expect(page.getByRole('heading',{name:'版本 2 · PUBLISHED'})).toBeVisible();
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();await expect(merchantPage.getByRole('heading',{name:'版本 2 · PUBLISHED'})).toBeVisible();await expect(merchantPage.getByRole('heading',{name:'版本 1 · RETIRED'})).toHaveCount(0);
  await page.screenshot({path:'frontend-evidence/m32-real-admin-catalog.png',fullPage:true});await merchantPage.screenshot({path:'frontend-evidence/m32-real-merchant-catalog.png',fullPage:true});
  await merchantPage.getByRole('link',{name:'报价与库存',exact:true}).click();await expect(merchantPage.getByRole('heading',{name:'报价与库存',exact:true})).toBeVisible();
  const selectedSku=await merchantPage.getByRole('combobox',{name:'标准规格',exact:true}).locator('option').filter({hasText:label}).getAttribute('value');expect(selectedSku).toBeTruthy();
  await merchantPage.getByRole('combobox',{name:'标准规格',exact:true}).selectOption(selectedSku!);await merchantPage.getByLabel('售价（分）',{exact:true}).fill('1250');await merchantPage.getByLabel('会员价（分，可空）',{exact:true}).fill('1150');await merchantPage.getByLabel('履约承诺',{exact:true}).fill('TEST-ONLY 48 hours');const createdOfferResponse=merchantPage.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith('/merchant/offers'));await merchantPage.getByRole('button',{name:'创建草稿报价'}).click();const createdOffer=(await (await createdOfferResponse).json()).data;await expect(merchantPage.getByRole('status')).toHaveText('已保存，操作已记录。');
  const offerCard=()=>merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})});await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('实物 0 · 预占 0 · 可用 0',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('增减数量').fill('10');await merchantPage.getByRole('button',{name:'提交库存调整'}).click();await expect(merchantPage.getByText('实物 10 · 预占 0 · 可用 10',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('cell',{name:'RESTOCK',exact:true})).toBeVisible();
  await merchantPage.getByLabel('操作原因').fill('TEST-ONLY initial sale');await merchantPage.getByRole('button',{name:'上架报价',exact:true}).click();await expect(merchantPage.getByText('状态 ACTIVE',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('售价（分）',{exact:true}).fill('1350');await merchantPage.getByRole('button',{name:'保存报价',exact:true}).click();await expect(merchantPage.getByText('售价 1350 分 · 会员价 1150 · TEST-ONLY 48 hours',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('增减数量').fill('-3');await merchantPage.getByRole('combobox',{name:'调整原因'}).selectOption('DAMAGE');await merchantPage.getByRole('button',{name:'提交库存调整'}).click();await expect(merchantPage.getByText('实物 7 · 预占 0 · 可用 7',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('cell',{name:'DAMAGE',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'报价与库存',exact:true}).click();await page.locator('article').filter({has:page.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看报价与流水'}).click();await page.getByLabel('操作原因').fill('TEST-ONLY risk verification');await fresh();await page.getByRole('button',{name:'冻结报价',exact:true}).click();await expect(page.getByText('状态 FROZEN',{exact:true})).toBeVisible();await expect(page.getByLabel('再次输入密码')).toHaveValue('');
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('状态 FROZEN',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('button',{name:'上架报价',exact:true})).toHaveCount(0);await expect(merchantPage.getByRole('button',{name:'保存报价',exact:true})).toHaveCount(0);
  await page.getByLabel('操作原因').fill('TEST-ONLY risk cleared');await fresh();await page.getByRole('button',{name:'解冻为暂停',exact:true}).click();await expect(page.getByText('状态 PAUSED',{exact:true})).toBeVisible();
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('状态 PAUSED',{exact:true})).toBeVisible();await merchantPage.getByLabel('操作原因').fill('TEST-ONLY explicit resume');await merchantPage.getByRole('button',{name:'上架报价',exact:true}).click();await expect(merchantPage.getByText('状态 ACTIVE',{exact:true})).toBeVisible();
  await page.screenshot({path:'frontend-evidence/m33-real-admin-offers.png',fullPage:true});await merchantPage.screenshot({path:'frontend-evidence/m33-real-merchant-offers.png',fullPage:true});await page.getByRole('link',{name:'配送规则',exact:true}).click();await expect(page.getByRole('heading',{name:'配送规则',exact:true})).toBeVisible();
  await page.getByLabel('商户 ID',{exact:true}).fill(createdOffer.merchant_id);await page.getByLabel('配送省份编码（逗号分隔）').fill('310000');await page.getByLabel('基础运费（分）',{exact:true}).fill('300');await page.getByLabel('每整公斤运费（分）',{exact:true}).fill('100');await fresh();await page.getByRole('button',{name:'验证并发布配送规则',exact:true}).click();await expect(page.getByRole('status')).toHaveText('新配送规则已发布，已有试算需重新确认');await expect(page.getByLabel('再次输入密码')).toHaveValue('');await page.screenshot({path:'frontend-evidence/m41-real-admin-shipping.png',fullPage:true});
  await page.getByRole('link',{name:'订单',exact:true}).click();await expect(page.getByRole('heading',{name:'平台订单',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'暂无访问权限',exact:true})).toHaveCount(0);await expect(page.getByText('暂时没有可查看的订单',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);
  await merchantPage.getByRole('link',{name:'订单',exact:true}).click();await expect(merchantPage.getByRole('heading',{name:'商家订单',exact:true})).toBeVisible();await expect(merchantPage.getByRole('heading',{name:'暂无访问权限',exact:true})).toHaveCount(0);await expect(merchantPage.getByRole('alert')).toHaveCount(0);
  await page.getByRole('link',{name:'付款期限规则',exact:true}).click();await expect(page.getByRole('heading',{name:'付款期限规则',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'暂无访问权限',exact:true})).toHaveCount(0);await page.getByLabel('新版本编码').fill('CI_REAL_ORDER_V1');await page.getByLabel('付款期限（秒）').fill('900');await fresh();await page.getByRole('button',{name:'验证并发布付款期限规则',exact:true}).click();await expect(page.getByRole('status')).toHaveText('新付款期限规则已发布，已有订单期限保持原值');await expect(page.getByLabel('再次输入密码')).toHaveValue('');await page.screenshot({path:'frontend-evidence/m42-real-admin-order-policy.png',fullPage:true});

  const api='http://127.0.0.1:8080/api/v1',phone='+8613900000043',sms=process.env.PAWDAY_REAL_SMS_DIRECTORY;if(!sms)throw new Error('Real SMS inbox required');
  expect((await page.request.post(api+'/consumer/auth/phone/request-code',{data:{phone_e164:phone,purpose:'LOGIN'}})).ok()).toBe(true);
  let otp='';await expect.poll(async()=>{let names:string[];try{names=await readdir(sms);}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return 0;throw e;}for(const name of names){const lines=(await readFile(join(sms,name),'utf8')).split(/\r?\n/);if(lines[0]===phone)otp=lines[1]??'';}return otp.length;},{timeout:30000,intervals:[250]}).toBe(6);
  const login=await page.request.post(api+'/consumer/auth/phone/verify',{data:{phone_e164:phone,code:otp,device_id:'ci-payment-browser'}});expect(login.ok()).toBe(true);const consumerTokens=(await login.json()).data;
  const create=async(path:string,data:unknown)=>{const response=await page.request.post(api+path,{data,headers:{Authorization:`Bearer ${consumerTokens.access_token}`,'Idempotency-Key':randomUUID()}});expect(response.ok()).toBe(true);return (await response.json()).data;};
  const address=await create('/consumer/addresses',{recipient:'TEST ONLY',phone:'13800000000',province_code:'310000',detail:'TEST ONLY Shanghai'});
  const cart=await create('/consumer/cart/items',{offer_id:createdOffer.id,quantity:1});const quote=await create('/consumer/checkout/quotes',{cart_item_ids:[cart.id],address_id:address.id});const order=await create('/consumer/orders',{quote_id:quote.quote_id});
  const pending=await create('/consumer/payments/'+order.payment.id+'/attempts',{channel:'WECHAT',client_platform:'WEB'});const success=await create('/consumer/payments/'+order.payment.id+'/simulation',{attempt_id:pending.attempts[0].id,outcome:'SUCCEEDED'});expect(success.status).toBe('SUCCEEDED');
  await page.getByRole('link',{name:'订单',exact:true}).click();const row=page.locator('tr').filter({hasText:order.order_no});await expect(row).toContainText('已付款待履约');await row.getByRole('button',{name:'查看详情'}).click();await expect(page.getByRole('heading',{name:'支付核对',exact:true})).toBeVisible();await expect(page.getByText('成功渠道 微信',{exact:true})).toBeVisible();
  const paymentStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(paymentStep);await page.getByLabel('核查密码',{exact:true}).fill(password);await page.getByLabel('核查动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'验证并核查支付',exact:true}).click();await expect(page.getByRole('status')).toHaveText('已按渠道事实核对支付与异常补偿');await expect(page.getByLabel('核查密码',{exact:true})).toHaveValue('');await page.screenshot({path:'frontend-evidence/m43-real-admin-payment.png',fullPage:true});
  await merchantPage.getByRole('button',{name:'刷新订单',exact:true}).click();await expect(merchantPage.locator('tr').filter({hasText:order.suborders[0].suborder_no})).toContainText('已付款待履约');await merchantPage.screenshot({path:'frontend-evidence/m43-real-merchant-paid-order.png',fullPage:true});
  const subRow=merchantPage.locator('tr').filter({hasText:order.suborders[0].suborder_no});await subRow.getByRole('button',{name:'查看详情'}).click();await expect(merchantPage.getByText('收件人 TEST ONLY',{exact:false})).toBeVisible();await merchantPage.getByLabel('物流公司编码',{exact:true}).fill('SF');const trackingNo='CI'+randomUUID().replaceAll('-','');await merchantPage.getByLabel('运单号',{exact:true}).fill(trackingNo);await merchantPage.getByRole('button',{name:'确认登记发货',exact:true}).click();await expect(merchantPage.getByRole('status')).toHaveText('包裹已登记发货');await expect(subRow).toContainText('待收货');await expect(merchantPage.getByText(`SF · ${trackingNo} · 等待用户确认收货`,{exact:true})).toBeVisible();await merchantPage.getByRole('button',{name:'查询此包裹物流',exact:true}).click();await expect(merchantPage.getByText('暂无可靠物流轨迹',{exact:false})).toBeVisible();await merchantPage.screenshot({path:'frontend-evidence/m44-real-merchant-shipment.png',fullPage:true});
  const own=await page.request.get(api+'/consumer/suborders/'+order.suborders[0].id+'/fulfillment',{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});expect(own.ok()).toBe(true);const fulfillment=(await own.json()).data;expect(fulfillment.fulfillment_status).toBe('SHIPPED_WAITING_RECEIPT');const received=await page.request.post(api+'/consumer/suborders/'+order.suborders[0].id+'/confirm-receipt',{data:{shipment_ids:[fulfillment.shipments[0].id]},headers:{Authorization:`Bearer ${consumerTokens.access_token}`,'Idempotency-Key':randomUUID(),'If-Match':`"${fulfillment.version}"`}});expect(received.ok()).toBe(true);expect((await received.json()).data.fulfillment_status).toBe('COMPLETED');
  await page.getByRole('button',{name:'刷新订单',exact:true}).click();await expect(row).toContainText('已完成');await row.getByRole('button',{name:'查看详情'}).click();await expect(page.getByText(`SF · ${trackingNo} · 用户已确认收货`,{exact:true})).toBeVisible();await page.screenshot({path:'frontend-evidence/m44-real-admin-receipt.png',fullPage:true});

  const purchasedReview=await create('/consumer/order-items/'+fulfillment.items[0].order_item_id+'/reviews',{rating:4,service_rating:5,body:'CI REAL M52 verified review',asset_ids:[],pet_id:null,share_pet_label:false});expect(purchasedReview.draft_status).toBe('PENDING');
  await page.getByRole('link',{name:'评价',exact:true}).click();const reviewCard=page.locator('article').filter({hasText:'CI REAL M52 verified review'});await reviewCard.getByRole('button',{name:'读取评价审核详情',exact:true}).click();const reviewForm=page.locator('form').filter({has:page.getByRole('button',{name:'验证并通过评价',exact:true})});await reviewForm.getByLabel('处理原因',{exact:true}).fill('TEST ONLY real moderation');const reviewStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(reviewStep);await reviewForm.getByLabel('再次输入密码',{exact:true}).fill(password);await reviewForm.getByLabel('新的动态验证码',{exact:true}).fill(totp());await reviewForm.getByRole('button',{name:'验证并通过评价',exact:true}).click();await expect(page.getByRole('status')).toHaveText('审核结果已保存');await page.screenshot({path:'frontend-evidence/m52-real-admin-review.png',fullPage:true});
  const publicReview=await page.request.get(api+'/public/reviews/'+purchasedReview.id);expect(publicReview.ok()).toBe(true);expect((await publicReview.json()).data.verified_purchase).toBe(true);
  await merchantPage.getByRole('link',{name:'评价',exact:true}).click();await expect(merchantPage.getByText('CI REAL M52 verified review',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('button',{name:'验证并通过评价',exact:true})).toHaveCount(0);await merchantPage.screenshot({path:'frontend-evidence/m52-real-merchant-review.png',fullPage:true});
  await page.getByRole('link',{name:'订单',exact:true}).click();await merchantPage.getByRole('link',{name:'订单',exact:true}).click();

  const applied=await create('/consumer/suborders/'+order.suborders[0].id+'/aftersales',{type:'REFUND_ONLY',reason_code:'QUALITY_ISSUE',reason_text:'TEST ONLY real e2e aftersale',items:[{order_item_id:fulfillment.items[0].order_item_id,quantity:1}],evidence:[{content:'TEST ONLY real e2e evidence'}]});expect(applied.status).toBe('PENDING_MERCHANT');expect(applied.refund_amount_fen).toBe(1350);
  await merchantPage.getByRole('button',{name:'刷新订单',exact:true}).click();const paidRow=merchantPage.locator('tr').filter({hasText:order.suborders[0].suborder_no});await paidRow.getByRole('button',{name:'查看详情'}).click();await expect(merchantPage.getByText('仅退款 · 待商家处理',{exact:false})).toBeVisible();
  await merchantPage.getByRole('combobox',{name:'处理决定',exact:true}).selectOption('REJECT');await merchantPage.getByLabel('处理说明',{exact:true}).fill('TEST ONLY merchant rejection');await merchantPage.getByRole('button',{name:'提交决定',exact:true}).click();await expect(merchantPage.getByText('已拒绝',{exact:false}).first()).toBeVisible();await merchantPage.screenshot({path:'frontend-evidence/m45-real-merchant-aftersale-reject.png',fullPage:true});
  const rejectedView=await page.request.get(api+'/consumer/aftersales/'+applied.id,{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});const rejectedData=(await rejectedView.json()).data;expect(rejectedData.status).toBe('REJECTED');
  const escalated=await page.request.post(api+'/consumer/aftersales/'+applied.id+'/escalate',{data:{reason:'TEST ONLY consumer escalation'},headers:{Authorization:`Bearer ${consumerTokens.access_token}`,'Idempotency-Key':randomUUID(),'If-Match':`"${rejectedData.version}"`}});expect(escalated.ok()).toBe(true);expect((await escalated.json()).data.status).toBe('PLATFORM_ESCALATED');
  await page.getByRole('button',{name:'刷新订单',exact:true}).click();await row.getByRole('button',{name:'查看详情'}).click();await expect(page.getByText('平台介入中',{exact:false})).toBeVisible();
  const rulingForm=page.locator('form').filter({has:page.getByRole('button',{name:'验证并裁决'})});await rulingForm.getByRole('combobox',{name:'裁决',exact:true}).selectOption('REFUND_APPROVED');await rulingForm.getByLabel('裁决理由',{exact:true}).fill('TEST ONLY platform ruling');const rulingStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(rulingStep);await rulingForm.getByLabel('核查密码',{exact:true}).fill(password);await rulingForm.getByLabel('核查动态验证码',{exact:true}).fill(totp());
  await rulingForm.getByRole('button',{name:'验证并裁决',exact:true}).click();await expect(page.getByText('售后处理已完成',{exact:true})).toBeVisible();await expect(page.getByText('已完成 · 退款 ¥13.50 · 退款成功',{exact:false}).first()).toBeVisible();await page.screenshot({path:'frontend-evidence/m45-real-admin-arbitration.png',fullPage:true});
  const finalView=await page.request.get(api+'/consumer/aftersales/'+applied.id,{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});const finalData=(await finalView.json()).data;expect(finalData.status).toBe('COMPLETED');expect(finalData.refund.status).toBe('SUCCEEDED');expect(finalData.decisions[0].decision).toBe('REFUND_APPROVED');
  await page.getByRole('button',{name:'刷新退款',exact:true}).click();await expect(page.getByRole('cell',{name:finalData.refund.refund_no,exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'退款成功',exact:true}).first()).toBeVisible();await page.screenshot({path:'frontend-evidence/m45-real-admin-refunds.png',fullPage:true});
  // M5.1: membership purchase through the shared payment pipeline, then consumer points check-in.
  const membershipOrder=await create('/consumer/membership/orders',{plan_code:'MEMBER_MONTH'});expect(membershipOrder.status).toBe('PENDING_PAYMENT');
  const membershipAttempt=await create('/consumer/payments/'+membershipOrder.payment.id+'/attempts',{channel:'ALIPAY',client_platform:'WEB'});const membershipPaid=await create('/consumer/payments/'+membershipOrder.payment.id+'/simulation',{attempt_id:membershipAttempt.attempts[0].id,outcome:'SUCCEEDED'});expect(membershipPaid.status).toBe('SUCCEEDED');expect(membershipPaid.order_id).toBeNull();
  const membershipView=await page.request.get(api+'/consumer/membership',{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});expect((await membershipView.json()).data.effective_status).toBe('ACTIVE');
  const checkin=await create('/consumer/points/checkins',{});expect(checkin.points).toBeGreaterThan(0);
  const pointsView=await page.request.get(api+'/consumer/points',{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});const pointsData=(await pointsView.json()).data;expect(pointsData.checked_in_today).toBe(true);expect(pointsData.balance).toBe(checkin.points);
  await page.getByRole('link',{name:'会员与积分',exact:true}).click();await expect(page.getByRole('heading',{name:'会员计划',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'月度会员（MEMBER_MONTH）· v1',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'积分政策',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'积分奖励',exact:true})).toBeVisible();await page.screenshot({path:'frontend-evidence/m51-real-admin-membership.png',fullPage:true});

  await page.getByRole('link',{name:'知识内容',exact:true}).click();await page.getByLabel('文章标题',{exact:true}).fill('CI REAL M52 sourced content');await page.getByLabel('正文',{exact:true}).fill('<script>plain knowledge text</script>');await page.getByLabel('信息来源（每行一条）',{exact:true}).fill('TEST ONLY published source');await page.getByLabel('关联商品 SKU（每行一个）',{exact:true}).fill(selectedSku!);await page.getByLabel('含商业推广',{exact:true}).check();
  const articleSaved=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/admin/content'));await page.getByRole('button',{name:'保存新稿件版本',exact:true}).click();const article=(await(await articleSaved).json()).data;expect(article.draft_status).toBe('DRAFT');await expect(page.getByRole('status')).toHaveText('稿件已保存，需提交审核后发布');await page.getByRole('button',{name:'提交已保存稿件审核',exact:true}).click();await expect(page.getByRole('status')).toHaveText('已提交保存的稿件');await page.getByLabel('审核原因',{exact:true}).fill('TEST ONLY real content publishing');await fresh();await page.getByRole('button',{name:'验证并发布文章',exact:true}).click();await expect(page.getByRole('status')).toHaveText('内容审核结果已保存');await expect(page.locator('script').filter({hasText:'plain knowledge text'})).toHaveCount(0);await page.screenshot({path:'frontend-evidence/m52-real-admin-content.png',fullPage:true});
  const publishedArticle=await page.request.get(api+'/public/content/'+article.id);expect(publishedArticle.ok()).toBe(true);const articleData=(await publishedArticle.json()).data;expect(articleData.sponsored).toBe(true);expect(articleData.products[0].available).toBe(true);expect(articleData.products[0].sku_id).toBe(selectedSku);

  // M5.3: consumer-created conversations, actual staff reverify, ordered message and private image delivery.
  const merchantConversation=await create('/consumer/conversations',{kind:'MERCHANT',store_id:createdOffer.store_id});
  const userMessage=await create('/consumer/conversations/'+merchantConversation.id+'/messages',{type:'TEXT',body:'CI REAL M53 consumer message <script>plain</script>',asset_ids:[],target_id:null});expect(userMessage.sequence).toBe(1);
  await merchantPage.getByRole('link',{name:'人工客服',exact:true}).click();await merchantPage.locator('.support-queue button').filter({hasText:merchantConversation.id.slice(0,8)}).click();await merchantPage.getByRole('button',{name:'领取会话',exact:true}).click();await merchantPage.getByLabel('分配原因',{exact:true}).fill('TEST ONLY real customer service');await merchantPage.getByLabel('再次输入密码',{exact:true}).fill(process.env.PAWDAY_DEMO_MERCHANT_PASSWORD!);await merchantPage.getByRole('button',{name:'验证并分配',exact:true}).click();await expect(merchantPage.getByText('CI REAL M53 consumer message <script>plain</script>',{exact:true})).toBeVisible();expect(await merchantPage.locator('.support-chat script').count()).toBe(0);
  await merchantPage.getByLabel('消息',{exact:true}).fill('CI REAL M53 merchant reply');await merchantPage.getByRole('button',{name:'发送消息',exact:true}).click();await expect(merchantPage.getByText('CI REAL M53 merchant reply',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('消息类型',{exact:true}).selectOption('IMAGE');await merchantPage.getByLabel('图片',{exact:true}).setInputFiles({name:'ci-support.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAEElEQVR4nGP4z8AARAwQCgAf7gP9i18U1AAAAABJRU5ErkJggg==','base64')});await expect(merchantPage.getByText('图片已上传，等待发送',{exact:true})).toBeVisible();await merchantPage.getByRole('button',{name:'发送消息',exact:true}).click();await merchantPage.getByRole('button',{name:'查看私有图片',exact:true}).click();await expect(merchantPage.getByAltText('会话图片')).toBeVisible();await merchantPage.screenshot({path:'frontend-evidence/m53-real-merchant-support.png',fullPage:true});
  const receivedSupport=await page.request.get(api+'/consumer/conversations/'+merchantConversation.id+'/messages',{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});expect(receivedSupport.ok()).toBe(true);const supportMessages=(await receivedSupport.json()).data;expect(supportMessages.map((m:{sequence:number})=>m.sequence)).toEqual([1,2,3]);const resource=await page.request.get('http://127.0.0.1:8080'+supportMessages[2].media[0].content_url,{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});expect(resource.ok()).toBe(true);expect((await resource.body()).length).toBeGreaterThan(0);expect(resource.headers()['cache-control']).toContain('no-store');
  const platformConversation=await create('/consumer/conversations',{kind:'PLATFORM',store_id:null});await create('/consumer/conversations/'+platformConversation.id+'/messages',{type:'ORDER',body:null,asset_ids:[],target_id:order.suborders[0].id});
  await page.getByRole('link',{name:'人工客服',exact:true}).click();await page.locator('.support-queue button').filter({hasText:platformConversation.id.slice(0,8)}).click();await page.getByRole('button',{name:'领取会话',exact:true}).click();await page.getByLabel('分配原因',{exact:true}).fill('TEST ONLY platform human support');const supportStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(supportStep);await page.getByLabel('再次输入密码',{exact:true}).fill(password);await page.getByLabel('动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'验证并分配',exact:true}).click();await expect(page.getByRole('button',{name:'查看订单卡片',exact:true})).toBeVisible();await page.getByLabel('消息',{exact:true}).fill('CI REAL M53 platform reply');await page.getByRole('button',{name:'发送消息',exact:true}).click();await expect(page.getByText('CI REAL M53 platform reply',{exact:true})).toBeVisible();await expect(page.getByLabel('再次输入密码',{exact:true})).toHaveCount(0);await page.screenshot({path:'frontend-evidence/m53-real-admin-support.png',fullPage:true});
  await expect.poll(async()=>{const inbox=await page.request.get(api+'/consumer/messages?category=SUPPORT',{headers:{Authorization:`Bearer ${consumerTokens.access_token}`}});return (await inbox.json()).data.length;},{timeout:15000}).toBe(3);

  // M5.4: real scoped store edit, TOTP review, guest discovery and safe destination handoff.
  await merchantPage.getByRole('link',{name:'附近资料',exact:true}).click();await merchantPage.getByLabel('城市',{exact:true}).fill('CI-M54-CITY');await merchantPage.getByLabel('地点类别',{exact:true}).selectOption('VET');await merchantPage.getByLabel('门店地址',{exact:true}).fill('TEST ONLY WGS84 nearby fixture');await merchantPage.getByLabel('联系电话',{exact:true}).fill('13800000000');await merchantPage.getByLabel('营业信息',{exact:true}).fill('TEST ONLY 09:00–18:00');await merchantPage.getByLabel('GPS 经度',{exact:true}).fill('121.5');await merchantPage.getByLabel('GPS 纬度',{exact:true}).fill('31.2');await merchantPage.getByLabel('医院咨询',{exact:true}).check();
  const nearbySaved=merchantPage.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/nearby-profile'));await merchantPage.getByRole('button',{name:'保存附近资料',exact:true}).click();const nearbyProfile=(await(await nearbySaved).json()).data;expect(nearbyProfile.id).toBe(createdOffer.store_id);expect(nearbyProfile.publication_status).toBe('DRAFT');await expect(merchantPage.getByRole('status')).toHaveText('资料已保存，等待平台审核后公开。');await merchantPage.screenshot({path:'frontend-evidence/m54-real-merchant-nearby.png',fullPage:true});
  const unpublished=await page.request.get(api+'/public/nearby/places/'+nearbyProfile.id);expect(unpublished.status()).toBe(404);
  await page.getByRole('link',{name:'附近审核',exact:true}).click();await page.getByRole('button',{name:'审核 LOCAL DEMO Store a',exact:true}).click();await page.getByLabel('平台认证（需审核资质）',{exact:true}).check();await page.getByLabel('审核依据与原因',{exact:true}).fill('TEST ONLY claim and qualification reviewed');
  const nearbyStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(nearbyStep);await page.getByLabel('再次输入密码',{exact:true}).fill(password);await page.getByLabel('动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'验证并提交审核',exact:true}).click();await expect(page.getByRole('status')).toHaveText('审核结果已记录。');await page.screenshot({path:'frontend-evidence/m54-real-admin-nearby.png',fullPage:true});
  const nearbyGuest=await page.request.get(api+'/public/nearby/places?city=CI-M54-CITY&category=VET');expect(nearbyGuest.ok()).toBe(true);const publicPlaces=(await nearbyGuest.json()).data;expect(publicPlaces.some((p:{id:string})=>p.id===nearbyProfile.id)).toBe(true);const nearbyDetail=await page.request.get(api+'/public/nearby/places/'+nearbyProfile.id);expect((await nearbyDetail.json()).data.services).toEqual(['CONSULTATION']);
  const handoff=await page.request.post(api+'/public/nearby/navigation-intents',{data:{place_id:nearbyProfile.id,mode:'DESTINATION'}});expect(handoff.ok()).toBe(true);const intent=(await handoff.json()).data;const destination=new URL(intent.launch_url);expect(destination.origin).toBe('https://uri.amap.com');expect(destination.pathname).toBe('/marker');expect(destination.searchParams.get('coordinate')).toBe('wgs84');expect(destination.searchParams.has('from')).toBe(false);

  // Actual Flutter Web + Chromium geolocation, actual PostgreSQL facts: no plugin or HTTP mocks.
  const geoContext=await browser.newContext({geolocation:{longitude:121.5,latitude:31.2},permissions:['geolocation'],viewport:{width:430,height:900}});const consumerPage=await geoContext.newPage();await consumerPage.goto('http://127.0.0.1:5173/consumer-preview/index.html#/nearby');await consumerPage.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});await consumerPage.locator('flt-semantics-placeholder').evaluate((el:HTMLElement)=>el.click());
  const located=consumerPage.waitForResponse(r=>r.url().includes('/public/nearby/places?')&&r.url().includes('longitude='));await consumerPage.getByRole('button',{name:'使用本次位置',exact:true}).click();expect((await(await located).json()).data.some((p:{id:string})=>p.id===nearbyProfile.id)).toBe(true);await expect(consumerPage.getByRole('button',{name:/^LOCAL DEMO Store a /})).toBeVisible();await consumerPage.screenshot({path:'frontend-evidence/m54-real-consumer-location.png',fullPage:true});await geoContext.close();
  const deniedContext=await browser.newContext({permissions:[],viewport:{width:430,height:900}});const deniedPage=await deniedContext.newPage();await deniedPage.goto('http://127.0.0.1:5173/consumer-preview/index.html#/nearby');await deniedPage.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});await deniedPage.locator('flt-semantics-placeholder').evaluate((el:HTMLElement)=>el.click());await deniedPage.getByRole('button',{name:'使用本次位置',exact:true}).click();await expect(deniedPage.getByText(/未授权位置|位置权限已关闭/)).toBeVisible({timeout:20000});await deniedPage.getByRole('textbox',{name:'浏览城市'}).fill('CI-M54-CITY');await deniedPage.getByRole('button',{name:'按城市浏览',exact:true}).click();await expect(deniedPage.getByRole('button',{name:/^LOCAL DEMO Store a /})).toBeVisible();await deniedPage.screenshot({path:'frontend-evidence/m54-real-consumer-denied.png',fullPage:true});await deniedContext.close();

  await merchantPage.getByRole('link',{name:'AI 资料解释',exact:true}).click();await expect(merchantPage.getByText('商家不能读取消费者 AI 会话。',{exact:false})).toBeVisible();await expect(merchantPage.getByRole('button',{name:'验证并启用',exact:true})).toHaveCount(0);await merchantPage.screenshot({path:'frontend-evidence/m55-real-merchant-ai.png',fullPage:true});
  await page.getByRole('link',{name:'AI 资料解释',exact:true}).click();await expect(page.getByRole('heading',{name:'AI 解释与额度',exact:true})).toBeVisible();await page.getByLabel('整理指令',{exact:true}).fill('Return JSON using verified evidence_ids. TEST_ONLY M55');
  const aiStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(aiStep);await page.getByLabel('再次输入密码',{exact:true}).fill(password);await page.getByLabel('动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'验证并保存提示版本',exact:true}).click();await expect(page.getByRole('status')).toHaveText('操作已提交并记录审计。');await expect(page.getByLabel('再次输入密码',{exact:true})).toHaveValue('');await page.screenshot({path:'frontend-evidence/m55-real-admin-ai.png',fullPage:true});
  // Actual Flutter Web authentication, PostgreSQL quota and local HTTP provider protocol fixture.
  const aiContext=await browser.newContext({viewport:{width:430,height:900}}),aiPage=await aiContext.newPage();await aiPage.goto(`http://127.0.0.1:5173/consumer-preview/index.html#/ai?sku_id=${selectedSku}`);await aiPage.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});await aiPage.locator('flt-semantics-placeholder').evaluate((el:HTMLElement)=>el.click());
  const aiPhone='+8613900000055';await aiPage.getByRole('textbox',{name:'手机号',exact:true}).fill(aiPhone);await aiPage.getByRole('button',{name:'发送验证码',exact:true}).click();let aiOtp='';await expect.poll(async()=>{for(const name of await readdir(sms)){const lines=(await readFile(join(sms,name),'utf8')).split(/\r?\n/);if(lines[0]===aiPhone)aiOtp=lines[1]??'';}return aiOtp.length;},{timeout:30000,intervals:[250]}).toBe(6);
  await aiPage.getByRole('textbox',{name:'验证码',exact:true}).fill(aiOtp);await aiPage.getByRole('checkbox').check();await aiPage.getByRole('button',{name:'登录',exact:true}).click();await expect(aiPage.getByRole('heading',{name:'AI 商品资料解释',exact:true})).toBeVisible();
  await aiPage.getByRole('textbox',{name:/想了解什么/}).fill('30元以内的配料说明');const explained=aiPage.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/consumer/ai/conversations/')&&r.url().endsWith('/messages'));await aiPage.getByRole('button',{name:'发送问题',exact:true}).click();const grounded=(await(await explained).json()).data;expect(grounded.product_cards[0].sku_id).toBe(selectedSku);expect(grounded.product_cards[0].fit_result).toBe('INSUFFICIENT_DATA');await expect(aiPage.getByText(/已根据平台核对过的商品资料整理/)).toBeVisible();await aiPage.screenshot({path:'frontend-evidence/m55-real-consumer-ai.png',fullPage:true});
  await aiPage.getByRole('button',{name:'清除当前 AI 会话',exact:true}).click();await aiPage.getByRole('button',{name:'清除会话',exact:true}).click();await expect(aiPage.getByText(/已根据平台核对过的商品资料整理/)).toHaveCount(0);await aiContext.close();
  await context.close();
});
