import {createHmac} from 'node:crypto';
import {test,expect} from '@playwright/test';
test.skip(!process.env.PAWDAY_REAL_E2E,'Run in the mandatory real-infrastructure CI job');
test.use({actionTimeout:15000});
function totp(){
  const secret=process.env.PAWDAY_DEMO_ADMIN_TOTP_BASE64;
  if(!secret)throw new Error('Real admin TOTP fixture must be explicitly configured');
  const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));
  const hash=createHmac('sha1',Buffer.from(secret,'base64')).update(counter).digest();const offset=hash[19]!&15;
  return String((hash.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');
}
test('real merchant login, scope, refresh rotation and cross-realm rejection',async({page,request})=>{
  const password=process.env.PAWDAY_DEMO_MERCHANT_PASSWORD;if(!password)throw new Error('Real merchant fixture required');
  await page.goto('http://127.0.0.1:5173/stores');await page.getByLabel('账号',{exact:true}).fill('local-staff-a');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录工作台'}).click();
  await expect(page).toHaveURL('http://127.0.0.1:5173/stores');await expect(page.getByRole('heading',{name:'LOCAL DEMO Store a'})).toBeVisible();await expect(page.getByText('LOCAL DEMO Store b',{exact:true})).toHaveCount(0);
  const login=await request.post('http://127.0.0.1:8080/api/v1/merchant/auth/login',{data:{login_name:'local-staff-b',password,device_id:'ci-real-client'}});expect(login.ok()).toBe(true);const tokens=(await login.json()).data;
  const badRealm=await request.get('http://127.0.0.1:8080/api/v1/admin/me',{headers:{Authorization:`Bearer ${tokens.access_token}`}});expect(badRealm.status()).toBe(403);
  const refresh=await request.post('http://127.0.0.1:8080/api/v1/merchant/auth/refresh',{data:{refresh_token:tokens.refresh_token}});expect(refresh.ok()).toBe(true);const rotated=(await refresh.json()).data;expect(rotated.refresh_token).not.toBe(tokens.refresh_token);
  const me=await request.get('http://127.0.0.1:8080/api/v1/merchant/me',{headers:{Authorization:`Bearer ${rotated.access_token}`}});expect(me.ok()).toBe(true);expect((await me.json()).data.realm).toBe('MERCHANT');
  await page.getByRole('link',{name:'账号与设备'}).click();await expect(page.getByText('当前设备',{exact:true})).toBeVisible();await page.getByRole('button',{name:'注销其他设备',exact:true}).click();await page.getByLabel('再次输入密码').fill(password);await page.getByRole('button',{name:'验证并注销其他设备',exact:true}).click();await expect(page.getByRole('status')).toHaveText('其他设备的会话已注销。');
  await page.getByRole('button',{name:'退出登录'}).click();await expect(page).toHaveURL(/\/login$/);
});
test('real administrator TOTP, catalog publication, merchant correction and review',async({page,browser})=>{
  test.setTimeout(480000);
  const password=process.env.PAWDAY_DEMO_ADMIN_PASSWORD;if(!password)throw new Error('Real admin fixture required');
  await page.goto('http://127.0.0.1:5174/audit');await page.getByLabel('账号',{exact:true}).fill('local-admin');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByLabel('动态验证码',{exact:true}).fill(totp());await page.getByRole('button',{name:'登录工作台'}).click();
  await expect(page).toHaveURL('http://127.0.0.1:5174/audit');await expect(page.getByRole('table')).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByRole('link',{name:'账号与设备'}).click();await expect(page.getByText('当前设备',{exact:true})).toBeVisible();await page.getByRole('button',{name:'注销其他设备',exact:true}).click();
  // A login TOTP is single-use. Wait for the next real step before reverify.
  const currentStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(currentStep);
  await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());await page.getByRole('button',{name:'验证并注销其他设备',exact:true}).click();await expect(page.getByRole('status')).toHaveText('其他设备的会话已注销。');
  await page.getByRole('link',{name:'审计记录'}).click();await expect(page.getByRole('cell',{name:'auth.sessions.revoked-others',exact:true}).first()).toBeVisible();
  await page.getByRole('link',{name:'宠物分类',exact:true}).click();await expect(page.getByRole('heading',{name:'宠物分类与年龄规则'})).toBeVisible();
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'维护分类词典'})});await form.getByLabel('类型').selectOption('allergens');await form.getByLabel('名称',{exact:true}).fill(`CI REAL TEST allergen ${Date.now()}`);
  const taxonomyStep=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(taxonomyStep);
  await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());await form.getByRole('button',{name:'保存词典项'}).click();await expect(page.getByRole('status')).toHaveText('已保存，操作已记录。');
  await page.getByRole('link',{name:'审计记录'}).click();await expect(page.getByRole('cell',{name:'pet.taxonomy.create',exact:true}).first()).toBeVisible();
  await page.getByRole('link',{name:'标准商品',exact:true}).click();
  await expect(page.getByRole('heading',{name:'标准商品与审核'})).toBeVisible();
  const fresh=async()=>{const step=Math.floor(Date.now()/30000);await expect.poll(()=>Math.floor(Date.now()/30000),{timeout:32000,intervals:[250]}).toBeGreaterThan(step);await page.getByLabel('再次输入密码').fill(password);await page.getByLabel('新的动态验证码').fill(totp());};
  const saved=async()=>{await expect(page.getByRole('status')).toHaveText('已保存，操作已记录。');await expect(page.getByLabel('再次输入密码')).toHaveValue('');};
  const label=`CI REAL TEST ${Date.now()}`;
  await page.getByText('新建品牌、商品与规格',{exact:true}).click();
  const brandForm=page.locator('form').filter({has:page.getByRole('heading',{name:'品牌',exact:true})});
  await brandForm.getByLabel('名称',{exact:true}).fill(label);await brandForm.getByLabel('来源依据',{exact:true}).fill('TEST-ONLY generated browser fixture, not real merchandise');await fresh();await brandForm.getByRole('button',{name:'创建品牌'}).click();await saved();
  const spuForm=page.locator('form').filter({has:page.getByRole('heading',{name:'标准商品',exact:true})});
  await spuForm.getByRole('combobox',{name:'品牌',exact:true}).selectOption({label},{timeout:10000});await spuForm.getByLabel('商品名称').fill(label);await spuForm.getByLabel('商品类目').fill('DRY_FOOD');await fresh();await spuForm.getByRole('button',{name:'创建商品'}).click();await saved();
  const skuForm=page.locator('form').filter({has:page.getByRole('heading',{name:'标准规格',exact:true})});
  await skuForm.getByRole('combobox',{name:'所属商品',exact:true}).selectOption({label},{timeout:10000});await skuForm.getByLabel('规格标识').fill(label);await skuForm.getByLabel('净重（克）').fill('1000');await fresh();await skuForm.getByRole('button',{name:'创建规格'}).click();await saved();
  await page.locator('article').filter({has:page.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();
  const standardForm=page.locator('form').filter({has:page.getByRole('heading',{name:'创建新的资料草稿',exact:true})});
  await standardForm.getByLabel('配料（每行一项，保留原始顺序）').fill('TEST-ONLY ingredient');await standardForm.getByLabel('来源依据（每行一条）').fill('TEST-ONLY label fixture');await standardForm.getByLabel('来源更新日期').fill('2026-10-01');await fresh();await standardForm.getByRole('button',{name:'保存新草稿'}).click();await saved();
  await fresh();await page.getByRole('button',{name:'发布此版本'}).click();await saved();await expect(page.getByRole('heading',{name:'版本 1 · PUBLISHED'})).toBeVisible();
  const context=await browser.newContext(),merchantPage=await context.newPage();
  await merchantPage.goto('http://127.0.0.1:5173/catalog');await merchantPage.getByLabel('账号',{exact:true}).fill('local-staff-a');await merchantPage.getByLabel('密码',{exact:true}).fill(process.env.PAWDAY_DEMO_MERCHANT_PASSWORD!);await merchantPage.getByRole('button',{name:'登录工作台'}).click();await expect(merchantPage.getByRole('heading',{name:'平台标准商品'})).toBeVisible();
  await merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();await expect(merchantPage.getByRole('button',{name:'发布此版本'})).toHaveCount(0);
  await merchantPage.getByLabel('配料（每行一项，保留原始顺序）').fill('TEST-ONLY corrected ingredient');await merchantPage.getByLabel('纠错原因').fill('TEST-ONLY packaging correction');await merchantPage.getByRole('button',{name:'提交审核',exact:true}).click();await expect(merchantPage.getByRole('status')).toHaveText('已保存，操作已记录。');
  await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.getByText('TEST-ONLY packaging correction',{exact:true})).toBeVisible();await page.getByLabel('审核理由').fill('TEST-ONLY source reviewed');await fresh();await page.getByRole('button',{name:'批准并发布新版本'}).click();await saved();await expect(page.getByRole('heading',{name:'版本 2 · PUBLISHED'})).toBeVisible();
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看标准资料'}).click();await expect(merchantPage.getByRole('heading',{name:'版本 2 · PUBLISHED'})).toBeVisible();await expect(merchantPage.getByRole('heading',{name:'版本 1 · RETIRED'})).toHaveCount(0);
  await page.screenshot({path:'frontend-evidence/m32-real-admin-catalog.png',fullPage:true});await merchantPage.screenshot({path:'frontend-evidence/m32-real-merchant-catalog.png',fullPage:true});
  await merchantPage.getByRole('link',{name:'报价与库存',exact:true}).click();await expect(merchantPage.getByRole('heading',{name:'报价与库存',exact:true})).toBeVisible();
  const selectedSku=await merchantPage.getByRole('combobox',{name:'标准规格',exact:true}).locator('option').filter({hasText:label}).getAttribute('value');expect(selectedSku).toBeTruthy();
  await merchantPage.getByRole('combobox',{name:'标准规格',exact:true}).selectOption(selectedSku!);await merchantPage.getByLabel('售价（分）',{exact:true}).fill('1250');await merchantPage.getByLabel('会员价（分，可空）',{exact:true}).fill('1150');await merchantPage.getByLabel('履约承诺',{exact:true}).fill('TEST-ONLY 48 hours');await merchantPage.getByRole('button',{name:'创建草稿报价'}).click();await expect(merchantPage.getByRole('status')).toHaveText('已保存，操作已记录。');
  const offerCard=()=>merchantPage.locator('article').filter({has:merchantPage.getByRole('heading',{name:label,exact:true})});await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('实物 0 · 预占 0 · 可用 0',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('增减数量').fill('10');await merchantPage.getByRole('button',{name:'提交库存调整'}).click();await expect(merchantPage.getByText('实物 10 · 预占 0 · 可用 10',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('cell',{name:'RESTOCK',exact:true})).toBeVisible();
  await merchantPage.getByLabel('操作原因').fill('TEST-ONLY initial sale');await merchantPage.getByRole('button',{name:'上架报价',exact:true}).click();await expect(merchantPage.getByText('状态 ACTIVE',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('售价（分）',{exact:true}).fill('1350');await merchantPage.getByRole('button',{name:'保存报价',exact:true}).click();await expect(merchantPage.getByText('售价 1350 分 · 会员价 1150 · TEST-ONLY 48 hours',{exact:true})).toBeVisible();
  await merchantPage.getByLabel('增减数量').fill('-3');await merchantPage.getByRole('combobox',{name:'调整原因'}).selectOption('DAMAGE');await merchantPage.getByRole('button',{name:'提交库存调整'}).click();await expect(merchantPage.getByText('实物 7 · 预占 0 · 可用 7',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('cell',{name:'DAMAGE',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'报价与库存',exact:true}).click();await page.locator('article').filter({has:page.getByRole('heading',{name:label,exact:true})}).getByRole('button',{name:'查看报价与流水'}).click();await page.getByLabel('操作原因').fill('TEST-ONLY risk verification');await fresh();await page.getByRole('button',{name:'冻结报价',exact:true}).click();await expect(page.getByText('状态 FROZEN',{exact:true})).toBeVisible();await expect(page.getByLabel('再次输入密码')).toHaveValue('');
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('状态 FROZEN',{exact:true})).toBeVisible();await expect(merchantPage.getByRole('button',{name:'上架报价',exact:true})).toHaveCount(0);await expect(merchantPage.getByRole('button',{name:'保存报价',exact:true})).toHaveCount(0);
  await page.getByLabel('操作原因').fill('TEST-ONLY risk cleared');await fresh();await page.getByRole('button',{name:'解冻为暂停',exact:true}).click();await expect(page.getByText('状态 PAUSED',{exact:true})).toBeVisible();
  await merchantPage.getByRole('button',{name:'刷新',exact:true}).click();await offerCard().getByRole('button',{name:'查看报价与流水'}).click();await expect(merchantPage.getByText('状态 PAUSED',{exact:true})).toBeVisible();await merchantPage.getByLabel('操作原因').fill('TEST-ONLY explicit resume');await merchantPage.getByRole('button',{name:'上架报价',exact:true}).click();await expect(merchantPage.getByText('状态 ACTIVE',{exact:true})).toBeVisible();
  await page.screenshot({path:'frontend-evidence/m33-real-admin-offers.png',fullPage:true});await merchantPage.screenshot({path:'frontend-evidence/m33-real-merchant-offers.png',fullPage:true});await context.close();
});
