package cn.pawday.checkout;

import cn.pawday.common.Api.Failure;
import cn.pawday.common.IdempotentCommandExecutor;
import cn.pawday.identity.*;
import cn.pawday.audit.AuditWriter;
import cn.pawday.pet.PetService;
import jakarta.servlet.http.HttpServletRequest;
import java.time.*;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;

@Service
public class CheckoutService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final IdempotentCommandExecutor commands;
 private final Crypto crypto;private final Clock clock;private final PetService pets;private final AuthService auth;private final AuditWriter audit;
 private final JsonMapper json=JsonMapper.builder().build();private final PricingEngine engine=new PricingEngine();
 public CheckoutService(JdbcTemplate db,TransactionTemplate tx,IdempotentCommandExecutor commands,Crypto crypto,Clock clock,PetService pets,AuthService auth,AuditWriter audit){this.db=db;this.tx=tx;this.commands=commands;this.crypto=crypto;this.clock=clock;this.pets=pets;this.auth=auth;this.audit=audit;}
 static void check(boolean ok){if(!ok)throw new Failure(400,"VALIDATION_ERROR");}
 static UUID id(Object x){try{return UUID.fromString(String.valueOf(x));}catch(Exception e){throw new Failure(400,"VALIDATION_ERROR");}}
 static long n(Object x,long min,long max){check(x instanceof Integer||x instanceof Long);long v=((Number)x).longValue();check(v>=min&&v<=max);return v;}
 static void fields(Map<String,Object>b,String... allowed){check(Set.of(allowed).containsAll(b.keySet()));}
 static String text(Object x,int max){check(x instanceof String&&!((String)x).isBlank()&&((String)x).length()<=max);return ((String)x).trim();}
 static long version(String s){if(s==null)throw new Failure(428,"PRECONDITION_REQUIRED");try{check(s.matches("\"[0-9]+\""));return Long.parseLong(s.substring(1,s.length()-1));}catch(NumberFormatException e){throw new Failure(400,"VALIDATION_ERROR");}}
 static void current(Map<String,Object>r,long v){if(((Number)r.get("version")).longValue()!=v)throw new Failure(409,"CONCURRENT_MODIFICATION");}
 static void consumer(Actor a){if(a.realm()!=Actor.Realm.CONSUMER)throw new Failure(403,"PERMISSION_DENIED");}
 private Map<String,Object> one(String sql,Object... args){var rows=db.queryForList(sql,args);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");return rows.getFirst();}
 private Map<String,Object> view(Map<String,Object>r){var out=new LinkedHashMap<String,Object>();r.forEach((k,v)->{if(!Set.of("user_id","created_by").contains(k))out.put(k,v==null?null:v instanceof Timestamp?v.toString():v);});return out;}
 private UUID cart(Actor a){consumer(a);db.update("INSERT INTO carts(id,user_id) VALUES (?,?) ON CONFLICT(user_id) DO NOTHING",UUID.randomUUID(),a.userId());return (UUID)one("SELECT * FROM carts WHERE user_id=? FOR UPDATE",a.userId()).get("id");}
 private void lockSelected(Actor a,List<UUID> selected){
  for(UUID i:selected.stream().sorted(Comparator.comparing(UUID::toString)).toList())db.queryForList("SELECT i.id FROM cart_items i JOIN carts c ON c.id=i.cart_id WHERE i.id=? AND c.user_id=? FOR UPDATE OF i",i,a.userId());
  var offers=new TreeSet<UUID>(Comparator.comparing(UUID::toString));
  for(UUID i:selected)for(var row:db.queryForList("SELECT i.offer_id FROM cart_items i JOIN carts c ON c.id=i.cart_id WHERE i.id=? AND c.user_id=?",i,a.userId()))offers.add((UUID)row.get("offer_id"));
  for(UUID o:offers){db.queryForList("SELECT id FROM offers WHERE id=? FOR SHARE",o);db.queryForList("SELECT offer_id FROM inventory_balances WHERE offer_id=? FOR SHARE",o);}
 }
 private Map<String,Object> offer(UUID id,long quantity){
  var r=one("SELECT o.*,i.available_qty,i.version inventory_version,k.weight_g,p.name,m.name merchant_name,(SELECT id FROM sku_standard_versions v WHERE v.sku_id=k.id AND v.status='PUBLISHED' ORDER BY version_no DESC LIMIT 1) standard_id FROM offers o JOIN inventory_balances i ON i.offer_id=o.id JOIN skus k ON k.id=o.sku_id JOIN spus p ON p.id=k.spu_id JOIN brands b ON b.id=p.brand_id JOIN merchant m ON m.id=o.merchant_id WHERE o.id=? AND o.sale_status='ACTIVE' AND k.status='ACTIVE' AND p.status='ACTIVE' AND b.status='ACTIVE' AND m.status='ACTIVE' FOR SHARE OF o,i,k,p,b,m",id);
  if(r.get("standard_id")==null)throw new Failure(422,"CATALOG_NOT_PUBLISHED");if(((Number)r.get("available_qty")).longValue()<quantity)throw new Failure(409,"INSUFFICIENT_STOCK");return r;
 }
 private Map<String,Object> item(Actor a,UUID id){return one("SELECT i.* FROM cart_items i JOIN carts c ON c.id=i.cart_id WHERE i.id=? AND c.user_id=? AND i.active FOR UPDATE OF i",id,a.userId());}
 private Map<String,Object> addLocked(Actor a,UUID c,Map<String,Object>b){
  fields(b,"offer_id","quantity","pet_id");UUID o=id(b.get("offer_id")),pet=b.get("pet_id")==null?null:id(b.get("pet_id"));long qty=n(b.get("quantity"),1,999);if(pet!=null)pets.get(a,pet);
  var prior=db.queryForList("SELECT * FROM cart_items WHERE cart_id=? AND offer_id=? AND pet_id IS NOT DISTINCT FROM ?::uuid AND active",c,o,pet);
  if(!prior.isEmpty())qty+=((Number)prior.getFirst().get("quantity")).longValue();check(qty<=999);offer(o,qty);
  UUID i=prior.isEmpty()?UUID.randomUUID():(UUID)prior.getFirst().get("id");
  if(prior.isEmpty())db.update("INSERT INTO cart_items(id,cart_id,offer_id,pet_id,quantity) VALUES (?,?,?,?,?)",i,c,o,pet,qty);
  else db.update("UPDATE cart_items SET quantity=?,version=version+1 WHERE id=?",qty,i);
  db.update("UPDATE carts SET version=version+1 WHERE id=?",c);return view(item(a,i));
 }
 public Map<String,Object> cartView(Actor a){return tx.execute(s->{UUID c=cart(a);var items=new ArrayList<Map<String,Object>>();for(var i:db.queryForList("SELECT * FROM cart_items WHERE cart_id=? AND active ORDER BY created_at,id",c)){var x=view(i);try{var o=offer((UUID)i.get("offer_id"),((Number)i.get("quantity")).longValue());x.put("availability","AVAILABLE");x.put("name",o.get("name"));x.put("merchant_name",o.get("merchant_name"));x.put("sale_price_fen",o.get("sale_price_fen"));x.put("available_qty",o.get("available_qty"));}catch(Failure f){x.put("availability",f.code);}items.add(x);}return Map.of("id",c,"version",db.queryForObject("SELECT version FROM carts WHERE id=?",Long.class,c),"items",items);});}
 public Map<String,Object> add(Actor a,Map<String,Object>b,String key){consumer(a);return commands.command(a,"cart.add",key,b,()->addLocked(a,cart(a),b));}
 public Map<String,Object> merge(Actor a,Map<String,Object>b,String key){consumer(a);fields(b,"items");check(b.get("items") instanceof List<?>);var list=(List<?>)b.get("items");check(list.size()>0&&list.size()<=100);return commands.command(a,"cart.merge",key,b,()->{UUID c=cart(a);for(Object x:list){check(x instanceof Map<?,?>);addLocked(a,c,(Map<String,Object>)x);}return cartView(a);});}
 public Map<String,Object> patch(Actor a,UUID i,Map<String,Object>b,String match,String key){consumer(a);fields(b,"quantity");long q=n(b.get("quantity"),1,999),v=version(match);return commands.command(a,"cart.patch:"+i,key,Map.of("body",b,"version",v),()->{UUID c=cart(a);var old=item(a,i);current(old,v);if(old.get("pet_id")!=null)pets.get(a,(UUID)old.get("pet_id"));offer((UUID)old.get("offer_id"),q);db.update("UPDATE cart_items SET quantity=?,version=version+1 WHERE id=?",q,i);db.update("UPDATE carts SET version=version+1 WHERE id=?",c);return view(item(a,i));});}
 public Map<String,Object> delete(Actor a,UUID i,String match,String key){consumer(a);long v=version(match);return commands.command(a,"cart.delete:"+i,key,Map.of("version",v),()->{UUID c=cart(a);current(item(a,i),v);db.update("UPDATE cart_items SET active=false,version=version+1 WHERE id=?",i);db.update("UPDATE carts SET version=version+1 WHERE id=?",c);return Map.of("id",i,"deleted",true);});}
 private Map<String,Object> address(Actor a,UUID id){return one("SELECT * FROM user_addresses WHERE id=? AND user_id=? AND status='ACTIVE' FOR SHARE",id,a.userId());}
 public List<Map<String,Object>> addresses(Actor a){consumer(a);return db.queryForList("SELECT * FROM user_addresses WHERE user_id=? AND status='ACTIVE' ORDER BY id",a.userId()).stream().map(this::view).toList();}
 private void addressBody(Map<String,Object>b){fields(b,"recipient","phone","province_code","city_code","district_code","detail");text(b.get("recipient"),80);text(b.get("detail"),500);check(text(b.get("phone"),32).matches("\\+?[0-9]{7,15}"));check(text(b.get("province_code"),12).matches("[0-9]{6}"));for(String x:List.of("city_code","district_code"))if(b.get(x)!=null)check(text(b.get(x),12).matches("[0-9]{6}"));}
 public Map<String,Object> saveAddress(Actor a,UUID i,Map<String,Object>b,String match,String key){consumer(a);addressBody(b);long v=i==null?0:version(match);return commands.command(a,"address.save:"+i,key,Map.of("body",b,"version",v),()->{UUID id=i==null?UUID.randomUUID():i;if(i==null)db.update("INSERT INTO user_addresses(id,user_id,recipient,phone,province_code,city_code,district_code,detail) VALUES (?,?,?,?,?,?,?,?)",id,a.userId(),b.get("recipient"),b.get("phone"),b.get("province_code"),b.get("city_code"),b.get("district_code"),b.get("detail"));else{var old=one("SELECT * FROM user_addresses WHERE id=? AND user_id=? AND status='ACTIVE' FOR UPDATE",id,a.userId());current(old,v);db.update("UPDATE user_addresses SET recipient=?,phone=?,province_code=?,city_code=?,district_code=?,detail=?,version=version+1 WHERE id=?",b.get("recipient"),b.get("phone"),b.get("province_code"),b.get("city_code"),b.get("district_code"),b.get("detail"),id);}return view(address(a,id));});}
 public Map<String,Object> deleteAddress(Actor a,UUID i,String match,String key){consumer(a);long v=version(match);return commands.command(a,"address.delete:"+i,key,Map.of("version",v),()->{current(one("SELECT * FROM user_addresses WHERE id=? AND user_id=? AND status='ACTIVE' FOR UPDATE",i,a.userId()),v);db.update("UPDATE user_addresses SET status='DELETED',version=version+1 WHERE id=?",i);return Map.of("id",i,"deleted",true);});}
 public Map<String,Object> publishShipping(Actor a,UUID m,Map<String,Object>b,String key,String proof,HttpServletRequest r){
  if(a.realm()!=Actor.Realm.ADMIN||!a.permissions().contains("pricing.shipping.manage"))throw new Failure(403,"PERMISSION_DENIED");
  fields(b,"province_codes","base_fen","per_kg_fen","free_threshold_fen");check(b.get("province_codes") instanceof List<?>);var codes=(List<?>)b.get("province_codes");check(!codes.isEmpty()&&codes.size()<=100&&new HashSet<>(codes).size()==codes.size());for(Object x:codes)check(text(x,12).matches("[0-9]{6}"));n(b.get("base_fen"),0,1000000000);n(b.get("per_kg_fen"),0,1000000000);if(b.get("free_threshold_fen")!=null)n(b.get("free_threshold_fen"),0,9007199254740991L);
  return commands.command(a,"shipping.publish:"+m,key,b,()->{auth.consumeProof(a,"pricing.shipping.manage",proof);one("SELECT * FROM merchant WHERE id=? FOR UPDATE",m);long v=db.queryForObject("SELECT coalesce(max(version_no),0)+1 FROM shipping_rule_versions WHERE merchant_id=?",Long.class,m);UUID id=UUID.randomUUID();db.update("INSERT INTO shipping_rule_versions(id,merchant_id,version_no,province_codes,base_fen,per_kg_fen,free_threshold_fen,created_by) VALUES (?,?,?,?::jsonb,?,?,?,?)",id,m,v,json.writeValueAsString(codes),b.get("base_fen"),b.get("per_kg_fen"),b.get("free_threshold_fen"),a.principalId());var result=shippingView(one("SELECT * FROM shipping_rule_versions WHERE id=?",id));audit.write(a,"pricing.shipping.publish","MERCHANT",m.toString(),Map.of(),result,r);return result;});
 }
 private Map<String,Object> shippingView(Map<String,Object>r){var out=view(r);out.put("province_codes",json.readValue(r.get("province_codes").toString(),List.class));return out;}
 public Map<String,Object> shipping(Actor a,UUID m){if(a.realm()!=Actor.Realm.ADMIN||!a.permissions().contains("pricing.shipping.manage"))throw new Failure(403,"PERMISSION_DENIED");return shippingView(one("SELECT * FROM shipping_rule_versions WHERE merchant_id=? ORDER BY version_no DESC LIMIT 1",m));}
 private Map<String,Object> membership(Actor a,boolean requested){if(!requested)return Map.of("used",false);var rows=db.queryForList("SELECT * FROM membership_subscriptions WHERE user_id=? AND status='ACTIVE' AND starts_at<=? AND expires_at>? FOR SHARE",a.userId(),Timestamp.from(clock.instant()),Timestamp.from(clock.instant()));if(rows.isEmpty())throw new Failure(422,"MEMBERSHIP_NOT_ELIGIBLE");var result=view(rows.getFirst());result.put("used",true);return result;}
 private List<Map<String,Object>> coupons(Actor a,List<UUID>ids,Set<String> merchants){var out=new ArrayList<Map<String,Object>>();var slots=new HashSet<String>();for(UUID id:ids){var rows=db.queryForList("SELECT * FROM user_coupons WHERE id=? AND user_id=? AND status IN ('AVAILABLE','RETURNED') AND expires_at>? AND EXISTS(SELECT 1 FROM coupon_definitions d WHERE d.id=user_coupons.definition_id AND d.status='PUBLISHED' AND d.version=user_coupons.definition_version) FOR SHARE",id,a.userId(),Timestamp.from(clock.instant()));if(rows.isEmpty())throw new Failure(422,"COUPON_NOT_ELIGIBLE");var c=rows.getFirst();String slot=c.get("scope")+":"+c.get("merchant_id");if(!slots.add(slot))throw new Failure(422,"COUPON_STACKING_CONFLICT");if(c.get("merchant_id")!=null&&!merchants.contains(c.get("merchant_id").toString()))throw new Failure(422,"COUPON_NOT_ELIGIBLE");out.add(c);}return out;}
 public Map<String,Object> benefits(Actor a){consumer(a);return tx.execute(s->{boolean eligible=db.queryForObject("SELECT count(*) FROM membership_subscriptions WHERE user_id=? AND status='ACTIVE' AND starts_at<=? AND expires_at>?",Integer.class,a.userId(),Timestamp.from(clock.instant()),Timestamp.from(clock.instant()))>0;
  var coupons=db.queryForList("SELECT c.id,c.scope,c.merchant_id,m.name merchant_name,c.amount_fen,c.threshold_fen,c.expires_at,c.version FROM user_coupons c JOIN coupon_definitions d ON d.id=c.definition_id LEFT JOIN merchant m ON m.id=c.merchant_id WHERE c.user_id=? AND c.status IN ('AVAILABLE','RETURNED') AND c.expires_at>? AND d.status='PUBLISHED' AND d.version=c.definition_version ORDER BY c.id",a.userId(),Timestamp.from(clock.instant())).stream().map(c->{var v=view(c);v.put("expires_at",((Timestamp)c.get("expires_at")).toInstant().toString());return v;}).toList();return Map.of("membership_eligible",eligible,"coupons",coupons);});}
 private List<UUID> ids(Object x){check(x instanceof List<?>);var values=(List<?>)x;check(values.size()<=100);var ids=values.stream().map(CheckoutService::id).toList();check(new HashSet<>(ids).size()==ids.size());return ids;}
 public Map<String,Object> quote(Actor a,Map<String,Object>b,String key){consumer(a);fields(b,"cart_item_ids","address_id","coupon_ids","use_membership");var selected=ids(b.get("cart_item_ids"));check(!selected.isEmpty());UUID address=id(b.get("address_id"));var selectedCoupons=ids(b.getOrDefault("coupon_ids",List.of()));check(b.getOrDefault("use_membership",false) instanceof Boolean);boolean use=(Boolean)b.getOrDefault("use_membership",false);
  return commands.command(a,"checkout.quote",key,b,()->{
   UUID cart=cart(a);lockSelected(a,selected);var addr=address(a,address);var member=membership(a,use);var lines=new ArrayList<Map<String,Object>>();
   for(UUID i:selected){var ci=item(a,i);if(ci.get("pet_id")!=null)pets.get(a,(UUID)ci.get("pet_id"));var o=offer((UUID)ci.get("offer_id"),((Number)ci.get("quantity")).longValue());var line=new LinkedHashMap<String,Object>();line.putAll(ci);line.put("offer",o);lines.add(line);}
   lines.sort(Comparator.comparing(x->{var o=(Map<?,?>)x.get("offer");return o.get("merchant_id")+":"+o.get("id")+":"+x.get("id");}));
   var inputLines=new ArrayList<PricingEngine.Line>();var weights=new TreeMap<String,Long>();var merchantGoods=new TreeMap<String,Long>();var snapshots=new ArrayList<Map<String,Object>>();int seq=0;
   for(var ci:lines){var o=(Map<String,Object>)ci.get("offer");String allocation=String.format(Locale.ROOT,"%06d",++seq),m=o.get("merchant_id").toString();long qty=((Number)ci.get("quantity")).longValue(),price=((Number)(use&&o.get("member_price_fen")!=null?o.get("member_price_fen"):o.get("sale_price_fen"))).longValue(),amount=Math.multiplyExact(qty,price);var x=new LinkedHashMap<String,Object>();for(String f:List.of("sku_id","merchant_id"))x.put(f,o.get(f));x.put("cart_item_id",ci.get("id"));x.put("cart_item_version",ci.get("version"));x.put("offer_id",o.get("id"));x.put("offer_version",o.get("version"));x.put("catalog_standard_version_id",o.get("standard_id"));x.put("quantity",qty);x.put("unit_price_fen",price);x.put("goods_amount_fen",amount);x.put("allocation_key",allocation);x.put("name",o.get("name"));x.put("merchant_name",o.get("merchant_name"));snapshots.add(x);inputLines.add(new PricingEngine.Line(allocation,m,amount));weights.merge(m,Math.multiplyExact(qty,((Number)o.get("weight_g")).longValue()),Math::addExact);merchantGoods.merge(m,amount,Math::addExact);}
   var shipping=new TreeMap<String,Long>();var templates=new TreeMap<String,Map<String,Object>>();
   for(String m:weights.keySet()){var rows=db.queryForList("SELECT * FROM shipping_rule_versions WHERE merchant_id=? ORDER BY version_no DESC LIMIT 1",UUID.fromString(m));if(rows.isEmpty())throw new Failure(422,"SHIPPING_RULE_REQUIRED");var t=rows.getFirst();if(!json.readValue(t.get("province_codes").toString(),List.class).contains(addr.get("province_code")))throw new Failure(422,"ADDRESS_OUTSIDE_DELIVERY_AREA");long cost=t.get("free_threshold_fen")!=null&&merchantGoods.get(m)>=((Number)t.get("free_threshold_fen")).longValue()?0:Math.addExact(((Number)t.get("base_fen")).longValue(),Math.multiplyExact((weights.get(m)+999)/1000,((Number)t.get("per_kg_fen")).longValue()));shipping.put(m,cost);templates.put(m,t);}
   var cs=coupons(a,selectedCoupons,weights.keySet());var discounts=new ArrayList<PricingEngine.Discount>();
   for(var c:cs){String scope=c.get("scope").toString();Set<String> keys=new TreeSet<>();if(scope.equals("SHIPPING"))keys.addAll(shipping.keySet());else for(var l:inputLines)if(!scope.equals("MERCHANT")||l.merchant().equals(c.get("merchant_id").toString()))keys.add(l.key());discounts.add(new PricingEngine.Discount(c.get("id").toString(),scope.equals("MERCHANT")?3:scope.equals("PLATFORM")?5:7,scope.equals("SHIPPING")?"SHIPPING":"GOODS",keys,((Number)c.get("threshold_fen")).longValue(),((Number)c.get("amount_fen")).longValue()));}
   var priced=engine.price(inputLines,shipping,discounts);UUID quote=UUID.randomUUID();var groups=new ArrayList<Map<String,Object>>();
   for(var x:snapshots){long payable=priced.goodsPayable().get(x.get("allocation_key"));x.put("payable_amount_fen",payable);x.put("discount_amount_fen",((Number)x.get("goods_amount_fen")).longValue()-payable);}
   for(String m:shipping.keySet()){long goodsPaid=snapshots.stream().filter(x->x.get("merchant_id").toString().equals(m)).mapToLong(x->((Number)x.get("payable_amount_fen")).longValue()).sum();String name=snapshots.stream().filter(x->x.get("merchant_id").toString().equals(m)).findFirst().get().get("merchant_name").toString();groups.add(Map.of("merchant_id",m,"merchant_name",name,"goods_amount_fen",merchantGoods.get(m),"goods_discount_fen",merchantGoods.get(m)-goodsPaid,"goods_payable_fen",goodsPaid,"shipping_rule_id",templates.get(m).get("id"),"shipping_amount_fen",shipping.get(m),"shipping_payable_fen",priced.shippingPayable().get(m),"shipping_discount_fen",shipping.get(m)-priced.shippingPayable().get(m)));}
   var allocations=priced.allocations().stream().map(x->Map.<String,Object>of("source_id",x.source(),"sequence_no",x.sequence(),"scope",x.scope(),"allocation_key",x.key(),"eligible_base_fen",x.eligibleBase(),"discount_fen",x.discount())).toList();
   var rule=one("SELECT * FROM pricing_rule_versions WHERE code=?",PricingEngine.RULE);var params=json.readValue(rule.get("parameters").toString(),Map.class);Instant expires=clock.instant().plusSeconds(((Number)params.get("quote_ttl_seconds")).longValue());
   var result=new LinkedHashMap<String,Object>();result.put("quote_id",quote);result.put("status","ACTIVE");result.put("version",0);result.put("expires_at",expires.toString());result.put("currency","CNY");result.put("goods_amount_fen",priced.goods());result.put("shipping_amount_fen",priced.shipping());result.put("discount_amount_fen",priced.discount());result.put("payable_amount_fen",priced.payable());result.put("pricing_rule_version",PricingEngine.RULE);result.put("algorithm_version",PricingEngine.ALGORITHM);result.put("address_snapshot",view(addr));result.put("membership_snapshot",member);result.put("items",snapshots);result.put("merchant_groups",groups);result.put("discount_allocations",allocations);
   var facts=new LinkedHashMap<String,Object>();facts.put("address_id",address);facts.put("address_version",addr.get("version"));facts.put("use_membership",use);facts.put("membership",member);facts.put("coupons",cs.stream().map(this::view).toList());facts.put("items",snapshots);facts.put("groups",groups);
   db.update("INSERT INTO pricing_quotes(id,user_id,address_id,address_version,address_snapshot,membership_snapshot,currency,goods_amount_fen,shipping_amount_fen,discount_amount_fen,payable_amount_fen,pricing_rule_version,algorithm_version,input_hash,snapshot_hash,facts_snapshot,result_snapshot,expires_at) VALUES (?,?,?,?,?::jsonb,?::jsonb,'CNY',?,?,?,?,?,?,?,?,?::jsonb,?::jsonb,?)",quote,a.userId(),address,addr.get("version"),json.writeValueAsString(view(addr)),json.writeValueAsString(member),priced.goods(),priced.shipping(),priced.discount(),priced.payable(),PricingEngine.RULE,PricingEngine.ALGORITHM,crypto.hash(json.writeValueAsString(b)),crypto.hash(json.writeValueAsString(result)),json.writeValueAsString(facts),json.writeValueAsString(result),Timestamp.from(expires));
   for(var x:snapshots)db.update("INSERT INTO pricing_quote_items(id,quote_id,allocation_key,cart_item_id,cart_item_version,offer_id,offer_version,sku_id,catalog_standard_version_id,merchant_id,quantity,unit_price_fen,goods_amount_fen,discount_amount_fen,payable_amount_fen) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),quote,x.get("allocation_key"),x.get("cart_item_id"),x.get("cart_item_version"),x.get("offer_id"),x.get("offer_version"),x.get("sku_id"),x.get("catalog_standard_version_id"),x.get("merchant_id"),x.get("quantity"),x.get("unit_price_fen"),x.get("goods_amount_fen"),x.get("discount_amount_fen"),x.get("payable_amount_fen"));
   for(var g:groups)db.update("INSERT INTO pricing_quote_merchant_groups VALUES (?,?,?,?,?,?)",quote,UUID.fromString(g.get("merchant_id").toString()),g.get("shipping_rule_id"),g.get("shipping_amount_fen"),g.get("shipping_discount_fen"),g.get("shipping_payable_fen"));
   for(var x:allocations)db.update("INSERT INTO pricing_quote_discount_allocations VALUES (?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),quote,UUID.fromString(x.get("source_id").toString()),x.get("scope"),x.get("allocation_key"),x.get("sequence_no"),x.get("eligible_base_fen"),x.get("discount_fen"),PricingEngine.RULE,PricingEngine.ALGORITHM);
   return result;
  });
 }
 public Map<String,Object> getQuote(Actor a,UUID q){consumer(a);return tx.execute(s->{var row=one("SELECT * FROM pricing_quotes WHERE id=? AND user_id=? FOR UPDATE",q,a.userId());String status=row.get("status").toString();if(status.equals("ACTIVE")){
   lockSelected(a,db.queryForList("SELECT cart_item_id FROM pricing_quote_items WHERE quote_id=?",q).stream().map(x->(UUID)x.get("cart_item_id")).toList());
   String next=((Timestamp)row.get("expires_at")).toInstant().isAfter(clock.instant())?null:"EXPIRED";
   if(next==null)try{var facts=json.readValue(row.get("facts_snapshot").toString(),Map.class);var addr=address(a,id(facts.get("address_id")));current(addr,((Number)facts.get("address_version")).longValue());if(!json.readTree(json.writeValueAsString(membership(a,(Boolean)facts.get("use_membership")))).equals(json.readTree(json.writeValueAsString(facts.get("membership")))))throw new Failure(409,"MEMBERSHIP_CHANGED");
    for(Object x:(List<?>)facts.get("items")){var line=(Map<String,Object>)x;var ci=item(a,id(line.get("cart_item_id")));current(ci,((Number)line.get("cart_item_version")).longValue());if(ci.get("pet_id")!=null)one("SELECT id FROM pets WHERE id=? AND owner_user_id=? AND status='ACTIVE' FOR SHARE",ci.get("pet_id"),a.userId());var o=offer(id(line.get("offer_id")),((Number)line.get("quantity")).longValue());current(o,((Number)line.get("offer_version")).longValue());if(!o.get("standard_id").toString().equals(line.get("catalog_standard_version_id").toString()))throw new Failure(409,"STANDARD_CHANGED");}
    for(Object x:(List<?>)facts.get("groups")){var g=(Map<?,?>)x;var t=one("SELECT id FROM shipping_rule_versions WHERE merchant_id=? ORDER BY version_no DESC LIMIT 1",id(g.get("merchant_id")));if(!t.get("id").toString().equals(g.get("shipping_rule_id").toString()))throw new Failure(409,"SHIPPING_CHANGED");}
    for(Object x:(List<?>)facts.get("coupons")){var c=(Map<?,?>)x;var now=one("SELECT * FROM user_coupons WHERE id=? AND user_id=? AND status IN ('AVAILABLE','RETURNED') AND expires_at>? AND EXISTS(SELECT 1 FROM coupon_definitions d WHERE d.id=user_coupons.definition_id AND d.status='PUBLISHED' AND d.version=user_coupons.definition_version)",id(c.get("id")),a.userId(),Timestamp.from(clock.instant()));current(now,((Number)c.get("version")).longValue());}
   }catch(Failure changed){next="INVALIDATED";}
   if(next!=null){db.update("UPDATE pricing_quotes SET status=?,version=version+1 WHERE id=?",next,q);status=next;row.put("version",((Number)row.get("version")).longValue()+1);}
  }var result=new LinkedHashMap<String,Object>(json.readValue(row.get("result_snapshot").toString(),Map.class));result.put("status",status);result.put("version",row.get("version"));return result;});}
}
