package cn.pawday.ordering;
import static cn.pawday.ordering.OrderService.*;
import cn.pawday.common.Api.Failure;
import cn.pawday.common.IdempotentCommandExecutor;
import cn.pawday.identity.Actor;
import cn.pawday.audit.AuditWriter;
import cn.pawday.outbox.OutboxWriter;
import jakarta.servlet.http.HttpServletRequest;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;
@Service public class FulfillmentService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final IdempotentCommandExecutor commands;private final OrderService orders;private final AuditWriter audit;private final OutboxWriter outbox;private final LogisticsProvider logistics;
 public FulfillmentService(JdbcTemplate db,TransactionTemplate tx,IdempotentCommandExecutor commands,OrderService orders,AuditWriter audit,OutboxWriter outbox,LogisticsProvider logistics){this.db=db;this.tx=tx;this.commands=commands;this.orders=orders;this.audit=audit;this.outbox=outbox;this.logistics=logistics;}
 private Map<String,Object> one(String q,Object...args){var rows=db.queryForList(q,args);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");return rows.getFirst();}
 private Map<String,Object> view(Map<String,Object>row){var v=new LinkedHashMap<String,Object>();row.forEach((k,x)->v.put(k,x instanceof Timestamp t?t.toInstant().toString():x));return v;}
 private UUID authorize(Actor a,UUID sub){var row=one("SELECT * FROM suborders WHERE id=?",sub);UUID order=(UUID)row.get("order_id");if(a.realm()==Actor.Realm.MERCHANT)orders.merchantGet(a,sub);else orders.get(a,order,a.realm()==Actor.Realm.ADMIN);return order;}
 private void locked(UUID order,UUID sub){one("SELECT id FROM orders WHERE id=? FOR UPDATE",order);one("SELECT id FROM suborders WHERE id=? FOR UPDATE",sub);}
 public Map<String,Object> get(Actor a,UUID sub){return tx.execute(s->{UUID order=authorize(a,sub);one("SELECT id FROM orders WHERE id=? FOR SHARE",order);return detail(a,sub);});}
 private Map<String,Object> detail(Actor a,UUID sub){var row=one("SELECT * FROM suborders WHERE id=?",sub);var v=new LinkedHashMap<String,Object>();v.put("suborder_id",sub);v.put("version",row.get("version"));v.put("fulfillment_status",row.get("fulfillment_status"));v.put("items",db.queryForList("SELECT i.id order_item_id,i.quantity,i.cancelled_qty,coalesce((SELECT sum(h.quantity) FROM shipment_items h WHERE h.order_item_id=i.id),0) shipped_qty,coalesce((SELECT sum(h.quantity) FROM shipment_items h JOIN shipment_receipts r ON r.shipment_id=h.shipment_id WHERE h.order_item_id=i.id),0) received_qty FROM order_items i WHERE suborder_id=? ORDER BY i.id",sub));v.put("shipments",db.queryForList("SELECT h.*,r.confirmed_at FROM shipments h LEFT JOIN shipment_receipts r ON r.shipment_id=h.id WHERE h.suborder_id=? ORDER BY h.created_at,h.id",sub).stream().map(h->{var x=view(h);x.remove("created_by");x.put("items",db.queryForList("SELECT order_item_id,quantity FROM shipment_items WHERE shipment_id=? ORDER BY order_item_id",h.get("id")));return x;}).toList());
 // Read permission alone never exposes recipient data, including unpaid/cancelled orders.
 v.put("delivery_address",a.realm()==Actor.Realm.MERCHANT&&a.permissions().contains("order.ship")&&!Set.of("PENDING_PAYMENT","CANCELLED","COMPLETED").contains(row.get("fulfillment_status"))?JsonMapper.builder().build().readValue(one("SELECT snapshot FROM order_address_snapshots WHERE order_id=?",row.get("order_id")).get("snapshot").toString(),Map.class):null);return v;}
 public Map<String,Object> ship(Actor a,UUID sub,Map<String,Object>b,String match,String key,HttpServletRequest r){permission(a,Actor.Realm.MERCHANT,"order.ship");fields(b,"carrier_code","tracking_no","items");long expected=version(match);if(!(b.get("carrier_code") instanceof String carrier)||!carrier.matches("[A-Z0-9_]{2,24}")||!(b.get("tracking_no") instanceof String tracking)||!tracking.matches("[A-Za-z0-9-]{6,80}")||!(b.get("items") instanceof List<?> items)||items.isEmpty()||items.size()>100)throw new Failure(400,"VALIDATION_ERROR");
 var quantities=new TreeMap<UUID,Long>(Comparator.comparing(UUID::toString));for(Object x:items){if(!(x instanceof Map<?,?> m)||!m.keySet().equals(Set.of("order_item_id","quantity"))||!(m.get("quantity") instanceof Number number)||number.longValue()<1||number.longValue()>100000||number.doubleValue()!=number.longValue())throw new Failure(400,"VALIDATION_ERROR");if(quantities.put(id(m.get("order_item_id")),number.longValue())!=null)throw new Failure(400,"VALIDATION_ERROR");}
 // Authorize again before reading a cached private command result.
 UUID authorizedOrder=authorize(a,sub);return commands.command(a,"shipment.create:"+sub,key,Map.of("body",b,"version",expected),()->{locked(authorizedOrder,sub);UUID order=authorize(a,sub);var row=one("SELECT * FROM suborders WHERE id=?",sub);if(n(row.get("version"))!=expected)throw new Failure(409,"CONCURRENT_MODIFICATION");if(!Set.of("PAID_WAITING_FULFILLMENT","PARTIALLY_SHIPPED","PARTIALLY_COMPLETED").contains(row.get("fulfillment_status"))||!one("SELECT status FROM payments WHERE order_id=?",order).get("status").equals("SUCCEEDED"))throw new Failure(409,"SUBORDER_NOT_SHIPPABLE");
 for(var e:quantities.entrySet()){var item=one("SELECT * FROM order_items WHERE id=? AND suborder_id=? FOR UPDATE",e.getKey(),sub);long sent=db.queryForObject("SELECT coalesce(sum(quantity),0) FROM shipment_items WHERE order_item_id=?",Long.class,e.getKey());if(e.getValue()>n(item.get("quantity"))-n(item.get("cancelled_qty"))-sent)throw new Failure(409,"SHIPMENT_QUANTITY_EXCEEDED");}
 one("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",carrier+":"+tracking);if(!db.queryForList("SELECT id FROM shipments WHERE carrier_code=? AND tracking_no=?",carrier,tracking).isEmpty())throw new Failure(409,"TRACKING_NUMBER_IN_USE");UUID shipment=UUID.randomUUID();db.update("INSERT INTO shipments(id,suborder_id,carrier_code,tracking_no,created_by) VALUES (?,?,?,?,?)",shipment,sub,carrier,tracking,a.principalId());for(var e:quantities.entrySet())db.update("INSERT INTO shipment_items VALUES (?,?,?,?)",shipment,sub,e.getKey(),e.getValue());advance(a,order,sub,"ShipmentCreated",shipment,r);return commandView(a,sub);});}
 public Map<String,Object> receive(Actor a,UUID sub,Map<String,Object>b,String match,String key,HttpServletRequest r){consumer(a);fields(b,"shipment_ids");long expected=version(match);if(!(b.get("shipment_ids") instanceof List<?> values)||values.isEmpty()||values.size()>100)throw new Failure(400,"VALIDATION_ERROR");var ids=new TreeSet<UUID>(Comparator.comparing(UUID::toString));for(var x:values)if(!ids.add(id(x)))throw new Failure(400,"VALIDATION_ERROR");UUID authorizedOrder=authorize(a,sub);return commands.command(a,"shipment.receive:"+sub,key,Map.of("body",b,"version",expected),()->{locked(authorizedOrder,sub);UUID order=authorize(a,sub);var row=one("SELECT * FROM suborders WHERE id=?",sub);if(n(row.get("version"))!=expected)throw new Failure(409,"CONCURRENT_MODIFICATION");if(Set.of("PENDING_PAYMENT","PAID_WAITING_FULFILLMENT","CANCELLED","COMPLETED").contains(row.get("fulfillment_status")))throw new Failure(409,"SUBORDER_NOT_RECEIVABLE");for(UUID shipment:ids){one("SELECT id FROM shipments WHERE id=? AND suborder_id=?",shipment,sub);if(!db.queryForList("SELECT shipment_id FROM shipment_receipts WHERE shipment_id=?",shipment).isEmpty())throw new Failure(409,"SHIPMENT_ALREADY_RECEIVED");db.update("INSERT INTO shipment_receipts(shipment_id,user_id) VALUES (?,?)",shipment,a.userId());}advance(a,order,sub,"SuborderReceiptConfirmed",sub,r);return commandView(a,sub);});}
 private void advance(Actor a,UUID order,UUID sub,String event,UUID reference,HttpServletRequest r){long total=db.queryForObject("SELECT sum(quantity-cancelled_qty) FROM order_items WHERE suborder_id=?",Long.class,sub),shipped=db.queryForObject("SELECT coalesce(sum(quantity),0) FROM shipment_items WHERE suborder_id=?",Long.class,sub),received=db.queryForObject("SELECT coalesce(sum(i.quantity),0) FROM shipment_items i JOIN shipment_receipts r ON r.shipment_id=i.shipment_id WHERE i.suborder_id=?",Long.class,sub);String state=received==total?"COMPLETED":received>0?"PARTIALLY_COMPLETED":shipped==total?"SHIPPED_WAITING_RECEIPT":shipped>0?"PARTIALLY_SHIPPED":"PAID_WAITING_FULFILLMENT";db.update("UPDATE suborders SET fulfillment_status=?,version=version+1 WHERE id=?",state,sub);db.update("UPDATE orders SET version=version+1 WHERE id=?",order);outbox.append("SUBORDER",sub.toString(),event,1,Map.of("order_id",order.toString(),"suborder_id",sub.toString(),"reference_id",reference.toString(),"version",one("SELECT version FROM suborders WHERE id=?",sub).get("version")),r==null?null:(String)r.getAttribute("correlation_id"));audit.write(a,event.equals("ShipmentCreated")?"order.ship":"order.receive","SUBORDER",sub.toString(),Map.of(),Map.of("reference_id",reference,"fulfillment_status",state),r);}
 private Map<String,Object> commandView(Actor a,UUID sub){var result=detail(a,sub);result.put("delivery_address",null);return result;}
 public Map<String,Object> tracking(Actor a,UUID shipment){var h=one("SELECT * FROM shipments WHERE id=?",shipment);authorize(a,(UUID)h.get("suborder_id"));return logistics.queryTracking(h.get("carrier_code").toString(),h.get("tracking_no").toString(),shipment.toString());}
}
