package cn.pawday.ordering;

import cn.pawday.common.Api.Failure;
import cn.pawday.common.IdempotentCommandExecutor;
import cn.pawday.checkout.CheckoutService;
import cn.pawday.identity.*;
import cn.pawday.audit.AuditWriter;
import cn.pawday.outbox.OutboxWriter;
import jakarta.servlet.http.HttpServletRequest;
import java.time.*;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;

@Service
public class OrderService {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final IdempotentCommandExecutor commands;
 private final CheckoutService checkout;private final OutboxWriter outbox;private final AuditWriter audit;private final AuthService auth;private final Clock clock;
 private final JsonMapper json=JsonMapper.builder().build();
 public OrderService(JdbcTemplate db,TransactionTemplate tx,IdempotentCommandExecutor commands,CheckoutService checkout,OutboxWriter outbox,AuditWriter audit,AuthService auth,Clock clock){this.db=db;this.tx=tx;this.commands=commands;this.checkout=checkout;this.outbox=outbox;this.audit=audit;this.auth=auth;this.clock=clock;}
 static UUID id(Object x){try{return UUID.fromString(String.valueOf(x));}catch(Exception e){throw new Failure(400,"VALIDATION_ERROR");}}
 static void fields(Map<String,Object>b,String...names){if(!Set.of(names).containsAll(b.keySet()))throw new Failure(400,"VALIDATION_ERROR");}
 static void consumer(Actor a){if(a.realm()!=Actor.Realm.CONSUMER)throw new Failure(403,"PERMISSION_DENIED");}
 static void permission(Actor a,Actor.Realm realm,String p){if(a.realm()!=realm||!a.permissions().contains(p))throw new Failure(403,"PERMISSION_DENIED");}
 static long n(Object x){return ((Number)x).longValue();}
 static long version(String v){if(v==null)throw new Failure(428,"PRECONDITION_REQUIRED");try{if(!v.matches("\"[0-9]+\""))throw new IllegalArgumentException();return Long.parseLong(v.substring(1,v.length()-1));}catch(Exception e){throw new Failure(400,"VALIDATION_ERROR");}}
 private Map<String,Object> one(String q,Object...args){var rows=db.queryForList(q,args);if(rows.isEmpty())throw new Failure(404,"RESOURCE_NOT_FOUND");return rows.getFirst();}
 private Map<String,Object> map(Object x){return json.readValue(x.toString(),Map.class);}
 private Map<String,Object> view(Map<String,Object> row){var m=new LinkedHashMap<String,Object>();row.forEach((k,v)->m.put(k,v instanceof Timestamp t?t.toInstant().toString():v));return m;}
 private String correlation(HttpServletRequest r){return r==null?null:(String)r.getAttribute("correlation_id");}
 private Map<String,Object> policy(){return one("SELECT * FROM order_policy_versions ORDER BY version_no DESC LIMIT 1");}
 public Map<String,Object> policy(Actor a){permission(a,Actor.Realm.ADMIN,"order.policy.manage");var row=view(policy());row.remove("created_by");return row;}
 public Map<String,Object> publishPolicy(Actor a,Map<String,Object>b,String key,String proof,HttpServletRequest r){permission(a,Actor.Realm.ADMIN,"order.policy.manage");fields(b,"version_code","reservation_ttl_seconds");if(!(b.get("version_code") instanceof String code)||!code.matches("[A-Z0-9_]{3,80}")||!(b.get("reservation_ttl_seconds") instanceof Integer ttl)||ttl<60||ttl>3600)throw new Failure(400,"VALIDATION_ERROR");
  return commands.command(a,"order.policy.publish",key,b,()->{auth.consumeProof(a,"order.policy.manage",proof);db.queryForList("SELECT pg_advisory_xact_lock(hashtextextended('order-policy-publish',0))");if(db.queryForObject("SELECT count(*) FROM order_policy_versions WHERE version_code=?",Integer.class,code)>0)throw new Failure(409,"POLICY_VERSION_EXISTS");UUID p=UUID.randomUUID();db.update("INSERT INTO order_policy_versions(id,version_code,reservation_ttl_seconds,created_by) VALUES (?,?,?,?)",p,code,ttl,a.principalId());var result=policy(a);audit.write(a,"order.policy.publish","ORDER_POLICY",p.toString(),Map.of(),result,r);return result;});
 }
 public Map<String,Object> create(Actor a,Map<String,Object>b,String key,HttpServletRequest r){consumer(a);fields(b,"quote_id");UUID q=id(b.get("quote_id"));
  return commands.command(a,"order.create",key,b,()->{
   // Cart commands take this same lock. Lock items, offers, then balances in UUID order;
   // balances are exclusive before Quote validation, preventing share-to-write upgrades.
   one("SELECT * FROM carts WHERE user_id=? FOR UPDATE",a.userId());
   var quote=one("SELECT * FROM pricing_quotes WHERE id=? AND user_id=? FOR UPDATE",q,a.userId());
   if(quote.get("status").equals("CONSUMED"))throw new Failure(409,"QUOTE_ALREADY_CONSUMED");
   if(!quote.get("status").equals("ACTIVE"))throw new Failure(409,"QUOTE_"+quote.get("status"));
   var rows=db.queryForList("SELECT * FROM pricing_quote_items WHERE quote_id=? ORDER BY allocation_key",q);
   db.queryForList("SELECT i.id FROM cart_items i JOIN pricing_quote_items qi ON qi.cart_item_id=i.id WHERE qi.quote_id=? ORDER BY i.id FOR UPDATE OF i",q);
   var offers=rows.stream().map(x->(UUID)x.get("offer_id")).distinct().sorted(Comparator.comparing(UUID::toString)).toList();
   for(UUID o:offers){one("SELECT id FROM offers WHERE id=? FOR UPDATE",o);one("SELECT * FROM inventory_balances WHERE offer_id=? FOR UPDATE",o);}
   var facts=map(quote.get("facts_snapshot"));var couponFacts=(List<Map<String,Object>>)facts.get("coupons");
   for(UUID c:couponFacts.stream().map(x->id(x.get("id"))).sorted(Comparator.comparing(UUID::toString)).toList()){var coupon=one("SELECT * FROM user_coupons WHERE id=? FOR UPDATE",c);one("SELECT id FROM coupon_definitions WHERE id=? FOR SHARE",coupon.get("definition_id"));}
   var checked=checkout.getQuote(a,q);if(!checked.get("status").equals("ACTIVE"))throw new Failure(409,"QUOTE_"+checked.get("status"));
   var pol=policy();Instant expires=clock.instant().plusSeconds(n(pol.get("reservation_ttl_seconds")));UUID order=UUID.randomUUID();String no="O"+order.toString().replace("-","");
   db.update("INSERT INTO orders(id,order_no,user_id,quote_id,currency,goods_amount_fen,shipping_amount_fen,discount_amount_fen,payable_amount_fen,pricing_snapshot,policy_version_id,reservation_expires_at) VALUES (?,?,?,?,'CNY',?,?,?,?,?::jsonb,?,?)",order,no,a.userId(),q,quote.get("goods_amount_fen"),quote.get("shipping_amount_fen"),quote.get("discount_amount_fen"),quote.get("payable_amount_fen"),quote.get("result_snapshot").toString(),pol.get("id"),Timestamp.from(expires));
   db.update("INSERT INTO order_address_snapshots VALUES (?,?::jsonb)",order,quote.get("address_snapshot").toString());
   UUID payment=UUID.randomUUID();db.update("INSERT INTO payments(id,payment_no,order_id,amount_fen,currency,expires_at) VALUES (?,?,?,?,'CNY',?)",payment,"P"+payment.toString().replace("-",""),order,quote.get("payable_amount_fen"),Timestamp.from(expires));
   var snapshot=map(quote.get("result_snapshot"));Map<UUID,UUID> subs=new HashMap<>();
   for(Object x:(List<?>)snapshot.get("merchant_groups")){var g=(Map<String,Object>)x;UUID m=id(g.get("merchant_id")),sub=UUID.randomUUID();subs.put(m,sub);db.update("INSERT INTO suborders(id,order_id,merchant_id,suborder_no,merchant_name,goods_amount_fen,shipping_amount_fen,discount_amount_fen,payable_amount_fen,shipping_snapshot) VALUES (?,?,?,?,?,?,?,?,?,?::jsonb)",sub,order,m,"S"+sub.toString().replace("-",""),g.get("merchant_name"),g.get("goods_amount_fen"),g.get("shipping_amount_fen"),n(g.get("goods_discount_fen"))+n(g.get("shipping_discount_fen")),n(g.get("goods_payable_fen"))+n(g.get("shipping_payable_fen")),json.writeValueAsString(g));}
   Map<UUID,Long> quantities=new TreeMap<>(Comparator.comparing(UUID::toString));
   for(var line:rows){UUID offer=(UUID)line.get("offer_id"),merchant=(UUID)line.get("merchant_id");var product=one("SELECT o.store_id,o.fulfillment_sla,o.member_price_fen,o.sale_price_fen,o.version offer_version,k.sku_code,k.weight_g,k.package_unit,p.name,b.name brand,v.id standard_version_id,(to_jsonb(v)-'created_by') standard_snapshot FROM offers o JOIN skus k ON k.id=o.sku_id JOIN spus p ON p.id=k.spu_id JOIN brands b ON b.id=p.brand_id JOIN sku_standard_versions v ON v.id=? WHERE o.id=?",line.get("catalog_standard_version_id"),offer);
    var ci=one("SELECT pet_id FROM cart_items WHERE id=?",line.get("cart_item_id"));product.put("pet_id",ci.get("pet_id"));product.put("member_price_used",Boolean.TRUE.equals(facts.get("use_membership"))&&product.get("member_price_fen")!=null);product.remove("member_price_fen");product.remove("sale_price_fen");product.put("standard_snapshot",map(product.get("standard_snapshot")));
    db.update("INSERT INTO order_items(id,suborder_id,allocation_key,offer_id,sku_id,merchant_id,store_id,quantity,unit_price_fen,goods_amount_fen,discount_amount_fen,payable_amount_fen,product_snapshot) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb)",UUID.randomUUID(),subs.get(merchant),line.get("allocation_key"),offer,line.get("sku_id"),merchant,product.get("store_id"),line.get("quantity"),line.get("unit_price_fen"),line.get("goods_amount_fen"),line.get("discount_amount_fen"),line.get("payable_amount_fen"),json.writeValueAsString(product));quantities.merge(offer,n(line.get("quantity")),Long::sum);
   }
   for(var entry:quantities.entrySet()){UUID reservation=UUID.randomUUID();db.update("INSERT INTO inventory_reservations(id,order_id,offer_id,quantity,expires_at) VALUES (?,?,?,?,?)",reservation,order,entry.getKey(),entry.getValue(),Timestamp.from(expires));inventory(order,reservation,entry.getKey(),entry.getValue(),"RESERVE",correlation(r));}
   for(var c:couponFacts){UUID cid=id(c.get("id"));db.update("INSERT INTO order_coupon_snapshots VALUES (?,?,?::jsonb)",order,cid,json.writeValueAsString(c));if(db.update("UPDATE user_coupons SET status='RESERVED',reserved_order_id=?,reserved_from_status=status,reservation_expires_at=?,version=version+1 WHERE id=? AND user_id=? AND status IN ('AVAILABLE','RETURNED') AND version=?",order,Timestamp.from(expires),cid,a.userId(),c.get("version"))!=1)throw new Failure(409,"COUPON_NOT_ELIGIBLE");}
   db.update("UPDATE pricing_quotes SET status='CONSUMED',consumed_order_id=?,consumed_at=?,version=version+1 WHERE id=?",order,Timestamp.from(clock.instant()),q);
   // Only selected, confirmed items are removed. Failed transactions restore the cart.
   for(var line:rows)db.update("UPDATE cart_items SET active=false,version=version+1 WHERE id=?",line.get("cart_item_id"));db.update("UPDATE carts SET version=version+1 WHERE user_id=?",a.userId());
   outbox.append("ORDER",order.toString(),"OrderCreated",1,Map.of("order_id",order.toString(),"payment_id",payment.toString()),correlation(r));audit.write(a,"order.create","ORDER",order.toString(),Map.of(),Map.of("quote_id",q,"payable_amount_fen",quote.get("payable_amount_fen")),r);return detailLocked(order);
  });
 }
 private void inventory(UUID order,UUID reservation,UUID offer,long delta,String operation,String correlation){var before=one("SELECT * FROM inventory_balances WHERE offer_id=? FOR UPDATE",offer);long qty=n(before.get("reserved_qty")),next=qty+delta;if(next<0||next>n(before.get("on_hand_qty")))throw new Failure(409,"INSUFFICIENT_STOCK");long version=n(before.get("version"))+1;db.update("UPDATE inventory_balances SET reserved_qty=?,version=version+1,updated_at=clock_timestamp() WHERE offer_id=?",next,offer);UUID event=UUID.randomUUID();db.update("INSERT INTO inventory_reservation_events(id,reservation_id,order_id,offer_id,operation,delta_reserved_qty,before_reserved_qty,resulting_reserved_qty,resulting_inventory_version) VALUES (?,?,?,?,?,?,?,?,?)",event,reservation,order,offer,operation,delta,qty,next,version);UUID sku=(UUID)one("SELECT sku_id FROM offers WHERE id=?",offer).get("sku_id");outbox.append("OFFER",offer.toString(),"InventoryReservationChanged",1,Map.of("offer_id",offer.toString(),"sku_id",sku.toString(),"reservation_event_id",event.toString(),"inventory_version",version),correlation);}
 public Map<String,Object> get(Actor a,UUID id,boolean admin){if(admin)permission(a,Actor.Realm.ADMIN,"order.admin.read");else consumer(a);return tx.execute(s->{var row=one("SELECT * FROM orders WHERE id=?"+(admin?"":" AND user_id=?")+" FOR SHARE",admin?new Object[]{id}:new Object[]{id,a.userId()});return detailLocked((UUID)row.get("id"));});}
 private Map<String,Object> summary(Map<String,Object>r){var v=view(r);v.remove("user_id");v.remove("pricing_snapshot");return v;}
 private Map<String,Object> detailLocked(UUID id){var result=summary(one("SELECT * FROM orders WHERE id=?",id));result.put("payment",view(one("SELECT * FROM payments WHERE order_id=?",id)));result.put("address_snapshot",map(one("SELECT snapshot FROM order_address_snapshots WHERE order_id=?",id).get("snapshot")));result.put("pricing_snapshot",map(one("SELECT pricing_snapshot FROM orders WHERE id=?",id).get("pricing_snapshot")));result.put("suborders",db.queryForList("SELECT * FROM suborders WHERE order_id=? ORDER BY merchant_id",id).stream().map(this::subView).toList());result.put("reservations",db.queryForList("SELECT * FROM inventory_reservations WHERE order_id=? ORDER BY offer_id",id).stream().map(this::view).toList());var cancellations=db.queryForList("SELECT * FROM order_cancellations WHERE order_id=?",id);result.put("cancellation",cancellations.isEmpty()?null:view(cancellations.getFirst()));return result;}
 private Map<String,Object> subView(Map<String,Object>sub){var r=view(sub);r.put("shipping_snapshot",map(r.get("shipping_snapshot")));r.put("items",db.queryForList("SELECT * FROM order_items WHERE suborder_id=? ORDER BY allocation_key",sub.get("id")).stream().map(x->{var m=view(x);m.put("product_snapshot",map(m.get("product_snapshot")));return m;}).toList());return r;}
 public Map<String,Object> cancel(Actor a,UUID id,Map<String,Object>b,String match,String key,HttpServletRequest r){consumer(a);fields(b,"reason_code");if(!"CONSUMER_CANCELLED".equals(b.get("reason_code")))throw new Failure(400,"VALIDATION_ERROR");long expected=version(match);return commands.command(a,"order.cancel:"+id,key,Map.of("body",b,"version",expected),()->{var order=one("SELECT * FROM orders WHERE id=? AND user_id=? FOR UPDATE",id,a.userId());if(n(order.get("version"))!=expected)throw new Failure(409,"CONCURRENT_MODIFICATION");close(order,a,"CONSUMER_CANCELLED",r);return detailLocked(id);});}
 private void close(Map<String,Object>order,Actor actor,String reason,HttpServletRequest r){UUID id=(UUID)order.get("id");if(!order.get("status").equals("PENDING_PAYMENT"))throw new Failure(409,"ORDER_NOT_CANCELLABLE");var payment=one("SELECT * FROM payments WHERE order_id=? FOR UPDATE",id);if(!payment.get("status").equals("PENDING"))throw new Failure(409,"PAYMENT_CONFIRMATION_PENDING");var reservations=db.queryForList("SELECT * FROM inventory_reservations WHERE order_id=? ORDER BY offer_id",id);for(var v:reservations){one("SELECT id FROM offers WHERE id=? FOR UPDATE",v.get("offer_id"));one("SELECT * FROM inventory_balances WHERE offer_id=? FOR UPDATE",v.get("offer_id"));}boolean expired=reason.equals("PAYMENT_WINDOW_EXPIRED");
  for(var v:reservations){if(!v.get("status").equals("ACTIVE"))throw new Failure(409,"RESERVATION_STATE_CONFLICT");db.update("UPDATE inventory_reservations SET status=?,version=version+1 WHERE id=?",expired?"EXPIRED":"RELEASED",v.get("id"));inventory(id,(UUID)v.get("id"),(UUID)v.get("offer_id"),-n(v.get("quantity")),expired?"EXPIRE":"RELEASE",correlation(r));}
  var coupons=db.queryForList("SELECT * FROM user_coupons WHERE reserved_order_id=? ORDER BY id FOR UPDATE",id);for(var c:coupons){String status=((Timestamp)c.get("expires_at")).toInstant().isAfter(clock.instant())?c.get("reserved_from_status").toString():"EXPIRED";db.update("UPDATE user_coupons SET status=?,reserved_order_id=NULL,reserved_from_status=NULL,reservation_expires_at=NULL,version=version+1 WHERE id=?",status,c.get("id"));}
  UUID cancellation=UUID.randomUUID();db.update("INSERT INTO order_cancellations(id,order_id,actor_type,actor_id,reason_code,status) VALUES (?,?,?,?,?,'COMPLETED')",cancellation,id,actor==null?"SYSTEM":"CONSUMER",actor==null?null:actor.principalId(),reason);
  for(var item:db.queryForList("SELECT i.* FROM order_items i JOIN suborders s ON s.id=i.suborder_id WHERE s.order_id=? ORDER BY i.id FOR UPDATE OF i",id)){db.update("INSERT INTO order_cancellation_items(id,cancellation_id,order_item_id,quantity,allocation_snapshot) VALUES (?,?,?,?,?::jsonb)",UUID.randomUUID(),cancellation,item.get("id"),item.get("quantity"),json.writeValueAsString(Map.of("allocation_key",item.get("allocation_key"),"discount_amount_fen",item.get("discount_amount_fen"),"payable_amount_fen",item.get("payable_amount_fen"))));db.update("UPDATE order_items SET cancelled_qty=quantity WHERE id=?",item.get("id"));}
  db.update("INSERT INTO order_cancellation_events(id,cancellation_id,from_status,to_status,reason_code) VALUES (?,?,'PENDING_PAYMENT','COMPLETED',?)",UUID.randomUUID(),cancellation,reason);
  db.update("UPDATE suborders SET fulfillment_status='CANCELLED',version=version+1 WHERE order_id=?",id);db.update("UPDATE payments SET status='CLOSED',version=version+1 WHERE order_id=?",id);db.update("UPDATE orders SET status='CANCELLED',version=version+1 WHERE id=?",id);
  outbox.append("ORDER",id.toString(),expired?"OrderExpired":"OrderCancelled",1,Map.of("order_id",id.toString(),"reason_code",reason),correlation(r));audit.write(actor,expired?"order.expire":"order.cancel","ORDER",id.toString(),Map.of("status","PENDING_PAYMENT"),Map.of("status","CANCELLED","reason_code",reason),r);
 }
 public int expireBatch(){int count=0;var candidates=db.queryForList("SELECT id FROM orders WHERE status='PENDING_PAYMENT' AND reservation_expires_at<=? ORDER BY reservation_expires_at,id LIMIT 50",Timestamp.from(clock.instant()));for(var candidate:candidates){boolean closed=tx.execute(s->{var rows=db.queryForList("SELECT * FROM orders WHERE id=? AND status='PENDING_PAYMENT' AND reservation_expires_at<=? FOR UPDATE SKIP LOCKED",candidate.get("id"),Timestamp.from(clock.instant()));if(rows.isEmpty())return false;close(rows.getFirst(),null,"PAYMENT_WINDOW_EXPIRED",null);return true;});if(closed)count++;}return count;}
 public List<Map<String,Object>> list(Actor a,boolean admin,UUID after,int limit){if(admin)permission(a,Actor.Realm.ADMIN,"order.admin.read");else consumer(a);if(limit<1||limit>100)throw new Failure(400,"VALIDATION_ERROR");return db.queryForList("SELECT * FROM orders WHERE id>?"+(admin?"":" AND user_id=?")+" ORDER BY id LIMIT ?",admin?new Object[]{after,limit+1}:new Object[]{after,a.userId(),limit+1}).stream().map(this::summary).toList();}
 private boolean scoped(Actor a,UUID sub){return db.queryForObject("SELECT count(*) FROM order_items i WHERE i.suborder_id=? AND ((i.store_id IS NULL AND NOT ?) OR (i.store_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM principal_store_scope p WHERE p.principal_id=? AND p.merchant_id=i.merchant_id AND p.store_id=i.store_id)))",Integer.class,sub,a.permissions().contains("order.default-scope"),a.principalId())==0;}
 public Map<String,Object> merchantGet(Actor a,UUID sub){permission(a,Actor.Realm.MERCHANT,"order.read");return tx.execute(s->{var row=one("SELECT * FROM suborders WHERE id=? AND merchant_id=?",sub,a.merchantId());if(!scoped(a,sub))throw new Failure(404,"RESOURCE_NOT_FOUND");one("SELECT id FROM orders WHERE id=? FOR SHARE",row.get("order_id"));return subView(one("SELECT * FROM suborders WHERE id=?",sub));});}
 public List<Map<String,Object>> merchantList(Actor a,UUID after,int limit){permission(a,Actor.Realm.MERCHANT,"order.read");if(limit<1||limit>100)throw new Failure(400,"VALIDATION_ERROR");return tx.execute(s->{var rows=db.queryForList("SELECT s.* FROM suborders s WHERE s.merchant_id=? AND s.id>? AND NOT EXISTS(SELECT 1 FROM order_items i WHERE i.suborder_id=s.id AND ((i.store_id IS NULL AND NOT ?) OR (i.store_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM principal_store_scope p WHERE p.principal_id=? AND p.merchant_id=i.merchant_id AND p.store_id=i.store_id)))) ORDER BY s.id LIMIT ?",a.merchantId(),after,a.permissions().contains("order.default-scope"),a.principalId(),limit+1);for(UUID id:rows.stream().map(x->(UUID)x.get("order_id")).distinct().sorted(Comparator.comparing(UUID::toString)).toList())one("SELECT id FROM orders WHERE id=? FOR SHARE",id);return rows.stream().map(x->subView(one("SELECT * FROM suborders WHERE id=?",x.get("id")))).toList();});}
}
